/*
 * Auto-generated collision data from: Catacombs Entry mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  30
 * Floors: 7
 * Bounds: X(-750 to 4800)  Z(0 to 4792)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Catacombs Entry mesh_collision.h"

void catacombs_entry_collision_init(CollisionRoom *r) {
    r->wall_count = CATACOMBS_ENTRY_WALL_COUNT;
    r->min_x = -750;
    r->max_x = 4800;
    r->min_z = 0;
    r->max_z = 4792;

    /* Wall 0 (avg Y: -392) */
    r->walls[0].x1 =    -321;  r->walls[0].z1 =    1400;
    r->walls[0].x2 =    -750;  r->walls[0].z2 =    1400;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4095;
    r->walls[0].y_min =    -799;  r->walls[0].y_max =       2;

    /* Wall 1 (avg Y: -392) */
    r->walls[1].x1 =     750;  r->walls[1].z1 =    1400;
    r->walls[1].x2 =     321;  r->walls[1].z2 =    1400;
    r->walls[1].nx =       0;  r->walls[1].nz =   -4095;
    r->walls[1].y_min =    -799;  r->walls[1].y_max =       2;

    /* Wall 2 (avg Y: -550) */
    r->walls[2].x1 =    -750;  r->walls[2].z1 =       0;
    r->walls[2].x2 =     750;  r->walls[2].z2 =       0;
    r->walls[2].nx =       0;  r->walls[2].nz =    4096;
    r->walls[2].y_min =   -1100;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -474) */
    r->walls[3].x1 =     750;  r->walls[3].z1 =       0;
    r->walls[3].x2 =     750;  r->walls[3].z2 =    1400;
    r->walls[3].nx =   -4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =   -1100;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -474) */
    r->walls[4].x1 =    -750;  r->walls[4].z1 =    1400;
    r->walls[4].x2 =    -750;  r->walls[4].z2 =       0;
    r->walls[4].nx =    4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =   -1100;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -32) */
    r->walls[5].x1 =     321;  r->walls[5].z1 =    1400;
    r->walls[5].x2 =     321;  r->walls[5].z2 =    4192;
    r->walls[5].nx =   -4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -770;  r->walls[5].y_max =     719;

    /* Wall 6 (avg Y: -32) */
    r->walls[6].x1 =    -321;  r->walls[6].z1 =    4192;
    r->walls[6].x2 =    -321;  r->walls[6].z2 =    1400;
    r->walls[6].nx =    4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =    -770;  r->walls[6].y_max =     719;

    /* Wall 7 (avg Y: 319) */
    r->walls[7].x1 =    -321;  r->walls[7].z1 =    4792;
    r->walls[7].x2 =    -321;  r->walls[7].z2 =    4192;
    r->walls[7].nx =    4096;  r->walls[7].nz =       0;
    r->walls[7].y_min =     -80;  r->walls[7].y_max =     719;

    /* Wall 8 (avg Y: 319) */
    r->walls[8].x1 =    1621;  r->walls[8].z1 =    4192;
    r->walls[8].x2 =    1621;  r->walls[8].z2 =    4792;
    r->walls[8].nx =   -4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =     -80;  r->walls[8].y_max =     721;

    /* Wall 9 (avg Y: 319) */
    r->walls[9].x1 =    1621;  r->walls[9].z1 =    4792;
    r->walls[9].x2 =    -321;  r->walls[9].z2 =    4792;
    r->walls[9].nx =       0;  r->walls[9].nz =   -4096;
    r->walls[9].y_min =     -80;  r->walls[9].y_max =     719;

    /* Wall 10 (avg Y: 319) */
    r->walls[10].x1 =     321;  r->walls[10].z1 =    4192;
    r->walls[10].x2 =     971;  r->walls[10].z2 =    4192;
    r->walls[10].nx =       0;  r->walls[10].nz =    4095;
    r->walls[10].y_min =     -80;  r->walls[10].y_max =     721;

    /* Wall 11 (avg Y: 840) */
    r->walls[11].x1 =    1800;  r->walls[11].z1 =    1701;
    r->walls[11].x2 =    1621;  r->walls[11].z2 =    1701;
    r->walls[11].nx =       0;  r->walls[11].nz =   -4096;
    r->walls[11].y_min =     440;  r->walls[11].y_max =    1240;

    /* Wall 12 (avg Y: 580) */
    r->walls[12].x1 =    1621;  r->walls[12].z1 =    2101;
    r->walls[12].x2 =    1621;  r->walls[12].z2 =    4192;
    r->walls[12].nx =   -4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =     -80;  r->walls[12].y_max =    1240;

    /* Wall 13 (avg Y: 580) */
    r->walls[13].x1 =     971;  r->walls[13].z1 =    4192;
    r->walls[13].x2 =     971;  r->walls[13].z2 =    2101;
    r->walls[13].nx =    4095;  r->walls[13].nz =       0;
    r->walls[13].y_min =     -80;  r->walls[13].y_max =    1240;

    /* Wall 14 (avg Y: 840) */
    r->walls[14].x1 =     971;  r->walls[14].z1 =    2101;
    r->walls[14].x2 =     971;  r->walls[14].z2 =    1101;
    r->walls[14].nx =    4096;  r->walls[14].nz =       0;
    r->walls[14].y_min =     440;  r->walls[14].y_max =    1240;

    /* Wall 15 (avg Y: 840) */
    r->walls[15].x1 =    1621;  r->walls[15].z1 =    1701;
    r->walls[15].x2 =    1621;  r->walls[15].z2 =    2101;
    r->walls[15].nx =   -4096;  r->walls[15].nz =       0;
    r->walls[15].y_min =     440;  r->walls[15].y_max =    1240;

    /* Wall 16 (avg Y: 840) */
    r->walls[16].x1 =     971;  r->walls[16].z1 =    1101;
    r->walls[16].x2 =    1800;  r->walls[16].z2 =    1101;
    r->walls[16].nx =       0;  r->walls[16].nz =    4096;
    r->walls[16].y_min =     440;  r->walls[16].y_max =    1240;

    /* Wall 17 (avg Y: 840) */
    r->walls[17].x1 =    1800;  r->walls[17].z1 =    2301;
    r->walls[17].x2 =    1800;  r->walls[17].z2 =    1701;
    r->walls[17].nx =    4096;  r->walls[17].nz =       0;
    r->walls[17].y_min =     440;  r->walls[17].y_max =    1240;

    /* Wall 18 (avg Y: 840) */
    r->walls[18].x1 =    1800;  r->walls[18].z1 =    1101;
    r->walls[18].x2 =    1800;  r->walls[18].z2 =     501;
    r->walls[18].nx =    4096;  r->walls[18].nz =       0;
    r->walls[18].y_min =     440;  r->walls[18].y_max =    1240;

    /* Wall 19 (avg Y: 840) */
    r->walls[19].x1 =    4800;  r->walls[19].z1 =     501;
    r->walls[19].x2 =    4800;  r->walls[19].z2 =    2301;
    r->walls[19].nx =   -4096;  r->walls[19].nz =       0;
    r->walls[19].y_min =     440;  r->walls[19].y_max =    1240;

    /* Wall 20 (avg Y: 840) */
    r->walls[20].x1 =    1800;  r->walls[20].z1 =     501;
    r->walls[20].x2 =    4800;  r->walls[20].z2 =     501;
    r->walls[20].nx =       0;  r->walls[20].nz =    4096;
    r->walls[20].y_min =     440;  r->walls[20].y_max =    1240;

    /* Wall 21 (avg Y: 840) */
    r->walls[21].x1 =    4800;  r->walls[21].z1 =    2301;
    r->walls[21].x2 =    1800;  r->walls[21].z2 =    2301;
    r->walls[21].nx =       0;  r->walls[21].nz =   -4096;
    r->walls[21].y_min =     440;  r->walls[21].y_max =    1240;

    /* Wall 22 (avg Y: 840) */
    r->walls[22].x1 =    2400;  r->walls[22].z1 =    1701;
    r->walls[22].x2 =    3000;  r->walls[22].z2 =    1701;
    r->walls[22].nx =       0;  r->walls[22].nz =    4096;
    r->walls[22].y_min =     440;  r->walls[22].y_max =    1240;

    /* Wall 23 (avg Y: 840) */
    r->walls[23].x1 =    2400;  r->walls[23].z1 =    1101;
    r->walls[23].x2 =    2400;  r->walls[23].z2 =    1701;
    r->walls[23].nx =   -4096;  r->walls[23].nz =       0;
    r->walls[23].y_min =     440;  r->walls[23].y_max =    1240;

    /* Wall 24 (avg Y: 840) */
    r->walls[24].x1 =    3000;  r->walls[24].z1 =    1701;
    r->walls[24].x2 =    3000;  r->walls[24].z2 =    1101;
    r->walls[24].nx =    4096;  r->walls[24].nz =       0;
    r->walls[24].y_min =     440;  r->walls[24].y_max =    1240;

    /* Wall 25 (avg Y: 840) */
    r->walls[25].x1 =    3000;  r->walls[25].z1 =    1101;
    r->walls[25].x2 =    2400;  r->walls[25].z2 =    1101;
    r->walls[25].nx =       0;  r->walls[25].nz =   -4096;
    r->walls[25].y_min =     440;  r->walls[25].y_max =    1240;

    /* Wall 26 (avg Y: 840) */
    r->walls[26].x1 =    4199;  r->walls[26].z1 =    1101;
    r->walls[26].x2 =    3599;  r->walls[26].z2 =    1101;
    r->walls[26].nx =       0;  r->walls[26].nz =   -4096;
    r->walls[26].y_min =     440;  r->walls[26].y_max =    1240;

    /* Wall 27 (avg Y: 840) */
    r->walls[27].x1 =    3599;  r->walls[27].z1 =    1701;
    r->walls[27].x2 =    4199;  r->walls[27].z2 =    1701;
    r->walls[27].nx =       0;  r->walls[27].nz =    4096;
    r->walls[27].y_min =     440;  r->walls[27].y_max =    1240;

    /* Wall 28 (avg Y: 840) */
    r->walls[28].x1 =    3599;  r->walls[28].z1 =    1101;
    r->walls[28].x2 =    3599;  r->walls[28].z2 =    1701;
    r->walls[28].nx =   -4096;  r->walls[28].nz =       0;
    r->walls[28].y_min =     440;  r->walls[28].y_max =    1240;

    /* Wall 29 (avg Y: 840) */
    r->walls[29].x1 =    4199;  r->walls[29].z1 =    1701;
    r->walls[29].x2 =    4199;  r->walls[29].z2 =    1101;
    r->walls[29].nx =    4096;  r->walls[29].nz =       0;
    r->walls[29].y_min =     440;  r->walls[29].y_max =    1240;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-750 to 750)  z(0 to 1400)
     * FLOOR   1: y=  1240  x(1621 to 1800)  z(1101 to 1701)
     * FLOOR   2: y=   719  x(-321 to 1621)  z(4192 to 4792)
     * FLOOR   3: y=   360  x(-321 to 321)  z(1400 to 4192)
     * FLOOR   4: y=  1240  x(1800 to 4800)  z(501 to 2301)
     * FLOOR   5: y=   981  x(971 to 1621)  z(2101 to 4192)
     * FLOOR   6: y=  1240  x(971 to 1621)  z(1101 to 2101)
     */
}
