/*
 * Auto-generated collision data from: Cleaver Corridor mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  4
 * Floors: 1
 * Bounds: X(0 to 4800)  Z(-300 to 300)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Cleaver Corridor mesh_collision.h"

void cleaver_corridor_collision_init(CollisionRoom *r) {
    r->wall_count = CLEAVER_CORRIDOR_WALL_COUNT;
    r->min_x = 0;
    r->max_x = 4800;
    r->min_z = -300;
    r->max_z = 300;

    /* Wall 0 (avg Y: -400) */
    r->walls[0].x1 =    4800;  r->walls[0].z1 =     300;
    r->walls[0].x2 =       0;  r->walls[0].z2 =     300;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =    -800;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -400) */
    r->walls[1].x1 =       0;  r->walls[1].z1 =    -300;
    r->walls[1].x2 =    4800;  r->walls[1].z2 =    -300;
    r->walls[1].nx =       0;  r->walls[1].nz =    4096;
    r->walls[1].y_min =    -800;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -400) */
    r->walls[2].x1 =    4800;  r->walls[2].z1 =    -300;
    r->walls[2].x2 =    4800;  r->walls[2].z2 =     300;
    r->walls[2].nx =   -4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -800;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -400) */
    r->walls[3].x1 =       0;  r->walls[3].z1 =     300;
    r->walls[3].x2 =       0;  r->walls[3].z2 =    -300;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -800;  r->walls[3].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(0 to 4800)  z(-300 to 300)
     */
}
