/*
 * Auto-generated collision data from: Cleaver Corridor mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef CLEAVER_CORRIDOR_MESH_COLLISION_H
#define CLEAVER_CORRIDOR_MESH_COLLISION_H

#include "collision.h"

#define CLEAVER_CORRIDOR_WALL_COUNT  4
#define CLEAVER_CORRIDOR_FLOOR_COUNT 1

void cleaver_corridor_collision_init(CollisionRoom *r);

#endif /* CLEAVER_CORRIDOR_MESH_COLLISION_H */
