/*
 * Auto-generated collision data from: Crucifix Corridor mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef CRUCIFIX_CORRIDOR_MESH_COLLISION_H
#define CRUCIFIX_CORRIDOR_MESH_COLLISION_H

#include "collision.h"

#define CRUCIFIX_CORRIDOR_WALL_COUNT  12
#define CRUCIFIX_CORRIDOR_FLOOR_COUNT 3

void crucifix_corridor_collision_init(CollisionRoom *r);

#endif /* CRUCIFIX_CORRIDOR_MESH_COLLISION_H */
