/*
 * Auto-generated collision data from: Dead End mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef DEAD_END_MESH_COLLISION_H
#define DEAD_END_MESH_COLLISION_H

#include "collision.h"

#define DEAD_END_WALL_COUNT  4
#define DEAD_END_FLOOR_COUNT 1

void dead_end_collision_init(CollisionRoom *r);

#endif /* DEAD_END_MESH_COLLISION_H */
