/*
 * Auto-generated collision data from: Gaol Cells mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef GAOL_CELLS_MESH_COLLISION_H
#define GAOL_CELLS_MESH_COLLISION_H

#include "collision.h"

#define GAOL_CELLS_WALL_COUNT  51
#define GAOL_CELLS_FLOOR_COUNT 2

void gaol_cells_collision_init(CollisionRoom *r);

#endif /* GAOL_CELLS_MESH_COLLISION_H */
