/*
 * Auto-generated collision data from: Gaol Entry mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef GAOL_ENTRY_MESH_COLLISION_H
#define GAOL_ENTRY_MESH_COLLISION_H

#include "collision.h"

#define GAOL_ENTRY_WALL_COUNT  4
#define GAOL_ENTRY_FLOOR_COUNT 1

void gaol_entry_collision_init(CollisionRoom *r);

#endif /* GAOL_ENTRY_MESH_COLLISION_H */
