/*
 * Auto-generated collision data from: H Corridor mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  10
 * Floors: 3
 * Bounds: X(0 to 2400)  Z(0 to 5400)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "H Corridor mesh_collision.h"

void h_corridor_collision_init(CollisionRoom *r) {
    r->wall_count = H_CORRIDOR_WALL_COUNT;
    r->min_x = 0;
    r->max_x = 2400;
    r->min_z = 0;
    r->max_z = 5400;

    /* Wall 0 (avg Y: -400) */
    r->walls[0].x1 =     600;  r->walls[0].z1 =       0;
    r->walls[0].x2 =     599;  r->walls[0].z2 =    1199;
    r->walls[0].nx =   -4095;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -800;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -400) */
    r->walls[1].x1 =       0;  r->walls[1].z1 =    5400;
    r->walls[1].x2 =       0;  r->walls[1].z2 =       0;
    r->walls[1].nx =    4095;  r->walls[1].nz =       0;
    r->walls[1].y_min =    -800;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -400) */
    r->walls[2].x1 =     599;  r->walls[2].z1 =    1800;
    r->walls[2].x2 =     599;  r->walls[2].z2 =    5400;
    r->walls[2].nx =   -4095;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -800;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -400) */
    r->walls[3].x1 =       0;  r->walls[3].z1 =       0;
    r->walls[3].x2 =     600;  r->walls[3].z2 =       0;
    r->walls[3].nx =       0;  r->walls[3].nz =    4095;
    r->walls[3].y_min =    -800;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -400) */
    r->walls[4].x1 =     599;  r->walls[4].z1 =    1199;
    r->walls[4].x2 =    1800;  r->walls[4].z2 =    1200;
    r->walls[4].nx =       0;  r->walls[4].nz =    4095;
    r->walls[4].y_min =    -800;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -400) */
    r->walls[5].x1 =    1800;  r->walls[5].z1 =       0;
    r->walls[5].x2 =    2400;  r->walls[5].z2 =       0;
    r->walls[5].nx =       0;  r->walls[5].nz =    4095;
    r->walls[5].y_min =    -800;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -400) */
    r->walls[6].x1 =    2400;  r->walls[6].z1 =    1800;
    r->walls[6].x2 =     599;  r->walls[6].z2 =    1800;
    r->walls[6].nx =       0;  r->walls[6].nz =   -4096;
    r->walls[6].y_min =    -800;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -400) */
    r->walls[7].x1 =    2400;  r->walls[7].z1 =       0;
    r->walls[7].x2 =    2400;  r->walls[7].z2 =    1800;
    r->walls[7].nx =   -4096;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -800;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -400) */
    r->walls[8].x1 =    1800;  r->walls[8].z1 =    1200;
    r->walls[8].x2 =    1800;  r->walls[8].z2 =       0;
    r->walls[8].nx =    4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =    -800;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -400) */
    r->walls[9].x1 =     599;  r->walls[9].z1 =    5400;
    r->walls[9].x2 =       0;  r->walls[9].z2 =    5400;
    r->walls[9].nx =       0;  r->walls[9].nz =   -4096;
    r->walls[9].y_min =    -800;  r->walls[9].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(0 to 600)  z(0 to 5400)
     * FLOOR   1: y=     0  x(599 to 2400)  z(1199 to 1800)
     * FLOOR   2: y=     0  x(1800 to 2400)  z(0 to 1800)
     */
}
