/*
 * Auto-generated collision data from: H Corridor mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef H_CORRIDOR_MESH_COLLISION_H
#define H_CORRIDOR_MESH_COLLISION_H

#include "collision.h"

#define H_CORRIDOR_WALL_COUNT  10
#define H_CORRIDOR_FLOOR_COUNT 3

void h_corridor_collision_init(CollisionRoom *r);

#endif /* H_CORRIDOR_MESH_COLLISION_H */
