/*
 * Auto-generated collision data from: Meat Plant mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef MEAT_PLANT_MESH_COLLISION_H
#define MEAT_PLANT_MESH_COLLISION_H

#include "collision.h"

#define MEAT_PLANT_WALL_COUNT  77
#define MEAT_PLANT_FLOOR_COUNT 5

void meat_plant_collision_init(CollisionRoom *r);

#endif /* MEAT_PLANT_MESH_COLLISION_H */
