/*
 * Auto-generated collision data from: Meat Plant mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  77
 * Floors: 5
 * Bounds: X(-3299 to 3299)  Z(0 to 6600)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Meat Plant mesh_collision.h"

void meat_plant_collision_init(CollisionRoom *r) {
    r->wall_count = MEAT_PLANT_WALL_COUNT;
    r->min_x = -3299;
    r->max_x = 3299;
    r->min_z = 0;
    r->max_z = 6600;

    /* Wall 0 (avg Y: -300) */
    r->walls[0].x1 =    -900;  r->walls[0].z1 =    5199;
    r->walls[0].x2 =    -900;  r->walls[0].z2 =    5399;
    r->walls[0].nx =   -4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -600;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -300) */
    r->walls[1].x1 =   -1299;  r->walls[1].z1 =    3000;
    r->walls[1].x2 =   -1100;  r->walls[1].z2 =    3000;
    r->walls[1].nx =       0;  r->walls[1].nz =    4096;
    r->walls[1].y_min =    -600;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -300) */
    r->walls[2].x1 =   -1499;  r->walls[2].z1 =    4800;
    r->walls[2].x2 =   -1499;  r->walls[2].z2 =    5000;
    r->walls[2].nx =   -4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -600;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -400) */
    r->walls[3].x1 =   -3299;  r->walls[3].z1 =    2399;
    r->walls[3].x2 =   -2700;  r->walls[3].z2 =    2399;
    r->walls[3].nx =       0;  r->walls[3].nz =    4096;
    r->walls[3].y_min =    -800;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -400) */
    r->walls[4].x1 =   -2700;  r->walls[4].z1 =     600;
    r->walls[4].x2 =    -900;  r->walls[4].z2 =     600;
    r->walls[4].nx =       0;  r->walls[4].nz =    4096;
    r->walls[4].y_min =    -800;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -400) */
    r->walls[5].x1 =    2700;  r->walls[5].z1 =    6000;
    r->walls[5].x2 =     900;  r->walls[5].z2 =    6000;
    r->walls[5].nx =       0;  r->walls[5].nz =   -4096;
    r->walls[5].y_min =    -800;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -400) */
    r->walls[6].x1 =    3299;  r->walls[6].z1 =    4199;
    r->walls[6].x2 =    2700;  r->walls[6].z2 =    4199;
    r->walls[6].nx =       0;  r->walls[6].nz =   -4096;
    r->walls[6].y_min =    -800;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -400) */
    r->walls[7].x1 =   -3299;  r->walls[7].z1 =    4199;
    r->walls[7].x2 =   -3299;  r->walls[7].z2 =    2399;
    r->walls[7].nx =    4096;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -800;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -400) */
    r->walls[8].x1 =   -2700;  r->walls[8].z1 =    2399;
    r->walls[8].x2 =   -2700;  r->walls[8].z2 =     600;
    r->walls[8].nx =    4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =    -800;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -400) */
    r->walls[9].x1 =   -2700;  r->walls[9].z1 =    6000;
    r->walls[9].x2 =   -2700;  r->walls[9].z2 =    4199;
    r->walls[9].nx =    4096;  r->walls[9].nz =       0;
    r->walls[9].y_min =    -800;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -400) */
    r->walls[10].x1 =    -900;  r->walls[10].z1 =    6600;
    r->walls[10].x2 =    -900;  r->walls[10].z2 =    6000;
    r->walls[10].nx =    4096;  r->walls[10].nz =       0;
    r->walls[10].y_min =    -800;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -400) */
    r->walls[11].x1 =    -900;  r->walls[11].z1 =     600;
    r->walls[11].x2 =    -900;  r->walls[11].z2 =       0;
    r->walls[11].nx =    4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -800;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -400) */
    r->walls[12].x1 =     900;  r->walls[12].z1 =       0;
    r->walls[12].x2 =     900;  r->walls[12].z2 =     600;
    r->walls[12].nx =   -4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =    -800;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -400) */
    r->walls[13].x1 =     900;  r->walls[13].z1 =    6000;
    r->walls[13].x2 =     900;  r->walls[13].z2 =    6600;
    r->walls[13].nx =   -4096;  r->walls[13].nz =       0;
    r->walls[13].y_min =    -800;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -400) */
    r->walls[14].x1 =     900;  r->walls[14].z1 =    6600;
    r->walls[14].x2 =    -900;  r->walls[14].z2 =    6600;
    r->walls[14].nx =       0;  r->walls[14].nz =   -4096;
    r->walls[14].y_min =    -800;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -400) */
    r->walls[15].x1 =    2700;  r->walls[15].z1 =    2399;
    r->walls[15].x2 =    3299;  r->walls[15].z2 =    2399;
    r->walls[15].nx =       0;  r->walls[15].nz =    4096;
    r->walls[15].y_min =    -800;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -400) */
    r->walls[16].x1 =    3299;  r->walls[16].z1 =    2399;
    r->walls[16].x2 =    3299;  r->walls[16].z2 =    4199;
    r->walls[16].nx =   -4096;  r->walls[16].nz =       0;
    r->walls[16].y_min =    -800;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -400) */
    r->walls[17].x1 =    2700;  r->walls[17].z1 =    4199;
    r->walls[17].x2 =    2700;  r->walls[17].z2 =    6000;
    r->walls[17].nx =   -4096;  r->walls[17].nz =       0;
    r->walls[17].y_min =    -800;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -400) */
    r->walls[18].x1 =   -2700;  r->walls[18].z1 =    4199;
    r->walls[18].x2 =   -3299;  r->walls[18].z2 =    4199;
    r->walls[18].nx =       0;  r->walls[18].nz =   -4096;
    r->walls[18].y_min =    -800;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -400) */
    r->walls[19].x1 =     900;  r->walls[19].z1 =     600;
    r->walls[19].x2 =    2700;  r->walls[19].z2 =     600;
    r->walls[19].nx =       0;  r->walls[19].nz =    4096;
    r->walls[19].y_min =    -800;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -400) */
    r->walls[20].x1 =    -900;  r->walls[20].z1 =    6000;
    r->walls[20].x2 =   -2700;  r->walls[20].z2 =    6000;
    r->walls[20].nx =       0;  r->walls[20].nz =   -4096;
    r->walls[20].y_min =    -800;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -400) */
    r->walls[21].x1 =    2700;  r->walls[21].z1 =     600;
    r->walls[21].x2 =    2700;  r->walls[21].z2 =    2399;
    r->walls[21].nx =   -4096;  r->walls[21].nz =       0;
    r->walls[21].y_min =    -800;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -400) */
    r->walls[22].x1 =    -900;  r->walls[22].z1 =       0;
    r->walls[22].x2 =     900;  r->walls[22].z2 =       0;
    r->walls[22].nx =       0;  r->walls[22].nz =    4096;
    r->walls[22].y_min =    -800;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -300) */
    r->walls[23].x1 =    1100;  r->walls[23].z1 =    3999;
    r->walls[23].x2 =    1100;  r->walls[23].z2 =    4199;
    r->walls[23].nx =   -4096;  r->walls[23].nz =       0;
    r->walls[23].y_min =    -600;  r->walls[23].y_max =       0;

    /* Wall 24 (avg Y: -300) */
    r->walls[24].x1 =     900;  r->walls[24].z1 =    5399;
    r->walls[24].x2 =     900;  r->walls[24].z2 =    5199;
    r->walls[24].nx =    4096;  r->walls[24].nz =       0;
    r->walls[24].y_min =    -600;  r->walls[24].y_max =       0;

    /* Wall 25 (avg Y: -300) */
    r->walls[25].x1 =    1100;  r->walls[25].z1 =    5000;
    r->walls[25].x2 =    1300;  r->walls[25].z2 =    5000;
    r->walls[25].nx =       0;  r->walls[25].nz =    4096;
    r->walls[25].y_min =    -600;  r->walls[25].y_max =       0;

    /* Wall 26 (avg Y: -300) */
    r->walls[26].x1 =    -300;  r->walls[26].z1 =    1199;
    r->walls[26].x2 =    -300;  r->walls[26].z2 =    1400;
    r->walls[26].nx =   -4096;  r->walls[26].nz =       0;
    r->walls[26].y_min =    -600;  r->walls[26].y_max =       0;

    /* Wall 27 (avg Y: -300) */
    r->walls[27].x1 =     700;  r->walls[27].z1 =    4400;
    r->walls[27].x2 =     700;  r->walls[27].z2 =    4600;
    r->walls[27].nx =   -4096;  r->walls[27].nz =       0;
    r->walls[27].y_min =    -600;  r->walls[27].y_max =       0;

    /* Wall 28 (avg Y: -300) */
    r->walls[28].x1 =   -1699;  r->walls[28].z1 =    2000;
    r->walls[28].x2 =   -1900;  r->walls[28].z2 =    2000;
    r->walls[28].nx =       0;  r->walls[28].nz =   -4096;
    r->walls[28].y_min =    -600;  r->walls[28].y_max =       0;

    /* Wall 29 (avg Y: -300) */
    r->walls[29].x1 =   -1699;  r->walls[29].z1 =    1800;
    r->walls[29].x2 =   -1699;  r->walls[29].z2 =    2000;
    r->walls[29].nx =   -4096;  r->walls[29].nz =       0;
    r->walls[29].y_min =    -600;  r->walls[29].y_max =       0;

    /* Wall 30 (avg Y: -300) */
    r->walls[30].x1 =    1500;  r->walls[30].z1 =    1600;
    r->walls[30].x2 =    1300;  r->walls[30].z2 =    1600;
    r->walls[30].nx =       0;  r->walls[30].nz =   -4096;
    r->walls[30].y_min =    -600;  r->walls[30].y_max =       0;

    /* Wall 31 (avg Y: -300) */
    r->walls[31].x1 =   -1100;  r->walls[31].z1 =    3799;
    r->walls[31].x2 =   -1299;  r->walls[31].z2 =    3799;
    r->walls[31].nx =       0;  r->walls[31].nz =   -4096;
    r->walls[31].y_min =    -600;  r->walls[31].y_max =       0;

    /* Wall 32 (avg Y: -300) */
    r->walls[32].x1 =   -1499;  r->walls[32].z1 =    5000;
    r->walls[32].x2 =   -1299;  r->walls[32].z2 =    5000;
    r->walls[32].nx =       0;  r->walls[32].nz =    4096;
    r->walls[32].y_min =    -600;  r->walls[32].y_max =       0;

    /* Wall 33 (avg Y: -300) */
    r->walls[33].x1 =     900;  r->walls[33].z1 =    5199;
    r->walls[33].x2 =    1100;  r->walls[33].z2 =    5199;
    r->walls[33].nx =       0;  r->walls[33].nz =    4096;
    r->walls[33].y_min =    -600;  r->walls[33].y_max =       0;

    /* Wall 34 (avg Y: -300) */
    r->walls[34].x1 =     300;  r->walls[34].z1 =    1400;
    r->walls[34].x2 =     300;  r->walls[34].z2 =    1199;
    r->walls[34].nx =    4096;  r->walls[34].nz =       0;
    r->walls[34].y_min =    -600;  r->walls[34].y_max =       0;

    /* Wall 35 (avg Y: -300) */
    r->walls[35].x1 =   -1900;  r->walls[35].z1 =    2399;
    r->walls[35].x2 =   -2100;  r->walls[35].z2 =    2399;
    r->walls[35].nx =       0;  r->walls[35].nz =   -4096;
    r->walls[35].y_min =    -600;  r->walls[35].y_max =       0;

    /* Wall 36 (avg Y: -300) */
    r->walls[36].x1 =    1100;  r->walls[36].z1 =    5199;
    r->walls[36].x2 =    1100;  r->walls[36].z2 =    5000;
    r->walls[36].nx =    4096;  r->walls[36].nz =       0;
    r->walls[36].y_min =    -600;  r->walls[36].y_max =       0;

    /* Wall 37 (avg Y: -300) */
    r->walls[37].x1 =     900;  r->walls[37].z1 =    4199;
    r->walls[37].x2 =     900;  r->walls[37].z2 =    4399;
    r->walls[37].nx =   -4096;  r->walls[37].nz =       0;
    r->walls[37].y_min =    -600;  r->walls[37].y_max =       0;

    /* Wall 38 (avg Y: -300) */
    r->walls[38].x1 =   -1499;  r->walls[38].z1 =    1600;
    r->walls[38].x2 =   -1499;  r->walls[38].z2 =    1800;
    r->walls[38].nx =   -4096;  r->walls[38].nz =       0;
    r->walls[38].y_min =    -600;  r->walls[38].y_max =       0;

    /* Wall 39 (avg Y: -300) */
    r->walls[39].x1 =    -900;  r->walls[39].z1 =    2800;
    r->walls[39].x2 =    -900;  r->walls[39].z2 =    2599;
    r->walls[39].nx =    4096;  r->walls[39].nz =       0;
    r->walls[39].y_min =    -600;  r->walls[39].y_max =       0;

    /* Wall 40 (avg Y: -300) */
    r->walls[40].x1 =    -900;  r->walls[40].z1 =    4199;
    r->walls[40].x2 =   -1100;  r->walls[40].z2 =    4199;
    r->walls[40].nx =       0;  r->walls[40].nz =   -4096;
    r->walls[40].y_min =    -600;  r->walls[40].y_max =       0;

    /* Wall 41 (avg Y: -300) */
    r->walls[41].x1 =   -2100;  r->walls[41].z1 =    4599;
    r->walls[41].x2 =   -1900;  r->walls[41].z2 =    4600;
    r->walls[41].nx =       0;  r->walls[41].nz =    4095;
    r->walls[41].y_min =    -600;  r->walls[41].y_max =       0;

    /* Wall 42 (avg Y: -300) */
    r->walls[42].x1 =     900;  r->walls[42].z1 =    4399;
    r->walls[42].x2 =     700;  r->walls[42].z2 =    4400;
    r->walls[42].nx =       0;  r->walls[42].nz =   -4095;
    r->walls[42].y_min =    -600;  r->walls[42].y_max =       0;

    /* Wall 43 (avg Y: -300) */
    r->walls[43].x1 =    -900;  r->walls[43].z1 =    4599;
    r->walls[43].x2 =    -900;  r->walls[43].z2 =    4199;
    r->walls[43].nx =    4096;  r->walls[43].nz =       0;
    r->walls[43].y_min =    -600;  r->walls[43].y_max =       0;

    /* Wall 44 (avg Y: -300) */
    r->walls[44].x1 =    1500;  r->walls[44].z1 =    4800;
    r->walls[44].x2 =    1500;  r->walls[44].z2 =    4599;
    r->walls[44].nx =    4096;  r->walls[44].nz =       0;
    r->walls[44].y_min =    -600;  r->walls[44].y_max =       0;

    /* Wall 45 (avg Y: -300) */
    r->walls[45].x1 =   -1100;  r->walls[45].z1 =    4199;
    r->walls[45].x2 =   -1100;  r->walls[45].z2 =    3799;
    r->walls[45].nx =    4096;  r->walls[45].nz =       0;
    r->walls[45].y_min =    -600;  r->walls[45].y_max =       0;

    /* Wall 46 (avg Y: -300) */
    r->walls[46].x1 =   -1299;  r->walls[46].z1 =    3799;
    r->walls[46].x2 =   -1299;  r->walls[46].z2 =    3000;
    r->walls[46].nx =    4096;  r->walls[46].nz =       0;
    r->walls[46].y_min =    -600;  r->walls[46].y_max =       0;

    /* Wall 47 (avg Y: -300) */
    r->walls[47].x1 =     700;  r->walls[47].z1 =    2599;
    r->walls[47].x2 =     700;  r->walls[47].z2 =    2800;
    r->walls[47].nx =   -4096;  r->walls[47].nz =       0;
    r->walls[47].y_min =    -600;  r->walls[47].y_max =       0;

    /* Wall 48 (avg Y: -300) */
    r->walls[48].x1 =    1100;  r->walls[48].z1 =    4199;
    r->walls[48].x2 =     900;  r->walls[48].z2 =    4199;
    r->walls[48].nx =       0;  r->walls[48].nz =   -4096;
    r->walls[48].y_min =    -600;  r->walls[48].y_max =       0;

    /* Wall 49 (avg Y: -300) */
    r->walls[49].x1 =    1700;  r->walls[49].z1 =    2000;
    r->walls[49].x2 =    1500;  r->walls[49].z2 =    2000;
    r->walls[49].nx =       0;  r->walls[49].nz =   -4096;
    r->walls[49].y_min =    -600;  r->walls[49].y_max =       0;

    /* Wall 50 (avg Y: -300) */
    r->walls[50].x1 =    1300;  r->walls[50].z1 =    1600;
    r->walls[50].x2 =    1300;  r->walls[50].z2 =    1400;
    r->walls[50].nx =    4096;  r->walls[50].nz =       0;
    r->walls[50].y_min =    -600;  r->walls[50].y_max =       0;

    /* Wall 51 (avg Y: -300) */
    r->walls[51].x1 =   -1100;  r->walls[51].z1 =    2800;
    r->walls[51].x2 =    -900;  r->walls[51].z2 =    2800;
    r->walls[51].nx =       0;  r->walls[51].nz =    4096;
    r->walls[51].y_min =    -600;  r->walls[51].y_max =       0;

    /* Wall 52 (avg Y: -300) */
    r->walls[52].x1 =     300;  r->walls[52].z1 =    1199;
    r->walls[52].x2 =    -300;  r->walls[52].z2 =    1199;
    r->walls[52].nx =       0;  r->walls[52].nz =   -4096;
    r->walls[52].y_min =    -600;  r->walls[52].y_max =       0;

    /* Wall 53 (avg Y: -300) */
    r->walls[53].x1 =    1300;  r->walls[53].z1 =    1400;
    r->walls[53].x2 =     300;  r->walls[53].z2 =    1400;
    r->walls[53].nx =       0;  r->walls[53].nz =   -4096;
    r->walls[53].y_min =    -600;  r->walls[53].y_max =       0;

    /* Wall 54 (avg Y: -300) */
    r->walls[54].x1 =   -1299;  r->walls[54].z1 =    5000;
    r->walls[54].x2 =   -1299;  r->walls[54].z2 =    5199;
    r->walls[54].nx =   -4096;  r->walls[54].nz =       0;
    r->walls[54].y_min =    -600;  r->walls[54].y_max =       0;

    /* Wall 55 (avg Y: -300) */
    r->walls[55].x1 =    1300;  r->walls[55].z1 =    5000;
    r->walls[55].x2 =    1300;  r->walls[55].z2 =    4800;
    r->walls[55].nx =    4096;  r->walls[55].nz =       0;
    r->walls[55].y_min =    -600;  r->walls[55].y_max =       0;

    /* Wall 56 (avg Y: -300) */
    r->walls[56].x1 =   -1900;  r->walls[56].z1 =    4800;
    r->walls[56].x2 =   -1499;  r->walls[56].z2 =    4800;
    r->walls[56].nx =       0;  r->walls[56].nz =    4096;
    r->walls[56].y_min =    -600;  r->walls[56].y_max =       0;

    /* Wall 57 (avg Y: -300) */
    r->walls[57].x1 =   -1299;  r->walls[57].z1 =    5199;
    r->walls[57].x2 =    -900;  r->walls[57].z2 =    5199;
    r->walls[57].nx =       0;  r->walls[57].nz =    4096;
    r->walls[57].y_min =    -600;  r->walls[57].y_max =       0;

    /* Wall 58 (avg Y: -300) */
    r->walls[58].x1 =    1700;  r->walls[58].z1 =    3999;
    r->walls[58].x2 =    1100;  r->walls[58].z2 =    3999;
    r->walls[58].nx =       0;  r->walls[58].nz =   -4096;
    r->walls[58].y_min =    -600;  r->walls[58].y_max =       0;

    /* Wall 59 (avg Y: -300) */
    r->walls[59].x1 =    1700;  r->walls[59].z1 =    2800;
    r->walls[59].x2 =    1700;  r->walls[59].z2 =    2000;
    r->walls[59].nx =    4096;  r->walls[59].nz =       0;
    r->walls[59].y_min =    -600;  r->walls[59].y_max =       0;

    /* Wall 60 (avg Y: -300) */
    r->walls[60].x1 =   -1299;  r->walls[60].z1 =    1600;
    r->walls[60].x2 =   -1499;  r->walls[60].z2 =    1600;
    r->walls[60].nx =       0;  r->walls[60].nz =   -4096;
    r->walls[60].y_min =    -600;  r->walls[60].y_max =       0;

    /* Wall 61 (avg Y: -300) */
    r->walls[61].x1 =    1500;  r->walls[61].z1 =    2000;
    r->walls[61].x2 =    1500;  r->walls[61].z2 =    1600;
    r->walls[61].nx =    4096;  r->walls[61].nz =       0;
    r->walls[61].y_min =    -600;  r->walls[61].y_max =       0;

    /* Wall 62 (avg Y: -300) */
    r->walls[62].x1 =   -1900;  r->walls[62].z1 =    2000;
    r->walls[62].x2 =   -1900;  r->walls[62].z2 =    2399;
    r->walls[62].nx =   -4096;  r->walls[62].nz =       0;
    r->walls[62].y_min =    -600;  r->walls[62].y_max =       0;

    /* Wall 63 (avg Y: -300) */
    r->walls[63].x1 =   -1100;  r->walls[63].z1 =    3000;
    r->walls[63].x2 =   -1100;  r->walls[63].z2 =    2800;
    r->walls[63].nx =    4096;  r->walls[63].nz =       0;
    r->walls[63].y_min =    -600;  r->walls[63].y_max =       0;

    /* Wall 64 (avg Y: -300) */
    r->walls[64].x1 =   -1499;  r->walls[64].z1 =    1800;
    r->walls[64].x2 =   -1699;  r->walls[64].z2 =    1800;
    r->walls[64].nx =       0;  r->walls[64].nz =   -4096;
    r->walls[64].y_min =    -600;  r->walls[64].y_max =       0;

    /* Wall 65 (avg Y: -300) */
    r->walls[65].x1 =    -300;  r->walls[65].z1 =    1400;
    r->walls[65].x2 =   -1100;  r->walls[65].z2 =    1400;
    r->walls[65].nx =       0;  r->walls[65].nz =   -4096;
    r->walls[65].y_min =    -600;  r->walls[65].y_max =       0;

    /* Wall 66 (avg Y: -300) */
    r->walls[66].x1 =     700;  r->walls[66].z1 =    4600;
    r->walls[66].x2 =    -900;  r->walls[66].z2 =    4599;
    r->walls[66].nx =       0;  r->walls[66].nz =   -4095;
    r->walls[66].y_min =    -600;  r->walls[66].y_max =       0;

    /* Wall 67 (avg Y: -300) */
    r->walls[67].x1 =   -1100;  r->walls[67].z1 =    1600;
    r->walls[67].x2 =   -1299;  r->walls[67].z2 =    1600;
    r->walls[67].nx =       0;  r->walls[67].nz =   -4096;
    r->walls[67].y_min =    -600;  r->walls[67].y_max =       0;

    /* Wall 68 (avg Y: -300) */
    r->walls[68].x1 =    -900;  r->walls[68].z1 =    2599;
    r->walls[68].x2 =     700;  r->walls[68].z2 =    2599;
    r->walls[68].nx =       0;  r->walls[68].nz =    4096;
    r->walls[68].y_min =    -600;  r->walls[68].y_max =       0;

    /* Wall 69 (avg Y: -300) */
    r->walls[69].x1 =   -1100;  r->walls[69].z1 =    1400;
    r->walls[69].x2 =   -1100;  r->walls[69].z2 =    1600;
    r->walls[69].nx =   -4096;  r->walls[69].nz =       0;
    r->walls[69].y_min =    -600;  r->walls[69].y_max =       0;

    /* Wall 70 (avg Y: -300) */
    r->walls[70].x1 =     700;  r->walls[70].z1 =    2800;
    r->walls[70].x2 =    1700;  r->walls[70].z2 =    2800;
    r->walls[70].nx =       0;  r->walls[70].nz =    4096;
    r->walls[70].y_min =    -600;  r->walls[70].y_max =       0;

    /* Wall 71 (avg Y: -300) */
    r->walls[71].x1 =    1500;  r->walls[71].z1 =    4599;
    r->walls[71].x2 =    1700;  r->walls[71].z2 =    4600;
    r->walls[71].nx =       0;  r->walls[71].nz =    4095;
    r->walls[71].y_min =    -600;  r->walls[71].y_max =       0;

    /* Wall 72 (avg Y: -300) */
    r->walls[72].x1 =   -1900;  r->walls[72].z1 =    4600;
    r->walls[72].x2 =   -1900;  r->walls[72].z2 =    4800;
    r->walls[72].nx =   -4096;  r->walls[72].nz =       0;
    r->walls[72].y_min =    -600;  r->walls[72].y_max =       0;

    /* Wall 73 (avg Y: -300) */
    r->walls[73].x1 =   -2100;  r->walls[73].z1 =    2399;
    r->walls[73].x2 =   -2100;  r->walls[73].z2 =    4599;
    r->walls[73].nx =   -4096;  r->walls[73].nz =       0;
    r->walls[73].y_min =    -600;  r->walls[73].y_max =       0;

    /* Wall 74 (avg Y: -300) */
    r->walls[74].x1 =    1700;  r->walls[74].z1 =    4600;
    r->walls[74].x2 =    1700;  r->walls[74].z2 =    3999;
    r->walls[74].nx =    4096;  r->walls[74].nz =       0;
    r->walls[74].y_min =    -600;  r->walls[74].y_max =       0;

    /* Wall 75 (avg Y: -300) */
    r->walls[75].x1 =    1300;  r->walls[75].z1 =    4800;
    r->walls[75].x2 =    1500;  r->walls[75].z2 =    4800;
    r->walls[75].nx =       0;  r->walls[75].nz =    4096;
    r->walls[75].y_min =    -600;  r->walls[75].y_max =       0;

    /* Wall 76 (avg Y: -300) */
    r->walls[76].x1 =    -900;  r->walls[76].z1 =    5399;
    r->walls[76].x2 =     900;  r->walls[76].z2 =    5399;
    r->walls[76].nx =       0;  r->walls[76].nz =    4096;
    r->walls[76].y_min =    -600;  r->walls[76].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-900 to 900)  z(6000 to 6600)
     * FLOOR   1: y=     0  x(-3299 to -2700)  z(2399 to 4199)
     * FLOOR   2: y=     0  x(2700 to 3299)  z(2399 to 4199)
     * FLOOR   3: y=     0  x(-900 to 900)  z(0 to 600)
     * FLOOR   4: y=     0  x(-2700 to 2700)  z(600 to 6000)
     */
}
