/*
 * Auto-generated collision data from: North Chamber mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  23
 * Floors: 12
 * Bounds: X(-1800 to 3000)  Z(0 to 3600)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "North Chamber mesh_collision.h"

void north_chamber_collision_init(CollisionRoom *r) {
    r->wall_count = NORTH_CHAMBER_WALL_COUNT;
    r->min_x = -1800;
    r->max_x = 3000;
    r->min_z = 0;
    r->max_z = 3600;

    /* Wall 0 (avg Y: -900) */
    r->walls[0].x1 =   -1200;  r->walls[0].z1 =       0;
    r->walls[0].x2 =    2399;  r->walls[0].z2 =       0;
    r->walls[0].nx =       0;  r->walls[0].nz =    4096;
    r->walls[0].y_min =   -1800;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -1400) */
    r->walls[1].x1 =    2399;  r->walls[1].z1 =    2000;
    r->walls[1].x2 =    2399;  r->walls[1].z2 =    3600;
    r->walls[1].nx =   -4096;  r->walls[1].nz =       0;
    r->walls[1].y_min =   -1800;  r->walls[1].y_max =   -1000;

    /* Wall 2 (avg Y: -1400) */
    r->walls[2].x1 =    2399;  r->walls[2].z1 =       0;
    r->walls[2].x2 =    2399;  r->walls[2].z2 =    1400;
    r->walls[2].nx =   -4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =   -1800;  r->walls[2].y_max =   -1000;

    /* Wall 3 (avg Y: -1400) */
    r->walls[3].x1 =   -1200;  r->walls[3].z1 =    3600;
    r->walls[3].x2 =   -1200;  r->walls[3].z2 =       0;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =   -1800;  r->walls[3].y_max =   -1000;

    /* Wall 4 (avg Y: -400) */
    r->walls[4].x1 =   -1800;  r->walls[4].z1 =    3600;
    r->walls[4].x2 =   -1800;  r->walls[4].z2 =    3000;
    r->walls[4].nx =    4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -800;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -400) */
    r->walls[5].x1 =    2399;  r->walls[5].z1 =    2400;
    r->walls[5].x2 =    3000;  r->walls[5].z2 =    2400;
    r->walls[5].nx =       0;  r->walls[5].nz =    4096;
    r->walls[5].y_min =    -800;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -400) */
    r->walls[6].x1 =    3000;  r->walls[6].z1 =    3000;
    r->walls[6].x2 =    2399;  r->walls[6].z2 =    3000;
    r->walls[6].nx =       0;  r->walls[6].nz =   -4096;
    r->walls[6].y_min =    -800;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -450) */
    r->walls[7].x1 =   -1200;  r->walls[7].z1 =    3600;
    r->walls[7].x2 =   -1800;  r->walls[7].z2 =    3600;
    r->walls[7].nx =       0;  r->walls[7].nz =   -4096;
    r->walls[7].y_min =   -1000;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -400) */
    r->walls[8].x1 =   -1800;  r->walls[8].z1 =    3000;
    r->walls[8].x2 =   -1200;  r->walls[8].z2 =    3000;
    r->walls[8].nx =       0;  r->walls[8].nz =    4096;
    r->walls[8].y_min =    -800;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -500) */
    r->walls[9].x1 =       0;  r->walls[9].z1 =    2400;
    r->walls[9].x2 =    1200;  r->walls[9].z2 =    2400;
    r->walls[9].nx =       0;  r->walls[9].nz =    4096;
    r->walls[9].y_min =   -1000;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -500) */
    r->walls[10].x1 =    1200;  r->walls[10].z1 =    1199;
    r->walls[10].x2 =       0;  r->walls[10].z2 =    1199;
    r->walls[10].nx =       0;  r->walls[10].nz =   -4096;
    r->walls[10].y_min =   -1000;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -400) */
    r->walls[11].x1 =    3000;  r->walls[11].z1 =    2400;
    r->walls[11].x2 =    3000;  r->walls[11].z2 =    3000;
    r->walls[11].nx =   -4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -800;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -450) */
    r->walls[12].x1 =   -1200;  r->walls[12].z1 =    3000;
    r->walls[12].x2 =   -1200;  r->walls[12].z2 =       0;
    r->walls[12].nx =    4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =   -1000;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -400) */
    r->walls[13].x1 =    2399;  r->walls[13].z1 =       0;
    r->walls[13].x2 =    2399;  r->walls[13].z2 =    2400;
    r->walls[13].nx =   -4096;  r->walls[13].nz =       0;
    r->walls[13].y_min =    -800;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -450) */
    r->walls[14].x1 =    2399;  r->walls[14].z1 =    3000;
    r->walls[14].x2 =    2399;  r->walls[14].z2 =    3600;
    r->walls[14].nx =   -4096;  r->walls[14].nz =       0;
    r->walls[14].y_min =   -1000;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -900) */
    r->walls[15].x1 =    2399;  r->walls[15].z1 =    3600;
    r->walls[15].x2 =   -1200;  r->walls[15].z2 =    3600;
    r->walls[15].nx =       0;  r->walls[15].nz =   -4096;
    r->walls[15].y_min =   -1800;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -500) */
    r->walls[16].x1 =    1799;  r->walls[16].z1 =    3600;
    r->walls[16].x2 =    1799;  r->walls[16].z2 =    3000;
    r->walls[16].nx =    4096;  r->walls[16].nz =       0;
    r->walls[16].y_min =   -1000;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -500) */
    r->walls[17].x1 =       0;  r->walls[17].z1 =    1199;
    r->walls[17].x2 =       0;  r->walls[17].z2 =    2400;
    r->walls[17].nx =   -4096;  r->walls[17].nz =       0;
    r->walls[17].y_min =   -1000;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -500) */
    r->walls[18].x1 =    1200;  r->walls[18].z1 =    2400;
    r->walls[18].x2 =    1200;  r->walls[18].z2 =    1199;
    r->walls[18].nx =    4096;  r->walls[18].nz =       0;
    r->walls[18].y_min =   -1000;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -1400) */
    r->walls[19].x1 =    2800;  r->walls[19].z1 =    1400;
    r->walls[19].x2 =    2800;  r->walls[19].z2 =    2000;
    r->walls[19].nx =   -4096;  r->walls[19].nz =       0;
    r->walls[19].y_min =   -1800;  r->walls[19].y_max =   -1000;

    /* Wall 20 (avg Y: -1400) */
    r->walls[20].x1 =    2800;  r->walls[20].z1 =    2000;
    r->walls[20].x2 =    2399;  r->walls[20].z2 =    2000;
    r->walls[20].nx =       0;  r->walls[20].nz =   -4096;
    r->walls[20].y_min =   -1800;  r->walls[20].y_max =   -1000;

    /* Wall 21 (avg Y: -1400) */
    r->walls[21].x1 =    2399;  r->walls[21].z1 =    1400;
    r->walls[21].x2 =    2800;  r->walls[21].z2 =    1400;
    r->walls[21].nx =       0;  r->walls[21].nz =    4096;
    r->walls[21].y_min =   -1800;  r->walls[21].y_max =   -1000;

    /* Wall 22 (avg Y: -333) */
    r->walls[22].x1 =    1799;  r->walls[22].z1 =    3000;
    r->walls[22].x2 =    -199;  r->walls[22].z2 =    3000;
    r->walls[22].nx =       0;  r->walls[22].nz =   -4096;
    r->walls[22].y_min =   -1000;  r->walls[22].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y= -1000  x(0 to 1200)  z(1199 to 2400)
     * FLOOR   1: y=     0  x(1799 to 2399)  z(3000 to 3600)
     * FLOOR   2: y= -1000  x(-1200 to -599)  z(600 to 3600)
     * FLOOR   3: y= -1000  x(1799 to 2399)  z(600 to 3600)
     * FLOOR   4: y= -1000  x(400 to 800)  z(600 to 1199)
     * FLOOR   5: y=     0  x(2399 to 3000)  z(2400 to 3000)
     * FLOOR   6: y=     0  x(-1800 to -1200)  z(3000 to 3600)
     * FLOOR   7: y=     0  x(-1200 to -199)  z(3000 to 3600)
     * FLOOR   8: y=     0  x(-1200 to 2399)  z(0 to 3000)
     * FLOOR   9: y= -1000  x(-1200 to 2399)  z(0 to 600)
     * FLOOR   10: y= -1000  x(2399 to 2800)  z(1400 to 2000)
     * FLOOR   11: y=  -500  x(-199 to 1799)  z(3000 to 3600)
     */
}
