/*
 * Auto-generated collision data from: Nursery mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef NURSERY_MESH_COLLISION_H
#define NURSERY_MESH_COLLISION_H

#include "collision.h"

#define NURSERY_WALL_COUNT  8
#define NURSERY_FLOOR_COUNT 3

void nursery_collision_init(CollisionRoom *r);

#endif /* NURSERY_MESH_COLLISION_H */
