/*
 * Auto-generated collision data from: Room of Arms mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  13
 * Floors: 3
 * Bounds: X(-1293 to 1293)  Z(-1293 to 1198)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Room of Arms mesh_collision.h"

void room_of_arms_collision_init(CollisionRoom *r) {
    r->wall_count = ROOM_OF_ARMS_WALL_COUNT;
    r->min_x = -1293;
    r->max_x = 1293;
    r->min_z = -1293;
    r->max_z = 1198;

    /* Wall 0 (avg Y: -399) */
    r->walls[0].x1 =     357;  r->walls[0].z1 =    -251;
    r->walls[0].x2 =     535;  r->walls[0].z2 =    -251;
    r->walls[0].nx =       0;  r->walls[0].nz =    4096;
    r->walls[0].y_min =    -799;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -399) */
    r->walls[1].x1 =     535;  r->walls[1].z1 =   -1293;
    r->walls[1].x2 =    1293;  r->walls[1].z2 =    -535;
    r->walls[1].nx =   -2896;  r->walls[1].nz =    2896;
    r->walls[1].y_min =    -799;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -399) */
    r->walls[2].x1 =    1293;  r->walls[2].z1 =    -535;
    r->walls[2].x2 =    1293;  r->walls[2].z2 =     535;
    r->walls[2].nx =   -4095;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -799;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -399) */
    r->walls[3].x1 =    -535;  r->walls[3].z1 =   -1293;
    r->walls[3].x2 =     357;  r->walls[3].z2 =   -1293;
    r->walls[3].nx =       0;  r->walls[3].nz =    4096;
    r->walls[3].y_min =    -800;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -400) */
    r->walls[4].x1 =   -1293;  r->walls[4].z1 =    -535;
    r->walls[4].x2 =    -535;  r->walls[4].z2 =   -1293;
    r->walls[4].nx =    2896;  r->walls[4].nz =    2896;
    r->walls[4].y_min =    -800;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -400) */
    r->walls[5].x1 =   -1293;  r->walls[5].z1 =     401;
    r->walls[5].x2 =   -1293;  r->walls[5].z2 =    -535;
    r->walls[5].nx =    4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -800;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -400) */
    r->walls[6].x1 =     630;  r->walls[6].z1 =    1198;
    r->walls[6].x2 =    -144;  r->walls[6].z2 =     424;
    r->walls[6].nx =    2896;  r->walls[6].nz =   -2896;
    r->walls[6].y_min =    -800;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -399) */
    r->walls[7].x1 =    1293;  r->walls[7].z1 =     535;
    r->walls[7].x2 =     630;  r->walls[7].z2 =    1198;
    r->walls[7].nx =   -2896;  r->walls[7].nz =   -2896;
    r->walls[7].y_min =    -799;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -399) */
    r->walls[8].x1 =     357;  r->walls[8].z1 =   -1293;
    r->walls[8].x2 =     357;  r->walls[8].z2 =    -251;
    r->walls[8].nx =   -4095;  r->walls[8].nz =       0;
    r->walls[8].y_min =    -799;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -399) */
    r->walls[9].x1 =     535;  r->walls[9].z1 =    -251;
    r->walls[9].x2 =     535;  r->walls[9].z2 =   -1293;
    r->walls[9].nx =    4096;  r->walls[9].nz =       0;
    r->walls[9].y_min =    -799;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -400) */
    r->walls[10].x1 =    -403;  r->walls[10].z1 =    -155;
    r->walls[10].x2 =    -483;  r->walls[10].z2 =    -263;
    r->walls[10].nx =    3286;  r->walls[10].nz =   -2444;
    r->walls[10].y_min =    -800;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -400) */
    r->walls[11].x1 =    -483;  r->walls[11].z1 =    -263;
    r->walls[11].x2 =   -1293;  r->walls[11].z2 =     401;
    r->walls[11].nx =   -2600;  r->walls[11].nz =   -3164;
    r->walls[11].y_min =    -800;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -400) */
    r->walls[12].x1 =    -144;  r->walls[12].z1 =     424;
    r->walls[12].x2 =    -403;  r->walls[12].z2 =    -155;
    r->walls[12].nx =    3738;  r->walls[12].nz =   -1673;
    r->walls[12].y_min =    -800;  r->walls[12].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-1293 to -535)  z(-1293 to 1293)
     * FLOOR   1: y=     0  x(535 to 1293)  z(-1293 to 1293)
     * FLOOR   2: y=     0  x(-535 to 535)  z(-1293 to 1293)
     */
}
