/*
 * Auto-generated collision data from: Room of Baby Names mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ROOM_OF_BABY_NAMES_MESH_COLLISION_H
#define ROOM_OF_BABY_NAMES_MESH_COLLISION_H

#include "collision.h"

#define ROOM_OF_BABY_NAMES_WALL_COUNT  12
#define ROOM_OF_BABY_NAMES_FLOOR_COUNT 3

void room_of_baby_names_collision_init(CollisionRoom *r);

#endif /* ROOM_OF_BABY_NAMES_MESH_COLLISION_H */
