/*
 * Auto-generated collision data from: Room of Heads mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  45
 * Floors: 3
 * Bounds: X(-1293 to 1293)  Z(-1293 to 1293)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Room of Heads mesh_collision.h"

void room_of_heads_collision_init(CollisionRoom *r) {
    r->wall_count = ROOM_OF_HEADS_WALL_COUNT;
    r->min_x = -1293;
    r->max_x = 1293;
    r->min_z = -1293;
    r->max_z = 1293;

    /* Wall 0 (avg Y: -92) */
    r->walls[0].x1 =    -724;  r->walls[0].z1 =    -696;
    r->walls[0].x2 =    -914;  r->walls[0].z2 =    -516;
    r->walls[0].nx =   -2820;  r->walls[0].nz =   -2970;
    r->walls[0].y_min =    -185;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -92) */
    r->walls[1].x1 =    -321;  r->walls[1].z1 =    -497;
    r->walls[1].x2 =    -321;  r->walls[1].z2 =    -696;
    r->walls[1].nx =    4095;  r->walls[1].nz =       0;
    r->walls[1].y_min =    -185;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -92) */
    r->walls[2].x1 =    -914;  r->walls[2].z1 =     516;
    r->walls[2].x2 =    -724;  r->walls[2].z2 =     696;
    r->walls[2].nx =   -2820;  r->walls[2].nz =    2970;
    r->walls[2].y_min =    -185;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -92) */
    r->walls[3].x1 =     724;  r->walls[3].z1 =     696;
    r->walls[3].x2 =     914;  r->walls[3].z2 =     516;
    r->walls[3].nx =    2820;  r->walls[3].nz =    2970;
    r->walls[3].y_min =    -185;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -92) */
    r->walls[4].x1 =     535;  r->walls[4].z1 =    -298;
    r->walls[4].x2 =     724;  r->walls[4].z2 =    -304;
    r->walls[4].nx =     124;  r->walls[4].nz =    4094;
    r->walls[4].y_min =    -185;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -92) */
    r->walls[5].x1 =     361;  r->walls[5].z1 =     348;
    r->walls[5].x2 =     321;  r->walls[5].z2 =     497;
    r->walls[5].nx =   -3955;  r->walls[5].nz =   -1062;
    r->walls[5].y_min =    -185;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -92) */
    r->walls[6].x1 =    -724;  r->walls[6].z1 =    -304;
    r->walls[6].x2 =    -535;  r->walls[6].z2 =    -298;
    r->walls[6].nx =    -124;  r->walls[6].nz =    4094;
    r->walls[6].y_min =    -185;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -92) */
    r->walls[7].x1 =    -321;  r->walls[7].z1 =     696;
    r->walls[7].x2 =    -321;  r->walls[7].z2 =     497;
    r->walls[7].nx =    4095;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -185;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -92) */
    r->walls[8].x1 =     914;  r->walls[8].z1 =     516;
    r->walls[8].x2 =     914;  r->walls[8].z2 =     309;
    r->walls[8].nx =    4095;  r->walls[8].nz =       0;
    r->walls[8].y_min =    -185;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -92) */
    r->walls[9].x1 =    -371;  r->walls[9].z1 =     348;
    r->walls[9].x2 =    -535;  r->walls[9].z2 =     298;
    r->walls[9].nx =    1192;  r->walls[9].nz =   -3918;
    r->walls[9].y_min =    -185;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -92) */
    r->walls[10].x1 =     914;  r->walls[10].z1 =     309;
    r->walls[10].x2 =     724;  r->walls[10].z2 =     304;
    r->walls[10].nx =     124;  r->walls[10].nz =   -4094;
    r->walls[10].y_min =    -185;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -92) */
    r->walls[11].x1 =     535;  r->walls[11].z1 =    -895;
    r->walls[11].x2 =     321;  r->walls[11].z2 =    -895;
    r->walls[11].nx =       0;  r->walls[11].nz =   -4096;
    r->walls[11].y_min =    -185;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -92) */
    r->walls[12].x1 =    -535;  r->walls[12].z1 =    -895;
    r->walls[12].x2 =    -724;  r->walls[12].z2 =    -696;
    r->walls[12].nx =   -2966;  r->walls[12].nz =   -2824;
    r->walls[12].y_min =    -185;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -92) */
    r->walls[13].x1 =    -914;  r->walls[13].z1 =    -309;
    r->walls[13].x2 =    -724;  r->walls[13].z2 =    -304;
    r->walls[13].nx =    -124;  r->walls[13].nz =    4094;
    r->walls[13].y_min =    -185;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -92) */
    r->walls[14].x1 =     321;  r->walls[14].z1 =    -895;
    r->walls[14].x2 =     321;  r->walls[14].z2 =    -696;
    r->walls[14].nx =   -4095;  r->walls[14].nz =       0;
    r->walls[14].y_min =    -185;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -92) */
    r->walls[15].x1 =    -535;  r->walls[15].z1 =     895;
    r->walls[15].x2 =    -321;  r->walls[15].z2 =     895;
    r->walls[15].nx =       0;  r->walls[15].nz =    4096;
    r->walls[15].y_min =    -185;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -92) */
    r->walls[16].x1 =    -535;  r->walls[16].z1 =     298;
    r->walls[16].x2 =    -724;  r->walls[16].z2 =     304;
    r->walls[16].nx =    -124;  r->walls[16].nz =   -4094;
    r->walls[16].y_min =    -185;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -92) */
    r->walls[17].x1 =     724;  r->walls[17].z1 =    -696;
    r->walls[17].x2 =     535;  r->walls[17].z2 =    -895;
    r->walls[17].nx =    2966;  r->walls[17].nz =   -2824;
    r->walls[17].y_min =    -185;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -92) */
    r->walls[18].x1 =     724;  r->walls[18].z1 =     304;
    r->walls[18].x2 =     535;  r->walls[18].z2 =     298;
    r->walls[18].nx =     124;  r->walls[18].nz =   -4094;
    r->walls[18].y_min =    -185;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -92) */
    r->walls[19].x1 =     321;  r->walls[19].z1 =     497;
    r->walls[19].x2 =     321;  r->walls[19].z2 =     696;
    r->walls[19].nx =   -4095;  r->walls[19].nz =       0;
    r->walls[19].y_min =    -185;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -92) */
    r->walls[20].x1 =    -321;  r->walls[20].z1 =    -696;
    r->walls[20].x2 =    -535;  r->walls[20].z2 =    -895;
    r->walls[20].nx =    2787;  r->walls[20].nz =   -3001;
    r->walls[20].y_min =    -185;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -92) */
    r->walls[21].x1 =    -321;  r->walls[21].z1 =     497;
    r->walls[21].x2 =    -371;  r->walls[21].z2 =     348;
    r->walls[21].nx =    3883;  r->walls[21].nz =   -1303;
    r->walls[21].y_min =    -185;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -92) */
    r->walls[22].x1 =    -535;  r->walls[22].z1 =    -298;
    r->walls[22].x2 =    -361;  r->walls[22].z2 =    -358;
    r->walls[22].nx =    1333;  r->walls[22].nz =    3872;
    r->walls[22].y_min =    -185;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -92) */
    r->walls[23].x1 =    -724;  r->walls[23].z1 =     304;
    r->walls[23].x2 =    -914;  r->walls[23].z2 =     309;
    r->walls[23].nx =    -124;  r->walls[23].nz =   -4094;
    r->walls[23].y_min =    -185;  r->walls[23].y_max =       0;

    /* Wall 24 (avg Y: -92) */
    r->walls[24].x1 =    -321;  r->walls[24].z1 =     895;
    r->walls[24].x2 =    -321;  r->walls[24].z2 =     696;
    r->walls[24].nx =    4095;  r->walls[24].nz =       0;
    r->walls[24].y_min =    -185;  r->walls[24].y_max =       0;

    /* Wall 25 (avg Y: -92) */
    r->walls[25].x1 =     724;  r->walls[25].z1 =    -304;
    r->walls[25].x2 =     914;  r->walls[25].z2 =    -516;
    r->walls[25].nx =    3056;  r->walls[25].nz =    2726;
    r->walls[25].y_min =    -185;  r->walls[25].y_max =       0;

    /* Wall 26 (avg Y: -92) */
    r->walls[26].x1 =     321;  r->walls[26].z1 =    -696;
    r->walls[26].x2 =     321;  r->walls[26].z2 =    -497;
    r->walls[26].nx =   -4095;  r->walls[26].nz =       0;
    r->walls[26].y_min =    -185;  r->walls[26].y_max =       0;

    /* Wall 27 (avg Y: -92) */
    r->walls[27].x1 =     321;  r->walls[27].z1 =     696;
    r->walls[27].x2 =     535;  r->walls[27].z2 =     895;
    r->walls[27].nx =   -2787;  r->walls[27].nz =    3001;
    r->walls[27].y_min =    -185;  r->walls[27].y_max =       0;

    /* Wall 28 (avg Y: -92) */
    r->walls[28].x1 =    -361;  r->walls[28].z1 =    -358;
    r->walls[28].x2 =    -321;  r->walls[28].z2 =    -497;
    r->walls[28].nx =    3936;  r->walls[28].nz =    1133;
    r->walls[28].y_min =    -185;  r->walls[28].y_max =       0;

    /* Wall 29 (avg Y: -92) */
    r->walls[29].x1 =    -724;  r->walls[29].z1 =     696;
    r->walls[29].x2 =    -535;  r->walls[29].z2 =     895;
    r->walls[29].nx =   -2966;  r->walls[29].nz =    2824;
    r->walls[29].y_min =    -185;  r->walls[29].y_max =       0;

    /* Wall 30 (avg Y: -92) */
    r->walls[30].x1 =    -914;  r->walls[30].z1 =    -516;
    r->walls[30].x2 =    -914;  r->walls[30].z2 =    -309;
    r->walls[30].nx =   -4095;  r->walls[30].nz =       0;
    r->walls[30].y_min =    -185;  r->walls[30].y_max =       0;

    /* Wall 31 (avg Y: -92) */
    r->walls[31].x1 =     914;  r->walls[31].z1 =    -516;
    r->walls[31].x2 =     724;  r->walls[31].z2 =    -696;
    r->walls[31].nx =    2820;  r->walls[31].nz =   -2970;
    r->walls[31].y_min =    -185;  r->walls[31].y_max =       0;

    /* Wall 32 (avg Y: -92) */
    r->walls[32].x1 =     535;  r->walls[32].z1 =     298;
    r->walls[32].x2 =     361;  r->walls[32].z2 =     348;
    r->walls[32].nx =   -1129;  r->walls[32].nz =   -3937;
    r->walls[32].y_min =    -185;  r->walls[32].y_max =       0;

    /* Wall 33 (avg Y: -92) */
    r->walls[33].x1 =     321;  r->walls[33].z1 =    -497;
    r->walls[33].x2 =     371;  r->walls[33].z2 =    -348;
    r->walls[33].nx =   -3883;  r->walls[33].nz =    1303;
    r->walls[33].y_min =    -185;  r->walls[33].y_max =       0;

    /* Wall 34 (avg Y: -92) */
    r->walls[34].x1 =     371;  r->walls[34].z1 =    -348;
    r->walls[34].x2 =     535;  r->walls[34].z2 =    -298;
    r->walls[34].nx =   -1192;  r->walls[34].nz =    3918;
    r->walls[34].y_min =    -185;  r->walls[34].y_max =       0;

    /* Wall 35 (avg Y: -92) */
    r->walls[35].x1 =     535;  r->walls[35].z1 =     895;
    r->walls[35].x2 =     724;  r->walls[35].z2 =     696;
    r->walls[35].nx =    2966;  r->walls[35].nz =    2824;
    r->walls[35].y_min =    -185;  r->walls[35].y_max =       0;

    /* Wall 36 (avg Y: -92) */
    r->walls[36].x1 =    -914;  r->walls[36].z1 =     309;
    r->walls[36].x2 =    -914;  r->walls[36].z2 =     516;
    r->walls[36].nx =   -4095;  r->walls[36].nz =       0;
    r->walls[36].y_min =    -185;  r->walls[36].y_max =       0;

    /* Wall 37 (avg Y: -400) */
    r->walls[37].x1 =   -1293;  r->walls[37].z1 =     535;
    r->walls[37].x2 =   -1293;  r->walls[37].z2 =    -535;
    r->walls[37].nx =    4096;  r->walls[37].nz =       0;
    r->walls[37].y_min =    -800;  r->walls[37].y_max =       0;

    /* Wall 38 (avg Y: -400) */
    r->walls[38].x1 =    1293;  r->walls[38].z1 =    -535;
    r->walls[38].x2 =    1293;  r->walls[38].z2 =     535;
    r->walls[38].nx =   -4096;  r->walls[38].nz =       0;
    r->walls[38].y_min =    -800;  r->walls[38].y_max =       0;

    /* Wall 39 (avg Y: -400) */
    r->walls[39].x1 =     535;  r->walls[39].z1 =    1293;
    r->walls[39].x2 =    -535;  r->walls[39].z2 =    1293;
    r->walls[39].nx =       0;  r->walls[39].nz =   -4096;
    r->walls[39].y_min =    -800;  r->walls[39].y_max =       0;

    /* Wall 40 (avg Y: -400) */
    r->walls[40].x1 =    -535;  r->walls[40].z1 =   -1293;
    r->walls[40].x2 =     535;  r->walls[40].z2 =   -1293;
    r->walls[40].nx =       0;  r->walls[40].nz =    4096;
    r->walls[40].y_min =    -800;  r->walls[40].y_max =       0;

    /* Wall 41 (avg Y: -400) */
    r->walls[41].x1 =     535;  r->walls[41].z1 =   -1293;
    r->walls[41].x2 =    1293;  r->walls[41].z2 =    -535;
    r->walls[41].nx =   -2896;  r->walls[41].nz =    2896;
    r->walls[41].y_min =    -800;  r->walls[41].y_max =       0;

    /* Wall 42 (avg Y: -400) */
    r->walls[42].x1 =   -1293;  r->walls[42].z1 =    -535;
    r->walls[42].x2 =    -535;  r->walls[42].z2 =   -1293;
    r->walls[42].nx =    2896;  r->walls[42].nz =    2896;
    r->walls[42].y_min =    -800;  r->walls[42].y_max =       0;

    /* Wall 43 (avg Y: -400) */
    r->walls[43].x1 =    1293;  r->walls[43].z1 =     535;
    r->walls[43].x2 =     535;  r->walls[43].z2 =    1293;
    r->walls[43].nx =   -2896;  r->walls[43].nz =   -2896;
    r->walls[43].y_min =    -800;  r->walls[43].y_max =       0;

    /* Wall 44 (avg Y: -400) */
    r->walls[44].x1 =    -535;  r->walls[44].z1 =    1293;
    r->walls[44].x2 =   -1293;  r->walls[44].z2 =     535;
    r->walls[44].nx =    2896;  r->walls[44].nz =   -2896;
    r->walls[44].y_min =    -800;  r->walls[44].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-1293 to 1293)  z(-1293 to -535)
     * FLOOR   1: y=     0  x(-1293 to 1293)  z(-535 to 535)
     * FLOOR   2: y=     0  x(-1293 to 1293)  z(535 to 1293)
     */
}
