/*
 * Auto-generated collision data from: Room of Legs mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ROOM_OF_LEGS_MESH_COLLISION_H
#define ROOM_OF_LEGS_MESH_COLLISION_H

#include "collision.h"

#define ROOM_OF_LEGS_WALL_COUNT  26
#define ROOM_OF_LEGS_FLOOR_COUNT 2

void room_of_legs_collision_init(CollisionRoom *r);

#endif /* ROOM_OF_LEGS_MESH_COLLISION_H */
