/*
 * Auto-generated collision data from: Room of Heads mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ROOM_OF_HEADS_MESH_COLLISION_H
#define ROOM_OF_HEADS_MESH_COLLISION_H

#include "collision.h"

#define ROOM_OF_HEADS_WALL_COUNT  45
#define ROOM_OF_HEADS_FLOOR_COUNT 3

void room_of_heads_collision_init(CollisionRoom *r);

#endif /* ROOM_OF_HEADS_MESH_COLLISION_H */
