/*
 * Auto-generated collision data from: Room of Arms mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ROOM_OF_ARMS_MESH_COLLISION_H
#define ROOM_OF_ARMS_MESH_COLLISION_H

#include "collision.h"

#define ROOM_OF_ARMS_WALL_COUNT  13
#define ROOM_OF_ARMS_FLOOR_COUNT 3

void room_of_arms_collision_init(CollisionRoom *r);

#endif /* ROOM_OF_ARMS_MESH_COLLISION_H */
