/*
 * Auto-generated collision data from: The Head mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  4
 * Floors: 1
 * Bounds: X(0 to 2210)  Z(0 to 3000)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "The Head mesh_collision.h"

void the_head_collision_init(CollisionRoom *r) {
    r->wall_count = THE_HEAD_WALL_COUNT;
    r->min_x = 0;
    r->max_x = 2210;
    r->min_z = 0;
    r->max_z = 3000;

    /* Wall 0 (avg Y: -400) */
    r->walls[0].x1 =    2210;  r->walls[0].z1 =    3000;
    r->walls[0].x2 =       0;  r->walls[0].z2 =    3000;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =    -800;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -400) */
    r->walls[1].x1 =       0;  r->walls[1].z1 =    3000;
    r->walls[1].x2 =       0;  r->walls[1].z2 =       0;
    r->walls[1].nx =    4096;  r->walls[1].nz =       0;
    r->walls[1].y_min =    -800;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -400) */
    r->walls[2].x1 =       0;  r->walls[2].z1 =       0;
    r->walls[2].x2 =    2210;  r->walls[2].z2 =       0;
    r->walls[2].nx =       0;  r->walls[2].nz =    4096;
    r->walls[2].y_min =    -800;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -400) */
    r->walls[3].x1 =    2210;  r->walls[3].z1 =       0;
    r->walls[3].x2 =    2210;  r->walls[3].z2 =    3000;
    r->walls[3].nx =   -4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -800;  r->walls[3].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(0 to 2210)  z(0 to 3000)
     */
}
