/*
 * Auto-generated collision data from: The Neck mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef THE_NECK_MESH_COLLISION_H
#define THE_NECK_MESH_COLLISION_H

#include "collision.h"

#define NECK_WALL_COUNT  12
#define NECK_FLOOR_COUNT 1

void neck_collision_init(CollisionRoom *r);

#endif /* THE_NECK_MESH_COLLISION_H */
