/*
 * Auto-generated collision data from: The Pit mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  24
 * Floors: 9
 * Bounds: X(-2104 to 2699)  Z(0 to 3900)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "The Pit mesh_collision.h"

void the_pit_collision_init(CollisionRoom *r) {
    r->wall_count = THE_PIT_WALL_COUNT;
    r->min_x = -2104;
    r->max_x = 2699;
    r->min_z = 0;
    r->max_z = 3900;

    /* Wall 0 (avg Y: -1300) */
    r->walls[0].x1 =    1800;  r->walls[0].z1 =     600;
    r->walls[0].x2 =   -1200;  r->walls[0].z2 =     600;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =   -1600;  r->walls[0].y_max =   -1000;

    /* Wall 1 (avg Y: -1300) */
    r->walls[1].x1 =    1998;  r->walls[1].z1 =     698;
    r->walls[1].x2 =    1800;  r->walls[1].z2 =     600;
    r->walls[1].nx =    1817;  r->walls[1].nz =   -3670;
    r->walls[1].y_min =   -1600;  r->walls[1].y_max =   -1000;

    /* Wall 2 (avg Y: -1300) */
    r->walls[2].x1 =    2099;  r->walls[2].z1 =     910;
    r->walls[2].x2 =    1998;  r->walls[2].z2 =     698;
    r->walls[2].nx =    3694;  r->walls[2].nz =   -1767;
    r->walls[2].y_min =   -1600;  r->walls[2].y_max =   -1000;

    /* Wall 3 (avg Y: -1300) */
    r->walls[3].x1 =   -1402;  r->walls[3].z1 =     698;
    r->walls[3].x2 =   -1504;  r->walls[3].z2 =     910;
    r->walls[3].nx =   -3690;  r->walls[3].nz =   -1776;
    r->walls[3].y_min =   -1600;  r->walls[3].y_max =   -1000;

    /* Wall 4 (avg Y: -1300) */
    r->walls[4].x1 =   -1200;  r->walls[4].z1 =     600;
    r->walls[4].x2 =   -1402;  r->walls[4].z2 =     698;
    r->walls[4].nx =   -1789;  r->walls[4].nz =   -3684;
    r->walls[4].y_min =   -1600;  r->walls[4].y_max =   -1000;

    /* Wall 5 (avg Y: -449) */
    r->walls[5].x1 =    1292;  r->walls[5].z1 =    1099;
    r->walls[5].x2 =    1292;  r->walls[5].z2 =    3300;
    r->walls[5].nx =   -4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -999;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -1400) */
    r->walls[6].x1 =   -2104;  r->walls[6].z1 =     910;
    r->walls[6].x2 =   -1826;  r->walls[6].z2 =     274;
    r->walls[6].nx =    3753;  r->walls[6].nz =    1638;
    r->walls[6].y_min =   -1800;  r->walls[6].y_max =   -1000;

    /* Wall 7 (avg Y: -1400) */
    r->walls[7].x1 =    2422;  r->walls[7].z1 =     274;
    r->walls[7].x2 =    2699;  r->walls[7].z2 =     910;
    r->walls[7].nx =   -3755;  r->walls[7].nz =    1635;
    r->walls[7].y_min =   -1800;  r->walls[7].y_max =   -1000;

    /* Wall 8 (avg Y: -1400) */
    r->walls[8].x1 =    2699;  r->walls[8].z1 =     910;
    r->walls[8].x2 =    2699;  r->walls[8].z2 =    3299;
    r->walls[8].nx =   -4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =   -1800;  r->walls[8].y_max =   -1000;

    /* Wall 9 (avg Y: -1400) */
    r->walls[9].x1 =   -2104;  r->walls[9].z1 =    3299;
    r->walls[9].x2 =   -2104;  r->walls[9].z2 =     910;
    r->walls[9].nx =    4096;  r->walls[9].nz =       0;
    r->walls[9].y_min =   -1800;  r->walls[9].y_max =   -1000;

    /* Wall 10 (avg Y: -1400) */
    r->walls[10].x1 =   -1504;  r->walls[10].z1 =    3300;
    r->walls[10].x2 =   -2104;  r->walls[10].z2 =    3299;
    r->walls[10].nx =       0;  r->walls[10].nz =   -4095;
    r->walls[10].y_min =   -1800;  r->walls[10].y_max =   -1000;

    /* Wall 11 (avg Y: -1400) */
    r->walls[11].x1 =    2699;  r->walls[11].z1 =    3299;
    r->walls[11].x2 =    2099;  r->walls[11].z2 =    3300;
    r->walls[11].nx =       0;  r->walls[11].nz =   -4095;
    r->walls[11].y_min =   -1800;  r->walls[11].y_max =   -1000;

    /* Wall 12 (avg Y: -1350) */
    r->walls[12].x1 =    2099;  r->walls[12].z1 =    3300;
    r->walls[12].x2 =    2099;  r->walls[12].z2 =     910;
    r->walls[12].nx =    4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =   -1800;  r->walls[12].y_max =   -1000;

    /* Wall 13 (avg Y: -1350) */
    r->walls[13].x1 =   -1504;  r->walls[13].z1 =     910;
    r->walls[13].x2 =   -1504;  r->walls[13].z2 =    3300;
    r->walls[13].nx =   -4096;  r->walls[13].nz =       0;
    r->walls[13].y_min =   -1800;  r->walls[13].y_max =   -1000;

    /* Wall 14 (avg Y: -499) */
    r->walls[14].x1 =     725;  r->walls[14].z1 =    3300;
    r->walls[14].x2 =     725;  r->walls[14].z2 =    3900;
    r->walls[14].nx =   -4096;  r->walls[14].nz =       0;
    r->walls[14].y_min =    -999;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -499) */
    r->walls[15].x1 =    -125;  r->walls[15].z1 =    3900;
    r->walls[15].x2 =    -125;  r->walls[15].z2 =    3300;
    r->walls[15].nx =    4096;  r->walls[15].nz =       0;
    r->walls[15].y_min =    -999;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -449) */
    r->walls[16].x1 =    -692;  r->walls[16].z1 =    3300;
    r->walls[16].x2 =    -692;  r->walls[16].z2 =    1099;
    r->walls[16].nx =    4096;  r->walls[16].nz =       0;
    r->walls[16].y_min =    -999;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -400) */
    r->walls[17].x1 =    -692;  r->walls[17].z1 =    1099;
    r->walls[17].x2 =    1292;  r->walls[17].z2 =    1099;
    r->walls[17].nx =       0;  r->walls[17].nz =    4096;
    r->walls[17].y_min =    -800;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -499) */
    r->walls[18].x1 =     725;  r->walls[18].z1 =    3900;
    r->walls[18].x2 =    -125;  r->walls[18].z2 =    3900;
    r->walls[18].nx =       0;  r->walls[18].nz =   -4096;
    r->walls[18].y_min =    -999;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -1400) */
    r->walls[19].x1 =   -1200;  r->walls[19].z1 =       0;
    r->walls[19].x2 =    1800;  r->walls[19].z2 =       0;
    r->walls[19].nx =       0;  r->walls[19].nz =    4096;
    r->walls[19].y_min =   -1800;  r->walls[19].y_max =   -1000;

    /* Wall 20 (avg Y: -1400) */
    r->walls[20].x1 =    1800;  r->walls[20].z1 =       0;
    r->walls[20].x2 =    2422;  r->walls[20].z2 =     274;
    r->walls[20].nx =   -1649;  r->walls[20].nz =    3749;
    r->walls[20].y_min =   -1800;  r->walls[20].y_max =   -1000;

    /* Wall 21 (avg Y: -1400) */
    r->walls[21].x1 =   -1826;  r->walls[21].z1 =     274;
    r->walls[21].x2 =   -1200;  r->walls[21].z2 =       0;
    r->walls[21].nx =    1640;  r->walls[21].nz =    3752;
    r->walls[21].y_min =   -1800;  r->walls[21].y_max =   -1000;

    /* Wall 22 (avg Y: -499) */
    r->walls[22].x1 =    1292;  r->walls[22].z1 =    3300;
    r->walls[22].x2 =     725;  r->walls[22].z2 =    3300;
    r->walls[22].nx =       0;  r->walls[22].nz =   -4096;
    r->walls[22].y_min =    -999;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -499) */
    r->walls[23].x1 =    -125;  r->walls[23].z1 =    3300;
    r->walls[23].x2 =    -692;  r->walls[23].z2 =    3300;
    r->walls[23].nx =       0;  r->walls[23].nz =   -4096;
    r->walls[23].y_min =    -999;  r->walls[23].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y= -1000  x(2099 to 2699)  z(910 to 3300)
     * FLOOR   1: y= -1000  x(-2104 to -1504)  z(910 to 3300)
     * FLOOR   2: y=     0  x(-125 to 725)  z(3300 to 3900)
     * FLOOR   3: y=     0  x(-692 to 1292)  z(1099 to 3300)
     * FLOOR   4: y= -1000  x(-1200 to 1800)  z(0 to 600)
     * FLOOR   5: y= -1000  x(1800 to 2422)  z(0 to 698)
     * FLOOR   6: y= -1000  x(1998 to 2699)  z(274 to 910)
     * FLOOR   7: y= -1000  x(-2104 to -1402)  z(274 to 910)
     * FLOOR   8: y= -1000  x(-1826 to -1200)  z(0 to 698)
     */
}
