/*
 * Auto-generated collision data from: Throat mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef THROAT_MESH_COLLISION_H
#define THROAT_MESH_COLLISION_H

#include "collision.h"

#define THROAT_WALL_COUNT  4
#define THROAT_FLOOR_COUNT 1

void throat_collision_init(CollisionRoom *r);

#endif /* THROAT_MESH_COLLISION_H */
