#!/usr/bin/env python3
"""
gen_dresser_tex_map.py — regenerate src/dresser_tex_map.h from assets/props/Dresser.smx.

The dresser prop is textured with two textures. Each <poly> stores texture="N"
indexing the SMX's own <textures> list, which the Blender exporter RENUMBERS
whenever the material set changes. So we resolve N -> name -> engine slot rather
than trusting the raw index (see tools/MESH_CONVERSION_NOTES.txt).

    slot 0 = wd_flr  (reused from the room's already-resident wood-floor texture)
    slot 1 = dresser (the prop's own streamed texture)

Run from the project root after re-exporting/reconverting the dresser mesh:
    python gen_dresser_tex_map.py
"""
import re

SMX = "assets/props/Dresser.smx"
OUT = "src/dresser_tex_map.h"
NAME_TO_SLOT = {"wd_flr": 0, "dresser": 1}

xml   = open(SMX).read()
texs  = re.findall(r'<texture file="([^"]+)"/>', xml)          # SMX texture list, in order
polys = re.findall(r'<poly[^>]*texture="(\d+)"', xml)          # per-poly texture index, in order
slots = [NAME_TO_SLOT[texs[int(i)]] for i in polys]

with open(OUT, "w") as f:
    f.write("#ifndef DRESSER_TEX_MAP_H\n#define DRESSER_TEX_MAP_H\n\n")
    f.write("/* Per-primitive texture slot for the dresser prop, in SMD primitive order\n")
    f.write("   (matches Dresser.smx poly order). Resolved by texture NAME so a change to\n")
    f.write("   the SMX <textures> ordering can't silently mis-map (see MESH_CONVERSION_NOTES).\n")
    f.write("     slot 0 = wd_flr  (reused from the room's resident wood-floor texture)\n")
    f.write("     slot 1 = dresser (the prop's own streamed texture)\n")
    f.write("   Generated by gen_dresser_tex_map.py. */\n")
    f.write("#define DRESSER_PRIM_COUNT %d\n\n" % len(slots))
    f.write("static const unsigned char dresser_tex_map[DRESSER_PRIM_COUNT] = {\n")
    for i in range(0, len(slots), 16):
        f.write("    " + ", ".join(str(v) for v in slots[i:i+16]) + ",\n")
    f.write("};\n\n#endif\n")

print("textures:", texs)
print("wrote %s (%d prims): %s" % (OUT, len(slots), slots))
