"""
gen_piano_room_tex_map.py — generate src/piano_room_tex_map.h from Piano_Room.smx.

Same scheme as gen_reception_tex_map.py: each <poly>'s texture="N" indexes the
SMX's own <textures> list, which the Blender exporter renumbers whenever the
material set changes — so we map per-poly by texture NAME, then name -> engine
VRAM slot via NAME_TO_SLOT.

NAME_TO_SLOT MUST match the slot order loaded in src/piano_room.c
(piano_room_load_assets). If you add/move a texture slot there, update it here.

Usage:
    python gen_piano_room_tex_map.py            # assets/Piano_Room.smx -> src/piano_room_tex_map.h
    python gen_piano_room_tex_map.py <smx> <out>
"""
import xml.etree.ElementTree as ET
import sys

SMX = sys.argv[1] if len(sys.argv) > 1 else 'assets/Piano_Room.smx'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'src/piano_room_tex_map.h'

# Engine VRAM slot for each texture name (must match src/piano_room.c load order).
NAME_TO_SLOT = {
    'prpl_wlppr': 0,
    'wd_flr':     1,
    'din_cl':     2,
    'wd_dr':      3,
}
UNTEXTURED = 0xFF

root = ET.parse(SMX).getroot()

smx_tex = [t.get('file') for t in root.find('textures').findall('texture')]
print("SMX textures: " + ", ".join(f"{i}={n}" for i, n in enumerate(smx_tex)))

verts = [(float(v.get('x')), float(v.get('y')), float(v.get('z')))
         for v in root.find('vertices').findall('v')]

def _collinear(a, b, c):
    ux, uy, uz = b[0]-a[0], b[1]-a[1], b[2]-a[2]
    vx, vy, vz = c[0]-a[0], c[1]-a[1], c[2]-a[2]
    cx, cy, cz = uy*vz-uz*vy, uz*vx-ux*vz, ux*vy-uy*vx
    return (cx*cx + cy*cy + cz*cz) < 1e-3

entries = []   # tex slot per prim
nocull  = []   # 1 = do NOT backface-cull (degenerate "triangle-shaped" quad)
for p in root.find('primitives').findall('poly'):
    n = p.get('texture')
    if n is None:
        entries.append(UNTEXTURED)
    else:
        name = smx_tex[int(n)]
        if name not in NAME_TO_SLOT:
            sys.exit(f"ERROR: SMX texture '{name}' has no engine slot in NAME_TO_SLOT "
                     f"(update both this script and src/piano_room.c).")
        entries.append(NAME_TO_SLOT[name])

    # A quad with three collinear verts renders as a triangle; gte_nclip on its
    # degenerate first triangle is ~0 and flickers the backface cull. Flag it so
    # the renderer never culls it. Triangles (no v3) are handled by the renderer's
    # is_quad check, so leave them 0.
    deg = 0
    if p.get('v3') is not None:
        q = [verts[int(p.get(f'v{k}'))] for k in range(4)]
        if any(_collinear(q[a], q[b], q[c])
               for a, b, c in ((0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3))):
            deg = 1
    nocull.append(deg)

inv = {v: k for k, v in NAME_TO_SLOT.items()}
counts = {}
for e in entries:
    counts[e] = counts.get(e, 0) + 1
print(f"{len(entries)} prims: " + ", ".join(
    (f"slot{k}({inv.get(k, '?')})={v}" if k != UNTEXTURED else f"untextured={v}")
    for k, v in sorted(counts.items())))

lines = [
    "/* Auto-generated by gen_piano_room_tex_map.py — do not edit.",
    "   Per-poly texture mapped by NAME to engine VRAM slots (see the script). */",
    "#pragma once",
    "#include <stdint.h>",
    f"#define PIANO_ROOM_PRIM_COUNT {len(entries)}",
    f"static const uint8_t piano_room_tex_map[{len(entries)}] = {{",
]
row = []
for i, e in enumerate(entries):
    row.append(f"0x{e:02X}")
    if len(row) == 16 or i == len(entries) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")

lines.append("/* 1 = triangle-shaped (degenerate) quad: never backface-cull it. */")
lines.append(f"static const uint8_t piano_room_nocull[{len(nocull)}] = {{")
row = []
for i, e in enumerate(nocull):
    row.append(str(e))
    if len(row) == 32 or i == len(nocull) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")
print(f"degenerate (never-cull) quads: {sum(nocull)}")

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Written to {OUT}")
