#!/usr/bin/env python3
"""
gen_grinder_tex_map.py — regenerate src/grinder_tex_map.h from assets/props/Grinder.smx.

The grinder prop is textured with two textures. Each <poly> stores texture="N"
indexing the SMX's own <textures> list, which the Blender exporter RENUMBERS
whenever the material set changes. So we resolve N -> name -> engine slot rather
than trusting the raw index (see tools/MESH_CONVERSION_NOTES.txt).

    slot 0 = plinth  (reused from the room's already-resident plinth texture —
                      plinth_rg in the Rear Gate)
    slot 1 = grinder (the prop's own texture, resident from startup)

Slot 1 is also what tells grinders_draw which faces need the half-page U remap;
see the note in src/grinder.c.

Run from the project root after re-exporting/reconverting the grinder mesh:
    py gen_grinder_tex_map.py
"""
import re

SMX = "assets/props/Grinder.smx"
OUT = "src/grinder_tex_map.h"
NAME_TO_SLOT = {"plinth": 0, "grinder": 1}

xml   = open(SMX).read()
texs  = re.findall(r'<texture file="([^"]+)"/>', xml)          # SMX texture list, in order
polys = re.findall(r'<poly[^>]*texture="(\d+)"', xml)          # per-poly texture index, in order
slots = [NAME_TO_SLOT[texs[int(i)]] for i in polys]

with open(OUT, "w") as f:
    f.write("#ifndef GRINDER_TEX_MAP_H\n#define GRINDER_TEX_MAP_H\n\n")
    f.write("/* Per-primitive texture slot for the grinder prop, in SMD primitive order\n")
    f.write("   (matches Grinder.smx poly order). Resolved by texture NAME so a change to\n")
    f.write("   the SMX <textures> ordering can't silently mis-map (see MESH_CONVERSION_NOTES).\n")
    f.write("     slot 0 = plinth  (reused from the room's resident plinth texture)\n")
    f.write("     slot 1 = grinder (the prop's own startup-resident texture, and the\n")
    f.write("                       faces that need the half-page U remap in grinder.c)\n")
    f.write("   Generated by gen_grinder_tex_map.py. */\n")
    f.write("#define GRINDER_PRIM_COUNT %d\n\n" % len(slots))
    f.write("static const unsigned char grinder_tex_map[GRINDER_PRIM_COUNT] = {\n")
    for i in range(0, len(slots), 16):
        f.write("    " + ", ".join(str(v) for v in slots[i:i+16]) + ",\n")
    f.write("};\n\n#endif\n")

print("textures:", texs)
print("wrote %s (%d prims): %s" % (OUT, len(slots), slots))
