"""
gen_maze_two_tex_map.py - generate src/maze_two_tex_map.h from "Maze Two.smx".
Same name-based scheme as gen_maze_one_tex_map.py (the Blender exporter
renumbers the SMX's own texture list whenever the material set changes, so raw
indices are unstable).

NAME_TO_SLOT MUST match the slot order loaded in src/maze_two.c
(maze_two_load_assets). If you add/move a texture slot there, update it here too.

NOTE THE SOURCE PATH: this room's exports live in assets/garden/, not in
assets/ like the older rooms' — the same as Maze One, Fountain Square and the
Outside Catacombs. Nothing in the build reads them except this script and the
two conversion commands in tools/ADDING_A_ROOM.txt STEP 4.

Usage:
    python gen_maze_two_tex_map.py         # assets/garden/Maze Two.smx ->
                                           # src/maze_two_tex_map.h
    python gen_maze_two_tex_map.py <smx> <out>
"""
import xml.etree.ElementTree as ET
import sys

SMX = sys.argv[1] if len(sys.argv) > 1 else 'assets/garden/Maze Two.smx'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'src/maze_two_tex_map.h'

# Engine VRAM slot for each texture name (must match src/maze_two.c load order).
NAME_TO_SLOT = {
    # Borrowed. hedge / grdn_gte / grss come from the Garden Courtyard's
    # uploader, which this room runs wholesale; 'grss' resolves to the grss_gs
    # CLONE for the same reason the courtyard's, Fountain Square's and Maze
    # One's do, so the whole garden chain draws from one set of slots.
    'hedge':              0,
    'grdn_gte':           1,
    'grss':               2,
    # poison_flower_base belongs to the Outside Catacombs and pipe to Maze One;
    # this room takes each through that module's NARROW upload rather than
    # registering a second RAM copy of either (see src/maze_two.c).
    'poison_flower_base': 3,
    'pipe':               4,
    # The one texture this room OWNS: the plinth standing in the maze.
    'plinth':             5,
}
UNTEXTURED = 0xFF

root = ET.parse(SMX).getroot()

smx_tex = [t.get('file') for t in root.find('textures').findall('texture')]
print("SMX textures: " + ", ".join(f"{i}={n}" for i, n in enumerate(smx_tex)))

verts = [(float(v.get('x')), float(v.get('y')), float(v.get('z')))
         for v in root.find('vertices').findall('v')]

def _collinear(a, b, c):
    ux, uy, uz = b[0]-a[0], b[1]-a[1], b[2]-a[2]
    vx, vy, vz = c[0]-a[0], c[1]-a[1], c[2]-a[2]
    cx, cy, cz = uy*vz-uz*vy, uz*vx-ux*vz, ux*vy-uy*vx
    return (cx*cx + cy*cy + cz*cz) < 1e-3

entries = []   # tex slot per prim
nocull  = []   # 1 = do NOT backface-cull (degenerate "triangle-shaped" quad)
for p in root.find('primitives').findall('poly'):
    n = p.get('texture')
    if n is None:
        entries.append(UNTEXTURED)
    else:
        name = smx_tex[int(n)]
        if name not in NAME_TO_SLOT:
            sys.exit(f"ERROR: SMX texture '{name}' has no engine slot in NAME_TO_SLOT "
                     f"(update both this script and src/maze_two.c).")
        entries.append(NAME_TO_SLOT[name])

    deg = 0
    if p.get('v3') is not None:
        q = [verts[int(p.get(f'v{k}'))] for k in range(4)]
        if any(_collinear(q[a], q[b], q[c])
               for a, b, c in ((0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3))):
            deg = 1
    nocull.append(deg)

inv = {v: k for k, v in NAME_TO_SLOT.items()}
counts = {}
for e in entries:
    counts[e] = counts.get(e, 0) + 1
print(f"{len(entries)} prims: " + ", ".join(
    (f"slot{k}({inv.get(k, '?')})={v}" if k != UNTEXTURED else f"untextured={v}")
    for k, v in sorted(counts.items())))

lines = [
    "/* Auto-generated by gen_maze_two_tex_map.py - do not edit.",
    "   Per-poly texture mapped by NAME to engine VRAM slots (see the script). */",
    "#pragma once",
    "#include <stdint.h>",
    f"#define MAZE_TWO_PRIM_COUNT {len(entries)}",
    f"static const uint8_t maze_two_tex_map[{len(entries)}] = {{",
]
row = []
for i, e in enumerate(entries):
    row.append(f"0x{e:02X}")
    if len(row) == 16 or i == len(entries) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")

lines.append("/* 1 = triangle-shaped (degenerate) quad: never backface-cull it. */")
lines.append(f"static const uint8_t maze_two_nocull[{len(nocull)}] = {{")
row = []
for i, e in enumerate(nocull):
    row.append(str(e))
    if len(row) == 32 or i == len(nocull) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")
print(f"degenerate (never-cull) quads: {sum(nocull)}")

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Written to {OUT}")
