"""
gen_reception_tex_map.py — generate src/reception_tex_map.h from Reception.smx.

Each <poly> in the SMX carries texture="N", where N indexes the SMX's own
<textures> list. That list is renumbered by the Blender exporter whenever the
material set changes (e.g. dropping a texture shifts every later index), so a
raw-index map silently mis-assigns textures after a re-export.

To be robust, we map per-poly by texture NAME: read the SMX <textures> list to
resolve N -> name, then look the name up in the engine's fixed VRAM slot order
(NAME_TO_SLOT below). The poly order in the SMX matches the SMD primitive order
after smxlink, so reception_tex_map[i] lines up with reception_smd prim i.

NAME_TO_SLOT MUST match the slot order loaded in src/reception.c
(reception_load_assets / new_tex[] + capture_tpage calls). If you add/move a
texture slot there, update it here too.

Usage:
    python gen_reception_tex_map.py            # assets/Reception.smx -> src/reception_tex_map.h
    python gen_reception_tex_map.py <smx> <out>
"""
import xml.etree.ElementTree as ET
import sys

SMX = sys.argv[1] if len(sys.argv) > 1 else 'assets/Reception.smx'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'src/reception_tex_map.h'

# Engine VRAM slot for each texture name (must match src/reception.c load order).
NAME_TO_SLOT = {
    'strs':       0,
    'red_wlppr':  1,
    'wd_flr':     2,
    'bnnstr':     3,
    'din_cl':     4,
    'frnt_dr':    5,
    'wd_dr':      6,
    'inr_dbl_dr': 7,
    'stn_gls':    8,
}
UNTEXTURED = 0xFF

root = ET.parse(SMX).getroot()

smx_tex = [t.get('file') for t in root.find('textures').findall('texture')]
print("SMX textures: " + ", ".join(f"{i}={n}" for i, n in enumerate(smx_tex)))

entries = []
for p in root.find('primitives').findall('poly'):
    n = p.get('texture')
    if n is None:
        entries.append(UNTEXTURED)
        continue
    name = smx_tex[int(n)]
    if name not in NAME_TO_SLOT:
        sys.exit(f"ERROR: SMX texture '{name}' has no engine slot in NAME_TO_SLOT "
                 f"(update both this script and src/reception.c).")
    entries.append(NAME_TO_SLOT[name])

inv = {v: k for k, v in NAME_TO_SLOT.items()}
counts = {}
for e in entries:
    counts[e] = counts.get(e, 0) + 1
print(f"{len(entries)} prims: " + ", ".join(
    (f"slot{k}({inv.get(k, '?')})={v}" if k != UNTEXTURED else f"untextured={v}")
    for k, v in sorted(counts.items())))

lines = [
    "/* Auto-generated by gen_reception_tex_map.py — do not edit.",
    "   Per-poly texture mapped by NAME to engine VRAM slots (see the script). */",
    "#pragma once",
    "#include <stdint.h>",
    f"#define RECEPTION_PRIM_COUNT {len(entries)}",
    f"static const uint8_t reception_tex_map[{len(entries)}] = {{",
]
row = []
for i, e in enumerate(entries):
    row.append(f"0x{e:02X}")
    if len(row) == 16 or i == len(entries) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Written to {OUT}")
