"""
gen_tex_map.py  —  generate src/level1_tex_map.h from a subdivided SMX.

Reads the texture="N" attribute on each poly (in primitive order, which
matches the SMD primitive order after smxlink conversion) and writes a
C header with a uint8_t array: 0xFF = untextured, 0 = gravel, 1 = rusty fence.

Usage:
    python gen_tex_map.py assets/level1_front_entrance.smx
"""
import xml.etree.ElementTree as ET
import sys

SMX = sys.argv[1] if len(sys.argv) > 1 else 'assets/level1_front_entrance.smx'
OUT = 'src/level1_tex_map.h'

tree = ET.parse(SMX)
root = tree.getroot()

entries = []
for p in root.find('primitives').findall('poly'):
    tex = p.get('texture')
    entries.append(int(tex) if tex is not None else 0xFF)

counts = {}
for e in entries:
    counts[e] = counts.get(e, 0) + 1
print(f"{len(entries)} prims: " + ", ".join(f"tex{k}={v}" if k != 0xFF else f"untextured={v}"
                                              for k, v in sorted(counts.items())))

lines = [
    "/* Auto-generated by gen_tex_map.py — do not edit. */",
    "#pragma once",
    "#include <stdint.h>",
    f"#define LEVEL1_PRIM_COUNT {len(entries)}",
    f"static const uint8_t level1_tex_map[{len(entries)}] = {{",
]

row = []
for i, e in enumerate(entries):
    row.append(f"0x{e:02X}")
    if len(row) == 16 or i == len(entries) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []

lines.append("};")

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Written to {OUT}")
