"""
gen_asag_arena_tex_map.py - generate src/asag_arena_tex_map.h from
"assets/garden/asag/Asag_Arena.smx". Same name-based scheme as
gen_chain_room_tex_map.py: the Blender exporter renumbers the SMX's own texture
list whenever the material set changes, so a raw-index map silently mis-assigns
every texture past the one that moved.

NAME_TO_SLOT MUST match the row order of stream_tex_file[] in src/asag_arena.c.
Unlike every other room in the game, that table is NOT a set of compile-time
constants out of src/tim_slots.h - asag_arena.c captures each TIM's tpage/clut
from GetTimInfo at read time, precisely so a texture can be added here and to
disc.xml without a generator run. The SLOT INDEX is still the row position, so
this map and that table have to agree.

>>> SLOTS 3..6 ARE NOT THE ROOM'S. <<< They are the boss's four skins, and they
are streamed by the ROOM because the room already owns the one loading screen
that reaches this area and the boss owns none. src/asag.c reads them back
through asag_arena_tex_slot(). No arena polygon uses them, so they never appear
in the map below - if one ever does, that is a texturing mistake, not a feature.

Usage:
    python gen_asag_arena_tex_map.py       # assets/garden/asag/Asag_Arena.smx ->
                                           # src/asag_arena_tex_map.h
    python gen_asag_arena_tex_map.py <smx> <out>
"""
import xml.etree.ElementTree as ET
import sys

SMX = sys.argv[1] if len(sys.argv) > 1 else 'assets/garden/asag/Asag_Arena.smx'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'src/asag_arena_tex_map.h'

# Engine VRAM slot for each texture name. MUST match stream_tex_file[] in
# src/asag_arena.c. VRAM slots come from tools/VRAM_MAP_ASAG.txt: every one is a
# full 8bpp page at Voff 0 whose occupants are all reclaimable in this bank, so
# taking them costs nothing and owes nobody a restore. chain_128 is the
# exception and is 4bpp - it needs only the left half of its page.
NAME_TO_SLOT = {
    'mud':       0,   # x384 y0    the arena floor and its mud banks
    'Boss Wall': 1,   # x512 y0    the perimeter wall
    'chain_128': 2,   # x320 y256, 4bpp, left half of the page
    # 3 asag / 4 leaf / 5 tentacle / 6 boil are the BOSS's, streamed by the room
    # but never referenced by an arena polygon. See the header.
}
UNTEXTURED = 0xFF

root = ET.parse(SMX).getroot()

smx_tex = [t.get('file') for t in root.find('textures').findall('texture')]
print("SMX textures: " + ", ".join(f"{i}={n}" for i, n in enumerate(smx_tex)))

verts = [(float(v.get('x')), float(v.get('y')), float(v.get('z')))
         for v in root.find('vertices').findall('v')]


def _collinear(a, b, c):
    ux, uy, uz = b[0]-a[0], b[1]-a[1], b[2]-a[2]
    vx, vy, vz = c[0]-a[0], c[1]-a[1], c[2]-a[2]
    cx, cy, cz = uy*vz-uz*vy, uz*vx-ux*vz, ux*vy-uy*vx
    return (cx*cx + cy*cy + cz*cz) < 1e-3


entries = []   # tex slot per prim
nocull = []    # 1 = do NOT backface-cull (degenerate "triangle-shaped" quad)
for p in root.find('primitives').findall('poly'):
    n = p.get('texture')
    if n is None:
        entries.append(UNTEXTURED)
    else:
        name = smx_tex[int(n)]
        if name not in NAME_TO_SLOT:
            sys.exit(f"ERROR: SMX texture '{name}' has no engine slot in "
                     f"NAME_TO_SLOT (update both this script and "
                     f"stream_tex_file[] in src/asag_arena.c).")
        entries.append(NAME_TO_SLOT[name])

    deg = 0
    if p.get('v3') is not None:
        q = [verts[int(p.get(f'v{k}'))] for k in range(4)]
        if any(_collinear(q[a], q[b], q[c])
               for a, b, c in ((0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3))):
            deg = 1
    nocull.append(deg)

inv = {v: k for k, v in NAME_TO_SLOT.items()}
counts = {}
for e in entries:
    counts[e] = counts.get(e, 0) + 1
print(f"{len(entries)} prims: " + ", ".join(
    (f"slot{k}({inv.get(k, '?')})={v}" if k != UNTEXTURED else f"untextured={v}")
    for k, v in sorted(counts.items())))

lines = [
    "/* Auto-generated by gen_asag_arena_tex_map.py - do not edit.",
    "   Per-poly texture mapped by NAME to engine VRAM slots (see the script). */",
    "#pragma once",
    "#include <stdint.h>",
    f"#define ASAG_ARENA_PRIM_COUNT {len(entries)}",
    f"static const uint8_t asag_arena_tex_map[{len(entries)}] = {{",
]
row = []
for i, e in enumerate(entries):
    row.append(f"0x{e:02X}")
    if len(row) == 16 or i == len(entries) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")

lines.append("/* 1 = triangle-shaped (degenerate) quad: never backface-cull it. */")
lines.append(f"static const uint8_t asag_arena_nocull[{len(nocull)}] = {{")
row = []
for i, e in enumerate(nocull):
    row.append(str(e))
    if len(row) == 32 or i == len(nocull) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")
print(f"degenerate (never-cull) quads: {sum(nocull)}")

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Written to {OUT}")
