"""
gen_the_shelf_tex_map.py - generate src/the_shelf_tex_map.h from
"The Shelf.smx". Same
name-based scheme as every other room's generator (the Blender exporter
renumbers the SMX's own texture list whenever the material set changes, so raw
indices are unstable).

NAME_TO_SLOT MUST match the slot order loaded in src/the_shelf.c
(the_shelf_load_assets).
If you add/move a texture slot there, update it here too.

NOTE THE SOURCE PATH: this room's exports live in assets/catacombs/, beside the
other Chapter 3 rooms'.

Usage:
    python gen_the_shelf_tex_map.py
        # assets/catacombs/The Shelf.smx -> src/the_shelf_tex_map.h
    python gen_the_shelf_tex_map.py <smx> <out>
"""
import xml.etree.ElementTree as ET
import sys

SMX = sys.argv[1] if len(sys.argv) > 1 else 'assets/catacombs/The Shelf.smx'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'src/the_shelf_tex_map.h'

# Engine VRAM slot for each texture name (must match src/the_shelf.c).
#
# FOUR ARE BORROWED AND ONE IS OWNED. Cobblestone and the inner door come from
# src/catacombs_entry.c through its narrow uploaders, the ladder from
# src/north_chamber.c through north_chamber_upload_ladder(), and the bars from
# src/bars.c through bars_upload_texture(). The incinerator panel is the room's
# OWN copy of the incinerator art (SHLFINCN.TIM, on the arms page): the real one
# shares x704 y256 and its CLUT line with the ladder, and this room draws both.
#
# The material is 'ladder_128' here, not 'ladder' as in the H Corridor - the
# same art (textures/ladder_128.tim is an EXPORTER_ALIASES copy of ladder.tim).
#
# NINE POLYS ARE UNTEXTURED on purpose: the black floor of the ladder shaft at
# y=+1200. They map to UNTEXTURED and draw flat.
NAME_TO_SLOT = {
    'cobblestones':        0,   # the walls, the floor and the shaft
    'catacomb inner door': 1,   # the north door (to the Up Down Maze)
    'ladder_128':          2,   # down the shaft's south wall (to the H Corridor)
    'incinerator':         3,   # the one panel on the west wall
    'bars':                4,   # the two barred partitions
}
UNTEXTURED = 0xFF

root = ET.parse(SMX).getroot()

smx_tex = [t.get('file') for t in root.find('textures').findall('texture')]
print("SMX textures: " + ", ".join(f"{i}={n}" for i, n in enumerate(smx_tex)))

verts = [(float(v.get('x')), float(v.get('y')), float(v.get('z')))
         for v in root.find('vertices').findall('v')]

def _collinear(a, b, c):
    ux, uy, uz = b[0]-a[0], b[1]-a[1], b[2]-a[2]
    vx, vy, vz = c[0]-a[0], c[1]-a[1], c[2]-a[2]
    cx, cy, cz = uy*vz-uz*vy, uz*vx-ux*vz, ux*vy-uy*vx
    return (cx*cx + cy*cy + cz*cz) < 1e-3

entries = []   # tex slot per prim
nocull  = []   # 1 = do NOT backface-cull (degenerate "triangle-shaped" quad)
for p in root.find('primitives').findall('poly'):
    n = p.get('texture')
    if n is None:
        entries.append(UNTEXTURED)
    else:
        name = smx_tex[int(n)]
        if name not in NAME_TO_SLOT:
            sys.exit(f"ERROR: SMX texture '{name}' has no engine slot in NAME_TO_SLOT "
                     f"(update both this script and src/the_shelf.c).")
        entries.append(NAME_TO_SLOT[name])

    deg = 0
    if p.get('v3') is not None:
        q = [verts[int(p.get(f'v{k}'))] for k in range(4)]
        if any(_collinear(q[a], q[b], q[c])
               for a, b, c in ((0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3))):
            deg = 1
    nocull.append(deg)

inv = {v: k for k, v in NAME_TO_SLOT.items()}
counts = {}
for e in entries:
    counts[e] = counts.get(e, 0) + 1
print(f"{len(entries)} prims: " + ", ".join(
    (f"slot{k}({inv.get(k, '?')})={v}" if k != UNTEXTURED else f"untextured={v}")
    for k, v in sorted(counts.items())))

lines = [
    "/* Auto-generated by gen_the_shelf_tex_map.py - do not edit.",
    "   Per-poly texture mapped by NAME to engine VRAM slots (see the script). */",
    "#pragma once",
    "#include <stdint.h>",
    f"#define THE_SHELF_PRIM_COUNT {len(entries)}",
    f"static const uint8_t the_shelf_tex_map[{len(entries)}] = {{",
]
row = []
for i, e in enumerate(entries):
    row.append(f"0x{e:02X}")
    if len(row) == 16 or i == len(entries) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")

lines.append("/* 1 = triangle-shaped (degenerate) quad: never backface-cull it. */")
lines.append(f"static const uint8_t the_shelf_nocull[{len(nocull)}] = {{")
row = []
for i, e in enumerate(nocull):
    row.append(str(e))
    if len(row) == 32 or i == len(nocull) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")
print(f"degenerate (never-cull) quads: {sum(nocull)}")

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Written to {OUT}")
