"""
gen_greenhouse_tex_map.py - generate src/greenhouse_tex_map.h from "Greenhouse.smx".
Same name-based scheme as gen_rear_gate_tex_map.py (the Blender exporter
renumbers the SMX's own texture list whenever the material set changes, so raw
indices are unstable).

NAME_TO_SLOT MUST match the slot order loaded in src/greenhouse.c
(greenhouse_load_assets). If you add/move a texture slot there, update it here too.

NOTE THE SOURCE PATH: this room's exports live in assets/garden/, like the rest
of the garden's.

Usage:
    python gen_greenhouse_tex_map.py          # assets/garden/Greenhouse.smx ->
                                           # src/greenhouse_tex_map.h
    python gen_greenhouse_tex_map.py <smx> <out>
"""
import xml.etree.ElementTree as ET
import sys

SMX = sys.argv[1] if len(sys.argv) > 1 else 'assets/garden/Greenhouse.smx'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'src/greenhouse_tex_map.h'

# Engine VRAM slot for each texture name (must match src/greenhouse.c load order).
#
# TEN textures, the most of any room. FIVE cost this room nothing: two come from
# garden_courtyard_upload_textures() and three from stables_upload_textures(),
# which this room calls wholesale on the way in. The other five are its own and
# are the second and last batch of the GARDEN-WEST VRAM BANK (see
# tools/VRAM_MAP_GARDEN_WEST.txt).
#
# THREE REDIRECTIONS, and all three exist for one reason: the texture's own TIM
# sits on a page this room ALREADY draws something else from.
#
#   'grss'               -> the grss_gs CLONE at x320 y0. grss.tim is at x768 y0,
#                           where brick_wall goes. Every garden room since the
#                           Garden Stairs makes this same swap.
#   'poison_flower_base' -> the PSNFLGH 4bpp clone at x704 y0. Its own TIM is at
#                           x640 y0, which is where 'greenhouse' lives.
#   'pipe'               -> the PIPEGH 4bpp clone at x384 y256. Its own TIM is at
#                           x768 y0, which is brick_wall's page again.
NAME_TO_SLOT = {
    # Borrowed from the Garden Courtyard's uploader (which runs the Garden
    # Stairs' first, and it is that call which puts brick_wall up).
    'grss':               0,   # -> grss_gs, x320 y0
    'brick_wall':         1,   # x768 y0
    # Borrowed from the Stables' uploader - the bank's first room owns these.
    'greenhouse':         2,   # x640 y0, 8bpp
    'stables wood':       3,   # x832 y0, 8bpp
    'greenhouse door':    4,   # x320 y256, 4bpp - also this room's door panel
    # The five this room OWNS.
    'flowerbed':          5,   # x384 y0,   8bpp, over hedge (pixels AND CLUT)
    'cuniform pipes':     6,   # x512 y0,   8bpp, over grdn_gte (pixels AND CLUT)
    'poison_flower_base': 7,   # -> PSNFLGH, x704 y0,  4bpp, over stable glyphs
    'pipe':               8,   # -> PIPEGH,  x384 y256, 4bpp
    'pipe_button_off':    9,   # x512 y256, 4bpp
}
UNTEXTURED = 0xFF

root = ET.parse(SMX).getroot()

smx_tex = [t.get('file') for t in root.find('textures').findall('texture')]
print("SMX textures: " + ", ".join(f"{i}={n}" for i, n in enumerate(smx_tex)))

verts = [(float(v.get('x')), float(v.get('y')), float(v.get('z')))
         for v in root.find('vertices').findall('v')]

def _collinear(a, b, c):
    ux, uy, uz = b[0]-a[0], b[1]-a[1], b[2]-a[2]
    vx, vy, vz = c[0]-a[0], c[1]-a[1], c[2]-a[2]
    cx, cy, cz = uy*vz-uz*vy, uz*vx-ux*vz, ux*vy-uy*vx
    return (cx*cx + cy*cy + cz*cz) < 1e-3

entries = []   # tex slot per prim
nocull  = []   # 1 = do NOT backface-cull (degenerate "triangle-shaped" quad)
for p in root.find('primitives').findall('poly'):
    n = p.get('texture')
    if n is None:
        entries.append(UNTEXTURED)
    else:
        name = smx_tex[int(n)]
        if name not in NAME_TO_SLOT:
            sys.exit(f"ERROR: SMX texture '{name}' has no engine slot in NAME_TO_SLOT "
                     f"(update both this script and src/greenhouse.c).")
        entries.append(NAME_TO_SLOT[name])

    deg = 0
    if p.get('v3') is not None:
        q = [verts[int(p.get(f'v{k}'))] for k in range(4)]
        if any(_collinear(q[a], q[b], q[c])
               for a, b, c in ((0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3))):
            deg = 1
    nocull.append(deg)

inv = {v: k for k, v in NAME_TO_SLOT.items()}
counts = {}
for e in entries:
    counts[e] = counts.get(e, 0) + 1
print(f"{len(entries)} prims: " + ", ".join(
    (f"slot{k}({inv.get(k, '?')})={v}" if k != UNTEXTURED else f"untextured={v}")
    for k, v in sorted(counts.items())))

lines = [
    "/* Auto-generated by gen_greenhouse_tex_map.py - do not edit.",
    "   Per-poly texture mapped by NAME to engine VRAM slots (see the script). */",
    "#pragma once",
    "#include <stdint.h>",
    f"#define GREENHOUSE_PRIM_COUNT {len(entries)}",
    f"static const uint8_t greenhouse_tex_map[{len(entries)}] = {{",
]
row = []
for i, e in enumerate(entries):
    row.append(f"0x{e:02X}")
    if len(row) == 16 or i == len(entries) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")

lines.append("/* 1 = triangle-shaped (degenerate) quad: never backface-cull it. */")
lines.append(f"static const uint8_t greenhouse_nocull[{len(nocull)}] = {{")
row = []
for i, e in enumerate(nocull):
    row.append(str(e))
    if len(row) == 32 or i == len(nocull) - 1:
        lines.append("    " + ",".join(row) + ",")
        row = []
lines.append("};")
print(f"degenerate (never-cull) quads: {sum(nocull)}")

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f"Written to {OUT}")
