/*
 * Auto-generated collision data from: Asag Version Two mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  12
 * Floors: 3
 * Bounds: X(-1500 to 1500)  Z(0 to 2700)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Asag Version Two mesh_collision.h"

void asag_arena_collision_init(CollisionRoom *r) {
    r->wall_count = ASAG_ARENA_WALL_COUNT;
    r->min_x = -1500;
    r->max_x = 1500;
    r->min_z = 0;
    r->max_z = 2700;

    /* Wall 0 (avg Y: -500) */
    r->walls[0].x1 =    1500;  r->walls[0].z1 =     186;
    r->walls[0].x2 =    1300;  r->walls[0].z2 =     186;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =   -1000;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -500) */
    r->walls[1].x1 =   -1300;  r->walls[1].z1 =    2700;
    r->walls[1].x2 =   -1299;  r->walls[1].z2 =    2610;
    r->walls[1].nx =    4095;  r->walls[1].nz =       0;
    r->walls[1].y_min =   -1000;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -500) */
    r->walls[2].x1 =    1300;  r->walls[2].z1 =    2700;
    r->walls[2].x2 =   -1300;  r->walls[2].z2 =    2700;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4096;
    r->walls[2].y_min =   -1000;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -500) */
    r->walls[3].x1 =    1500;  r->walls[3].z1 =    2613;
    r->walls[3].x2 =    1300;  r->walls[3].z2 =    2610;
    r->walls[3].nx =      68;  r->walls[3].nz =   -4095;
    r->walls[3].y_min =   -1000;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -500) */
    r->walls[4].x1 =   -1299;  r->walls[4].z1 =     190;
    r->walls[4].x2 =   -1300;  r->walls[4].z2 =       0;
    r->walls[4].nx =    4095;  r->walls[4].nz =       0;
    r->walls[4].y_min =   -1000;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -500) */
    r->walls[5].x1 =    1300;  r->walls[5].z1 =       0;
    r->walls[5].x2 =    1300;  r->walls[5].z2 =     190;
    r->walls[5].nx =   -4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =   -1000;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -500) */
    r->walls[6].x1 =    1300;  r->walls[6].z1 =    2610;
    r->walls[6].x2 =    1300;  r->walls[6].z2 =    2700;
    r->walls[6].nx =   -4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =   -1000;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -500) */
    r->walls[7].x1 =    1500;  r->walls[7].z1 =     186;
    r->walls[7].x2 =    1500;  r->walls[7].z2 =    2613;
    r->walls[7].nx =   -4096;  r->walls[7].nz =       0;
    r->walls[7].y_min =   -1000;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -500) */
    r->walls[8].x1 =   -1500;  r->walls[8].z1 =    2613;
    r->walls[8].x2 =   -1500;  r->walls[8].z2 =     186;
    r->walls[8].nx =    4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =   -1000;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -500) */
    r->walls[9].x1 =   -1500;  r->walls[9].z1 =     186;
    r->walls[9].x2 =   -1299;  r->walls[9].z2 =     190;
    r->walls[9].nx =     -68;  r->walls[9].nz =    4095;
    r->walls[9].y_min =   -1000;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -500) */
    r->walls[10].x1 =   -1300;  r->walls[10].z1 =       0;
    r->walls[10].x2 =    1300;  r->walls[10].z2 =       0;
    r->walls[10].nx =       0;  r->walls[10].nz =    4096;
    r->walls[10].y_min =   -1000;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -500) */
    r->walls[11].x1 =   -1299;  r->walls[11].z1 =    2610;
    r->walls[11].x2 =   -1500;  r->walls[11].z2 =    2613;
    r->walls[11].nx =     -68;  r->walls[11].nz =   -4095;
    r->walls[11].y_min =   -1000;  r->walls[11].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-1300 to 1300)  z(2613 to 2700)
     * FLOOR   1: y=     0  x(-1300 to 1300)  z(0 to 186)
     * FLOOR   2: y=     0  x(-1500 to 1500)  z(186 to 2613)
     */
}
