/*
 * Auto-generated collision data from: Asag Version Two_Boss.smx
 * Generated by smx_to_collision.py
 * Walls:  26
 * Floors: 34
 * Bounds: X(-168 to 145)  Z(2261 to 3931)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Asag Version Two_Boss_collision.h"

void asag_boss_collision_init(CollisionRoom *r) {
    r->wall_count = ASAG_BOSS_WALL_COUNT;
    r->min_x = -168;
    r->max_x = 145;
    r->min_z = 2261;
    r->max_z = 3931;

    /* Wall 0 (avg Y: -624) */
    r->walls[0].x1 =    -100;  r->walls[0].z1 =    3606;
    r->walls[0].x2 =    -100;  r->walls[0].z2 =    3931;
    r->walls[0].nx =   -4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -727;  r->walls[0].y_max =    -527;

    /* Wall 1 (avg Y: -624) */
    r->walls[1].x1 =     100;  r->walls[1].z1 =    3931;
    r->walls[1].x2 =     100;  r->walls[1].z2 =    3606;
    r->walls[1].nx =    4095;  r->walls[1].nz =       0;
    r->walls[1].y_min =    -727;  r->walls[1].y_max =    -527;

    /* Wall 2 (avg Y: -603) */
    r->walls[2].x1 =     -98;  r->walls[2].z1 =    3506;
    r->walls[2].x2 =     -98;  r->walls[2].z2 =    3660;
    r->walls[2].nx =   -4095;  r->walls[2].nz =     -40;
    r->walls[2].y_min =    -714;  r->walls[2].y_max =    -527;

    /* Wall 3 (avg Y: -604) */
    r->walls[3].x1 =     101;  r->walls[3].z1 =    3658;
    r->walls[3].x2 =     101;  r->walls[3].z2 =    3504;
    r->walls[3].nx =    4095;  r->walls[3].nz =      38;
    r->walls[3].y_min =    -716;  r->walls[3].y_max =    -527;

    /* Wall 4 (avg Y: -694) */
    r->walls[4].x1 =    -102;  r->walls[4].z1 =    3370;
    r->walls[4].x2 =     -98;  r->walls[4].z2 =    3660;
    r->walls[4].nx =   -4094;  r->walls[4].nz =      90;
    r->walls[4].y_min =    -844;  r->walls[4].y_max =    -568;

    /* Wall 5 (avg Y: -695) */
    r->walls[5].x1 =     101;  r->walls[5].z1 =    3658;
    r->walls[5].x2 =      97;  r->walls[5].z2 =    3367;
    r->walls[5].nx =    4095;  r->walls[5].nz =     -42;
    r->walls[5].y_min =    -845;  r->walls[5].y_max =    -571;

    /* Wall 6 (avg Y: -790) */
    r->walls[6].x1 =      98;  r->walls[6].z1 =    3453;
    r->walls[6].x2 =      97;  r->walls[6].z2 =    3367;
    r->walls[6].nx =    4095;  r->walls[6].nz =     -36;
    r->walls[6].y_min =    -875;  r->walls[6].y_max =    -650;

    /* Wall 7 (avg Y: -790) */
    r->walls[7].x1 =    -102;  r->walls[7].z1 =    3370;
    r->walls[7].x2 =    -101;  r->walls[7].z2 =    3455;
    r->walls[7].nx =   -4095;  r->walls[7].nz =      36;
    r->walls[7].y_min =    -875;  r->walls[7].y_max =    -650;

    /* Wall 8 (avg Y: -798) */
    r->walls[8].x1 =      97;  r->walls[8].z1 =    3374;
    r->walls[8].x2 =      94;  r->walls[8].z2 =    3118;
    r->walls[8].nx =    4095;  r->walls[8].nz =     -75;
    r->walls[8].y_min =    -952;  r->walls[8].y_max =    -650;

    /* Wall 9 (avg Y: -799) */
    r->walls[9].x1 =    -105;  r->walls[9].z1 =    3121;
    r->walls[9].x2 =    -102;  r->walls[9].z2 =    3378;
    r->walls[9].nx =   -4095;  r->walls[9].nz =      54;
    r->walls[9].y_min =    -952;  r->walls[9].y_max =    -650;

    /* Wall 10 (avg Y: -811) */
    r->walls[10].x1 =    -106;  r->walls[10].z1 =    3096;
    r->walls[10].x2 =    -105;  r->walls[10].z2 =    3146;
    r->walls[10].nx =   -4095;  r->walls[10].nz =      55;
    r->walls[10].y_min =    -952;  r->walls[10].y_max =    -717;

    /* Wall 11 (avg Y: -810) */
    r->walls[11].x1 =      94;  r->walls[11].z1 =    3143;
    r->walls[11].x2 =      93;  r->walls[11].z2 =    3093;
    r->walls[11].nx =    4095;  r->walls[11].nz =     -56;
    r->walls[11].y_min =    -952;  r->walls[11].y_max =    -717;

    /* Wall 12 (avg Y: -777) */
    r->walls[12].x1 =     -96;  r->walls[12].z1 =    2857;
    r->walls[12].x2 =     -96;  r->walls[12].z2 =    2887;
    r->walls[12].nx =   -4095;  r->walls[12].nz =      69;
    r->walls[12].y_min =    -822;  r->walls[12].y_max =    -717;

    /* Wall 13 (avg Y: -782) */
    r->walls[13].x1 =     -96;  r->walls[13].z1 =    2879;
    r->walls[13].x2 =    -105;  r->walls[13].z2 =    3108;
    r->walls[13].nx =   -4092;  r->walls[13].nz =    -171;
    r->walls[13].y_min =    -844;  r->walls[13].y_max =    -731;

    /* Wall 14 (avg Y: -771) */
    r->walls[14].x1 =      76;  r->walls[14].z1 =    2862;
    r->walls[14].x2 =      97;  r->walls[14].z2 =    2825;
    r->walls[14].nx =    3344;  r->walls[14].nz =    2365;
    r->walls[14].y_min =    -821;  r->walls[14].y_max =    -716;

    /* Wall 15 (avg Y: -757) */
    r->walls[15].x1 =    -167;  r->walls[15].z1 =    2715;
    r->walls[15].x2 =    -117;  r->walls[15].z2 =    2835;
    r->walls[15].nx =   -3717;  r->walls[15].nz =    1718;
    r->walls[15].y_min =    -938;  r->walls[15].y_max =    -684;

    /* Wall 16 (avg Y: -869) */
    r->walls[16].x1 =      97;  r->walls[16].z1 =    2825;
    r->walls[16].x2 =     145;  r->walls[16].z2 =    2713;
    r->walls[16].nx =    3792;  r->walls[16].nz =    1546;
    r->walls[16].y_min =    -937;  r->walls[16].y_max =    -683;

    /* Wall 17 (avg Y: -836) */
    r->walls[17].x1 =     144;  r->walls[17].z1 =    2510;
    r->walls[17].x2 =      59;  r->walls[17].z2 =    2417;
    r->walls[17].nx =    3009;  r->walls[17].nz =   -2778;
    r->walls[17].y_min =    -921;  r->walls[17].y_max =    -670;

    /* Wall 18 (avg Y: -864) */
    r->walls[18].x1 =     145;  r->walls[18].z1 =    2713;
    r->walls[18].x2 =     115;  r->walls[18].z2 =    2504;
    r->walls[18].nx =    4094;  r->walls[18].nz =    -101;
    r->walls[18].y_min =    -937;  r->walls[18].y_max =    -670;

    /* Wall 19 (avg Y: -739) */
    r->walls[19].x1 =    -168;  r->walls[19].z1 =    2512;
    r->walls[19].x2 =    -135;  r->walls[19].z2 =    2725;
    r->walls[19].nx =   -4094;  r->walls[19].nz =     113;
    r->walls[19].y_min =    -938;  r->walls[19].y_max =    -671;

    /* Wall 20 (avg Y: -820) */
    r->walls[20].x1 =     -84;  r->walls[20].z1 =    2358;
    r->walls[20].x2 =     -83;  r->walls[20].z2 =    2425;
    r->walls[20].nx =   -3959;  r->walls[20].nz =   -1047;
    r->walls[20].y_min =    -859;  r->walls[20].y_max =    -709;

    /* Wall 21 (avg Y: -739) */
    r->walls[21].x1 =     -83;  r->walls[21].z1 =    2418;
    r->walls[21].x2 =    -168;  r->walls[21].z2 =    2512;
    r->walls[21].nx =   -3068;  r->walls[21].nz =   -2713;
    r->walls[21].y_min =    -922;  r->walls[21].y_max =    -671;

    /* Wall 22 (avg Y: -743) */
    r->walls[22].x1 =      59;  r->walls[22].z1 =    2430;
    r->walls[22].x2 =      58;  r->walls[22].z2 =    2359;
    r->walls[22].nx =    4053;  r->walls[22].nz =    -587;
    r->walls[22].y_min =    -859;  r->walls[22].y_max =    -708;

    /* Wall 23 (avg Y: -782) */
    r->walls[23].x1 =      94;  r->walls[23].z1 =    3105;
    r->walls[23].x2 =      77;  r->walls[23].z2 =    2876;
    r->walls[23].nx =    4083;  r->walls[23].nz =    -318;
    r->walls[23].y_min =    -843;  r->walls[23].y_max =    -730;

    /* Wall 24 (avg Y: -821) */
    r->walls[24].x1 =      58;  r->walls[24].z1 =    2356;
    r->walls[24].x2 =      27;  r->walls[24].z2 =    2261;
    r->walls[24].nx =    3898;  r->walls[24].nz =   -1256;
    r->walls[24].y_min =    -859;  r->walls[24].y_max =    -708;

    /* Wall 25 (avg Y: -821) */
    r->walls[25].x1 =     -56;  r->walls[25].z1 =    2263;
    r->walls[25].x2 =     -66;  r->walls[25].z2 =    2365;
    r->walls[25].nx =   -4079;  r->walls[25].nz =     366;
    r->walls[25].y_min =    -859;  r->walls[25].y_max =    -709;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * CEILING 0: y=  -548  x(-100 to 101)  z(3504 to 3606)
     * CEILING 1: y=  -527  x(-100 to 100)  z(3606 to 3931)
     * FLOOR   2: y=  -721  x(-100 to 101)  z(3658 to 3923)
     * CEILING 3: y=  -610  x(-102 to 101)  z(3367 to 3506)
     * FLOOR   4: y=  -780  x(-101 to 101)  z(3453 to 3660)
     * FLOOR   5: y=  -913  x(-105 to 97)  z(3118 to 3378)
     * FLOOR   6: y=  -860  x(-102 to 98)  z(3374 to 3455)
     * CEILING 7: y=  -684  x(-105 to 97)  z(3143 to 3370)
     * CEILING 8: y=  -732  x(-106 to 93)  z(2884 to 3096)
     * CEILING 9: y=  -724  x(-106 to 94)  z(3093 to 3146)
     * FLOOR   10: y=  -929  x(-105 to 94)  z(2868 to 3121)
     * CEILING 11: y=  -700  x(-135 to 115)  z(2724 to 2835)
     * FLOOR   12: y=  -905  x(-96 to 77)  z(2846 to 2871)
     * CEILING 13: y=  -732  x(-96 to 77)  z(2862 to 2887)
     * CEILING 14: y=  -724  x(-117 to 97)  z(2834 to 2865)
     * FLOOR   15: y=  -909  x(-117 to 98)  z(2816 to 2849)
     * FLOOR   16: y=  -954  x(-80 to 62)  z(2534 to 2669)
     * FLOOR   17: y=  -926  x(-134 to 116)  z(2702 to 2818)
     * CEILING 18: y=  -677  x(-136 to 115)  z(2519 to 2725)
     * CEILING 19: y=  -693  x(-136 to 114)  z(2430 to 2521)
     * FLOOR   20: y=  -888  x(-135 to 115)  z(2424 to 2506)
     * CEILING 21: y=  -790  x(-84 to 58)  z(2261 to 2358)
     * FLOOR   22: y=  -856  x(-83 to 59)  z(2363 to 2425)
     * CEILING 23: y=  -783  x(-84 to 59)  z(2356 to 2418)
     * FLOOR   24: y=  -851  x(-67 to 36)  z(2299 to 2365)
     * FLOOR   25: y=  -761  x(-84 to 58)  z(2273 to 2361)
     * FLOOR   26: y=  -775  x(-84 to 59)  z(2359 to 2418)
     * CEILING 27: y=  -712  x(-84 to 59)  z(2372 to 2432)
     * CEILING 28: y=  -738  x(-73 to 48)  z(2273 to 2314)
     * CEILING 29: y=  -715  x(-73 to 49)  z(2312 to 2374)
     * FLOOR   30: y=  -948  x(-134 to 116)  z(2668 to 2704)
     * FLOOR   31: y=  -935  x(-135 to 115)  z(2504 to 2536)
     * FLOOR   32: y=  -942  x(-135 to -79)  z(2506 to 2704)
     * FLOOR   33: y=  -941  x(61 to 116)  z(2504 to 2702)
     */
}
