/*
 * Auto-generated collision data from: Asag Version Two mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ASAG_VERSION_TWO_MESH_COLLISION_H
#define ASAG_VERSION_TWO_MESH_COLLISION_H

#include "collision.h"

#define ASAG_ARENA_WALL_COUNT  12
#define ASAG_ARENA_FLOOR_COUNT 3

void asag_arena_collision_init(CollisionRoom *r);

#endif /* ASAG_VERSION_TWO_MESH_COLLISION_H */
