/*
 * Auto-generated collision data from: Asag Version Two_Boss.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ASAG_VERSION_TWO_BOSS_COLLISION_H
#define ASAG_VERSION_TWO_BOSS_COLLISION_H

#include "collision.h"

#define ASAG_BOSS_WALL_COUNT  26
#define ASAG_BOSS_FLOOR_COUNT 34

void asag_boss_collision_init(CollisionRoom *r);

#endif /* ASAG_VERSION_TWO_BOSS_COLLISION_H */
