/*
 * Auto-generated collision data from: 2f Hall Mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  14
 * Floors: 4
 * Bounds: X(-3797 to 101)  Z(-1398 to 500)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "2f Hall Mesh_collision.h"

void hall_2f_collision_init(CollisionRoom *r) {
    r->wall_count = HALL_2F_WALL_COUNT;
    r->min_x = -3797;
    r->max_x = 101;
    r->min_z = -1398;
    r->max_z = 500;

    /* Wall 0 (avg Y: -179) */
    r->walls[0].x1 =   -2770;  r->walls[0].z1 =       0;
    r->walls[0].x2 =   -2770;  r->walls[0].z2 =    -656;
    r->walls[0].nx =    4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -375;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -171) */
    r->walls[1].x1 =     101;  r->walls[1].z1 =    -656;
    r->walls[1].x2 =     101;  r->walls[1].z2 =     -13;
    r->walls[1].nx =   -4095;  r->walls[1].nz =       0;
    r->walls[1].y_min =    -342;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -171) */
    r->walls[2].x1 =     101;  r->walls[2].z1 =     -13;
    r->walls[2].x2 =   -2124;  r->walls[2].z2 =     -13;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4095;
    r->walls[2].y_min =    -342;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -179) */
    r->walls[3].x1 =   -2770;  r->walls[3].z1 =     500;
    r->walls[3].x2 =   -2770;  r->walls[3].z2 =     300;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -375;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -171) */
    r->walls[4].x1 =   -2124;  r->walls[4].z1 =     500;
    r->walls[4].x2 =   -2770;  r->walls[4].z2 =     500;
    r->walls[4].nx =       0;  r->walls[4].nz =   -4095;
    r->walls[4].y_min =    -342;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -171) */
    r->walls[5].x1 =   -2770;  r->walls[5].z1 =    -656;
    r->walls[5].x2 =     101;  r->walls[5].z2 =    -656;
    r->walls[5].nx =       0;  r->walls[5].nz =    4095;
    r->walls[5].y_min =    -342;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -85) */
    r->walls[6].x1 =   -2770;  r->walls[6].z1 =     300;
    r->walls[6].x2 =   -2801;  r->walls[6].z2 =     300;
    r->walls[6].nx =       0;  r->walls[6].nz =   -4096;
    r->walls[6].y_min =    -171;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -171) */
    r->walls[7].x1 =   -2124;  r->walls[7].z1 =     -13;
    r->walls[7].x2 =   -2124;  r->walls[7].z2 =     500;
    r->walls[7].nx =   -4095;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -342;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -85) */
    r->walls[8].x1 =   -2801;  r->walls[8].z1 =       0;
    r->walls[8].x2 =   -2770;  r->walls[8].z2 =       0;
    r->walls[8].nx =       0;  r->walls[8].nz =    4095;
    r->walls[8].y_min =    -171;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -187) */
    r->walls[9].x1 =   -2801;  r->walls[9].z1 =     300;
    r->walls[9].x2 =   -2801;  r->walls[9].z2 =     500;
    r->walls[9].nx =   -4096;  r->walls[9].nz =       0;
    r->walls[9].y_min =    -375;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -187) */
    r->walls[10].x1 =   -2801;  r->walls[10].z1 =   -1398;
    r->walls[10].x2 =   -2801;  r->walls[10].z2 =       0;
    r->walls[10].nx =   -4095;  r->walls[10].nz =       0;
    r->walls[10].y_min =    -375;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -187) */
    r->walls[11].x1 =   -3797;  r->walls[11].z1 =     499;
    r->walls[11].x2 =   -3797;  r->walls[11].z2 =   -1398;
    r->walls[11].nx =    4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -375;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -187) */
    r->walls[12].x1 =   -3797;  r->walls[12].z1 =   -1398;
    r->walls[12].x2 =   -2801;  r->walls[12].z2 =   -1398;
    r->walls[12].nx =       0;  r->walls[12].nz =    4095;
    r->walls[12].y_min =    -375;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -187) */
    r->walls[13].x1 =   -2801;  r->walls[13].z1 =     500;
    r->walls[13].x2 =   -3797;  r->walls[13].z2 =     499;
    r->walls[13].nx =       0;  r->walls[13].nz =   -4095;
    r->walls[13].y_min =    -375;  r->walls[13].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-2770 to 101)  z(-656 to 0)
     * FLOOR   1: y=     0  x(-2770 to -2124)  z(-13 to 500)
     * FLOOR   2: y=     0  x(-2801 to -2770)  z(0 to 300)
     * FLOOR   3: y=     0  x(-3797 to -2801)  z(-1398 to 500)
     */
}
