/*
 * Auto-generated collision data from: 2f Hall Mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef 2F_HALL_MESH_COLLISION_H
#define 2F_HALL_MESH_COLLISION_H

#include "collision.h"

#define HALL_2F_WALL_COUNT  14
#define HALL_2F_FLOOR_COUNT 4

void hall_2f_collision_init(CollisionRoom *r);

#endif /* 2F_HALL_MESH_COLLISION_H */
