/*
 * Auto-generated collision data from: Attic Stairwell mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ATTIC_STAIRWELL_MESH_COLLISION_H
#define ATTIC_STAIRWELL_MESH_COLLISION_H

#include "collision.h"

#define ATTIC_STAIRWELL_WALL_COUNT  26
#define ATTIC_STAIRWELL_FLOOR_COUNT 7

void attic_stairwell_collision_init(CollisionRoom *r);

#endif /* ATTIC_STAIRWELL_MESH_COLLISION_H */
