/*
 * Auto-generated collision data from: Attic Exit mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ATTIC_EXIT_MESH_COLLISION_H
#define ATTIC_EXIT_MESH_COLLISION_H

#include "collision.h"

#define ATTIC_EXIT_WALL_COUNT  26
#define ATTIC_EXIT_FLOOR_COUNT 9

void attic_exit_collision_init(CollisionRoom *r);

#endif /* ATTIC_EXIT_MESH_COLLISION_H */
