/*
 * Auto-generated collision data from: Delivery Area v2 mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  36
 * Floors: 54
 * Bounds: X(-5451 to 1800)  Z(-1800 to 5425)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Delivery Area v2 mesh_collision.h"

void delivery_area_v2_collision_init(CollisionRoom *r) {
    r->wall_count = DELIVERY_AREA_V2_WALL_COUNT;
    r->min_x = -5451;
    r->max_x = 1800;
    r->min_z = -1800;
    r->max_z = 5425;

    /* Wall 0 (avg Y: 0) */
    r->walls[0].x1 =   -1800;  r->walls[0].z1 =    1800;
    r->walls[0].x2 =   -1800;  r->walls[0].z2 =   -1800;
    r->walls[0].nx =    4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -150;  r->walls[0].y_max =     150;

    /* Wall 1 (avg Y: 0) */
    r->walls[1].x1 =   -1400;  r->walls[1].z1 =    1800;
    r->walls[1].x2 =   -1800;  r->walls[1].z2 =    1800;
    r->walls[1].nx =       0;  r->walls[1].nz =   -4096;
    r->walls[1].y_min =    -150;  r->walls[1].y_max =     150;

    /* Wall 2 (avg Y: 0) */
    r->walls[2].x1 =    1800;  r->walls[2].z1 =    1800;
    r->walls[2].x2 =   -1000;  r->walls[2].z2 =    1800;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4096;
    r->walls[2].y_min =    -150;  r->walls[2].y_max =     150;

    /* Wall 3 (avg Y: 0) */
    r->walls[3].x1 =    1800;  r->walls[3].z1 =   -1800;
    r->walls[3].x2 =    1800;  r->walls[3].z2 =    1800;
    r->walls[3].nx =   -4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -150;  r->walls[3].y_max =     150;

    /* Wall 4 (avg Y: 0) */
    r->walls[4].x1 =   -1800;  r->walls[4].z1 =   -1800;
    r->walls[4].x2 =    1800;  r->walls[4].z2 =   -1800;
    r->walls[4].nx =       0;  r->walls[4].nz =    4096;
    r->walls[4].y_min =    -150;  r->walls[4].y_max =     150;

    /* Wall 5 (avg Y: 75) */
    r->walls[5].x1 =   -1711;  r->walls[5].z1 =    2556;
    r->walls[5].x2 =   -1400;  r->walls[5].z2 =    2556;
    r->walls[5].nx =       0;  r->walls[5].nz =    4096;
    r->walls[5].y_min =       0;  r->walls[5].y_max =     150;

    /* Wall 6 (avg Y: -65) */
    r->walls[6].x1 =   -3900;  r->walls[6].z1 =    3330;
    r->walls[6].x2 =   -3586;  r->walls[6].z2 =    3334;
    r->walls[6].nx =       7;  r->walls[6].nz =    4095;
    r->walls[6].y_min =    -307;  r->walls[6].y_max =     150;

    /* Wall 7 (avg Y: -85) */
    r->walls[7].x1 =   -2023;  r->walls[7].z1 =    2556;
    r->walls[7].x2 =   -1867;  r->walls[7].z2 =    2556;
    r->walls[7].nx =       0;  r->walls[7].nz =    4096;
    r->walls[7].y_min =    -150;  r->walls[7].y_max =      22;

    /* Wall 8 (avg Y: 86) */
    r->walls[8].x1 =   -2023;  r->walls[8].z1 =    3339;
    r->walls[8].x2 =   -2075;  r->walls[8].z2 =    3321;
    r->walls[8].nx =   -3647;  r->walls[8].nz =   -1864;
    r->walls[8].y_min =      22;  r->walls[8].y_max =     150;

    /* Wall 9 (avg Y: 69) */
    r->walls[9].x1 =   -4204;  r->walls[9].z1 =    3339;
    r->walls[9].x2 =   -3893;  r->walls[9].z2 =    3339;
    r->walls[9].nx =      65;  r->walls[9].nz =    4095;
    r->walls[9].y_min =    -524;  r->walls[9].y_max =     150;

    /* Wall 10 (avg Y: -496) */
    r->walls[10].x1 =   -3581;  r->walls[10].z1 =    5425;
    r->walls[10].x2 =   -4204;  r->walls[10].z2 =    5425;
    r->walls[10].nx =       0;  r->walls[10].nz =   -4096;
    r->walls[10].y_min =    -524;  r->walls[10].y_max =     150;

    /* Wall 11 (avg Y: -711) */
    r->walls[11].x1 =   -3581;  r->walls[11].z1 =    5425;
    r->walls[11].x2 =   -5451;  r->walls[11].z2 =    5425;
    r->walls[11].nx =       0;  r->walls[11].nz =   -4096;
    r->walls[11].y_min =    -898;  r->walls[11].y_max =    -524;

    /* Wall 12 (avg Y: 27) */
    r->walls[12].x1 =   -2023;  r->walls[12].z1 =    2556;
    r->walls[12].x2 =   -1711;  r->walls[12].z2 =    2556;
    r->walls[12].nx =       0;  r->walls[12].nz =    4096;
    r->walls[12].y_min =     -63;  r->walls[12].y_max =     150;

    /* Wall 13 (avg Y: -601) */
    r->walls[13].x1 =   -4204;  r->walls[13].z1 =    2556;
    r->walls[13].x2 =   -3893;  r->walls[13].z2 =    2556;
    r->walls[13].nx =       0;  r->walls[13].nz =    4096;
    r->walls[13].y_min =    -711;  r->walls[13].y_max =    -459;

    /* Wall 14 (avg Y: -568) */
    r->walls[14].x1 =   -3893;  r->walls[14].z1 =    2556;
    r->walls[14].x2 =   -3581;  r->walls[14].z2 =    2556;
    r->walls[14].nx =       0;  r->walls[14].nz =    4096;
    r->walls[14].y_min =    -711;  r->walls[14].y_max =    -389;

    /* Wall 15 (avg Y: 133) */
    r->walls[15].x1 =   -2049;  r->walls[15].z1 =    3330;
    r->walls[15].x2 =   -1777;  r->walls[15].z2 =    3339;
    r->walls[15].nx =      35;  r->walls[15].nz =    4095;
    r->walls[15].y_min =      86;  r->walls[15].y_max =     165;

    /* Wall 16 (avg Y: -584) */
    r->walls[16].x1 =   -3581;  r->walls[16].z1 =    2556;
    r->walls[16].x2 =   -3269;  r->walls[16].z2 =    2556;
    r->walls[16].nx =       0;  r->walls[16].nz =    4096;
    r->walls[16].y_min =    -711;  r->walls[16].y_max =    -296;

    /* Wall 17 (avg Y: -617) */
    r->walls[17].x1 =   -3269;  r->walls[17].z1 =    2556;
    r->walls[17].x2 =   -2958;  r->walls[17].z2 =    2556;
    r->walls[17].nx =       0;  r->walls[17].nz =    4096;
    r->walls[17].y_min =    -711;  r->walls[17].y_max =    -202;

    /* Wall 18 (avg Y: -213) */
    r->walls[18].x1 =   -2646;  r->walls[18].z1 =    2556;
    r->walls[18].x2 =   -2334;  r->walls[18].z2 =    2556;
    r->walls[18].nx =       0;  r->walls[18].nz =    4096;
    r->walls[18].y_min =    -337;  r->walls[18].y_max =     -52;

    /* Wall 19 (avg Y: -617) */
    r->walls[19].x1 =   -2958;  r->walls[19].z1 =    2556;
    r->walls[19].x2 =   -2646;  r->walls[19].z2 =    2556;
    r->walls[19].nx =       0;  r->walls[19].nz =    4096;
    r->walls[19].y_min =    -711;  r->walls[19].y_max =    -127;

    /* Wall 20 (avg Y: -219) */
    r->walls[20].x1 =   -2334;  r->walls[20].z1 =    2556;
    r->walls[20].x2 =   -2023;  r->walls[20].z2 =    2556;
    r->walls[20].nx =       0;  r->walls[20].nz =    4096;
    r->walls[20].y_min =    -337;  r->walls[20].y_max =      22;

    /* Wall 21 (avg Y: -159) */
    r->walls[21].x1 =   -5451;  r->walls[21].z1 =    5425;
    r->walls[21].x2 =   -5451;  r->walls[21].z2 =    2556;
    r->walls[21].nx =    4096;  r->walls[21].nz =       0;
    r->walls[21].y_min =    -898;  r->walls[21].y_max =     150;

    /* Wall 22 (avg Y: -711) */
    r->walls[22].x1 =   -5451;  r->walls[22].z1 =    2556;
    r->walls[22].x2 =   -4204;  r->walls[22].z2 =    2556;
    r->walls[22].nx =       0;  r->walls[22].nz =    4096;
    r->walls[22].y_min =    -898;  r->walls[22].y_max =     150;

    /* Wall 23 (avg Y: 0) */
    r->walls[23].x1 =   -1000;  r->walls[23].z1 =    1800;
    r->walls[23].x2 =   -1000;  r->walls[23].z2 =    2556;
    r->walls[23].nx =   -4096;  r->walls[23].nz =       0;
    r->walls[23].y_min =    -150;  r->walls[23].y_max =     150;

    /* Wall 24 (avg Y: 0) */
    r->walls[24].x1 =   -1400;  r->walls[24].z1 =    2556;
    r->walls[24].x2 =   -1400;  r->walls[24].z2 =    1800;
    r->walls[24].nx =    4096;  r->walls[24].nz =       0;
    r->walls[24].y_min =    -150;  r->walls[24].y_max =     150;

    /* Wall 25 (avg Y: 0) */
    r->walls[25].x1 =    -238;  r->walls[25].z1 =    5425;
    r->walls[25].x2 =   -3581;  r->walls[25].z2 =    5425;
    r->walls[25].nx =       0;  r->walls[25].nz =   -4096;
    r->walls[25].y_min =    -150;  r->walls[25].y_max =     150;

    /* Wall 26 (avg Y: 0) */
    r->walls[26].x1 =   -1000;  r->walls[26].z1 =    2556;
    r->walls[26].x2 =    -238;  r->walls[26].z2 =    2556;
    r->walls[26].nx =       0;  r->walls[26].nz =    4096;
    r->walls[26].y_min =    -150;  r->walls[26].y_max =     150;

    /* Wall 27 (avg Y: -159) */
    r->walls[27].x1 =   -4204;  r->walls[27].z1 =    5425;
    r->walls[27].x2 =   -5451;  r->walls[27].z2 =    5425;
    r->walls[27].nx =       0;  r->walls[27].nz =   -4096;
    r->walls[27].y_min =    -469;  r->walls[27].y_max =     150;

    /* Wall 28 (avg Y: 105) */
    r->walls[28].x1 =   -2075;  r->walls[28].z1 =    3321;
    r->walls[28].x2 =   -1711;  r->walls[28].z2 =    3339;
    r->walls[28].nx =     -78;  r->walls[28].nz =    4095;
    r->walls[28].y_min =      22;  r->walls[28].y_max =     165;

    /* Wall 29 (avg Y: -161) */
    r->walls[29].x1 =   -4204;  r->walls[29].z1 =    2556;
    r->walls[29].x2 =   -4193;  r->walls[29].z2 =    3339;
    r->walls[29].nx =   -4095;  r->walls[29].nz =      55;
    r->walls[29].y_min =    -476;  r->walls[29].y_max =     150;

    /* Wall 30 (avg Y: -86) */
    r->walls[30].x1 =   -2977;  r->walls[30].z1 =    3321;
    r->walls[30].x2 =   -2656;  r->walls[30].z2 =    3330;
    r->walls[30].nx =      31;  r->walls[30].nz =    4095;
    r->walls[30].y_min =    -202;  r->walls[30].y_max =     150;

    /* Wall 31 (avg Y: 89) */
    r->walls[31].x1 =   -2656;  r->walls[31].z1 =    3330;
    r->walls[31].x2 =   -2334;  r->walls[31].z2 =    3339;
    r->walls[31].nx =       0;  r->walls[31].nz =    4096;
    r->walls[31].y_min =      11;  r->walls[31].y_max =     150;

    /* Wall 32 (avg Y: 108) */
    r->walls[32].x1 =   -2344;  r->walls[32].z1 =    3330;
    r->walls[32].x2 =   -2023;  r->walls[32].z2 =    3339;
    r->walls[32].nx =      75;  r->walls[32].nz =    4095;
    r->walls[32].y_min =      48;  r->walls[32].y_max =     150;

    /* Wall 33 (avg Y: 105) */
    r->walls[33].x1 =   -3586;  r->walls[33].z1 =    3334;
    r->walls[33].x2 =   -3269;  r->walls[33].z2 =    3339;
    r->walls[33].nx =       0;  r->walls[33].nz =    4096;
    r->walls[33].y_min =    -119;  r->walls[33].y_max =     150;

    /* Wall 34 (avg Y: 46) */
    r->walls[34].x1 =   -3294;  r->walls[34].z1 =    3325;
    r->walls[34].x2 =   -2958;  r->walls[34].z2 =    3339;
    r->walls[34].nx =       0;  r->walls[34].nz =    4096;
    r->walls[34].y_min =     -88;  r->walls[34].y_max =     150;

    /* Wall 35 (avg Y: 0) */
    r->walls[35].x1 =    -238;  r->walls[35].z1 =    2556;
    r->walls[35].x2 =    -238;  r->walls[35].z2 =    5425;
    r->walls[35].nx =   -4096;  r->walls[35].nz =       0;
    r->walls[35].y_min =    -150;  r->walls[35].y_max =     150;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=   150  x(-1800 to 1800)  z(-1800 to 1800)
     * FLOOR   1: y=   150  x(-1711 to -1400)  z(3078 to 3339)
     * FLOOR   2: y=  -492  x(-4193 to -3907)  z(3060 to 3339)
     * FLOOR   3: y=   150  x(-1711 to -1400)  z(2817 to 3078)
     * FLOOR   4: y=   150  x(-1711 to -1400)  z(2556 to 2817)
     * FLOOR   5: y=   150  x(-1777 to -1711)  z(5164 to 5425)
     * FLOOR   6: y=   150  x(-1711 to -1400)  z(3339 to 5425)
     * FLOOR   7: y=   153  x(-4204 to -1777)  z(3339 to 5425)
     * FLOOR   8: y=   150  x(-5451 to -4204)  z(2556 to 5425)
     * FLOOR   9: y=   150  x(-1400 to -238)  z(2556 to 5425)
     * FLOOR   10: y=  -524  x(-4508 to -4193)  z(3078 to 3339)
     * FLOOR   11: y=  -524  x(-4508 to -4193)  z(2817 to 3078)
     * FLOOR   12: y=  -524  x(-5451 to -5136)  z(2817 to 3078)
     * FLOOR   13: y=  -524  x(-5136 to -4822)  z(2817 to 3078)
     * FLOOR   14: y=  -524  x(-4822 to -4508)  z(2817 to 3078)
     * FLOOR   15: y=  -524  x(-5451 to -5136)  z(3078 to 3339)
     * FLOOR   16: y=  -524  x(-5136 to -4822)  z(3078 to 3339)
     * FLOOR   17: y=  -524  x(-4822 to -4508)  z(3078 to 3339)
     * FLOOR   18: y=  -524  x(-5451 to -4193)  z(3339 to 5425)
     * FLOOR   19: y=  -524  x(-4516 to -4193)  z(2556 to 2817)
     * FLOOR   20: y=  -524  x(-4827 to -4508)  z(2556 to 2817)
     * FLOOR   21: y=  -524  x(-5139 to -4822)  z(2556 to 2817)
     * FLOOR   22: y=  -524  x(-5451 to -5136)  z(2556 to 2817)
     * FLOOR   23: y=   153  x(-1777 to -1711)  z(3339 to 3599)
     * FLOOR   24: y=   150  x(-1777 to -1711)  z(3599 to 3860)
     * FLOOR   25: y=   150  x(-1777 to -1711)  z(3860 to 4121)
     * FLOOR   26: y=   150  x(-1777 to -1711)  z(4121 to 4382)
     * FLOOR   27: y=   150  x(-1777 to -1711)  z(4382 to 4643)
     * FLOOR   28: y=   150  x(-1777 to -1711)  z(4643 to 4904)
     * FLOOR   29: y=   150  x(-1777 to -1711)  z(4904 to 5164)
     * FLOOR   30: y=  -343  x(-3600 to -3289)  z(3060 to 3321)
     * FLOOR   31: y=   -90  x(-2666 to -2354)  z(3060 to 3321)
     * FLOOR   32: y=  -424  x(-3907 to -3600)  z(3060 to 3321)
     * FLOOR   33: y=  -165  x(-2977 to -2666)  z(2799 to 3060)
     * FLOOR   34: y=  -343  x(-3600 to -3289)  z(2799 to 3060)
     * FLOOR   35: y=    86  x(-2075 to -1711)  z(2799 to 3078)
     * FLOOR   36: y=   -15  x(-2354 to -2075)  z(2799 to 3060)
     * FLOOR   37: y=   -15  x(-2354 to -2075)  z(3060 to 3321)
     * FLOOR   38: y=   -90  x(-2666 to -2354)  z(2799 to 3060)
     * FLOOR   39: y=  -165  x(-2977 to -2666)  z(3060 to 3321)
     * FLOOR   40: y=  -249  x(-3289 to -2977)  z(2799 to 3060)
     * FLOOR   41: y=  -249  x(-3289 to -2977)  z(3060 to 3321)
     * FLOOR   42: y=  -424  x(-3907 to -3600)  z(2799 to 3060)
     * FLOOR   43: y=  -492  x(-4204 to -3893)  z(2556 to 2817)
     * FLOOR   44: y=  -492  x(-4193 to -3907)  z(2799 to 3078)
     * FLOOR   45: y=  -424  x(-3907 to -3581)  z(2556 to 2799)
     * FLOOR   46: y=  -343  x(-3600 to -3269)  z(2556 to 2799)
     * FLOOR   47: y=  -249  x(-3289 to -2958)  z(2556 to 2799)
     * FLOOR   48: y=  -165  x(-2977 to -2646)  z(2556 to 2799)
     * FLOOR   49: y=   -90  x(-2666 to -2334)  z(2556 to 2799)
     * FLOOR   50: y=   -15  x(-2354 to -2023)  z(2556 to 2799)
     * FLOOR   51: y=    86  x(-2075 to -1711)  z(2556 to 2817)
     * FLOOR   52: y=    86  x(-2075 to -1711)  z(3060 to 3339)
     * FLOOR   53: y=   150  x(-1400 to -1000)  z(1800 to 2556)
     */
}
