/*
 * Auto-generated collision data from: East Stairwell mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  8
 * Floors: 2
 * Bounds: X(-1750 to 1750)  Z(-349 to 349)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "East Stairwell mesh_collision.h"

void east_stairwell_collision_init(CollisionRoom *r) {
    r->wall_count = EAST_STAIRWELL_WALL_COUNT;
    r->min_x = -1750;
    r->max_x = 1750;
    r->min_z = -349;
    r->max_z = 349;

    /* Wall 0 (avg Y: -259) */
    r->walls[0].x1 =     -44;  r->walls[0].z1 =     349;
    r->walls[0].x2 =   -1750;  r->walls[0].z2 =     349;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =    -519;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -259) */
    r->walls[1].x1 =   -1750;  r->walls[1].z1 =     349;
    r->walls[1].x2 =   -1750;  r->walls[1].z2 =    -349;
    r->walls[1].nx =    4096;  r->walls[1].nz =       0;
    r->walls[1].y_min =    -519;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -259) */
    r->walls[2].x1 =     -44;  r->walls[2].z1 =    -349;
    r->walls[2].x2 =     -44;  r->walls[2].z2 =     349;
    r->walls[2].nx =   -4095;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -519;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -259) */
    r->walls[3].x1 =    1750;  r->walls[3].z1 =     349;
    r->walls[3].x2 =      44;  r->walls[3].z2 =     349;
    r->walls[3].nx =       0;  r->walls[3].nz =   -4096;
    r->walls[3].y_min =    -519;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -259) */
    r->walls[4].x1 =      44;  r->walls[4].z1 =    -349;
    r->walls[4].x2 =    1750;  r->walls[4].z2 =    -349;
    r->walls[4].nx =       0;  r->walls[4].nz =    4096;
    r->walls[4].y_min =    -519;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -259) */
    r->walls[5].x1 =   -1750;  r->walls[5].z1 =    -349;
    r->walls[5].x2 =     -44;  r->walls[5].z2 =    -349;
    r->walls[5].nx =       0;  r->walls[5].nz =    4096;
    r->walls[5].y_min =    -519;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -259) */
    r->walls[6].x1 =    1750;  r->walls[6].z1 =    -349;
    r->walls[6].x2 =    1750;  r->walls[6].z2 =     349;
    r->walls[6].nx =   -4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =    -519;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -259) */
    r->walls[7].x1 =      44;  r->walls[7].z1 =     349;
    r->walls[7].x2 =      44;  r->walls[7].z2 =    -349;
    r->walls[7].nx =    4095;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -519;  r->walls[7].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(44 to 1750)  z(-349 to 349)
     * FLOOR   1: y=     0  x(-1750 to -44)  z(-349 to 349)
     */
}
