/*
 * Auto-generated collision data from: East Hall mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  19
 * Floors: 14
 * Bounds: X(19 to 2671)  Z(-992 to 721)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "East Hall mesh_collision.h"

void east_hall_collision_init(CollisionRoom *r) {
    r->wall_count = EAST_HALL_WALL_COUNT;
    r->min_x = 19;
    r->max_x = 2671;
    r->min_z = -992;
    r->max_z = 721;

    /* Wall 0 (avg Y: -62) */
    r->walls[0].x1 =     879;  r->walls[0].z1 =      21;
    r->walls[0].x2 =     879;  r->walls[0].z2 =     -33;
    r->walls[0].nx =    4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -125;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -190) */
    r->walls[1].x1 =    1195;  r->walls[1].z1 =    -608;
    r->walls[1].x2 =    1290;  r->walls[1].z2 =    -608;
    r->walls[1].nx =       0;  r->walls[1].nz =    4095;
    r->walls[1].y_min =    -387;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -187) */
    r->walls[2].x1 =    1290;  r->walls[2].z1 =    -608;
    r->walls[2].x2 =    1290;  r->walls[2].z2 =     -33;
    r->walls[2].nx =   -4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -374;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -62) */
    r->walls[3].x1 =    1290;  r->walls[3].z1 =     -33;
    r->walls[3].x2 =    1219;  r->walls[3].z2 =     -33;
    r->walls[3].nx =       0;  r->walls[3].nz =   -4096;
    r->walls[3].y_min =    -125;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -62) */
    r->walls[4].x1 =      31;  r->walls[4].z1 =    -992;
    r->walls[4].x2 =     139;  r->walls[4].z2 =    -992;
    r->walls[4].nx =       0;  r->walls[4].nz =    4096;
    r->walls[4].y_min =    -125;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -187) */
    r->walls[5].x1 =      19;  r->walls[5].z1 =     721;
    r->walls[5].x2 =      20;  r->walls[5].z2 =      21;
    r->walls[5].nx =    4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -375;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -187) */
    r->walls[6].x1 =      31;  r->walls[6].z1 =     -33;
    r->walls[6].x2 =      31;  r->walls[6].z2 =    -992;
    r->walls[6].nx =    4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =    -375;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -187) */
    r->walls[7].x1 =    2671;  r->walls[7].z1 =      21;
    r->walls[7].x2 =    2671;  r->walls[7].z2 =     721;
    r->walls[7].nx =   -4096;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -375;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -187) */
    r->walls[8].x1 =      19;  r->walls[8].z1 =      21;
    r->walls[8].x2 =     880;  r->walls[8].z2 =      21;
    r->walls[8].nx =       0;  r->walls[8].nz =    4095;
    r->walls[8].y_min =    -375;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -187) */
    r->walls[9].x1 =    1219;  r->walls[9].z1 =      21;
    r->walls[9].x2 =    2671;  r->walls[9].z2 =      21;
    r->walls[9].nx =       0;  r->walls[9].nz =    4095;
    r->walls[9].y_min =    -375;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -187) */
    r->walls[10].x1 =    2671;  r->walls[10].z1 =     721;
    r->walls[10].x2 =      19;  r->walls[10].z2 =     721;
    r->walls[10].nx =       0;  r->walls[10].nz =   -4096;
    r->walls[10].y_min =    -375;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -62) */
    r->walls[11].x1 =    1219;  r->walls[11].z1 =     -33;
    r->walls[11].x2 =    1219;  r->walls[11].z2 =      21;
    r->walls[11].nx =   -4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -125;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -182) */
    r->walls[12].x1 =     900;  r->walls[12].z1 =    -698;
    r->walls[12].x2 =    1200;  r->walls[12].z2 =    -608;
    r->walls[12].nx =    -964;  r->walls[12].nz =    3980;
    r->walls[12].y_min =    -387;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -62) */
    r->walls[13].x1 =     139;  r->walls[13].z1 =    -992;
    r->walls[13].x2 =     345;  r->walls[13].z2 =    -992;
    r->walls[13].nx =       0;  r->walls[13].nz =    4096;
    r->walls[13].y_min =    -125;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -187) */
    r->walls[14].x1 =     880;  r->walls[14].z1 =     -33;
    r->walls[14].x2 =      31;  r->walls[14].z2 =     -33;
    r->walls[14].nx =       0;  r->walls[14].nz =   -4096;
    r->walls[14].y_min =    -375;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -163) */
    r->walls[15].x1 =     682;  r->walls[15].z1 =    -750;
    r->walls[15].x2 =     927;  r->walls[15].z2 =    -673;
    r->walls[15].nx =    -937;  r->walls[15].nz =    3987;
    r->walls[15].y_min =    -343;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -154) */
    r->walls[16].x1 =     465;  r->walls[16].z1 =    -750;
    r->walls[16].x2 =     705;  r->walls[16].z2 =    -711;
    r->walls[16].nx =       0;  r->walls[16].nz =    4095;
    r->walls[16].y_min =    -311;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -152) */
    r->walls[17].x1 =     340;  r->walls[17].z1 =    -750;
    r->walls[17].x2 =     495;  r->walls[17].z2 =    -730;
    r->walls[17].nx =       0;  r->walls[17].nz =    4095;
    r->walls[17].y_min =    -305;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -169) */
    r->walls[18].x1 =     340;  r->walls[18].z1 =    -992;
    r->walls[18].x2 =     358;  r->walls[18].z2 =    -740;
    r->walls[18].nx =   -4096;  r->walls[18].nz =       0;
    r->walls[18].y_min =    -375;  r->walls[18].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(879 to 1219)  z(-33 to 21)
     * FLOOR   1: y=     0  x(31 to 139)  z(-992 to -800)
     * FLOOR   2: y=     0  x(1200 to 1290)  z(-608 to -417)
     * FLOOR   3: y=     0  x(31 to 139)  z(-608 to -417)
     * FLOOR   4: y=     0  x(31 to 139)  z(-800 to -608)
     * FLOOR   5: y=     0  x(900 to 1200)  z(-698 to -417)
     * FLOOR   6: y=     0  x(682 to 900)  z(-750 to -417)
     * FLOOR   7: y=     0  x(465 to 682)  z(-750 to -417)
     * FLOOR   8: y=     0  x(248 to 465)  z(-750 to -417)
     * FLOOR   9: y=     0  x(19 to 2671)  z(21 to 721)
     * FLOOR   10: y=     0  x(139 to 345)  z(-800 to -608)
     * FLOOR   11: y=     0  x(139 to 340)  z(-750 to -417)
     * FLOOR   12: y=     0  x(31 to 1290)  z(-417 to -33)
     * FLOOR   13: y=     0  x(139 to 345)  z(-992 to -800)
     */
}
