/*
 * Auto-generated collision data from: Garden Courtyard mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef GARDEN_COURTYARD_MESH_COLLISION_H
#define GARDEN_COURTYARD_MESH_COLLISION_H

#include "collision.h"

#define GARDEN_COURTYARD_WALL_COUNT  10
#define GARDEN_COURTYARD_FLOOR_COUNT 7

void garden_courtyard_collision_init(CollisionRoom *r);

#endif /* GARDEN_COURTYARD_MESH_COLLISION_H */
