/*
 * Auto-generated collision data from: Garden Stairs mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef GARDEN_STAIRS_MESH_COLLISION_H
#define GARDEN_STAIRS_MESH_COLLISION_H

#include "collision.h"

#define GARDEN_STAIRS_WALL_COUNT  17
#define GARDEN_STAIRS_FLOOR_COUNT 34

void garden_stairs_collision_init(CollisionRoom *r);

#endif /* GARDEN_STAIRS_MESH_COLLISION_H */
