/*
 * Auto-generated collision data from: Garden Courtyard mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  10
 * Floors: 7
 * Bounds: X(-2579 to 2000)  Z(-2000 to 2000)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Garden Courtyard mesh_collision.h"

void garden_courtyard_collision_init(CollisionRoom *r) {
    r->wall_count = GARDEN_COURTYARD_WALL_COUNT;
    r->min_x = -2579;
    r->max_x = 2000;
    r->min_z = -2000;
    r->max_z = 2000;

    /* Wall 0 (avg Y: 825) */
    r->walls[0].x1 =    1142;  r->walls[0].z1 =   -1142;
    r->walls[0].x2 =    1142;  r->walls[0].z2 =    -857;
    r->walls[0].nx =   -4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =     800;  r->walls[0].y_max =     900;

    /* Wall 1 (avg Y: 457) */
    r->walls[1].x1 =   -1722;  r->walls[1].z1 =    2000;
    r->walls[1].x2 =   -2579;  r->walls[1].z2 =    2000;
    r->walls[1].nx =       0;  r->walls[1].nz =   -4096;
    r->walls[1].y_min =     114;  r->walls[1].y_max =     800;

    /* Wall 2 (avg Y: 457) */
    r->walls[2].x1 =    2000;  r->walls[2].z1 =   -2000;
    r->walls[2].x2 =    2000;  r->walls[2].z2 =    2000;
    r->walls[2].nx =   -4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =     114;  r->walls[2].y_max =     800;

    /* Wall 3 (avg Y: 457) */
    r->walls[3].x1 =   -2579;  r->walls[3].z1 =    2000;
    r->walls[3].x2 =   -2579;  r->walls[3].z2 =   -2000;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =     114;  r->walls[3].y_max =     800;

    /* Wall 4 (avg Y: 825) */
    r->walls[4].x1 =   -1722;  r->walls[4].z1 =    -857;
    r->walls[4].x2 =   -1579;  r->walls[4].z2 =   -1142;
    r->walls[4].nx =    3663;  r->walls[4].nz =    1831;
    r->walls[4].y_min =     800;  r->walls[4].y_max =     900;

    /* Wall 5 (avg Y: 850) */
    r->walls[5].x1 =    1142;  r->walls[5].z1 =    -857;
    r->walls[5].x2 =    1142;  r->walls[5].z2 =    2000;
    r->walls[5].nx =   -4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =     800;  r->walls[5].y_max =     900;

    /* Wall 6 (avg Y: 850) */
    r->walls[6].x1 =   -1722;  r->walls[6].z1 =    2000;
    r->walls[6].x2 =   -1722;  r->walls[6].z2 =    -857;
    r->walls[6].nx =    4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =     800;  r->walls[6].y_max =     900;

    /* Wall 7 (avg Y: 457) */
    r->walls[7].x1 =   -2579;  r->walls[7].z1 =   -2000;
    r->walls[7].x2 =    2000;  r->walls[7].z2 =   -2000;
    r->walls[7].nx =       0;  r->walls[7].nz =    4096;
    r->walls[7].y_min =     114;  r->walls[7].y_max =     800;

    /* Wall 8 (avg Y: 457) */
    r->walls[8].x1 =    2000;  r->walls[8].z1 =    2000;
    r->walls[8].x2 =    1142;  r->walls[8].z2 =    2000;
    r->walls[8].nx =       0;  r->walls[8].nz =   -4096;
    r->walls[8].y_min =     114;  r->walls[8].y_max =     800;

    /* Wall 9 (avg Y: 507) */
    r->walls[9].x1 =    1142;  r->walls[9].z1 =    2000;
    r->walls[9].x2 =   -1722;  r->walls[9].z2 =    2000;
    r->walls[9].nx =       0;  r->walls[9].nz =   -4096;
    r->walls[9].y_min =     114;  r->walls[9].y_max =     900;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=   850  x(-1722 to -1437)  z(-1142 to -857)
     * FLOOR   1: y=   800  x(-2579 to -1722)  z(-1142 to 2000)
     * FLOOR   2: y=   800  x(1142 to 2000)  z(-1142 to 2000)
     * FLOOR   3: y=   850  x(857 to 1142)  z(-1142 to -857)
     * FLOOR   4: y=   850  x(-1437 to 857)  z(-1142 to -857)
     * FLOOR   5: y=   900  x(-1722 to 1142)  z(-857 to 2000)
     * FLOOR   6: y=   800  x(-2579 to 2000)  z(-2000 to -1142)
     */
}
