/*
 * Auto-generated collision data from: level1_mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef LEVEL1_MESH_COLLISION_H
#define LEVEL1_MESH_COLLISION_H

#include "collision.h"

#define ROOM_WALL_COUNT  13
#define ROOM_FLOOR_COUNT 3

void room_collision_init(CollisionRoom *r);

#endif /* LEVEL1_MESH_COLLISION_H */
