/*
 * Auto-generated collision data from: level1_mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  13
 * Floors: 3
 * Bounds: X(-5451 to 1800)  Z(-1800 to 5425)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "level1_mesh_collision.h"

void room_collision_init(CollisionRoom *r) {
    r->wall_count = ROOM_WALL_COUNT;
    r->min_x = -5451;
    r->max_x = 1800;
    r->min_z = -1800;
    r->max_z = 5425;

    /* Wall 0 (avg Y: 0) */
    r->walls[0].x1 =   -1800;  r->walls[0].z1 =    1800;
    r->walls[0].x2 =   -1800;  r->walls[0].z2 =   -1800;
    r->walls[0].nx =    4096;  r->walls[0].nz =       0;

    /* Wall 1 (avg Y: 0) */
    r->walls[1].x1 =   -1800;  r->walls[1].z1 =   -1800;
    r->walls[1].x2 =    1800;  r->walls[1].z2 =   -1800;
    r->walls[1].nx =       0;  r->walls[1].nz =    4096;

    /* Wall 2 (avg Y: 0) */
    r->walls[2].x1 =    1800;  r->walls[2].z1 =   -1800;
    r->walls[2].x2 =    1800;  r->walls[2].z2 =    1800;
    r->walls[2].nx =   -4096;  r->walls[2].nz =       0;

    /* Wall 3 (avg Y: 0) */
    r->walls[3].x1 =    1800;  r->walls[3].z1 =    1800;
    r->walls[3].x2 =   -1000;  r->walls[3].z2 =    1800;
    r->walls[3].nx =       0;  r->walls[3].nz =   -4096;

    /* Wall 4 (avg Y: 0) */
    r->walls[4].x1 =   -1400;  r->walls[4].z1 =    1800;
    r->walls[4].x2 =   -1800;  r->walls[4].z2 =    1800;
    r->walls[4].nx =       0;  r->walls[4].nz =   -4096;

    /* Wall 5 (avg Y: 0) */
    r->walls[5].x1 =   -1400;  r->walls[5].z1 =    2556;
    r->walls[5].x2 =   -1400;  r->walls[5].z2 =    1800;
    r->walls[5].nx =    4096;  r->walls[5].nz =       0;

    /* Wall 6 (avg Y: 0) */
    r->walls[6].x1 =   -1000;  r->walls[6].z1 =    1800;
    r->walls[6].x2 =   -1000;  r->walls[6].z2 =    2556;
    r->walls[6].nx =   -4096;  r->walls[6].nz =       0;

    /* Wall 7 (avg Y: 0) */
    r->walls[7].x1 =   -1000;  r->walls[7].z1 =    2556;
    r->walls[7].x2 =    -238;  r->walls[7].z2 =    2556;
    r->walls[7].nx =       0;  r->walls[7].nz =    4096;

    /* Wall 8 (avg Y: 0) */
    r->walls[8].x1 =    -238;  r->walls[8].z1 =    2556;
    r->walls[8].x2 =    -238;  r->walls[8].z2 =    5425;
    r->walls[8].nx =   -4096;  r->walls[8].nz =       0;

    /* Wall 9 (avg Y: 0) */
    r->walls[9].x1 =    -238;  r->walls[9].z1 =    5425;
    r->walls[9].x2 =   -1400;  r->walls[9].z2 =    5425;
    r->walls[9].nx =       0;  r->walls[9].nz =   -4096;

    /* Wall 10 (avg Y: -561) */
    r->walls[10].x1 =   -1400;  r->walls[10].z1 =    5425;
    r->walls[10].x2 =   -5451;  r->walls[10].z2 =    5425;
    r->walls[10].nx =       0;  r->walls[10].nz =   -4096;

    /* Wall 11 (avg Y: -561) */
    r->walls[11].x1 =   -5451;  r->walls[11].z1 =    5425;
    r->walls[11].x2 =   -5451;  r->walls[11].z2 =    2556;
    r->walls[11].nx =    4096;  r->walls[11].nz =       0;

    /* Wall 12 (avg Y: -561) */
    r->walls[12].x1 =   -5451;  r->walls[12].z1 =    2556;
    r->walls[12].x2 =   -1400;  r->walls[12].z2 =    2556;
    r->walls[12].nx =       0;  r->walls[12].nz =    4096;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=   150  x(-5451 to -238)  z(2556 to 5425)
     * FLOOR   1: y=   150  x(-1400 to -1000)  z(1800 to 2556)
     * FLOOR   2: y=   150  x(-1800 to 1800)  z(-1800 to 1800)
     */
}
