/*
 * Auto-generated collision data from: Library mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  14
 * Floors: 2
 * Bounds: X(-1780 to 350)  Z(-2080 to 349)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Library mesh_collision.h"

void library_collision_init(CollisionRoom *r) {
    r->wall_count = LIBRARY_WALL_COUNT;
    r->min_x = -1780;
    r->max_x = 350;
    r->min_z = -2080;
    r->max_z = 349;

    /* Wall 0 (avg Y: -250) */
    r->walls[0].x1 =    -350;  r->walls[0].z1 =    -349;
    r->walls[0].x2 =   -1780;  r->walls[0].z2 =    -349;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =    -500;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -250) */
    r->walls[1].x1 =     350;  r->walls[1].z1 =     349;
    r->walls[1].x2 =    -350;  r->walls[1].z2 =     349;
    r->walls[1].nx =       0;  r->walls[1].nz =   -4096;
    r->walls[1].y_min =    -500;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -250) */
    r->walls[2].x1 =    -350;  r->walls[2].z1 =     349;
    r->walls[2].x2 =    -350;  r->walls[2].z2 =    -349;
    r->walls[2].nx =    4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -500;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -250) */
    r->walls[3].x1 =   -1780;  r->walls[3].z1 =   -2080;
    r->walls[3].x2 =     350;  r->walls[3].z2 =   -2080;
    r->walls[3].nx =       0;  r->walls[3].nz =    4096;
    r->walls[3].y_min =    -500;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -250) */
    r->walls[4].x1 =     350;  r->walls[4].z1 =   -2080;
    r->walls[4].x2 =     350;  r->walls[4].z2 =     349;
    r->walls[4].nx =   -4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -500;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -250) */
    r->walls[5].x1 =   -1780;  r->walls[5].z1 =    -349;
    r->walls[5].x2 =   -1780;  r->walls[5].z2 =   -2080;
    r->walls[5].nx =    4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -500;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -220) */
    r->walls[6].x1 =    -350;  r->walls[6].z1 =    -963;
    r->walls[6].x2 =   -1303;  r->walls[6].z2 =    -963;
    r->walls[6].nx =       0;  r->walls[6].nz =   -4096;
    r->walls[6].y_min =    -440;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -220) */
    r->walls[7].x1 =   -1303;  r->walls[7].z1 =    -911;
    r->walls[7].x2 =    -350;  r->walls[7].z2 =    -911;
    r->walls[7].nx =       0;  r->walls[7].nz =    4096;
    r->walls[7].y_min =    -440;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -220) */
    r->walls[8].x1 =    -350;  r->walls[8].z1 =    -911;
    r->walls[8].x2 =    -350;  r->walls[8].z2 =    -963;
    r->walls[8].nx =    4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =    -440;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -220) */
    r->walls[9].x1 =    -350;  r->walls[9].z1 =   -1520;
    r->walls[9].x2 =    -350;  r->walls[9].z2 =   -1577;
    r->walls[9].nx =    4096;  r->walls[9].nz =       0;
    r->walls[9].y_min =    -440;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -220) */
    r->walls[10].x1 =    -350;  r->walls[10].z1 =   -1577;
    r->walls[10].x2 =   -1303;  r->walls[10].z2 =   -1577;
    r->walls[10].nx =       0;  r->walls[10].nz =   -4096;
    r->walls[10].y_min =    -440;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -220) */
    r->walls[11].x1 =   -1303;  r->walls[11].z1 =   -1520;
    r->walls[11].x2 =    -350;  r->walls[11].z2 =   -1520;
    r->walls[11].nx =       0;  r->walls[11].nz =    4096;
    r->walls[11].y_min =    -440;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -220) */
    r->walls[12].x1 =   -1303;  r->walls[12].z1 =   -1577;
    r->walls[12].x2 =   -1303;  r->walls[12].z2 =   -1520;
    r->walls[12].nx =   -4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =    -440;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -220) */
    r->walls[13].x1 =   -1303;  r->walls[13].z1 =    -963;
    r->walls[13].x2 =   -1303;  r->walls[13].z2 =    -911;
    r->walls[13].nx =   -4096;  r->walls[13].nz =       0;
    r->walls[13].y_min =    -440;  r->walls[13].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-1780 to 350)  z(-2080 to -349)
     * FLOOR   1: y=     0  x(-350 to 350)  z(-2080 to 349)
     */
}
