/*
 * Auto-generated collision data from: Library Destroyed Mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  13
 * Floors: 78
 * Bounds: X(-1780 to 350)  Z(-2080 to 349)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Library Destroyed Mesh_collision.h"

void library_destroyed_collision_init(CollisionRoom *r) {
    r->wall_count = LIBRARY_DESTROYED_WALL_COUNT;
    r->min_x = -1780;
    r->max_x = 350;
    r->min_z = -2080;
    r->max_z = 349;

    /* Wall 0 (avg Y: -307) */
    r->walls[0].x1 =     350;  r->walls[0].z1 =   -2080;
    r->walls[0].x2 =     350;  r->walls[0].z2 =     349;
    r->walls[0].nx =   -4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -730;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -365) */
    r->walls[1].x1 =    -350;  r->walls[1].z1 =   -2080;
    r->walls[1].x2 =     350;  r->walls[1].z2 =   -2080;
    r->walls[1].nx =       0;  r->walls[1].nz =    4096;
    r->walls[1].y_min =    -730;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -307) */
    r->walls[2].x1 =    -350;  r->walls[2].z1 =    -174;
    r->walls[2].x2 =    -350;  r->walls[2].z2 =    -349;
    r->walls[2].nx =    4076;  r->walls[2].nz =     395;
    r->walls[2].y_min =    -730;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -365) */
    r->walls[3].x1 =   -1780;  r->walls[3].z1 =    -349;
    r->walls[3].x2 =   -1780;  r->walls[3].z2 =   -2080;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -730;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -351) */
    r->walls[4].x1 =   -1299;  r->walls[4].z1 =   -2080;
    r->walls[4].x2 =   -1303;  r->walls[4].z2 =    -759;
    r->walls[4].nx =   -4095;  r->walls[4].nz =     -10;
    r->walls[4].y_min =    -730;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -250) */
    r->walls[5].x1 =     350;  r->walls[5].z1 =     349;
    r->walls[5].x2 =    -350;  r->walls[5].z2 =     349;
    r->walls[5].nx =       0;  r->walls[5].nz =   -4096;
    r->walls[5].y_min =    -500;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -250) */
    r->walls[6].x1 =    -350;  r->walls[6].z1 =     349;
    r->walls[6].x2 =    -350;  r->walls[6].z2 =    -174;
    r->walls[6].nx =    4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =    -500;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -365) */
    r->walls[7].x1 =   -1780;  r->walls[7].z1 =   -2080;
    r->walls[7].x2 =   -1299;  r->walls[7].z2 =   -2080;
    r->walls[7].nx =       0;  r->walls[7].nz =    4096;
    r->walls[7].y_min =    -730;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -243) */
    r->walls[8].x1 =    -300;  r->walls[8].z1 =    -309;
    r->walls[8].x2 =   -1303;  r->walls[8].z2 =    -349;
    r->walls[8].nx =     163;  r->walls[8].nz =   -4092;
    r->walls[8].y_min =    -730;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -243) */
    r->walls[9].x1 =   -1303;  r->walls[9].z1 =    -349;
    r->walls[9].x2 =   -1780;  r->walls[9].z2 =    -349;
    r->walls[9].nx =       0;  r->walls[9].nz =   -4096;
    r->walls[9].y_min =    -730;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -486) */
    r->walls[10].x1 =    -350;  r->walls[10].z1 =    -349;
    r->walls[10].x2 =   -1780;  r->walls[10].z2 =    -349;
    r->walls[10].nx =       0;  r->walls[10].nz =   -4096;
    r->walls[10].y_min =    -730;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -333) */
    r->walls[11].x1 =   -1303;  r->walls[11].z1 =    -759;
    r->walls[11].x2 =    -349;  r->walls[11].z2 =    -759;
    r->walls[11].nx =       0;  r->walls[11].nz =    4095;
    r->walls[11].y_min =    -675;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -346) */
    r->walls[12].x1 =    -349;  r->walls[12].z1 =    -759;
    r->walls[12].x2 =    -350;  r->walls[12].z2 =   -2080;
    r->walls[12].nx =    4095;  r->walls[12].nz =       0;
    r->walls[12].y_min =    -730;  r->walls[12].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * CEILING 0: y=  -730  x(-350 to -116)  z(-1577 to -1520)
     * CEILING 1: y=  -730  x(-1541 to -1303)  z(-1912 to -1745)
     * CEILING 2: y=  -730  x(-1541 to -1303)  z(-1745 to -1577)
     * CEILING 3: y=  -730  x(-1780 to -1541)  z(-1520 to -1373)
     * CEILING 4: y=  -730  x(-1780 to -1541)  z(-1373 to -1168)
     * CEILING 5: y=  -730  x(-1780 to -1541)  z(-1168 to -963)
     * CEILING 6: y=  -730  x(-1780 to -1541)  z(-911 to -759)
     * CEILING 7: y=  -730  x(-1780 to -1541)  z(-759 to -554)
     * CEILING 8: y=  -730  x(-350 to -116)  z(-759 to -554)
     * CEILING 9: y=  -730  x(-350 to -116)  z(-963 to -911)
     * CEILING 10: y=  -730  x(-350 to -116)  z(-1168 to -963)
     * CEILING 11: y=  -730  x(-350 to -116)  z(-1373 to -1168)
     * CEILING 12: y=  -730  x(-116 to 116)  z(-1373 to -1168)
     * CEILING 13: y=  -730  x(-116 to 116)  z(-1168 to -963)
     * CEILING 14: y=  -730  x(-116 to 116)  z(-963 to -911)
     * CEILING 15: y=  -730  x(-116 to 116)  z(-759 to -554)
     * FLOOR   16: y=     0  x(-1780 to -1299)  z(-2080 to -349)
     * CEILING 17: y=  -730  x(-116 to 116)  z(-1577 to -1520)
     * CEILING 18: y=  -730  x(-350 to -116)  z(-1912 to -1745)
     * CEILING 19: y=  -730  x(-350 to -116)  z(-1745 to -1577)
     * FLOOR   20: y=     0  x(-1303 to -300)  z(-759 to -309)
     * CEILING 21: y=  -730  x(-588 to -350)  z(-759 to -554)
     * CEILING 22: y=  -730  x(-826 to -588)  z(-759 to -554)
     * CEILING 23: y=  -730  x(-1065 to -826)  z(-759 to -554)
     * CEILING 24: y=  -730  x(-1303 to -1065)  z(-759 to -554)
     * CEILING 25: y=  -730  x(-1541 to -1303)  z(-759 to -554)
     * CEILING 26: y=  -730  x(-588 to -350)  z(-911 to -759)
     * CEILING 27: y=  -730  x(-826 to -588)  z(-911 to -759)
     * CEILING 28: y=  -730  x(-1065 to -826)  z(-911 to -759)
     * CEILING 29: y=  -730  x(-1303 to -1065)  z(-911 to -759)
     * CEILING 30: y=  -730  x(-1541 to -1303)  z(-911 to -759)
     * CEILING 31: y=  -730  x(-588 to -350)  z(-1168 to -963)
     * CEILING 32: y=  -730  x(-826 to -588)  z(-1168 to -963)
     * CEILING 33: y=  -730  x(-1065 to -826)  z(-1168 to -963)
     * CEILING 34: y=  -730  x(-1303 to -1065)  z(-1168 to -963)
     * CEILING 35: y=  -730  x(-1541 to -1303)  z(-1168 to -963)
     * CEILING 36: y=  -730  x(-588 to -350)  z(-1373 to -1168)
     * CEILING 37: y=  -730  x(-826 to -588)  z(-1373 to -1168)
     * CEILING 38: y=  -730  x(-1065 to -826)  z(-1373 to -1168)
     * CEILING 39: y=  -730  x(-1303 to -1065)  z(-1373 to -1168)
     * CEILING 40: y=  -730  x(-1541 to -1303)  z(-1373 to -1168)
     * CEILING 41: y=  -730  x(-588 to -350)  z(-1520 to -1373)
     * CEILING 42: y=  -730  x(-826 to -588)  z(-1520 to -1373)
     * CEILING 43: y=  -730  x(-1065 to -826)  z(-1520 to -1373)
     * CEILING 44: y=  -730  x(-1303 to -1065)  z(-1520 to -1373)
     * CEILING 45: y=  -730  x(-1541 to -1303)  z(-1520 to -1373)
     * CEILING 46: y=  -730  x(-1541 to -1303)  z(-963 to -911)
     * CEILING 47: y=  -730  x(-1303 to -1065)  z(-963 to -911)
     * CEILING 48: y=  -730  x(-1065 to -826)  z(-963 to -911)
     * CEILING 49: y=  -730  x(-826 to -588)  z(-963 to -911)
     * CEILING 50: y=  -730  x(-588 to -350)  z(-963 to -911)
     * CEILING 51: y=  -730  x(-116 to 116)  z(-911 to -759)
     * CEILING 52: y=  -730  x(-350 to -116)  z(-911 to -759)
     * CEILING 53: y=  -730  x(-1780 to -1541)  z(-963 to -911)
     * CEILING 54: y=  -730  x(-1541 to -1303)  z(-1577 to -1520)
     * CEILING 55: y=  -730  x(-1303 to -1065)  z(-1577 to -1520)
     * CEILING 56: y=  -730  x(-1065 to -826)  z(-1577 to -1520)
     * CEILING 57: y=  -730  x(-826 to -588)  z(-1577 to -1520)
     * CEILING 58: y=  -730  x(-588 to -350)  z(-1577 to -1520)
     * CEILING 59: y=  -730  x(-116 to 116)  z(-1520 to -1373)
     * CEILING 60: y=  -730  x(-1780 to -1541)  z(-1577 to -1520)
     * CEILING 61: y=  -730  x(-350 to -116)  z(-1520 to -1373)
     * CEILING 62: y=  -730  x(-1303 to -1065)  z(-1745 to -1577)
     * CEILING 63: y=  -730  x(-1303 to -1065)  z(-1912 to -1745)
     * CEILING 64: y=  -730  x(-1065 to -826)  z(-1745 to -1577)
     * CEILING 65: y=  -730  x(-1065 to -826)  z(-1912 to -1745)
     * CEILING 66: y=  -730  x(-826 to -588)  z(-1745 to -1577)
     * CEILING 67: y=  -730  x(-826 to -588)  z(-1912 to -1745)
     * CEILING 68: y=  -730  x(-116 to 116)  z(-1745 to -1577)
     * CEILING 69: y=  -730  x(-116 to 116)  z(-1912 to -1745)
     * FLOOR   70: y=     0  x(-350 to 350)  z(-174 to 349)
     * FLOOR   71: y=     0  x(-350 to 350)  z(-349 to -174)
     * CEILING 72: y=  -730  x(-588 to -350)  z(-1745 to -1577)
     * CEILING 73: y=  -730  x(-588 to -350)  z(-1912 to -1745)
     * FLOOR   74: y=     0  x(-349 to 350)  z(-759 to -309)
     * FLOOR   75: y=     0  x(-350 to 350)  z(-2080 to -759)
     * CEILING 76: y=  -730  x(-1780 to -1541)  z(-1745 to -1577)
     * CEILING 77: y=  -730  x(-1780 to -1541)  z(-1912 to -1745)
     */
}
