/*
 * Auto-generated collision data from: Library Destroyed Mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef LIBRARY_DESTROYED_MESH_COLLISION_H
#define LIBRARY_DESTROYED_MESH_COLLISION_H

#include "collision.h"

#define LIBRARY_DESTROYED_WALL_COUNT  13
#define LIBRARY_DESTROYED_FLOOR_COUNT 78

void library_destroyed_collision_init(CollisionRoom *r);

#endif /* LIBRARY_DESTROYED_MESH_COLLISION_H */
