/*
 * Auto-generated collision data from: Master Bedroom mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  24
 * Floors: 7
 * Bounds: X(-1594 to 1245)  Z(-441 to 319)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Master Bedroom mesh_collision.h"

void master_bedroom_collision_init(CollisionRoom *r) {
    r->wall_count = MASTER_BEDROOM_WALL_COUNT;
    r->min_x = -1594;
    r->max_x = 1245;
    r->min_z = -441;
    r->max_z = 319;

    /* Wall 0 (avg Y: -59) */
    r->walls[0].x1 =    -500;  r->walls[0].z1 =     189;
    r->walls[0].x2 =    -546;  r->walls[0].z2 =     189;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =    -119;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -59) */
    r->walls[1].x1 =    -500;  r->walls[1].z1 =    -194;
    r->walls[1].x2 =    -500;  r->walls[1].z2 =    -379;
    r->walls[1].nx =    4096;  r->walls[1].nz =       0;
    r->walls[1].y_min =    -119;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -59) */
    r->walls[2].x1 =     536;  r->walls[2].z1 =     189;
    r->walls[2].x2 =     500;  r->walls[2].z2 =     189;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4096;
    r->walls[2].y_min =    -119;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -59) */
    r->walls[3].x1 =     500;  r->walls[3].z1 =     189;
    r->walls[3].x2 =     500;  r->walls[3].z2 =     319;
    r->walls[3].nx =   -4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -119;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -59) */
    r->walls[4].x1 =     500;  r->walls[4].z1 =    -379;
    r->walls[4].x2 =     500;  r->walls[4].z2 =    -194;
    r->walls[4].nx =   -4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -119;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -59) */
    r->walls[5].x1 =    -500;  r->walls[5].z1 =     319;
    r->walls[5].x2 =    -500;  r->walls[5].z2 =     189;
    r->walls[5].nx =    4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -119;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -59) */
    r->walls[6].x1 =     500;  r->walls[6].z1 =    -194;
    r->walls[6].x2 =     536;  r->walls[6].z2 =    -194;
    r->walls[6].nx =       0;  r->walls[6].nz =    4096;
    r->walls[6].y_min =    -119;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -59) */
    r->walls[7].x1 =    -546;  r->walls[7].z1 =    -431;
    r->walls[7].x2 =    -546;  r->walls[7].z2 =    -194;
    r->walls[7].nx =   -4096;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -119;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -59) */
    r->walls[8].x1 =     536;  r->walls[8].z1 =     315;
    r->walls[8].x2 =     536;  r->walls[8].z2 =     189;
    r->walls[8].nx =    4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =    -119;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -59) */
    r->walls[9].x1 =    -546;  r->walls[9].z1 =     189;
    r->walls[9].x2 =    -546;  r->walls[9].z2 =     315;
    r->walls[9].nx =   -4096;  r->walls[9].nz =       0;
    r->walls[9].y_min =    -119;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -59) */
    r->walls[10].x1 =    -546;  r->walls[10].z1 =    -194;
    r->walls[10].x2 =    -500;  r->walls[10].z2 =    -194;
    r->walls[10].nx =       0;  r->walls[10].nz =    4096;
    r->walls[10].y_min =    -119;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -59) */
    r->walls[11].x1 =     536;  r->walls[11].z1 =    -194;
    r->walls[11].x2 =     536;  r->walls[11].z2 =    -441;
    r->walls[11].nx =    4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -119;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -59) */
    r->walls[12].x1 =    1245;  r->walls[12].z1 =    -441;
    r->walls[12].x2 =    1245;  r->walls[12].z2 =    -194;
    r->walls[12].nx =   -4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =    -119;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -59) */
    r->walls[13].x1 =   -1594;  r->walls[13].z1 =    -194;
    r->walls[13].x2 =   -1594;  r->walls[13].z2 =    -431;
    r->walls[13].nx =    4096;  r->walls[13].nz =       0;
    r->walls[13].y_min =    -119;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -119) */
    r->walls[14].x1 =   -1419;  r->walls[14].z1 =    -224;
    r->walls[14].x2 =   -1594;  r->walls[14].z2 =    -204;
    r->walls[14].nx =       0;  r->walls[14].nz =   -4096;
    r->walls[14].y_min =    -240;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -119) */
    r->walls[15].x1 =   -1419;  r->walls[15].z1 =     315;
    r->walls[15].x2 =   -1419;  r->walls[15].z2 =    -224;
    r->walls[15].nx =    4096;  r->walls[15].nz =       0;
    r->walls[15].y_min =    -240;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -120) */
    r->walls[16].x1 =    -500;  r->walls[16].z1 =    -379;
    r->walls[16].x2 =     500;  r->walls[16].z2 =    -379;
    r->walls[16].nx =       0;  r->walls[16].nz =    4095;
    r->walls[16].y_min =    -240;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -120) */
    r->walls[17].x1 =     500;  r->walls[17].z1 =     319;
    r->walls[17].x2 =    -500;  r->walls[17].z2 =     319;
    r->walls[17].nx =       0;  r->walls[17].nz =   -4096;
    r->walls[17].y_min =    -240;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -120) */
    r->walls[18].x1 =    -546;  r->walls[18].z1 =     315;
    r->walls[18].x2 =   -1419;  r->walls[18].z2 =     315;
    r->walls[18].nx =       0;  r->walls[18].nz =   -4096;
    r->walls[18].y_min =    -240;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -120) */
    r->walls[19].x1 =   -1594;  r->walls[19].z1 =    -431;
    r->walls[19].x2 =    -546;  r->walls[19].z2 =    -431;
    r->walls[19].nx =       0;  r->walls[19].nz =    4096;
    r->walls[19].y_min =    -240;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -120) */
    r->walls[20].x1 =    1083;  r->walls[20].z1 =     315;
    r->walls[20].x2 =     536;  r->walls[20].z2 =     315;
    r->walls[20].nx =       0;  r->walls[20].nz =   -4096;
    r->walls[20].y_min =    -240;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -125) */
    r->walls[21].x1 =    1083;  r->walls[21].z1 =    -224;
    r->walls[21].x2 =    1083;  r->walls[21].z2 =     315;
    r->walls[21].nx =   -4095;  r->walls[21].nz =       0;
    r->walls[21].y_min =    -259;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -125) */
    r->walls[22].x1 =    1245;  r->walls[22].z1 =    -194;
    r->walls[22].x2 =    1083;  r->walls[22].z2 =    -224;
    r->walls[22].nx =     526;  r->walls[22].nz =   -4062;
    r->walls[22].y_min =    -259;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -120) */
    r->walls[23].x1 =     536;  r->walls[23].z1 =    -441;
    r->walls[23].x2 =    1245;  r->walls[23].z2 =    -441;
    r->walls[23].nx =       0;  r->walls[23].nz =    4096;
    r->walls[23].y_min =    -240;  r->walls[23].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(1083 to 1245)  z(-441 to -224)
     * FLOOR   1: y=     0  x(-1594 to -1419)  z(-431 to -224)
     * FLOOR   2: y=     0  x(-1419 to -546)  z(-431 to 315)
     * FLOOR   3: y=     0  x(-546 to -500)  z(-194 to 189)
     * FLOOR   4: y=     0  x(-500 to 500)  z(-379 to 319)
     * FLOOR   5: y=     0  x(500 to 536)  z(-194 to 189)
     * FLOOR   6: y=     0  x(536 to 1083)  z(-441 to 315)
     */
}
