/*
 * Auto-generated collision data from: Master Bedroom mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef MASTER_BEDROOM_MESH_COLLISION_H
#define MASTER_BEDROOM_MESH_COLLISION_H

#include "collision.h"

#define MASTER_BEDROOM_WALL_COUNT  24
#define MASTER_BEDROOM_FLOOR_COUNT 7

void master_bedroom_collision_init(CollisionRoom *r);

#endif /* MASTER_BEDROOM_MESH_COLLISION_H */
