/*
 * Auto-generated collision data from: Reception_mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef RECEPTION_MESH_COLLISION_H
#define RECEPTION_MESH_COLLISION_H

#include "collision.h"

#define RECEPTION_WALL_COUNT  40
#define RECEPTION_FLOOR_COUNT 10

void reception_collision_init(CollisionRoom *r);

#endif /* RECEPTION_MESH_COLLISION_H */
