/*
 * Auto-generated collision data from: West Corridor mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef WEST_CORRIDOR_MESH_COLLISION_H
#define WEST_CORRIDOR_MESH_COLLISION_H

#include "collision.h"

#define WEST_CORRIDOR_WALL_COUNT  14
#define WEST_CORRIDOR_FLOOR_COUNT 4

void west_corridor_collision_init(CollisionRoom *r);

#endif /* WEST_CORRIDOR_MESH_COLLISION_H */
