/*
 * Auto-generated collision data from: Asag_Left_Tentacle.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ASAG_LEFT_TENTACLE_COLLISION_H
#define ASAG_LEFT_TENTACLE_COLLISION_H

#include "collision.h"

#define ASAG_TENT_L_WALL_COUNT  20
#define ASAG_TENT_L_FLOOR_COUNT 20

void asag_tent_l_collision_init(CollisionRoom *r);

#endif /* ASAG_LEFT_TENTACLE_COLLISION_H */
