/*
 * Auto-generated collision data from: Chain Room mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef CHAIN_ROOM_MESH_COLLISION_H
#define CHAIN_ROOM_MESH_COLLISION_H

#include "collision.h"

#define CHAIN_ROOM_WALL_COUNT  16
#define CHAIN_ROOM_FLOOR_COUNT 3

void chain_room_collision_init(CollisionRoom *r);

#endif /* CHAIN_ROOM_MESH_COLLISION_H */
