/*
 * Auto-generated collision data from: Chain Room mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  16
 * Floors: 3
 * Bounds: X(-200 to 1800)  Z(-1100 to 900)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Chain Room mesh_collision.h"

void chain_room_collision_init(CollisionRoom *r) {
    r->wall_count = CHAIN_ROOM_WALL_COUNT;
    r->min_x = -200;
    r->max_x = 1800;
    r->min_z = -1100;
    r->max_z = 900;

    /* Wall 0 (avg Y: -250) */
    r->walls[0].x1 =    1200;  r->walls[0].z1 =   -1100;
    r->walls[0].x2 =    1200;  r->walls[0].z2 =    -900;
    r->walls[0].nx =   -4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -500;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -250) */
    r->walls[1].x1 =     600;  r->walls[1].z1 =    -900;
    r->walls[1].x2 =     600;  r->walls[1].z2 =   -1100;
    r->walls[1].nx =    4096;  r->walls[1].nz =       0;
    r->walls[1].y_min =    -500;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -250) */
    r->walls[2].x1 =       0;  r->walls[2].z1 =    -300;
    r->walls[2].x2 =       0;  r->walls[2].z2 =    -900;
    r->walls[2].nx =    4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -500;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -250) */
    r->walls[3].x1 =    1200;  r->walls[3].z1 =    -900;
    r->walls[3].x2 =    1800;  r->walls[3].z2 =    -900;
    r->walls[3].nx =       0;  r->walls[3].nz =    4096;
    r->walls[3].y_min =    -500;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -250) */
    r->walls[4].x1 =       0;  r->walls[4].z1 =    -900;
    r->walls[4].x2 =     600;  r->walls[4].z2 =    -900;
    r->walls[4].nx =       0;  r->walls[4].nz =    4096;
    r->walls[4].y_min =    -500;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -250) */
    r->walls[5].x1 =       0;  r->walls[5].z1 =     900;
    r->walls[5].x2 =       0;  r->walls[5].z2 =     300;
    r->walls[5].nx =    4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -500;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -250) */
    r->walls[6].x1 =    1800;  r->walls[6].z1 =     900;
    r->walls[6].x2 =       0;  r->walls[6].z2 =     900;
    r->walls[6].nx =       0;  r->walls[6].nz =   -4096;
    r->walls[6].y_min =    -500;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -250) */
    r->walls[7].x1 =    1800;  r->walls[7].z1 =     700;
    r->walls[7].x2 =    1800;  r->walls[7].z2 =     900;
    r->walls[7].nx =   -4096;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -500;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -250) */
    r->walls[8].x1 =    1800;  r->walls[8].z1 =    -900;
    r->walls[8].x2 =    1800;  r->walls[8].z2 =     500;
    r->walls[8].nx =   -4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =    -500;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -250) */
    r->walls[9].x1 =     600;  r->walls[9].z1 =   -1100;
    r->walls[9].x2 =    1200;  r->walls[9].z2 =   -1100;
    r->walls[9].nx =       0;  r->walls[9].nz =    4096;
    r->walls[9].y_min =    -500;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -250) */
    r->walls[10].x1 =       0;  r->walls[10].z1 =     300;
    r->walls[10].x2 =    -200;  r->walls[10].z2 =     300;
    r->walls[10].nx =       0;  r->walls[10].nz =   -4096;
    r->walls[10].y_min =    -500;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -250) */
    r->walls[11].x1 =    -200;  r->walls[11].z1 =    -300;
    r->walls[11].x2 =       0;  r->walls[11].z2 =    -300;
    r->walls[11].nx =       0;  r->walls[11].nz =    4096;
    r->walls[11].y_min =    -500;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -250) */
    r->walls[12].x1 =    -200;  r->walls[12].z1 =     300;
    r->walls[12].x2 =    -200;  r->walls[12].z2 =    -300;
    r->walls[12].nx =    4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =    -500;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -250) */
    r->walls[13].x1 =    1800;  r->walls[13].z1 =     500;
    r->walls[13].x2 =    1605;  r->walls[13].z2 =     500;
    r->walls[13].nx =       0;  r->walls[13].nz =   -4096;
    r->walls[13].y_min =    -500;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -250) */
    r->walls[14].x1 =    1605;  r->walls[14].z1 =     500;
    r->walls[14].x2 =    1605;  r->walls[14].z2 =     700;
    r->walls[14].nx =   -4096;  r->walls[14].nz =       0;
    r->walls[14].y_min =    -500;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -250) */
    r->walls[15].x1 =    1605;  r->walls[15].z1 =     700;
    r->walls[15].x2 =    1800;  r->walls[15].z2 =     700;
    r->walls[15].nx =       0;  r->walls[15].nz =    4096;
    r->walls[15].y_min =    -500;  r->walls[15].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(0 to 1800)  z(-900 to 900)
     * FLOOR   1: y=     0  x(600 to 1200)  z(-1100 to -900)
     * FLOOR   2: y=     0  x(-200 to 0)  z(-300 to 300)
     */
}
