/*
 * Auto-generated collision data from: Keystone Maze mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef KEYSTONE_MAZE_MESH_COLLISION_H
#define KEYSTONE_MAZE_MESH_COLLISION_H

#include "collision.h"

#define KEYSTONE_MAZE_WALL_COUNT  68
#define KEYSTONE_MAZE_FLOOR_COUNT 13

void keystone_maze_collision_init(CollisionRoom *r);

#endif /* KEYSTONE_MAZE_MESH_COLLISION_H */
