/*
 * Auto-generated collision data from: Maze One mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  76
 * Floors: 27
 * Bounds: X(-100 to 7500)  Z(-2095 to 4496)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Maze One mesh_collision.h"

void maze_one_collision_init(CollisionRoom *r) {
    r->wall_count = MAZE_ONE_WALL_COUNT;
    r->min_x = -100;
    r->max_x = 7500;
    r->min_z = -2095;
    r->max_z = 4496;

    /* Wall 0 (avg Y: -166) */
    r->walls[0].x1 =    5705;  r->walls[0].z1 =    1900;
    r->walls[0].x2 =    5705;  r->walls[0].z2 =    2500;
    r->walls[0].nx =   -4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -333;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -166) */
    r->walls[1].x1 =    1501;  r->walls[1].z1 =    4300;
    r->walls[1].x2 =     298;  r->walls[1].z2 =    4300;
    r->walls[1].nx =       0;  r->walls[1].nz =   -4096;
    r->walls[1].y_min =    -333;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -166) */
    r->walls[2].x1 =    6901;  r->walls[2].z1 =    1900;
    r->walls[2].x2 =    5705;  r->walls[2].z2 =    1900;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4096;
    r->walls[2].y_min =    -333;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -166) */
    r->walls[3].x1 =    6900;  r->walls[3].z1 =    2001;
    r->walls[3].x2 =    7500;  r->walls[3].z2 =    2001;
    r->walls[3].nx =       0;  r->walls[3].nz =    4096;
    r->walls[3].y_min =    -333;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -166) */
    r->walls[4].x1 =    7100;  r->walls[4].z1 =    -900;
    r->walls[4].x2 =    7100;  r->walls[4].z2 =    -312;
    r->walls[4].nx =   -4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -333;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -166) */
    r->walls[5].x1 =    5700;  r->walls[5].z1 =    -312;
    r->walls[5].x2 =    5700;  r->walls[5].z2 =     898;
    r->walls[5].nx =   -4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -333;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -166) */
    r->walls[6].x1 =    5705;  r->walls[6].z1 =    2500;
    r->walls[6].x2 =    6900;  r->walls[6].z2 =    2500;
    r->walls[6].nx =       0;  r->walls[6].nz =    4096;
    r->walls[6].y_min =    -333;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -166) */
    r->walls[7].x1 =    6901;  r->walls[7].z1 =    -900;
    r->walls[7].x2 =    7100;  r->walls[7].z2 =    -900;
    r->walls[7].nx =       0;  r->walls[7].nz =    4096;
    r->walls[7].y_min =    -333;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -166) */
    r->walls[8].x1 =    7100;  r->walls[8].z1 =    -312;
    r->walls[8].x2 =    6901;  r->walls[8].z2 =    -312;
    r->walls[8].nx =       0;  r->walls[8].nz =   -4096;
    r->walls[8].y_min =    -333;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -166) */
    r->walls[9].x1 =    6900;  r->walls[9].z1 =    2500;
    r->walls[9].x2 =    6900;  r->walls[9].z2 =    2001;
    r->walls[9].nx =    4096;  r->walls[9].nz =       0;
    r->walls[9].y_min =    -333;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -166) */
    r->walls[10].x1 =    7500;  r->walls[10].z1 =    2001;
    r->walls[10].x2 =    7500;  r->walls[10].z2 =    4300;
    r->walls[10].nx =   -4096;  r->walls[10].nz =       0;
    r->walls[10].y_min =    -333;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -166) */
    r->walls[11].x1 =    6901;  r->walls[11].z1 =    -312;
    r->walls[11].x2 =    6901;  r->walls[11].z2 =    1900;
    r->walls[11].nx =   -4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -333;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -166) */
    r->walls[12].x1 =    6901;  r->walls[12].z1 =   -2095;
    r->walls[12].x2 =    6901;  r->walls[12].z2 =    -900;
    r->walls[12].nx =   -4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =    -333;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -166) */
    r->walls[13].x1 =    3299;  r->walls[13].z1 =   -1502;
    r->walls[13].x2 =    3299;  r->walls[13].z2 =   -2095;
    r->walls[13].nx =    4096;  r->walls[13].nz =       0;
    r->walls[13].y_min =    -333;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -166) */
    r->walls[14].x1 =    3299;  r->walls[14].z1 =   -2095;
    r->walls[14].x2 =    6901;  r->walls[14].z2 =   -2095;
    r->walls[14].nx =       0;  r->walls[14].nz =    4096;
    r->walls[14].y_min =    -333;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -166) */
    r->walls[15].x1 =    7500;  r->walls[15].z1 =    4300;
    r->walls[15].x2 =    2095;  r->walls[15].z2 =    4300;
    r->walls[15].nx =       0;  r->walls[15].nz =   -4096;
    r->walls[15].y_min =    -333;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -166) */
    r->walls[16].x1 =    2696;  r->walls[16].z1 =   -1502;
    r->walls[16].x2 =    3299;  r->walls[16].z2 =   -1502;
    r->walls[16].nx =       0;  r->walls[16].nz =    4096;
    r->walls[16].y_min =    -333;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -166) */
    r->walls[17].x1 =    2696;  r->walls[17].z1 =    -298;
    r->walls[17].x2 =    2696;  r->walls[17].z2 =   -1502;
    r->walls[17].nx =    4096;  r->walls[17].nz =       0;
    r->walls[17].y_min =    -333;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -166) */
    r->walls[18].x1 =    1501;  r->walls[18].z1 =    4496;
    r->walls[18].x2 =    1501;  r->walls[18].z2 =    4300;
    r->walls[18].nx =    4096;  r->walls[18].nz =       0;
    r->walls[18].y_min =    -333;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -166) */
    r->walls[19].x1 =    2095;  r->walls[19].z1 =    4496;
    r->walls[19].x2 =    1501;  r->walls[19].z2 =    4496;
    r->walls[19].nx =       0;  r->walls[19].nz =   -4096;
    r->walls[19].y_min =    -333;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -166) */
    r->walls[20].x1 =    2095;  r->walls[20].z1 =    4300;
    r->walls[20].x2 =    2095;  r->walls[20].z2 =    4496;
    r->walls[20].nx =   -4096;  r->walls[20].nz =       0;
    r->walls[20].y_min =    -333;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -166) */
    r->walls[21].x1 =     298;  r->walls[21].z1 =    1898;
    r->walls[21].x2 =     898;  r->walls[21].z2 =    1898;
    r->walls[21].nx =       0;  r->walls[21].nz =    4096;
    r->walls[21].y_min =    -333;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -166) */
    r->walls[22].x1 =     898;  r->walls[22].z1 =    2496;
    r->walls[22].x2 =     898;  r->walls[22].z2 =    3698;
    r->walls[22].nx =   -4096;  r->walls[22].nz =       0;
    r->walls[22].y_min =    -333;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -166) */
    r->walls[23].x1 =     898;  r->walls[23].z1 =    1898;
    r->walls[23].x2 =     898;  r->walls[23].z2 =    1299;
    r->walls[23].nx =    4096;  r->walls[23].nz =       0;
    r->walls[23].y_min =    -333;  r->walls[23].y_max =       0;

    /* Wall 24 (avg Y: -166) */
    r->walls[24].x1 =     298;  r->walls[24].z1 =    4300;
    r->walls[24].x2 =     298;  r->walls[24].z2 =    1898;
    r->walls[24].nx =    4096;  r->walls[24].nz =       0;
    r->walls[24].y_min =    -333;  r->walls[24].y_max =       0;

    /* Wall 25 (avg Y: -166) */
    r->walls[25].x1 =    2094;  r->walls[25].z1 =     300;
    r->walls[25].x2 =    2094;  r->walls[25].z2 =    1299;
    r->walls[25].nx =   -4096;  r->walls[25].nz =       0;
    r->walls[25].y_min =    -333;  r->walls[25].y_max =       0;

    /* Wall 26 (avg Y: -166) */
    r->walls[26].x1 =    2094;  r->walls[26].z1 =   -1294;
    r->walls[26].x2 =    2094;  r->walls[26].z2 =    -298;
    r->walls[26].nx =   -4096;  r->walls[26].nz =       0;
    r->walls[26].y_min =    -333;  r->walls[26].y_max =       0;

    /* Wall 27 (avg Y: -166) */
    r->walls[27].x1 =     100;  r->walls[27].z1 =    1299;
    r->walls[27].x2 =     100;  r->walls[27].z2 =     499;
    r->walls[27].nx =    4096;  r->walls[27].nz =       0;
    r->walls[27].y_min =    -333;  r->walls[27].y_max =       0;

    /* Wall 28 (avg Y: -166) */
    r->walls[28].x1 =     100;  r->walls[28].z1 =    -300;
    r->walls[28].x2 =     100;  r->walls[28].z2 =   -1294;
    r->walls[28].nx =    4096;  r->walls[28].nz =       0;
    r->walls[28].y_min =    -333;  r->walls[28].y_max =       0;

    /* Wall 29 (avg Y: -166) */
    r->walls[29].x1 =     898;  r->walls[29].z1 =    1299;
    r->walls[29].x2 =     100;  r->walls[29].z2 =    1299;
    r->walls[29].nx =       0;  r->walls[29].nz =   -4096;
    r->walls[29].y_min =    -333;  r->walls[29].y_max =       0;

    /* Wall 30 (avg Y: -166) */
    r->walls[30].x1 =     100;  r->walls[30].z1 =   -1294;
    r->walls[30].x2 =    2094;  r->walls[30].z2 =   -1294;
    r->walls[30].nx =       0;  r->walls[30].nz =    4096;
    r->walls[30].y_min =    -333;  r->walls[30].y_max =       0;

    /* Wall 31 (avg Y: -166) */
    r->walls[31].x1 =    -100;  r->walls[31].z1 =    -300;
    r->walls[31].x2 =     100;  r->walls[31].z2 =    -300;
    r->walls[31].nx =       0;  r->walls[31].nz =    4096;
    r->walls[31].y_min =    -333;  r->walls[31].y_max =       0;

    /* Wall 32 (avg Y: -166) */
    r->walls[32].x1 =     898;  r->walls[32].z1 =     699;
    r->walls[32].x2 =    1496;  r->walls[32].z2 =     699;
    r->walls[32].nx =       0;  r->walls[32].nz =    4096;
    r->walls[32].y_min =    -333;  r->walls[32].y_max =       0;

    /* Wall 33 (avg Y: -166) */
    r->walls[33].x1 =    1496;  r->walls[33].z1 =    -697;
    r->walls[33].x2 =     898;  r->walls[33].z2 =    -697;
    r->walls[33].nx =       0;  r->walls[33].nz =   -4096;
    r->walls[33].y_min =    -333;  r->walls[33].y_max =       0;

    /* Wall 34 (avg Y: -166) */
    r->walls[34].x1 =    2696;  r->walls[34].z1 =     300;
    r->walls[34].x2 =    2094;  r->walls[34].z2 =     300;
    r->walls[34].nx =       0;  r->walls[34].nz =   -4096;
    r->walls[34].y_min =    -333;  r->walls[34].y_max =       0;

    /* Wall 35 (avg Y: -166) */
    r->walls[35].x1 =    1501;  r->walls[35].z1 =    3698;
    r->walls[35].x2 =    1501;  r->walls[35].z2 =    2501;
    r->walls[35].nx =    4096;  r->walls[35].nz =       0;
    r->walls[35].y_min =    -333;  r->walls[35].y_max =       0;

    /* Wall 36 (avg Y: -166) */
    r->walls[36].x1 =    1501;  r->walls[36].z1 =    2501;
    r->walls[36].x2 =    2699;  r->walls[36].z2 =    2501;
    r->walls[36].nx =       0;  r->walls[36].nz =    4096;
    r->walls[36].y_min =    -333;  r->walls[36].y_max =       0;

    /* Wall 37 (avg Y: -166) */
    r->walls[37].x1 =    2094;  r->walls[37].z1 =    1299;
    r->walls[37].x2 =    1496;  r->walls[37].z2 =    1299;
    r->walls[37].nx =       0;  r->walls[37].nz =   -4096;
    r->walls[37].y_min =    -333;  r->walls[37].y_max =       0;

    /* Wall 38 (avg Y: -166) */
    r->walls[38].x1 =     898;  r->walls[38].z1 =    3698;
    r->walls[38].x2 =    1501;  r->walls[38].z2 =    3698;
    r->walls[38].nx =       0;  r->walls[38].nz =    4096;
    r->walls[38].y_min =    -333;  r->walls[38].y_max =       0;

    /* Wall 39 (avg Y: -166) */
    r->walls[39].x1 =    1501;  r->walls[39].z1 =    2501;
    r->walls[39].x2 =     898;  r->walls[39].z2 =    2496;
    r->walls[39].nx =      33;  r->walls[39].nz =   -4095;
    r->walls[39].y_min =    -333;  r->walls[39].y_max =       0;

    /* Wall 40 (avg Y: -166) */
    r->walls[40].x1 =    1496;  r->walls[40].z1 =    1299;
    r->walls[40].x2 =    1501;  r->walls[40].z2 =    2501;
    r->walls[40].nx =   -4095;  r->walls[40].nz =      17;
    r->walls[40].y_min =    -333;  r->walls[40].y_max =       0;

    /* Wall 41 (avg Y: -166) */
    r->walls[41].x1 =    2094;  r->walls[41].z1 =    -298;
    r->walls[41].x2 =    2696;  r->walls[41].z2 =    -298;
    r->walls[41].nx =       0;  r->walls[41].nz =    4096;
    r->walls[41].y_min =    -333;  r->walls[41].y_max =       0;

    /* Wall 42 (avg Y: -166) */
    r->walls[42].x1 =    6293;  r->walls[42].z1 =    1300;
    r->walls[42].x2 =    6293;  r->walls[42].z2 =    -312;
    r->walls[42].nx =    4096;  r->walls[42].nz =       0;
    r->walls[42].y_min =    -333;  r->walls[42].y_max =       0;

    /* Wall 43 (avg Y: -166) */
    r->walls[43].x1 =    6293;  r->walls[43].z1 =    -900;
    r->walls[43].x2 =    6293;  r->walls[43].z2 =   -1502;
    r->walls[43].nx =    4096;  r->walls[43].nz =       0;
    r->walls[43].y_min =    -333;  r->walls[43].y_max =       0;

    /* Wall 44 (avg Y: -166) */
    r->walls[44].x1 =    3500;  r->walls[44].z1 =    -312;
    r->walls[44].x2 =    4100;  r->walls[44].z2 =    -312;
    r->walls[44].nx =       0;  r->walls[44].nz =    4096;
    r->walls[44].y_min =    -333;  r->walls[44].y_max =       0;

    /* Wall 45 (avg Y: -166) */
    r->walls[45].x1 =    4800;  r->walls[45].z1 =    3700;
    r->walls[45].x2 =    6900;  r->walls[45].z2 =    3700;
    r->walls[45].nx =       0;  r->walls[45].nz =    4096;
    r->walls[45].y_min =    -333;  r->walls[45].y_max =       0;

    /* Wall 46 (avg Y: -166) */
    r->walls[46].x1 =    6900;  r->walls[46].z1 =    3700;
    r->walls[46].x2 =    6900;  r->walls[46].z2 =    3100;
    r->walls[46].nx =    4096;  r->walls[46].nz =       0;
    r->walls[46].y_min =    -333;  r->walls[46].y_max =       0;

    /* Wall 47 (avg Y: -166) */
    r->walls[47].x1 =    6293;  r->walls[47].z1 =    1300;
    r->walls[47].x2 =    5108;  r->walls[47].z2 =    1300;
    r->walls[47].nx =       0;  r->walls[47].nz =   -4096;
    r->walls[47].y_min =    -333;  r->walls[47].y_max =       0;

    /* Wall 48 (avg Y: -166) */
    r->walls[48].x1 =    6900;  r->walls[48].z1 =    3100;
    r->walls[48].x2 =    5108;  r->walls[48].z2 =    3100;
    r->walls[48].nx =       0;  r->walls[48].nz =   -4096;
    r->walls[48].y_min =    -333;  r->walls[48].y_max =       0;

    /* Wall 49 (avg Y: -166) */
    r->walls[49].x1 =    5108;  r->walls[49].z1 =    3100;
    r->walls[49].x2 =    5108;  r->walls[49].z2 =    1300;
    r->walls[49].nx =    4096;  r->walls[49].nz =       0;
    r->walls[49].y_min =    -333;  r->walls[49].y_max =       0;

    /* Wall 50 (avg Y: -166) */
    r->walls[50].x1 =    3897;  r->walls[50].z1 =   -1502;
    r->walls[50].x2 =    3897;  r->walls[50].z2 =    -900;
    r->walls[50].nx =   -4096;  r->walls[50].nz =       0;
    r->walls[50].y_min =    -333;  r->walls[50].y_max =       0;

    /* Wall 51 (avg Y: -166) */
    r->walls[51].x1 =    4100;  r->walls[51].z1 =    -900;
    r->walls[51].x2 =    6293;  r->walls[51].z2 =    -900;
    r->walls[51].nx =       0;  r->walls[51].nz =    4096;
    r->walls[51].y_min =    -333;  r->walls[51].y_max =       0;

    /* Wall 52 (avg Y: -166) */
    r->walls[52].x1 =    6293;  r->walls[52].z1 =   -1502;
    r->walls[52].x2 =    3897;  r->walls[52].z2 =   -1502;
    r->walls[52].nx =       0;  r->walls[52].nz =   -4096;
    r->walls[52].y_min =    -333;  r->walls[52].y_max =       0;

    /* Wall 53 (avg Y: -166) */
    r->walls[53].x1 =    3897;  r->walls[53].z1 =    -900;
    r->walls[53].x2 =    3299;  r->walls[53].z2 =    -900;
    r->walls[53].nx =       0;  r->walls[53].nz =   -4096;
    r->walls[53].y_min =    -333;  r->walls[53].y_max =       0;

    /* Wall 54 (avg Y: -166) */
    r->walls[54].x1 =    3295;  r->walls[54].z1 =    1300;
    r->walls[54].x2 =    4800;  r->walls[54].z2 =    1300;
    r->walls[54].nx =       0;  r->walls[54].nz =    4096;
    r->walls[54].y_min =    -333;  r->walls[54].y_max =       0;

    /* Wall 55 (avg Y: -166) */
    r->walls[55].x1 =    5242;  r->walls[55].z1 =    1100;
    r->walls[55].x2 =    3500;  r->walls[55].z2 =    1100;
    r->walls[55].nx =       0;  r->walls[55].nz =   -4096;
    r->walls[55].y_min =    -333;  r->walls[55].y_max =       0;

    /* Wall 56 (avg Y: -166) */
    r->walls[56].x1 =    4800;  r->walls[56].z1 =    1300;
    r->walls[56].x2 =    4800;  r->walls[56].z2 =    3700;
    r->walls[56].nx =   -4096;  r->walls[56].nz =       0;
    r->walls[56].y_min =    -333;  r->walls[56].y_max =       0;

    /* Wall 57 (avg Y: -166) */
    r->walls[57].x1 =    4200;  r->walls[57].z1 =    3700;
    r->walls[57].x2 =    4199;  r->walls[57].z2 =    3100;
    r->walls[57].nx =    4095;  r->walls[57].nz =      -4;
    r->walls[57].y_min =    -333;  r->walls[57].y_max =       0;

    /* Wall 58 (avg Y: -166) */
    r->walls[58].x1 =    2095;  r->walls[58].z1 =    3100;
    r->walls[58].x2 =    2095;  r->walls[58].z2 =    3698;
    r->walls[58].nx =   -4096;  r->walls[58].nz =       0;
    r->walls[58].y_min =    -333;  r->walls[58].y_max =       0;

    /* Wall 59 (avg Y: -166) */
    r->walls[59].x1 =    2095;  r->walls[59].z1 =    3698;
    r->walls[59].x2 =    4200;  r->walls[59].z2 =    3700;
    r->walls[59].nx =      -2;  r->walls[59].nz =    4095;
    r->walls[59].y_min =    -333;  r->walls[59].y_max =       0;

    /* Wall 60 (avg Y: -166) */
    r->walls[60].x1 =    4199;  r->walls[60].z1 =    3100;
    r->walls[60].x2 =    2095;  r->walls[60].z2 =    3100;
    r->walls[60].nx =       0;  r->walls[60].nz =   -4096;
    r->walls[60].y_min =    -333;  r->walls[60].y_max =       0;

    /* Wall 61 (avg Y: -166) */
    r->walls[61].x1 =    3295;  r->walls[61].z1 =    1901;
    r->walls[61].x2 =    3295;  r->walls[61].z2 =    2501;
    r->walls[61].nx =   -4096;  r->walls[61].nz =       0;
    r->walls[61].y_min =    -333;  r->walls[61].y_max =       0;

    /* Wall 62 (avg Y: -166) */
    r->walls[62].x1 =    4199;  r->walls[62].z1 =    2501;
    r->walls[62].x2 =    4198;  r->walls[62].z2 =    1901;
    r->walls[62].nx =    4095;  r->walls[62].nz =      -6;
    r->walls[62].y_min =    -333;  r->walls[62].y_max =       0;

    /* Wall 63 (avg Y: -166) */
    r->walls[63].x1 =    4198;  r->walls[63].z1 =    1901;
    r->walls[63].x2 =    3295;  r->walls[63].z2 =    1901;
    r->walls[63].nx =       0;  r->walls[63].nz =   -4096;
    r->walls[63].y_min =    -333;  r->walls[63].y_max =       0;

    /* Wall 64 (avg Y: -166) */
    r->walls[64].x1 =    3295;  r->walls[64].z1 =    2501;
    r->walls[64].x2 =    4199;  r->walls[64].z2 =    2501;
    r->walls[64].nx =       0;  r->walls[64].nz =    4096;
    r->walls[64].y_min =    -333;  r->walls[64].y_max =       0;

    /* Wall 65 (avg Y: -166) */
    r->walls[65].x1 =    6293;  r->walls[65].z1 =    -312;
    r->walls[65].x2 =    5700;  r->walls[65].z2 =    -312;
    r->walls[65].nx =       0;  r->walls[65].nz =   -4096;
    r->walls[65].y_min =    -333;  r->walls[65].y_max =       0;

    /* Wall 66 (avg Y: -166) */
    r->walls[66].x1 =    5700;  r->walls[66].z1 =     898;
    r->walls[66].x2 =    5242;  r->walls[66].z2 =     898;
    r->walls[66].nx =       0;  r->walls[66].nz =   -4095;
    r->walls[66].y_min =    -333;  r->walls[66].y_max =       0;

    /* Wall 67 (avg Y: -166) */
    r->walls[67].x1 =    4100;  r->walls[67].z1 =    -312;
    r->walls[67].x2 =    4100;  r->walls[67].z2 =    -900;
    r->walls[67].nx =    4096;  r->walls[67].nz =       0;
    r->walls[67].y_min =    -333;  r->walls[67].y_max =       0;

    /* Wall 68 (avg Y: -166) */
    r->walls[68].x1 =    3500;  r->walls[68].z1 =    1100;
    r->walls[68].x2 =    3500;  r->walls[68].z2 =    -312;
    r->walls[68].nx =    4096;  r->walls[68].nz =       0;
    r->walls[68].y_min =    -333;  r->walls[68].y_max =       0;

    /* Wall 69 (avg Y: -166) */
    r->walls[69].x1 =    3299;  r->walls[69].z1 =    -900;
    r->walls[69].x2 =    3295;  r->walls[69].z2 =    1300;
    r->walls[69].nx =   -4095;  r->walls[69].nz =      -7;
    r->walls[69].y_min =    -333;  r->walls[69].y_max =       0;

    /* Wall 70 (avg Y: -166) */
    r->walls[70].x1 =    2699;  r->walls[70].z1 =    2501;
    r->walls[70].x2 =    2696;  r->walls[70].z2 =     300;
    r->walls[70].nx =    4095;  r->walls[70].nz =      -4;
    r->walls[70].y_min =    -333;  r->walls[70].y_max =       0;

    /* Wall 71 (avg Y: -166) */
    r->walls[71].x1 =    1496;  r->walls[71].z1 =     699;
    r->walls[71].x2 =    1496;  r->walls[71].z2 =    -697;
    r->walls[71].nx =    4096;  r->walls[71].nz =       0;
    r->walls[71].y_min =    -333;  r->walls[71].y_max =       0;

    /* Wall 72 (avg Y: -166) */
    r->walls[72].x1 =     898;  r->walls[72].z1 =    -697;
    r->walls[72].x2 =     898;  r->walls[72].z2 =     699;
    r->walls[72].nx =   -4096;  r->walls[72].nz =       0;
    r->walls[72].y_min =    -333;  r->walls[72].y_max =       0;

    /* Wall 73 (avg Y: -166) */
    r->walls[73].x1 =     -99;  r->walls[73].z1 =     500;
    r->walls[73].x2 =    -100;  r->walls[73].z2 =    -300;
    r->walls[73].nx =    4095;  r->walls[73].nz =       0;
    r->walls[73].y_min =    -333;  r->walls[73].y_max =       0;

    /* Wall 74 (avg Y: -166) */
    r->walls[74].x1 =    5242;  r->walls[74].z1 =     898;
    r->walls[74].x2 =    5242;  r->walls[74].z2 =    1100;
    r->walls[74].nx =   -4096;  r->walls[74].nz =       0;
    r->walls[74].y_min =    -333;  r->walls[74].y_max =       0;

    /* Wall 75 (avg Y: -166) */
    r->walls[75].x1 =     100;  r->walls[75].z1 =     499;
    r->walls[75].x2 =     -99;  r->walls[75].z2 =     500;
    r->walls[75].nx =      -1;  r->walls[75].nz =   -4095;
    r->walls[75].y_min =    -333;  r->walls[75].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(298 to 898)  z(1898 to 3698)
     * FLOOR   1: y=     0  x(298 to 7500)  z(3698 to 4300)
     * FLOOR   2: y=     0  x(3299 to 6293)  z(-2095 to -1502)
     * FLOOR   3: y=     0  x(3299 to 3897)  z(-1502 to -900)
     * FLOOR   4: y=     0  x(1501 to 2095)  z(4300 to 4496)
     * FLOOR   5: y=     0  x(4100 to 6293)  z(-900 to -312)
     * FLOOR   6: y=     0  x(3500 to 5242)  z(-312 to 1100)
     * FLOOR   7: y=     0  x(5242 to 5700)  z(-312 to 898)
     * FLOOR   8: y=     0  x(898 to 1496)  z(1299 to 2496)
     * FLOOR   9: y=     0  x(100 to 2094)  z(699 to 1299)
     * FLOOR   10: y=     0  x(100 to 898)  z(-697 to 699)
     * FLOOR   11: y=     0  x(-100 to 100)  z(-300 to 500)
     * FLOOR   12: y=     0  x(100 to 2094)  z(-1294 to -697)
     * FLOOR   13: y=     0  x(1496 to 2094)  z(-697 to 699)
     * FLOOR   14: y=     0  x(2094 to 2696)  z(-298 to 300)
     * FLOOR   15: y=     0  x(2696 to 3299)  z(-1502 to 3100)
     * FLOOR   16: y=     0  x(1501 to 2095)  z(2501 to 3698)
     * FLOOR   17: y=     0  x(2095 to 2699)  z(2501 to 3100)
     * FLOOR   18: y=     0  x(3295 to 4199)  z(2501 to 3100)
     * FLOOR   19: y=     0  x(3295 to 4198)  z(1300 to 1901)
     * FLOOR   20: y=     0  x(4198 to 4800)  z(1300 to 3700)
     * FLOOR   21: y=     0  x(6900 to 7500)  z(2001 to 3700)
     * FLOOR   22: y=     0  x(5108 to 6900)  z(2500 to 3100)
     * FLOOR   23: y=     0  x(5108 to 5705)  z(1900 to 2500)
     * FLOOR   24: y=     0  x(5108 to 6901)  z(1300 to 1900)
     * FLOOR   25: y=     0  x(6293 to 6901)  z(-2095 to 1300)
     * FLOOR   26: y=     0  x(6901 to 7100)  z(-900 to -312)
     */
}
