/*
 * Auto-generated collision data from: Outside Catacombs mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef OUTSIDE_CATACOMBS_MESH_COLLISION_H
#define OUTSIDE_CATACOMBS_MESH_COLLISION_H

#include "collision.h"

#define OUTSIDE_CATACOMBS_WALL_COUNT  56
#define OUTSIDE_CATACOMBS_FLOOR_COUNT 16

void outside_catacombs_collision_init(CollisionRoom *r);

#endif /* OUTSIDE_CATACOMBS_MESH_COLLISION_H */
