/*
 * Auto-generated collision data from: Outside Catacombs mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  56
 * Floors: 16
 * Bounds: X(-4396 to 4399)  Z(-2000 to 4353)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Outside Catacombs mesh_collision.h"

void outside_catacombs_collision_init(CollisionRoom *r) {
    r->wall_count = OUTSIDE_CATACOMBS_WALL_COUNT;
    r->min_x = -4396;
    r->max_x = 4399;
    r->min_z = -2000;
    r->max_z = 4353;

    /* Wall 0 (avg Y: -252) */
    r->walls[0].x1 =    -750;  r->walls[0].z1 =    1714;
    r->walls[0].x2 =    -750;  r->walls[0].z2 =    1428;
    r->walls[0].nx =    4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -504;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -207) */
    r->walls[1].x1 =    1364;  r->walls[1].z1 =    4150;
    r->walls[1].x2 =     750;  r->walls[1].z2 =    3850;
    r->walls[1].nx =    1796;  r->walls[1].nz =   -3680;
    r->walls[1].y_min =    -430;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -207) */
    r->walls[2].x1 =    -750;  r->walls[2].z1 =    3850;
    r->walls[2].x2 =   -1343;  r->walls[2].z2 =    4150;
    r->walls[2].nx =   -1847;  r->walls[2].nz =   -3655;
    r->walls[2].y_min =    -430;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -250) */
    r->walls[3].x1 =    2286;  r->walls[3].z1 =    3217;
    r->walls[3].x2 =    2286;  r->walls[3].z2 =    4353;
    r->walls[3].nx =   -4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -500;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -250) */
    r->walls[4].x1 =   -2234;  r->walls[4].z1 =    4353;
    r->walls[4].x2 =   -2234;  r->walls[4].z2 =    3217;
    r->walls[4].nx =    4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -500;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -250) */
    r->walls[5].x1 =   -2234;  r->walls[5].z1 =    3217;
    r->walls[5].x2 =   -3763;  r->walls[5].z2 =    3232;
    r->walls[5].nx =     -38;  r->walls[5].nz =   -4095;
    r->walls[5].y_min =    -500;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -252) */
    r->walls[6].x1 =   -3131;  r->walls[6].z1 =    2653;
    r->walls[6].x2 =   -2234;  r->walls[6].z2 =    2649;
    r->walls[6].nx =      16;  r->walls[6].nz =    4095;
    r->walls[6].y_min =    -504;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -252) */
    r->walls[7].x1 =   -2498;  r->walls[7].z1 =     285;
    r->walls[7].x2 =   -2498;  r->walls[7].z2 =    1424;
    r->walls[7].nx =   -4096;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -504;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -250) */
    r->walls[8].x1 =    2504;  r->walls[8].z1 =   -1414;
    r->walls[8].x2 =    4399;  r->walls[8].z2 =   -1414;
    r->walls[8].nx =       0;  r->walls[8].nz =    4096;
    r->walls[8].y_min =    -500;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -249) */
    r->walls[9].x1 =    4399;  r->walls[9].z1 =    1406;
    r->walls[9].x2 =    3767;  r->walls[9].z2 =    1406;
    r->walls[9].nx =       0;  r->walls[9].nz =   -4096;
    r->walls[9].y_min =    -499;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -250) */
    r->walls[10].x1 =    1895;  r->walls[10].z1 =    -285;
    r->walls[10].x2 =    2504;  r->walls[10].z2 =    -285;
    r->walls[10].nx =       0;  r->walls[10].nz =    4096;
    r->walls[10].y_min =    -500;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -250) */
    r->walls[11].x1 =   -3763;  r->walls[11].z1 =    1424;
    r->walls[11].x2 =   -4396;  r->walls[11].z2 =    1424;
    r->walls[11].nx =       0;  r->walls[11].nz =   -4096;
    r->walls[11].y_min =    -500;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -250) */
    r->walls[12].x1 =   -4396;  r->walls[12].z1 =    1424;
    r->walls[12].x2 =   -4396;  r->walls[12].z2 =   -1449;
    r->walls[12].nx =    4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =    -500;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -249) */
    r->walls[13].x1 =   -2498;  r->walls[13].z1 =    -285;
    r->walls[13].x2 =   -2498;  r->walls[13].z2 =   -1449;
    r->walls[13].nx =    4096;  r->walls[13].nz =       0;
    r->walls[13].y_min =    -500;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -250) */
    r->walls[14].x1 =   -1915;  r->walls[14].z1 =    -285;
    r->walls[14].x2 =   -1915;  r->walls[14].z2 =   -1428;
    r->walls[14].nx =    4096;  r->walls[14].nz =       0;
    r->walls[14].y_min =    -500;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -250) */
    r->walls[15].x1 =     750;  r->walls[15].z1 =   -1428;
    r->walls[15].x2 =    1895;  r->walls[15].z2 =   -1428;
    r->walls[15].nx =       0;  r->walls[15].nz =    4096;
    r->walls[15].y_min =    -500;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -250) */
    r->walls[16].x1 =   -1915;  r->walls[16].z1 =   -1428;
    r->walls[16].x2 =    -750;  r->walls[16].z2 =   -1428;
    r->walls[16].nx =       0;  r->walls[16].nz =    4096;
    r->walls[16].y_min =    -500;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -250) */
    r->walls[17].x1 =    -750;  r->walls[17].z1 =   -2000;
    r->walls[17].x2 =     750;  r->walls[17].z2 =   -2000;
    r->walls[17].nx =       0;  r->walls[17].nz =    4096;
    r->walls[17].y_min =    -500;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -250) */
    r->walls[18].x1 =    -750;  r->walls[18].z1 =   -1428;
    r->walls[18].x2 =    -750;  r->walls[18].z2 =   -2000;
    r->walls[18].nx =    4096;  r->walls[18].nz =       0;
    r->walls[18].y_min =    -500;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -250) */
    r->walls[19].x1 =     750;  r->walls[19].z1 =   -2000;
    r->walls[19].x2 =     750;  r->walls[19].z2 =   -1428;
    r->walls[19].nx =   -4096;  r->walls[19].nz =       0;
    r->walls[19].y_min =    -500;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -252) */
    r->walls[20].x1 =   -3131;  r->walls[20].z1 =    1424;
    r->walls[20].x2 =   -3131;  r->walls[20].z2 =    2653;
    r->walls[20].nx =   -4096;  r->walls[20].nz =       0;
    r->walls[20].y_min =    -504;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -250) */
    r->walls[21].x1 =   -3763;  r->walls[21].z1 =    3232;
    r->walls[21].x2 =   -3763;  r->walls[21].z2 =    1424;
    r->walls[21].nx =    4096;  r->walls[21].nz =       0;
    r->walls[21].y_min =    -500;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -252) */
    r->walls[22].x1 =   -2234;  r->walls[22].z1 =    2649;
    r->walls[22].x2 =   -2234;  r->walls[22].z2 =    1714;
    r->walls[22].nx =    4096;  r->walls[22].nz =       0;
    r->walls[22].y_min =    -504;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -252) */
    r->walls[23].x1 =   -2234;  r->walls[23].z1 =    1714;
    r->walls[23].x2 =    -750;  r->walls[23].z2 =    1714;
    r->walls[23].nx =       0;  r->walls[23].nz =    4096;
    r->walls[23].y_min =    -504;  r->walls[23].y_max =       0;

    /* Wall 24 (avg Y: -252) */
    r->walls[24].x1 =   -2498;  r->walls[24].z1 =    1424;
    r->walls[24].x2 =   -3131;  r->walls[24].z2 =    1424;
    r->walls[24].nx =       0;  r->walls[24].nz =   -4096;
    r->walls[24].y_min =    -504;  r->walls[24].y_max =       0;

    /* Wall 25 (avg Y: -252) */
    r->walls[25].x1 =   -1915;  r->walls[25].z1 =     285;
    r->walls[25].x2 =   -2498;  r->walls[25].z2 =     285;
    r->walls[25].nx =       0;  r->walls[25].nz =   -4096;
    r->walls[25].y_min =    -504;  r->walls[25].y_max =       0;

    /* Wall 26 (avg Y: -252) */
    r->walls[26].x1 =    -750;  r->walls[26].z1 =    1428;
    r->walls[26].x2 =   -1915;  r->walls[26].z2 =    1428;
    r->walls[26].nx =       0;  r->walls[26].nz =   -4096;
    r->walls[26].y_min =    -504;  r->walls[26].y_max =       0;

    /* Wall 27 (avg Y: -252) */
    r->walls[27].x1 =   -1915;  r->walls[27].z1 =    1428;
    r->walls[27].x2 =   -1915;  r->walls[27].z2 =     285;
    r->walls[27].nx =    4096;  r->walls[27].nz =       0;
    r->walls[27].y_min =    -504;  r->walls[27].y_max =       0;

    /* Wall 28 (avg Y: -252) */
    r->walls[28].x1 =    2504;  r->walls[28].z1 =     285;
    r->walls[28].x2 =    1895;  r->walls[28].z2 =     285;
    r->walls[28].nx =       0;  r->walls[28].nz =   -4096;
    r->walls[28].y_min =    -504;  r->walls[28].y_max =       0;

    /* Wall 29 (avg Y: -250) */
    r->walls[29].x1 =    2504;  r->walls[29].z1 =    -285;
    r->walls[29].x2 =    2504;  r->walls[29].z2 =   -1414;
    r->walls[29].nx =    4096;  r->walls[29].nz =       0;
    r->walls[29].y_min =    -500;  r->walls[29].y_max =       0;

    /* Wall 30 (avg Y: -249) */
    r->walls[30].x1 =    3767;  r->walls[30].z1 =    3214;
    r->walls[30].x2 =    2286;  r->walls[30].z2 =    3217;
    r->walls[30].nx =      -9;  r->walls[30].nz =   -4095;
    r->walls[30].y_min =    -500;  r->walls[30].y_max =       0;

    /* Wall 31 (avg Y: -252) */
    r->walls[31].x1 =     750;  r->walls[31].z1 =    1714;
    r->walls[31].x2 =    2286;  r->walls[31].z2 =    1714;
    r->walls[31].nx =       0;  r->walls[31].nz =    4096;
    r->walls[31].y_min =    -504;  r->walls[31].y_max =       0;

    /* Wall 32 (avg Y: -252) */
    r->walls[32].x1 =    2286;  r->walls[32].z1 =    2649;
    r->walls[32].x2 =    3135;  r->walls[32].z2 =    2635;
    r->walls[32].nx =      69;  r->walls[32].nz =    4095;
    r->walls[32].y_min =    -504;  r->walls[32].y_max =       0;

    /* Wall 33 (avg Y: -252) */
    r->walls[33].x1 =    2286;  r->walls[33].z1 =    1714;
    r->walls[33].x2 =    2286;  r->walls[33].z2 =    2649;
    r->walls[33].nx =   -4096;  r->walls[33].nz =       0;
    r->walls[33].y_min =    -504;  r->walls[33].y_max =       0;

    /* Wall 34 (avg Y: -249) */
    r->walls[34].x1 =    3767;  r->walls[34].z1 =    1406;
    r->walls[34].x2 =    3767;  r->walls[34].z2 =    3214;
    r->walls[34].nx =   -4096;  r->walls[34].nz =       0;
    r->walls[34].y_min =    -499;  r->walls[34].y_max =       0;

    /* Wall 35 (avg Y: -252) */
    r->walls[35].x1 =    3135;  r->walls[35].z1 =    2635;
    r->walls[35].x2 =    3135;  r->walls[35].z2 =    1406;
    r->walls[35].nx =    4096;  r->walls[35].nz =       0;
    r->walls[35].y_min =    -504;  r->walls[35].y_max =       0;

    /* Wall 36 (avg Y: -252) */
    r->walls[36].x1 =    2504;  r->walls[36].z1 =    1406;
    r->walls[36].x2 =    2504;  r->walls[36].z2 =     285;
    r->walls[36].nx =    4096;  r->walls[36].nz =       0;
    r->walls[36].y_min =    -504;  r->walls[36].y_max =       0;

    /* Wall 37 (avg Y: -252) */
    r->walls[37].x1 =    1895;  r->walls[37].z1 =    1428;
    r->walls[37].x2 =     750;  r->walls[37].z2 =    1428;
    r->walls[37].nx =       0;  r->walls[37].nz =   -4096;
    r->walls[37].y_min =    -504;  r->walls[37].y_max =       0;

    /* Wall 38 (avg Y: -250) */
    r->walls[38].x1 =    4399;  r->walls[38].z1 =   -1414;
    r->walls[38].x2 =    4399;  r->walls[38].z2 =    1406;
    r->walls[38].nx =   -4096;  r->walls[38].nz =       0;
    r->walls[38].y_min =    -500;  r->walls[38].y_max =       0;

    /* Wall 39 (avg Y: -252) */
    r->walls[39].x1 =    3135;  r->walls[39].z1 =    1406;
    r->walls[39].x2 =    2504;  r->walls[39].z2 =    1406;
    r->walls[39].nx =       0;  r->walls[39].nz =   -4096;
    r->walls[39].y_min =    -504;  r->walls[39].y_max =       0;

    /* Wall 40 (avg Y: -250) */
    r->walls[40].x1 =    1895;  r->walls[40].z1 =   -1428;
    r->walls[40].x2 =    1895;  r->walls[40].z2 =    -285;
    r->walls[40].nx =   -4096;  r->walls[40].nz =       0;
    r->walls[40].y_min =    -500;  r->walls[40].y_max =       0;

    /* Wall 41 (avg Y: -252) */
    r->walls[41].x1 =    1895;  r->walls[41].z1 =     285;
    r->walls[41].x2 =    1895;  r->walls[41].z2 =    1428;
    r->walls[41].nx =   -4096;  r->walls[41].nz =       0;
    r->walls[41].y_min =    -504;  r->walls[41].y_max =       0;

    /* Wall 42 (avg Y: -252) */
    r->walls[42].x1 =     750;  r->walls[42].z1 =    1428;
    r->walls[42].x2 =     750;  r->walls[42].z2 =    1714;
    r->walls[42].nx =   -4096;  r->walls[42].nz =       0;
    r->walls[42].y_min =    -504;  r->walls[42].y_max =       0;

    /* Wall 43 (avg Y: -250) */
    r->walls[43].x1 =    1322;  r->walls[43].z1 =     857;
    r->walls[43].x2 =    1322;  r->walls[43].z2 =    -857;
    r->walls[43].nx =    4096;  r->walls[43].nz =       0;
    r->walls[43].y_min =    -500;  r->walls[43].y_max =       0;

    /* Wall 44 (avg Y: -250) */
    r->walls[44].x1 =    -750;  r->walls[44].z1 =     857;
    r->walls[44].x2 =    -750;  r->walls[44].z2 =    -857;
    r->walls[44].nx =    4096;  r->walls[44].nz =       0;
    r->walls[44].y_min =    -500;  r->walls[44].y_max =       0;

    /* Wall 45 (avg Y: -250) */
    r->walls[45].x1 =   -1332;  r->walls[45].z1 =    -857;
    r->walls[45].x2 =   -1332;  r->walls[45].z2 =     857;
    r->walls[45].nx =   -4096;  r->walls[45].nz =       0;
    r->walls[45].y_min =    -500;  r->walls[45].y_max =       0;

    /* Wall 46 (avg Y: -250) */
    r->walls[46].x1 =     750;  r->walls[46].z1 =    -857;
    r->walls[46].x2 =     750;  r->walls[46].z2 =     857;
    r->walls[46].nx =   -4096;  r->walls[46].nz =       0;
    r->walls[46].y_min =    -500;  r->walls[46].y_max =       0;

    /* Wall 47 (avg Y: -250) */
    r->walls[47].x1 =     750;  r->walls[47].z1 =     857;
    r->walls[47].x2 =    1322;  r->walls[47].z2 =     857;
    r->walls[47].nx =       0;  r->walls[47].nz =    4096;
    r->walls[47].y_min =    -500;  r->walls[47].y_max =       0;

    /* Wall 48 (avg Y: -250) */
    r->walls[48].x1 =    1322;  r->walls[48].z1 =    -857;
    r->walls[48].x2 =     750;  r->walls[48].z2 =    -857;
    r->walls[48].nx =       0;  r->walls[48].nz =   -4096;
    r->walls[48].y_min =    -500;  r->walls[48].y_max =       0;

    /* Wall 49 (avg Y: -250) */
    r->walls[49].x1 =    -750;  r->walls[49].z1 =    -857;
    r->walls[49].x2 =   -1332;  r->walls[49].z2 =    -857;
    r->walls[49].nx =       0;  r->walls[49].nz =   -4096;
    r->walls[49].y_min =    -500;  r->walls[49].y_max =       0;

    /* Wall 50 (avg Y: -250) */
    r->walls[50].x1 =   -1332;  r->walls[50].z1 =     857;
    r->walls[50].x2 =    -750;  r->walls[50].z2 =     857;
    r->walls[50].nx =       0;  r->walls[50].nz =    4096;
    r->walls[50].y_min =    -500;  r->walls[50].y_max =       0;

    /* Wall 51 (avg Y: -215) */
    r->walls[51].x1 =     750;  r->walls[51].z1 =    3850;
    r->walls[51].x2 =    -750;  r->walls[51].z2 =    3850;
    r->walls[51].nx =       0;  r->walls[51].nz =   -4096;
    r->walls[51].y_min =    -430;  r->walls[51].y_max =       0;

    /* Wall 52 (avg Y: -225) */
    r->walls[52].x1 =   -1343;  r->walls[52].z1 =    4150;
    r->walls[52].x2 =   -2234;  r->walls[52].z2 =    4353;
    r->walls[52].nx =    -912;  r->walls[52].nz =   -3993;
    r->walls[52].y_min =    -500;  r->walls[52].y_max =       0;

    /* Wall 53 (avg Y: -225) */
    r->walls[53].x1 =    2286;  r->walls[53].z1 =    4353;
    r->walls[53].x2 =    1364;  r->walls[53].z2 =    4150;
    r->walls[53].nx =     882;  r->walls[53].nz =   -3999;
    r->walls[53].y_min =    -500;  r->walls[53].y_max =       0;

    /* Wall 54 (avg Y: -250) */
    r->walls[54].x1 =   -2498;  r->walls[54].z1 =    -285;
    r->walls[54].x2 =   -1915;  r->walls[54].z2 =    -285;
    r->walls[54].nx =       0;  r->walls[54].nz =    4096;
    r->walls[54].y_min =    -500;  r->walls[54].y_max =       0;

    /* Wall 55 (avg Y: -249) */
    r->walls[55].x1 =   -4396;  r->walls[55].z1 =   -1449;
    r->walls[55].x2 =   -2498;  r->walls[55].z2 =   -1449;
    r->walls[55].nx =       0;  r->walls[55].nz =    4096;
    r->walls[55].y_min =    -499;  r->walls[55].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-750 to 750)  z(-2000 to 1714)
     * FLOOR   1: y=     0  x(750 to 1895)  z(857 to 1428)
     * FLOOR   2: y=     0  x(-1915 to -750)  z(857 to 1428)
     * FLOOR   3: y=     0  x(-1915 to -1332)  z(-857 to 857)
     * FLOOR   4: y=     0  x(-1915 to -750)  z(-1428 to -857)
     * FLOOR   5: y=     0  x(750 to 1895)  z(-1428 to -857)
     * FLOOR   6: y=     0  x(1322 to 1895)  z(-857 to 857)
     * FLOOR   7: y=     0  x(1895 to 2504)  z(-285 to 285)
     * FLOOR   8: y=     0  x(2504 to 4399)  z(-1414 to 1406)
     * FLOOR   9: y=     0  x(-2498 to -1915)  z(-285 to 285)
     * FLOOR   10: y=     0  x(-4396 to -2498)  z(-1449 to 1424)
     * FLOOR   11: y=     0  x(-3763 to -3131)  z(1424 to 3232)
     * FLOOR   12: y=     0  x(-3131 to -2234)  z(2649 to 3232)
     * FLOOR   13: y=     0  x(-2234 to 2286)  z(1714 to 4637)
     * FLOOR   14: y=     0  x(2286 to 3135)  z(2635 to 3217)
     * FLOOR   15: y=     0  x(3135 to 3767)  z(1406 to 3214)
     */
}
