/*
 * Auto-generated collision data from: Rear Gate mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef REAR_GATE_MESH_COLLISION_H
#define REAR_GATE_MESH_COLLISION_H

#include "collision.h"

#define REAR_GATE_WALL_COUNT  40
#define REAR_GATE_FLOOR_COUNT 13

void rear_gate_collision_init(CollisionRoom *r);

#endif /* REAR_GATE_MESH_COLLISION_H */
