/*
 * Auto-generated collision data from: Stables mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  16
 * Floors: 2
 * Bounds: X(-3400 to 100)  Z(-1600 to 1600)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Stables mesh_collision.h"

void stables_collision_init(CollisionRoom *r) {
    r->wall_count = STABLES_WALL_COUNT;
    r->min_x = -3400;
    r->max_x = 100;
    r->min_z = -1600;
    r->max_z = 1600;

    /* Wall 0 (avg Y: -300) */
    r->walls[0].x1 =   -2799;  r->walls[0].z1 =    1200;
    r->walls[0].x2 =    -700;  r->walls[0].z2 =    1200;
    r->walls[0].nx =       0;  r->walls[0].nz =    4096;
    r->walls[0].y_min =    -600;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -300) */
    r->walls[1].x1 =    -700;  r->walls[1].z1 =     400;
    r->walls[1].x2 =   -2799;  r->walls[1].z2 =     400;
    r->walls[1].nx =       0;  r->walls[1].nz =   -4096;
    r->walls[1].y_min =    -600;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -300) */
    r->walls[2].x1 =    -700;  r->walls[2].z1 =    1200;
    r->walls[2].x2 =    -700;  r->walls[2].z2 =     400;
    r->walls[2].nx =    4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -600;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -300) */
    r->walls[3].x1 =    -700;  r->walls[3].z1 =    -400;
    r->walls[3].x2 =    -700;  r->walls[3].z2 =   -1200;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -600;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -300) */
    r->walls[4].x1 =   -2799;  r->walls[4].z1 =   -1200;
    r->walls[4].x2 =   -2799;  r->walls[4].z2 =    -400;
    r->walls[4].nx =   -4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -600;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -300) */
    r->walls[5].x1 =   -2799;  r->walls[5].z1 =     400;
    r->walls[5].x2 =   -2799;  r->walls[5].z2 =    1200;
    r->walls[5].nx =   -4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -600;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -250) */
    r->walls[6].x1 =    -100;  r->walls[6].z1 =     400;
    r->walls[6].x2 =    -100;  r->walls[6].z2 =    1600;
    r->walls[6].nx =   -4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =    -500;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -250) */
    r->walls[7].x1 =   -3400;  r->walls[7].z1 =   -1600;
    r->walls[7].x2 =    -100;  r->walls[7].z2 =   -1600;
    r->walls[7].nx =       0;  r->walls[7].nz =    4096;
    r->walls[7].y_min =    -500;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -250) */
    r->walls[8].x1 =    -100;  r->walls[8].z1 =    1600;
    r->walls[8].x2 =   -3400;  r->walls[8].z2 =    1600;
    r->walls[8].nx =       0;  r->walls[8].nz =   -4096;
    r->walls[8].y_min =    -500;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -250) */
    r->walls[9].x1 =    -100;  r->walls[9].z1 =    -400;
    r->walls[9].x2 =     100;  r->walls[9].z2 =    -400;
    r->walls[9].nx =       0;  r->walls[9].nz =    4096;
    r->walls[9].y_min =    -500;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -250) */
    r->walls[10].x1 =     100;  r->walls[10].z1 =    -400;
    r->walls[10].x2 =     100;  r->walls[10].z2 =     400;
    r->walls[10].nx =   -4096;  r->walls[10].nz =       0;
    r->walls[10].y_min =    -500;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -250) */
    r->walls[11].x1 =    -100;  r->walls[11].z1 =   -1600;
    r->walls[11].x2 =    -100;  r->walls[11].z2 =    -400;
    r->walls[11].nx =   -4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -500;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -250) */
    r->walls[12].x1 =     100;  r->walls[12].z1 =     400;
    r->walls[12].x2 =    -100;  r->walls[12].z2 =     400;
    r->walls[12].nx =       0;  r->walls[12].nz =   -4096;
    r->walls[12].y_min =    -500;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -300) */
    r->walls[13].x1 =    -700;  r->walls[13].z1 =   -1200;
    r->walls[13].x2 =   -2799;  r->walls[13].z2 =   -1200;
    r->walls[13].nx =       0;  r->walls[13].nz =   -4096;
    r->walls[13].y_min =    -600;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -300) */
    r->walls[14].x1 =   -2799;  r->walls[14].z1 =    -400;
    r->walls[14].x2 =    -700;  r->walls[14].z2 =    -400;
    r->walls[14].nx =       0;  r->walls[14].nz =    4096;
    r->walls[14].y_min =    -600;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -250) */
    r->walls[15].x1 =   -3400;  r->walls[15].z1 =    1600;
    r->walls[15].x2 =   -3400;  r->walls[15].z2 =   -1600;
    r->walls[15].nx =    4096;  r->walls[15].nz =       0;
    r->walls[15].y_min =    -500;  r->walls[15].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-3400 to -100)  z(-1600 to 1600)
     * FLOOR   1: y=     0  x(-100 to 100)  z(-400 to 400)
     */
}
