/*
 * Auto-generated collision data from: Stables mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef STABLES_MESH_COLLISION_H
#define STABLES_MESH_COLLISION_H

#include "collision.h"

#define STABLES_WALL_COUNT  16
#define STABLES_FLOOR_COUNT 2

void stables_collision_init(CollisionRoom *r);

#endif /* STABLES_MESH_COLLISION_H */
