/*
 * Auto-generated collision data from: The Hatch mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef THE_HATCH_MESH_COLLISION_H
#define THE_HATCH_MESH_COLLISION_H

#include "collision.h"

#define THE_HATCH_WALL_COUNT  32
#define THE_HATCH_FLOOR_COUNT 8

void the_hatch_collision_init(CollisionRoom *r);

#endif /* THE_HATCH_MESH_COLLISION_H */
