#!/usr/bin/env python3
"""Convert textures/save_icon.png into the memory-card icon C data.

A PlayStation save block's icon is a 16x16 4bpp bitmap plus a 16-entry BGR555
palette. The palette lives in the block's title frame (offset 96); the bitmap is
the next frame. See src/savegame.c.

    py tools/gen_save_icon.py

Writes src/save_icon_data.h. Re-run whenever textures/save_icon.png changes.
"""

import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "textures", "save_icon.png")
DST = os.path.join(ROOT, "src", "save_icon_data.h")


def bgr555(r, g, b):
    """Pack 8-bit RGB into the PS1's 15-bit BGR word.

    Bit 15 is the semi-transparency flag; a fully zero word means "transparent"
    to the card manager, so opaque near-black has to carry that bit to survive
    as a visible pixel."""
    w = (b >> 3) << 10 | (g >> 3) << 5 | (r >> 3)
    return w if w else 0x8000


def main():
    im = Image.open(SRC)
    if im.size != (16, 16):
        sys.exit("save_icon.png must be 16x16, got %dx%d" % im.size)

    rgb = im.convert("RGB")
    # Median-cut to 15 colours: index 0 is reserved for transparency, so any
    # pixel the source marks transparent lands there and the picture itself
    # never uses it.
    quant = rgb.quantize(colors=15, method=Image.Quantize.MEDIANCUT)
    pal = quant.getpalette()[: 15 * 3]
    idx = list(quant.getdata())

    alpha = im.convert("RGBA").split()[3]
    trans = [p < 128 for p in alpha.getdata()]

    # 15-bit colour is coarse enough that median cut hands back near-duplicate
    # entries (the PNG's four flat colours plus resampling noise). Fold those
    # together so the CLUT reads as the handful of colours the icon really uses.
    clut = [0x0000]
    remap = {}
    for i in range(15):
        c = bgr555(pal[i * 3], pal[i * 3 + 1], pal[i * 3 + 2])
        if c not in clut:
            clut.append(c)
        remap[i] = clut.index(c)
    clut += [0x0000] * (16 - len(clut))

    # Two pixels per byte, low nibble = left pixel.
    pix = []
    for y in range(16):
        for x in range(0, 16, 2):
            lo = 0 if trans[y * 16 + x] else remap[idx[y * 16 + x]]
            hi = 0 if trans[y * 16 + x + 1] else remap[idx[y * 16 + x + 1]]
            pix.append((hi << 4) | lo)

    with open(DST, "w") as f:
        f.write("/* Generated by tools/gen_save_icon.py from textures/save_icon.png.\n")
        f.write("   Do not edit by hand: edit the PNG and re-run the script. */\n")
        f.write("#ifndef SAVE_ICON_DATA_H\n#define SAVE_ICON_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("/* 16-entry BGR555 palette; entry 0 is transparent. */\n")
        f.write("static const uint16_t save_icon_clut[16] = {\n")
        for i in range(0, 16, 8):
            f.write("    " + ", ".join("0x%04X" % c for c in clut[i : i + 8]) + ",\n")
        f.write("};\n\n")
        f.write("/* 16x16 4bpp bitmap, two pixels per byte, low nibble = left. */\n")
        f.write("static const uint8_t save_icon_pixels[128] = {\n")
        for i in range(0, 128, 16):
            f.write("    " + ", ".join("0x%02X" % p for p in pix[i : i + 16]) + ",\n")
        f.write("};\n\n#endif\n")

    used = len([c for c in clut[1:] if c]) + 1
    print("wrote %s (%d palette entries used)" % (DST, used))


if __name__ == "__main__":
    main()
