#!/usr/bin/env python3
"""
gen_room_arena.py - size the room geometry arena from the actual room meshes.

WHY THIS EXISTS
---------------
Room geometry used to be loaded at startup and kept resident for the whole run:
fourteen malloc'd SMD buffers, roughly 490 KB of a ~1.5 MB heap, thirteen of
which were rooms the player was not standing in. src/room_arena.c replaces them
with ONE buffer that the incoming room is read into on each transition.

That buffer has to be big enough for the largest room on the disc, and "big
enough" is not a number anyone should be maintaining by hand - add one detailed
room and a stale constant turns into a silent overflow. So it is computed here,
from the same disc.xml the game reads its files out of.

REGENERATE WHENEVER A ROOM MESH CHANGES SIZE:

    py tools/gen_room_arena.py

Forgetting to is not fatal: room_arena_load() checks the incoming file against
the arena at runtime and refuses to read a mesh that does not fit, so the room
renders empty instead of scribbling over the heap. But it IS a bug, and an
obvious one on screen.

WHAT IT MEASURES
----------------
Every .smd on the disc, not just the fourteen rooms. Props are an order of
magnitude smaller so they never set the maximum, and including them means a
prop promoted to a streamed room later cannot catch this script out.

The figure is in SECTORS, rounded up, because CdRead transfers whole 2048-byte
sectors and will write all of the last one.
"""
import os
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
DISC = os.path.join(ROOT, "disc.xml")
OUT = os.path.join(ROOT, "src", "room_arena_size.h")


def collect_smds():
    tree = ET.parse(DISC)
    out = []

    def walk(node, prefix):
        for child in node:
            if child.tag == "dir":
                walk(child, prefix + "\\" + child.get("name"))
            elif child.tag == "file":
                name = child.get("name")
                if name.upper().endswith(".SMD"):
                    out.append((prefix + "\\" + name, child.get("source")))

    walk(tree.find(".//directory_tree"), "")
    return out


def main():
    entries = collect_smds()
    if not entries:
        sys.exit("gen_room_arena.py: no .smd files found in disc.xml")

    rows = []
    for disc_path, source in entries:
        if not os.path.isfile(source):
            sys.exit("gen_room_arena.py: %s missing (disc.xml says %s)"
                     % (source, disc_path))
        size = os.path.getsize(source)
        rows.append(((size + 2047) // 2048, size, disc_path,
                     os.path.basename(source)))

    rows.sort(reverse=True)
    max_sectors = rows[0][0]

    with open(OUT, "w", newline="\n") as f:
        f.write("""/* room_arena_size.h - GENERATED by tools/gen_room_arena.py. DO NOT EDIT.
 *
 * How big the single room-geometry buffer in src/room_arena.c has to be: the
 * largest .smd on the disc, rounded up to whole 2048-byte CD sectors.
 *
 * REGENERATE WHENEVER A ROOM MESH CHANGES SIZE:
 *     py tools/gen_room_arena.py
 *
 * A stale value here is caught at runtime - room_arena_load() refuses a mesh
 * that does not fit and the room draws empty - but fix it here, not there.
 *
 * The ten largest meshes on the disc at generation time:
 *
""")
        for sectors, size, disc_path, base in rows[:10]:
            f.write(" *   %7d bytes  %3d sectors  %s\n" % (size, sectors, base))
        f.write(""" *
 */
#ifndef ROOM_ARENA_SIZE_H
#define ROOM_ARENA_SIZE_H

#define ROOM_ARENA_SECTORS %d
#define ROOM_ARENA_BYTES   (ROOM_ARENA_SECTORS * 2048)

#endif /* ROOM_ARENA_SIZE_H */
""" % max_sectors)

    print("gen_room_arena.py: wrote %s" % OUT)
    print("  largest mesh: %s (%d bytes, %d sectors)"
          % (rows[0][3], rows[0][1], max_sectors))
    print("  arena: %d bytes (%.1f KB)"
          % (max_sectors * 2048, max_sectors * 2048 / 1024))
    resident = sum(s * 2048 for s, _, p, _ in rows
                   if s * 2048 > 16 * 1024)  # rooms, not props
    print("  replaces ~%.0f KB of permanently resident room buffers"
          % (resident / 1024))


if __name__ == "__main__":
    main()
