"""Merge Asag's arena collision out of THREE meshes into one CollisionRoom.

    py assets/smx_to_collision.py "assets/garden/asag/Asag_Arena mesh.smx"      --room asag_arena
    py assets/smx_to_collision.py "assets/garden/asag/Asag_Left_Tentacle.smx"   --room asag_tent_l
    py assets/smx_to_collision.py "assets/garden/asag/Asag_Right_Tentacle.smx"  --room asag_tent_r
    py tools/gen_asag_arena_collision.py

WHY A MERGE STEP EXISTS HERE AND NOWHERE ELSE IN THE GAME. Every other room's
collision is one proxy mesh through smx_to_collision.py, copied into src/. This
room is three, because two of the three are parts of the BOSS rather than parts
of the room:

  Asag_Arena mesh.smx    the room proxy - perimeter, and the alcove the head
                         sits in
  Asag_Left_Tentacle     the tentacle's OWN geometry, at the user's request:
  Asag_Right_Tentacle    the two arms lie along the arena's side walls and the
                         player must not walk through them

>>> THE TENTACLE WALLS ARE STATIC AND THE TENTACLES ARE NOT. <<< They are baked
from frame 1 of Tentacle_Idle, where each arm lies low along its wall (y span
[-204,-4], about 200 tall). The attack clip rears them up through 1464 units of
travel, and NONE of that moves these walls. That is the right trade while the
fight does not exist yet - the player cannot walk through the resting arms, which
is what was asked for - but when the encounter animates them, either accept that
the collision is the resting silhouette or replace these walls with a runtime
capsule the way rabisus_collide() does. Do not try to re-bake walls per frame:
CollisionRoom is a fixed table read by every movement query in the frame.

The generator's output is not hand-editable, so the two edits the runbook says
smx_to_collision.py never emits are applied HERE instead:
  - the lowercase #include (src/ filenames are lowercase)
  - r->multi_level and r->shoot_over_mask, both 0 and both argued for below
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, "assets", "garden", "asag")
OUT_C = os.path.join(ROOT, "src", "asag_arena_mesh_collision.c")
OUT_H = os.path.join(ROOT, "src", "asag_arena_mesh_collision.h")

SOURCES = [
    ("Asag_Arena mesh_collision.c",         "the room proxy: perimeter + head alcove"),
    ("Asag_Left_Tentacle_collision.c",      "the left arm, resting (Tentacle_Idle frame 1)"),
    ("Asag_Right_Tentacle_collision.c",     "the right arm, resting (Tentacle_Idle frame 1)"),
]

WALL_RE = re.compile(
    r"r->walls\[\d+\]\.x1 =\s*(-?\d+);\s*r->walls\[\d+\]\.z1 =\s*(-?\d+);\s*"
    r"r->walls\[\d+\]\.x2 =\s*(-?\d+);\s*r->walls\[\d+\]\.z2 =\s*(-?\d+);\s*"
    r"r->walls\[\d+\]\.nx =\s*(-?\d+);\s*r->walls\[\d+\]\.nz =\s*(-?\d+);\s*"
    r"r->walls\[\d+\]\.y_min =\s*(-?\d+);\s*r->walls\[\d+\]\.y_max =\s*(-?\d+);")

FLOOR_RE = re.compile(
    r"FLOOR\s+\d+: y=\s*(-?\d+)\s+x\((-?\d+) to (-?\d+)\)\s+z\((-?\d+) to (-?\d+)\)")


def main():
    walls, floors, groups = [], [], []
    for fname, what in SOURCES:
        text = open(os.path.join(GEN, fname), encoding="utf-8").read()
        w = WALL_RE.findall(text)
        first = len(walls)
        walls += [(tuple(int(v) for v in m), what) for m in w]
        groups.append((what, first, len(w)))
        if "Arena mesh" in fname:
            floors = [tuple(int(v) for v in m) for m in FLOOR_RE.findall(text)]

    xs = [w[0][0] for w in walls] + [w[0][2] for w in walls]
    zs = [w[0][1] for w in walls] + [w[0][3] for w in walls]

    h = ['#ifndef ASAG_ARENA_MESH_COLLISION_H',
         '#define ASAG_ARENA_MESH_COLLISION_H',
         '',
         '#include "collision.h"',
         '',
         '/* GENERATED by tools/gen_asag_arena_collision.py - do not hand-edit.',
         '   See that script for what the three source meshes are and for why the',
         '   tentacle walls do not follow the tentacle animation. */',
         '']
    for what, first, n in groups:
        h.append('/* walls %3d..%-3d  %s */' % (first, first + n - 1, what))
    h += ['',
          '#define ASAG_ARENA_WALL_COUNT  %d' % len(walls),
          '#define ASAG_ARENA_FLOOR_COUNT %d' % len(floors),
          '',
          'void asag_arena_collision_init(CollisionRoom *r);',
          '',
          '#endif /* ASAG_ARENA_MESH_COLLISION_H */',
          '']
    open(OUT_H, "w", encoding="utf-8", newline="\n").write("\n".join(h))

    c = ['/*',
         ' * GENERATED by tools/gen_asag_arena_collision.py - do not hand-edit.',
         ' *',
         ' * Merged from three meshes (see the generator for the argument):']
    for what, first, n in groups:
        c.append(' *   walls %3d..%-3d  %s' % (first, first + n - 1, what))
    c += [' *',
          ' * Walls:  %d   (MAX_WALLS_PER_ROOM is 128)' % len(walls),
          ' * Floors: %d' % len(floors),
          ' * Bounds: X(%d to %d)  Z(%d to %d)' % (min(xs), max(xs), min(zs), max(zs)),
          ' * Normal scale: 4096 = 1.0 (fixed point)',
          ' */',
          '',
          '#include "asag_arena_mesh_collision.h"',
          '',
          'void asag_arena_collision_init(CollisionRoom *r) {',
          '    r->wall_count = ASAG_ARENA_WALL_COUNT;',
          '    r->min_x = %d;' % min(xs),
          '    r->max_x = %d;' % max(xs),
          '    r->min_z = %d;' % min(zs),
          '    r->max_z = %d;' % max(zs),
          '',
          '    /* SINGLE LEVEL. Both floor planes the proxy carries are at y=0 - the',
          '       arena floor and the head alcove\'s - so there is one walkable height',
          '       and asag_arena_floor_zones_init() describes it with two flat zones.',
          '       A terrace, a step or a pit in a later mesh needs this set AND one',
          '       floor zone per level. */',
          '    r->multi_level = 0;',
          '',
          '    /* NO SHORT-WALL EXEMPTION, and that is a measurement, not an oversight.',
          '       collision_shoot_over_short_walls() exists so a projectile is not eaten',
          '       by a knee-high lip. The shortest wall here is the head alcove\'s side',
          '       at 550 tall, which is chest height on a 900-unit room and is meant to',
          '       stop a shot; the tentacles are 200 tall but the player is supposed to',
          '       be unable to shoot THROUGH an arm at floor level either. Nothing here',
          '       is decorative, so nothing is exempt. If the finished fight wants shots',
          '       to clear the resting arms, the call goes in asag_arena_init() AFTER',
          '       this function, which zeroes the mask. */',
          '    r->shoot_over_mask = 0;',
          '']
    for i, (w, what) in enumerate(walls):
        x1, z1, x2, z2, nx, nz, ymin, ymax = w
        c += ['    /* Wall %d - %s */' % (i, what),
              '    r->walls[%d].x1 = %6d;  r->walls[%d].z1 = %6d;' % (i, x1, i, z1),
              '    r->walls[%d].x2 = %6d;  r->walls[%d].z2 = %6d;' % (i, x2, i, z2),
              '    r->walls[%d].nx = %6d;  r->walls[%d].nz = %6d;' % (i, nx, i, nz),
              '    r->walls[%d].y_min = %6d;  r->walls[%d].y_max = %6d;' % (i, ymin, i, ymax),
              '']
    c += ['    /*',
          '     * Floor planes from the room proxy. These are what',
          '     * asag_arena_floor_zones_init() in src/asag_arena.c mirrors.',
          '     *']
    for i, f in enumerate(floors):
        c.append('     * FLOOR %d: y=%d  x(%d to %d)  z(%d to %d)' % (i, f[0], f[1], f[2], f[3], f[4]))
    c += ['     */', '}', '']
    open(OUT_C, "w", encoding="utf-8", newline="\n").write("\n".join(c))

    print("walls %d, floors %d" % (len(walls), len(floors)))
    for what, first, n in groups:
        print("  %3d..%-3d  %s" % (first, first + n - 1, what))
    for i, f in enumerate(floors):
        print("  FLOOR %d: y=%d x(%d..%d) z(%d..%d)" % (i, f[0], f[1], f[2], f[3], f[4]))
    print("wrote %s" % OUT_C)
    print("wrote %s" % OUT_H)


main()
