#!/usr/bin/env python3
"""
vram_map.py - authoritative VRAM occupancy map for the PS1 horror game.

VRAM is 1024x512 16-bit words. It is the game's tightest resource (see
tools/TEXTURING_NOTES.txt). This script is the SINGLE SOURCE OF TRUTH for what
lives where: it reads the real rects out of every textures/*.tim, adds the fixed
regions (framebuffers, font, CLUT band), detects overlaps, and prints a sorted
map. Regenerate tools/VRAM_MAP.txt after adding/moving any texture:

    python tools/vram_map.py > tools/VRAM_MAP.txt

KEY COLUMN FOR RENDERING BUGS: "Voff" = the texture's y within its 256-tall
tpage (VRAM y % 256). A texture with Voff >= 128 drawn while a 128x128 texture
window is active gets its V wrapped mod-128 and samples the WRONG region (this
was the crucifaxe menu-icon bug). Such textures must be drawn with the window
reset/adjusted (see tools/TEXTURING_NOTES.txt, PART on texture windows).

OVERLAPS are NOT necessarily bugs: several slots are intentionally time-shared
via texture streaming (e.g. reception uploads strs/bnnstr/frnt_dr over the
kitchen's stn_stl/kchn_tile/red_crpt, and the dresser prop streams over kchn_wl
while in reception). Those pairs are listed under "time-shared".
"""
import struct, glob, os

TEXDIR = os.path.join(os.path.dirname(__file__), "..", "textures")

# Slots that are deliberately time-shared by streaming (physical, logical-a, logical-b).
# The map flags overlaps between these as expected rather than a collision.
KNOWN_STREAM_PAIRS = [
    ("stn_stl.tim",  "strs.tim"),      # reception streams strs over stn_stl
    ("red_crpt.tim", "frnt_dr.tim"),   # reception streams frnt_dr over red_crpt
    ("kchn_wl.tim",  "dresser.tim"),   # dresser prop streams over kchn_wl in reception
    ("stove.tim",    "prpl_wlppr.tim"),# piano room streams prpl_wlppr over stove
    ("stn_stl.tim",  "bookshelf.tim"), # piano room streams bookshelf over stn_stl...
    ("strs.tim",     "bookshelf.tim"), # ...which reception also time-shares (strs)
    ("kchn_tile.tim","piano_keys.tim"),# piano room streams piano_keys over kchn_tile
    ("kchn_tile.tim","cncrte.tim"),    # conservatory concrete props stream cncrte over kchn_tile
    ("piano_keys.tim","cncrte.tim"),   # ...same slot the piano room uses for piano_keys
    ("key.tim",      "cppr_pt.tim"),   # copper pot time-shares the (spent) key slot
    ("gravel_texture.tim", "trees.tim"),   # conservatory streams over delivery slots...
    ("rusty_fence.tim",    "upstairs.tim"),
    ("brick_wall.tim",     "grss.tim"),
    ("double_door.tim",    "con_tile.tim"),# ...double_door is kitchen+delivery
]

def read_tim(path):
    with open(path, "rb") as f: d = f.read()
    if d[0] != 0x10: return None
    flags = struct.unpack("<I", d[4:8])[0]
    bpp = {0: 4, 1: 8, 2: 16, 3: 16}[flags & 3]
    off = 8; clut = None
    if flags & 8:
        bs = struct.unpack("<I", d[off:off+4])[0]
        cx, cy, cw, ch = struct.unpack("<HHHH", d[off+4:off+12]); clut = (cx, cy, cw, ch); off += bs
    bs = struct.unpack("<I", d[off:off+4])[0]
    px, py, pw, ph = struct.unpack("<HHHH", d[off+4:off+12])   # pw = VRAM columns
    return {"bpp": bpp, "x": px, "y": py, "cols": pw,
            "wpx": pw * (16 // bpp), "h": ph, "clut": clut}

def rects_overlap(a, b):
    ax, ay, aw, ah = a; bx, by, bw, bh = b
    return not (ax+aw <= bx or bx+bw <= ax or ay+ah <= by or by+bh <= ay)

tims = {}
for p in sorted(glob.glob(os.path.join(TEXDIR, "*.tim"))):
    r = read_tim(p)
    if r: tims[os.path.basename(p)] = r

print("=" * 78)
print(" VRAM MAP  (1024 x 512 16-bit words)   generated by tools/vram_map.py")
print("=" * 78)
print(__doc__.strip().split("\n\n", 1)[1])   # print the explanatory prose
print()
print("FIXED REGIONS")
print("  Framebuffers : x[0,320)   y[0,480)   (two 320x240 buffers stacked)")
print("  Font (FntLoad): x[960,1024) y[0,256)  approx")
print("  CLUT band    : x[0,256)   y[480,512)  (256-word CLUTs, 1 line each)")
print()

# Texture pixel slots, sorted by (y, x).
hdr = "  %-20s %-5s %5s %5s %5s %5s %5s   %s" % (
    "texture", "bpp", "x", "y", "wpx", "h", "Voff", "clut(x,y)")
print("TEXTURE PIXEL SLOTS  (Voff = y %% 256; Voff>=128 is window-sensitive)")
print(hdr)
print("  " + "-" * 74)
for name, r in sorted(tims.items(), key=lambda kv: (kv[1]["y"], kv[1]["x"])):
    voff = r["y"] % 256
    warn = "  <-- Voff>=128" if voff >= 128 else ""
    clut = "%d,%d" % (r["clut"][0], r["clut"][1]) if r["clut"] else "-"
    print("  %-20s %-5d %5d %5d %5d %5d %5d   %s%s" %
          (name, r["bpp"], r["x"], r["y"], r["wpx"], r["h"], voff, clut, warn))
print()

# CLUT slots, sorted by y.
print("CLUT SLOTS  (8bpp = 256 words wide, 4bpp = 16)")
for name, r in sorted(tims.items(), key=lambda kv: (kv[1]["clut"][1] if kv[1]["clut"] else 0)):
    if not r["clut"]: continue
    cx, cy, cw, ch = r["clut"]
    print("  y=%-4d x[%d,%d)  %s" % (cy, cx, cx + cw, name))
print()

# Overlap detection.
print("OVERLAP CHECK")
def pair_is_known(a, b):
    for x, y in KNOWN_STREAM_PAIRS:
        if {a, b} == {x, y}: return True
    return False
names = list(tims.keys())
unexpected = []
for i in range(len(names)):
    for j in range(i+1, len(names)):
        a, b = names[i], names[j]
        ra, rb = tims[a], tims[b]
        ta = (ra["x"], ra["y"], ra["cols"], ra["h"])
        tb = (rb["x"], rb["y"], rb["cols"], rb["h"])
        if rects_overlap(ta, tb):
            tag = "time-shared (streaming)" if pair_is_known(a, b) else "!! UNEXPECTED COLLISION"
            print("  %-40s %-20s %s" % (a, b, tag))
            if not pair_is_known(a, b): unexpected.append((a, b))
if not unexpected:
    print("  No unexpected pixel collisions.")
print()
print("Regenerate with:  python tools/vram_map.py > tools/VRAM_MAP.txt")
