#ifndef ASAG_ARENA_H
#define ASAG_ARENA_H

#include <stdint.h>
#include "render.h"

/* =========================================================================
   ASAG'S ARENA — the room at the bottom of The Hatch's shaft.
   =========================================================================
   THE ROOM IS BUILT. Mesh, two textures, collision and the boss's one animated
   body are all in, and src/asag_boss.c cycles its six clips on a loop so they
   can be looked at. What is still missing is the FIGHT — no phases, no attacks,
   no camera, no sounds, no music, and NO WAY OUT. Every system the encounter
   needs was wired and budgeted before any of it existed, so what is left is a
   real director module and not an architecture change.

   >>> READ tools/ADDING_THE_ASAG_FIGHT.txt BEFORE PUTTING ANYTHING IN IT. <<<
   That file is the handover: what is reserved, what it cost, and the exact
   order the pieces go in.

   ---- HOW IT IS REACHED, AND WHY THAT MATTERS MORE THAN IT LOOKS ------------
   ONE WAY IN: the 1200-unit drop down the pit in The Hatch's yard, after both
   keyholes are turned (src/hatch_puzzle.c). >>> AND, FOR NOW, NO WAY OUT AT
   ALL. <<< The previous arena had a placeholder exit at the shaft mouth that
   gated back up into The Hatch, which the fiction never supported; this mesh
   has no door in it and where the room actually leads has not been decided, so
   rather than ship a lie the exit is GONE — no prompt, no trigger, no
   destination. The only ways out of the room today are the debug level select
   and dying.

   That is a deliberate hole and not an oversight, but it does mean a save made
   before the drop is the only route back into the rest of the game.

   That shape is not decoration — it is what makes every budget in this file
   legal. Nothing else in the game is ever drawn, heard or updated while the
   player is down here, and the player cannot arrive from anywhere else, so:

     - VRAM: everything except the player's own kit may be overwritten, because
       nothing that is clobbered can be seen again until the player leaves
       through a transition that puts it back. See tools/VRAM_MAP_ASAG.txt.
     - SPU: the room takes a bank of its own (SND_BANK_ASAG) holding NOTHING
       shared, because every monster in the game is somewhere else. That hands
       the fight the entire 232 KB bank region — the largest sound budget any
       room in this game has ever had. See src/sound.h.
     - HEAP: the room registers nothing with texmgr and keeps no RAM copy of
       anything, so it costs ZERO permanent bytes. See the texture note below.

   A one-way drop also means there is no "walk back out mid-fight" case to
   handle, and no re-entry replay of the reveal: the only exits are winning and
   dying. There is deliberately NO SAVE POINT here, which is what makes that
   true rather than wishful (tools/ADDING_A_BOSS_ENCOUNTER.txt STEP 9).

   ---- THE GEOMETRY ---------------------------------------------------------
   Own coordinate space, like every garden room. \TEXASAG\ASAGARNA.SMD,
   exported from "assets/bosses/Asag Version Two/Asag Version Two_Arena.smx":
   522 TEXTURED primitives over x[-1500,1500] z[0,2900], floor y=0, perimeter
   walls to y=-1000 and detail up to y=-1534. It is read into the shared room
   arena on entry and drawn by this module's own loop, which is chain_room.c's.

   COLLISION FOLLOWS IT, and follows the BOSS too:
   src/asag_arena_mesh_collision.c is generated by
   tools/gen_asag_arena_collision.py out of TWO meshes — a low-poly room proxy
   (12 walls, 3 floor planes) plus the boss's OWN DRAWN GEOMETRY (26 walls),
   because this boss has no separate collision proxy. 38 walls against a cap of
   128.

   >>> NONE OF THE BOSS'S 26 WALLS CAN FIRE AT REST, AND THAT IS CORRECT. <<<
   The body hangs at y[-960,-528], so its lowest point is 528 above the floor
   and 342 above the player's eye, and collision.c's vertical gate rejects every
   one of them. They are generated anyway because they cost 26 rows in a table
   with 90 spare and they become the right answer the instant the art comes down
   — which is the point of deriving collision from the drawn mesh. See the head
   of the generator.

   THE ROOM IS A SEALED PIT WITH A RECESS AT EACH END, both floored at y=0 and
   both narrower than the middle (x[-1300,1300] against x[-1500,1500]). There is
   no door in the mesh anywhere.

   The player lands in the NORTH recess (low z) and faces +Z, straight down the
   arena at Asag.

   ---- THE TEXTURES: STREAMED, NOT RESIDENT. THIS IS NOT OPTIONAL. -----------
   texmgr keeps the WHOLE TIM in main RAM for the life of the run, and main RAM
   is the budget this project is closest to breaking — the MEASURED boot cliff is
   between 233 and 235 KB of free-at-rest, and the failure there is not a tidy
   malloc error, it is the stack being handed out and the next CdRead DMAing over
   a return address in some unrelated function. When this room was built
   free-at-rest was 245 KB, and six 8bpp 128x128 registrations would have been
   ~110 KB: it would not have booted.

   >>> AND WHAT HEADROOM THERE IS, IS ALREADY SPOKEN FOR. <<< It came from
   making the BOSS MODEL room-scoped rather than resident (PART 6 of
   tools/ADDING_THE_ASAG_FIGHT.txt), and it pays for Asag's own mesh and six
   animation clips, which at 139 KB sector-rounded are far larger than its
   textures. Streaming the art costs a few hundred milliseconds on ONE loading
   screen and nothing at all at rest, so there is no reason to spend permanent
   bytes on it whatever the figure says.

   So this room reads its own art off the disc on the transition into it, into
   ONE scratch buffer that is freed again: the Greenhouse's shape
   (src/greenhouse.c), by way of the Chain Room's. Zero permanent bytes, against
   a few hundred milliseconds of drive time behind a door fade that already
   makes two other bracketed reads.

   >>> AND UNLIKE THOSE TWO, THE tpage/clut ARE CAPTURED AT READ TIME. <<< The
   Greenhouse and the Chain Room take theirs as compile-time constants out of
   src/tim_slots.h, which is generated from the TIMs listed in disc.xml — so a
   texture that does not exist yet cannot have a constant. Capturing from
   GetTimInfo instead costs two stores per texture on one loading screen and
   means a new TIM can be added to ASAG_TEX below and to disc.xml with NO
   generator run and no header regeneration. Swap to TIM_SLOT() if that ever
   matters; it will not.

   ---- WHAT IS STILL MISSING (all of it is the FIGHT) ------------------------
     - the encounter           src/asag_boss.c is a DEMO: it cycles the six
                               clips end to end and decides nothing. No health,
                               no phases, no attacks, no camera, no seal, no
                               death. tools/ADDING_A_BOSS_ENCOUNTER.txt.
     - the exit                there is NO WAY OUT of this room. Where it leads
                               and the geometry of the way out are both
                               undecided — see HOW IT IS REACHED above.
     - the music               CDAUDIO_ASAG_TRACK is defined; track 9 is not
                               yet on the disc
     - the sounds              SND_BANK_ASAG exists and is EMPTY
   ========================================================================= */

/* How many texture slots the room's draw can address. Sized, not measured: the
   biggest textured room in the game (the Greenhouse) uses eleven, and a boss
   arena should be simpler than a greenhouse, not richer. Raising it costs one
   pair of uint16_t in BSS per slot and nothing else — but every slot filled
   costs real VRAM, so check tools/VRAM_MAP_ASAG.txt before spending one. */
#define ASAG_ARENA_TEX_COUNT 12

/* ---- The streamed texture slots -------------------------------------------
   The row order of stream_tex_file[] in the .c, and the slot numbers
   gen_asag_arena_tex_map.py's NAME_TO_SLOT writes into the per-poly map. The
   two names above the line are the ROOM's; the one below is ASAG'S SKIN,
   streamed here rather than registered by src/asag.c.

   >>> THE BOSS'S SKIN LIVES IN THE ROOM'S TABLE ON PURPOSE. <<< texmgr keeps
   the whole TIM in main RAM for the life of the run, so a registration would be
   ~17 KB permanent for art that can only be seen in one room reached by a
   one-way drop. This room already makes a bracketed CD read on the only
   transition that gets here, and one more TIM on it costs nothing at rest.

   >>> ALL THREE ARE 128x128 BECAUSE THE SMX SAYS SO, NOT BECAUSE THE ENGINE
   INSISTS ON IT. <<< The source art is three different sizes (asag 128, Boss
   wall 256, mud 64), but io_export_smx_v3.py normalises every UV in an export
   to exp_tex_size=128 regardless of the image it came from, and the arena's own
   UVs prove it: mud runs u[10..147] and Boss Wall u[7..117], both addressed
   over a 128-texel tile. Ship mud at its native 64 and UV 127 reads off its
   right edge into whatever sits next in VRAM; ship Boss Wall at 256 and only
   its top-left quarter is ever sampled. tools/TEXTURING_NOTES.txt PART 5 spells
   this out, and records that the one 256x256 attempt in this game — the
   Greenhouse's cuniform pipes — was reverted. */
#define ASAG_TEX_MUD    0    /* the arena floor and its mud banks   */
#define ASAG_TEX_WALL   1    /* "Boss Wall", the perimeter          */
#define ASAG_TEX_SKIN   2    /* Asag's own skin                     */

/* Read back what the entry-time stream captured from each TIM. Returns 0 for a
   slot that never loaded, which draws in whatever art sits at tpage 0 rather
   than crashing — the same fallback a failed texmgr registration has. */
uint16_t asag_arena_tex_page(int slot);
uint16_t asag_arena_tex_clut(int slot);

/* ---- The room's view constants, shared with src/asag.c ---------------------
   The boss fogs with the room's own near/far (g_fog_near/g_fog_far, set by the
   room's draw) toward the room's own clear colour, and is rejected at the same
   distance. Sharing the literals is what keeps the boss fading INTO the arena
   rather than alongside it. */
#define ASAG_CULL_DIST  7000
#define ASAG_FOG_R         6
#define ASAG_FOG_G         4
#define ASAG_FOG_B        10

void asag_arena_load_assets(void);     /* startup: nothing. See the .c.        */
void asag_arena_load_geometry(void);   /* ROOM ENTRY: mesh -> the shared arena */
void asag_arena_upload_textures(void); /* ROOM ENTRY: stream this room's TIMs  */
void asag_arena_init(void);            /* collision, floor zones, spawn        */
void asag_arena_draw(RenderContext *ctx);

/* The one arrival: dropped down the shaft from The Hatch, facing +Z. */
void asag_arena_spawn_shaft(void);

/* >>> THERE IS NO EXIT, AND SO THERE IS NO EXIT API. <<< The previous arena
   declared asag_arena_exit_arm(), _triggered() and _sealed() against a prompt
   standing at the shaft mouth, offering to climb a shaft the fiction says
   cannot be climbed, with main.c's destination for it flagged as a placeholder
   in as many words. All of it is gone rather than left switched off, because a
   switched-off door is a thing the next reader has to work out the status of.

   WHEN THE WAY OUT IS DECIDED, the three come back together and the encounter's
   seal predicate goes in _sealed() — that one function is the only place it
   belongs, so main.c's trigger test and the floating sign cannot disagree about
   whether the door is offering something it will not do. The exact shape,
   including why the re-arm has to happen on the frame the seal LIFTS, is
   tools/ADDING_A_BOSS_ENCOUNTER.txt STEP 9. */

#endif /* ASAG_ARENA_H */
