#ifndef ASAG_ARENA_MESH_COLLISION_H
#define ASAG_ARENA_MESH_COLLISION_H

#include "collision.h"

/* GENERATED by tools/gen_asag_arena_collision.py - do not hand-edit.
   See that script for what the three source meshes are and for why the
   tentacle walls do not follow the tentacle animation. */

/* walls   0..7    the room proxy: perimeter + head alcove */
/* walls   8..27   the left arm, resting (Tentacle_Idle frame 1) */
/* walls  28..47   the right arm, resting (Tentacle_Idle frame 1) */

#define ASAG_ARENA_WALL_COUNT  48
#define ASAG_ARENA_FLOOR_COUNT 2

void asag_arena_collision_init(CollisionRoom *r);

#endif /* ASAG_ARENA_MESH_COLLISION_H */
