/*
 * GENERATED by tools/gen_asag_arena_collision.py - do not hand-edit.
 *
 * Merged from three meshes (see the generator for the argument):
 *   walls   0..7    the room proxy: perimeter + head alcove
 *   walls   8..27   the left arm, resting (Tentacle_Idle frame 1)
 *   walls  28..47   the right arm, resting (Tentacle_Idle frame 1)
 *
 * Walls:  48   (MAX_WALLS_PER_ROOM is 128)
 * Floors: 2
 * Bounds: X(-1500 to 1500)  Z(0 to 3248)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "asag_arena_mesh_collision.h"

void asag_arena_collision_init(CollisionRoom *r) {
    r->wall_count = ASAG_ARENA_WALL_COUNT;
    r->min_x = -1500;
    r->max_x = 1500;
    r->min_z = 0;
    r->max_z = 3248;

    /* SINGLE LEVEL. Both floor planes the proxy carries are at y=0 - the
       arena floor and the head alcove's - so there is one walkable height
       and asag_arena_floor_zones_init() describes it with two flat zones.
       A terrace, a step or a pit in a later mesh needs this set AND one
       floor zone per level. */
    r->multi_level = 0;

    /* NO SHORT-WALL EXEMPTION, and that is a measurement, not an oversight.
       collision_shoot_over_short_walls() exists so a projectile is not eaten
       by a knee-high lip. The shortest wall here is the head alcove's side
       at 550 tall, which is chest height on a 900-unit room and is meant to
       stop a shot; the tentacles are 200 tall but the player is supposed to
       be unable to shoot THROUGH an arm at floor level either. Nothing here
       is decorative, so nothing is exempt. If the finished fight wants shots
       to clear the resting arms, the call goes in asag_arena_init() AFTER
       this function, which zeroes the mask. */
    r->shoot_over_mask = 0;

    /* Wall 0 - the room proxy: perimeter + head alcove */
    r->walls[0].x1 =  -1500;  r->walls[0].z1 =   2613;
    r->walls[0].x2 =  -1500;  r->walls[0].z2 =      0;
    r->walls[0].nx =   4096;  r->walls[0].nz =      0;
    r->walls[0].y_min =  -1000;  r->walls[0].y_max =      0;

    /* Wall 1 - the room proxy: perimeter + head alcove */
    r->walls[1].x1 =  -1500;  r->walls[1].z1 =      0;
    r->walls[1].x2 =   1500;  r->walls[1].z2 =      0;
    r->walls[1].nx =      0;  r->walls[1].nz =   4096;
    r->walls[1].y_min =  -1000;  r->walls[1].y_max =      0;

    /* Wall 2 - the room proxy: perimeter + head alcove */
    r->walls[2].x1 =   1500;  r->walls[2].z1 =      0;
    r->walls[2].x2 =   1500;  r->walls[2].z2 =   2613;
    r->walls[2].nx =  -4096;  r->walls[2].nz =      0;
    r->walls[2].y_min =  -1000;  r->walls[2].y_max =      0;

    /* Wall 3 - the room proxy: perimeter + head alcove */
    r->walls[3].x1 =   1500;  r->walls[3].z1 =   2613;
    r->walls[3].x2 =    219;  r->walls[3].z2 =   2613;
    r->walls[3].nx =      0;  r->walls[3].nz =  -4096;
    r->walls[3].y_min =  -1000;  r->walls[3].y_max =      0;

    /* Wall 4 - the room proxy: perimeter + head alcove */
    r->walls[4].x1 =   -189;  r->walls[4].z1 =   2613;
    r->walls[4].x2 =  -1500;  r->walls[4].z2 =   2613;
    r->walls[4].nx =      0;  r->walls[4].nz =  -4096;
    r->walls[4].y_min =  -1000;  r->walls[4].y_max =      0;

    /* Wall 5 - the room proxy: perimeter + head alcove */
    r->walls[5].x1 =   -300;  r->walls[5].z1 =   3248;
    r->walls[5].x2 =   -189;  r->walls[5].z2 =   2613;
    r->walls[5].nx =   4077;  r->walls[5].nz =    385;
    r->walls[5].y_min =   -550;  r->walls[5].y_max =      0;

    /* Wall 6 - the room proxy: perimeter + head alcove */
    r->walls[6].x1 =    219;  r->walls[6].z1 =   2613;
    r->walls[6].x2 =    300;  r->walls[6].z2 =   3248;
    r->walls[6].nx =  -4095;  r->walls[6].nz =      0;
    r->walls[6].y_min =   -559;  r->walls[6].y_max =      0;

    /* Wall 7 - the room proxy: perimeter + head alcove */
    r->walls[7].x1 =    300;  r->walls[7].z1 =   3248;
    r->walls[7].x2 =   -300;  r->walls[7].z2 =   3248;
    r->walls[7].nx =      0;  r->walls[7].nz =  -4096;
    r->walls[7].y_min =   -550;  r->walls[7].y_max =      0;

    /* Wall 8 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[8].x1 =  -1266;  r->walls[8].z1 =   2553;
    r->walls[8].x2 =  -1265;  r->walls[8].z2 =   2818;
    r->walls[8].nx =  -4095;  r->walls[8].nz =      0;
    r->walls[8].y_min =   -204;  r->walls[8].y_max =     -4;

    /* Wall 9 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[9].x1 =  -1065;  r->walls[9].z1 =   2818;
    r->walls[9].x2 =  -1066;  r->walls[9].z2 =   2553;
    r->walls[9].nx =   4095;  r->walls[9].nz =      0;
    r->walls[9].y_min =   -204;  r->walls[9].y_max =     -4;

    /* Wall 10 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[10].x1 =  -1265;  r->walls[10].z1 =   2334;
    r->walls[10].x2 =  -1266;  r->walls[10].z2 =   2553;
    r->walls[10].nx =  -4095;  r->walls[10].nz =      0;
    r->walls[10].y_min =   -204;  r->walls[10].y_max =     -4;

    /* Wall 11 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[11].x1 =  -1066;  r->walls[11].z1 =   2553;
    r->walls[11].x2 =  -1065;  r->walls[11].z2 =   2334;
    r->walls[11].nx =   4095;  r->walls[11].nz =      0;
    r->walls[11].y_min =   -204;  r->walls[11].y_max =     -4;

    /* Wall 12 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[12].x1 =  -1265;  r->walls[12].z1 =   2145;
    r->walls[12].x2 =  -1265;  r->walls[12].z2 =   2334;
    r->walls[12].nx =  -4095;  r->walls[12].nz =     -1;
    r->walls[12].y_min =   -204;  r->walls[12].y_max =     -4;

    /* Wall 13 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[13].x1 =  -1065;  r->walls[13].z1 =   2334;
    r->walls[13].x2 =  -1065;  r->walls[13].z2 =   2145;
    r->walls[13].nx =   4095;  r->walls[13].nz =      1;
    r->walls[13].y_min =   -204;  r->walls[13].y_max =     -4;

    /* Wall 14 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[14].x1 =  -1065;  r->walls[14].z1 =   2145;
    r->walls[14].x2 =  -1065;  r->walls[14].z2 =   1962;
    r->walls[14].nx =   4095;  r->walls[14].nz =     -2;
    r->walls[14].y_min =   -204;  r->walls[14].y_max =     -4;

    /* Wall 15 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[15].x1 =  -1265;  r->walls[15].z1 =   1962;
    r->walls[15].x2 =  -1265;  r->walls[15].z2 =   2145;
    r->walls[15].nx =  -4095;  r->walls[15].nz =      2;
    r->walls[15].y_min =   -204;  r->walls[15].y_max =     -4;

    /* Wall 16 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[16].x1 =  -1266;  r->walls[16].z1 =   1768;
    r->walls[16].x2 =  -1265;  r->walls[16].z2 =   1962;
    r->walls[16].nx =  -4095;  r->walls[16].nz =      2;
    r->walls[16].y_min =   -204;  r->walls[16].y_max =     -4;

    /* Wall 17 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[17].x1 =  -1065;  r->walls[17].z1 =   1962;
    r->walls[17].x2 =  -1066;  r->walls[17].z2 =   1769;
    r->walls[17].nx =   4095;  r->walls[17].nz =     -2;
    r->walls[17].y_min =   -204;  r->walls[17].y_max =     -4;

    /* Wall 18 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[18].x1 =  -1265;  r->walls[18].z1 =   1569;
    r->walls[18].x2 =  -1266;  r->walls[18].z2 =   1768;
    r->walls[18].nx =  -4095;  r->walls[18].nz =     -3;
    r->walls[18].y_min =   -204;  r->walls[18].y_max =     -4;

    /* Wall 19 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[19].x1 =  -1066;  r->walls[19].z1 =   1769;
    r->walls[19].x2 =  -1065;  r->walls[19].z2 =   1569;
    r->walls[19].nx =   4095;  r->walls[19].nz =      3;
    r->walls[19].y_min =   -204;  r->walls[19].y_max =     -4;

    /* Wall 20 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[20].x1 =  -1065;  r->walls[20].z1 =   1569;
    r->walls[20].x2 =  -1084;  r->walls[20].z2 =   1373;
    r->walls[20].nx =   4077;  r->walls[20].nz =   -386;
    r->walls[20].y_min =   -204;  r->walls[20].y_max =     -4;

    /* Wall 21 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[21].x1 =  -1247;  r->walls[21].z1 =   1373;
    r->walls[21].x2 =  -1265;  r->walls[21].z2 =   1569;
    r->walls[21].nx =  -4077;  r->walls[21].nz =   -389;
    r->walls[21].y_min =   -204;  r->walls[21].y_max =     -4;

    /* Wall 22 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[22].x1 =  -1084;  r->walls[22].z1 =   1373;
    r->walls[22].x2 =  -1103;  r->walls[22].z2 =   1201;
    r->walls[22].nx =   4071;  r->walls[22].nz =   -448;
    r->walls[22].y_min =   -196;  r->walls[22].y_max =    -13;

    /* Wall 23 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[23].x1 =  -1228;  r->walls[23].z1 =   1201;
    r->walls[23].x2 =  -1247;  r->walls[23].z2 =   1373;
    r->walls[23].nx =  -4072;  r->walls[23].nz =   -442;
    r->walls[23].y_min =   -196;  r->walls[23].y_max =    -13;

    /* Wall 24 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[24].x1 =  -1199;  r->walls[24].z1 =   1046;
    r->walls[24].x2 =  -1228;  r->walls[24].z2 =   1201;
    r->walls[24].nx =  -4024;  r->walls[24].nz =   -761;
    r->walls[24].y_min =   -178;  r->walls[24].y_max =    -31;

    /* Wall 25 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[25].x1 =  -1103;  r->walls[25].z1 =   1201;
    r->walls[25].x2 =  -1132;  r->walls[25].z2 =   1047;
    r->walls[25].nx =   4025;  r->walls[25].nz =   -754;
    r->walls[25].y_min =   -178;  r->walls[25].y_max =    -31;

    /* Wall 26 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[26].x1 =  -1149;  r->walls[26].z1 =    901;
    r->walls[26].x2 =  -1199;  r->walls[26].z2 =   1046;
    r->walls[26].nx =  -3871;  r->walls[26].nz =  -1338;
    r->walls[26].y_min =   -150;  r->walls[26].y_max =    -59;

    /* Wall 27 - the left arm, resting (Tentacle_Idle frame 1) */
    r->walls[27].x1 =  -1132;  r->walls[27].z1 =   1047;
    r->walls[27].x2 =  -1149;  r->walls[27].z2 =    901;
    r->walls[27].nx =   4069;  r->walls[27].nz =   -468;
    r->walls[27].y_min =   -150;  r->walls[27].y_max =    -59;

    /* Wall 28 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[28].x1 =   1264;  r->walls[28].z1 =   2818;
    r->walls[28].x2 =   1264;  r->walls[28].z2 =   2553;
    r->walls[28].nx =   4095;  r->walls[28].nz =      0;
    r->walls[28].y_min =   -204;  r->walls[28].y_max =     -4;

    /* Wall 29 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[29].x1 =   1064;  r->walls[29].z1 =   2553;
    r->walls[29].x2 =   1064;  r->walls[29].z2 =   2818;
    r->walls[29].nx =  -4095;  r->walls[29].nz =      0;
    r->walls[29].y_min =   -204;  r->walls[29].y_max =     -4;

    /* Wall 30 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[30].x1 =   1264;  r->walls[30].z1 =   2553;
    r->walls[30].x2 =   1264;  r->walls[30].z2 =   2334;
    r->walls[30].nx =   4095;  r->walls[30].nz =      0;
    r->walls[30].y_min =   -204;  r->walls[30].y_max =     -4;

    /* Wall 31 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[31].x1 =   1064;  r->walls[31].z1 =   2334;
    r->walls[31].x2 =   1064;  r->walls[31].z2 =   2553;
    r->walls[31].nx =  -4095;  r->walls[31].nz =      0;
    r->walls[31].y_min =   -204;  r->walls[31].y_max =     -4;

    /* Wall 32 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[32].x1 =   1264;  r->walls[32].z1 =   2334;
    r->walls[32].x2 =   1264;  r->walls[32].z2 =   2145;
    r->walls[32].nx =   4095;  r->walls[32].nz =     -1;
    r->walls[32].y_min =   -204;  r->walls[32].y_max =     -4;

    /* Wall 33 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[33].x1 =   1064;  r->walls[33].z1 =   2145;
    r->walls[33].x2 =   1064;  r->walls[33].z2 =   2334;
    r->walls[33].nx =  -4095;  r->walls[33].nz =      1;
    r->walls[33].y_min =   -204;  r->walls[33].y_max =     -4;

    /* Wall 34 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[34].x1 =   1064;  r->walls[34].z1 =   1962;
    r->walls[34].x2 =   1064;  r->walls[34].z2 =   2145;
    r->walls[34].nx =  -4095;  r->walls[34].nz =     -2;
    r->walls[34].y_min =   -204;  r->walls[34].y_max =     -4;

    /* Wall 35 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[35].x1 =   1264;  r->walls[35].z1 =   2145;
    r->walls[35].x2 =   1264;  r->walls[35].z2 =   1962;
    r->walls[35].nx =   4095;  r->walls[35].nz =      2;
    r->walls[35].y_min =   -204;  r->walls[35].y_max =     -4;

    /* Wall 36 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[36].x1 =   1264;  r->walls[36].z1 =   1962;
    r->walls[36].x2 =   1264;  r->walls[36].z2 =   1768;
    r->walls[36].nx =   4095;  r->walls[36].nz =      2;
    r->walls[36].y_min =   -204;  r->walls[36].y_max =     -4;

    /* Wall 37 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[37].x1 =   1064;  r->walls[37].z1 =   1769;
    r->walls[37].x2 =   1064;  r->walls[37].z2 =   1962;
    r->walls[37].nx =  -4095;  r->walls[37].nz =     -2;
    r->walls[37].y_min =   -204;  r->walls[37].y_max =     -4;

    /* Wall 38 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[38].x1 =   1264;  r->walls[38].z1 =   1768;
    r->walls[38].x2 =   1264;  r->walls[38].z2 =   1569;
    r->walls[38].nx =   4095;  r->walls[38].nz =     -3;
    r->walls[38].y_min =   -204;  r->walls[38].y_max =     -4;

    /* Wall 39 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[39].x1 =   1064;  r->walls[39].z1 =   1569;
    r->walls[39].x2 =   1064;  r->walls[39].z2 =   1769;
    r->walls[39].nx =  -4095;  r->walls[39].nz =      3;
    r->walls[39].y_min =   -204;  r->walls[39].y_max =     -4;

    /* Wall 40 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[40].x1 =   1082;  r->walls[40].z1 =   1373;
    r->walls[40].x2 =   1064;  r->walls[40].z2 =   1569;
    r->walls[40].nx =  -4077;  r->walls[40].nz =   -386;
    r->walls[40].y_min =   -204;  r->walls[40].y_max =     -4;

    /* Wall 41 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[41].x1 =   1264;  r->walls[41].z1 =   1569;
    r->walls[41].x2 =   1245;  r->walls[41].z2 =   1373;
    r->walls[41].nx =   4077;  r->walls[41].nz =   -389;
    r->walls[41].y_min =   -204;  r->walls[41].y_max =     -4;

    /* Wall 42 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[42].x1 =   1101;  r->walls[42].z1 =   1201;
    r->walls[42].x2 =   1082;  r->walls[42].z2 =   1373;
    r->walls[42].nx =  -4071;  r->walls[42].nz =   -448;
    r->walls[42].y_min =   -196;  r->walls[42].y_max =    -13;

    /* Wall 43 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[43].x1 =   1245;  r->walls[43].z1 =   1373;
    r->walls[43].x2 =   1226;  r->walls[43].z2 =   1201;
    r->walls[43].nx =   4072;  r->walls[43].nz =   -442;
    r->walls[43].y_min =   -196;  r->walls[43].y_max =    -13;

    /* Wall 44 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[44].x1 =   1226;  r->walls[44].z1 =   1201;
    r->walls[44].x2 =   1197;  r->walls[44].z2 =   1046;
    r->walls[44].nx =   4024;  r->walls[44].nz =   -761;
    r->walls[44].y_min =   -178;  r->walls[44].y_max =    -31;

    /* Wall 45 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[45].x1 =   1130;  r->walls[45].z1 =   1047;
    r->walls[45].x2 =   1101;  r->walls[45].z2 =   1201;
    r->walls[45].nx =  -4025;  r->walls[45].nz =   -754;
    r->walls[45].y_min =   -178;  r->walls[45].y_max =    -31;

    /* Wall 46 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[46].x1 =   1197;  r->walls[46].z1 =   1046;
    r->walls[46].x2 =   1147;  r->walls[46].z2 =    901;
    r->walls[46].nx =   3871;  r->walls[46].nz =  -1338;
    r->walls[46].y_min =   -150;  r->walls[46].y_max =    -59;

    /* Wall 47 - the right arm, resting (Tentacle_Idle frame 1) */
    r->walls[47].x1 =   1147;  r->walls[47].z1 =    901;
    r->walls[47].x2 =   1130;  r->walls[47].z2 =   1047;
    r->walls[47].nx =  -4069;  r->walls[47].nz =   -468;
    r->walls[47].y_min =   -150;  r->walls[47].y_max =    -59;

    /*
     * Floor planes from the room proxy. These are what
     * asag_arena_floor_zones_init() in src/asag_arena.c mirrors.
     *
     * FLOOR 0: y=0  x(-1500 to 1500)  z(0 to 2613)
     * FLOOR 1: y=0  x(-300 to 300)  z(2613 to 3248)
     */
}
