/*
 * Auto-generated collision data from: Attic Stairwell mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 *
 * NOTE: this src/ copy is NOT byte-identical to the generated
 * assets/"Attic Stairwell mesh_collision.[ch]" — the .c include is lowercased
 * and multi_level/shoot_over_mask are added by hand (see tools/ADDING_A_ROOM.txt
 * step 4c).
 */

#ifndef ATTIC_STAIRWELL_MESH_COLLISION_H
#define ATTIC_STAIRWELL_MESH_COLLISION_H

#include "collision.h"

#define ATTIC_STAIRWELL_WALL_COUNT  26
#define ATTIC_STAIRWELL_FLOOR_COUNT 7

void attic_stairwell_collision_init(CollisionRoom *r);

#endif /* ATTIC_STAIRWELL_MESH_COLLISION_H */
