/*
 * Auto-generated collision data from: Attic Exit mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  26
 * Floors: 9
 * Bounds: X(-1500 to 1500)  Z(-999 to 999)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "attic_exit_mesh_collision.h"

void attic_exit_collision_init(CollisionRoom *r) {
    r->wall_count = ATTIC_EXIT_WALL_COUNT;
    r->multi_level     = 0;   /* one flat floor at y=0 */
    r->shoot_over_mask = 0;   /* nothing low enough to shoot over */
    r->min_x = -1500;
    r->max_x = 1500;
    r->min_z = -999;
    r->max_z = 999;

    /* Wall 0 (avg Y: -209) */
    r->walls[0].x1 =    -543;  r->walls[0].z1 =     999;
    r->walls[0].x2 =   -1500;  r->walls[0].z2 =     999;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =    -466;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -186) */
    r->walls[1].x1 =   -1500;  r->walls[1].z1 =    -999;
    r->walls[1].x2 =    1500;  r->walls[1].z2 =    -999;
    r->walls[1].nx =       0;  r->walls[1].nz =    4096;
    r->walls[1].y_min =    -373;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -186) */
    r->walls[2].x1 =    1500;  r->walls[2].z1 =    -999;
    r->walls[2].x2 =    1500;  r->walls[2].z2 =     999;
    r->walls[2].nx =   -4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -373;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -186) */
    r->walls[3].x1 =   -1500;  r->walls[3].z1 =     999;
    r->walls[3].x2 =   -1500;  r->walls[3].z2 =    -999;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -373;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -191) */
    r->walls[4].x1 =    -543;  r->walls[4].z1 =     249;
    r->walls[4].x2 =    -543;  r->walls[4].z2 =     749;
    r->walls[4].nx =   -4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -383;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -63) */
    r->walls[5].x1 =    -543;  r->walls[5].z1 =      31;
    r->walls[5].x2 =    -543;  r->walls[5].z2 =     249;
    r->walls[5].nx =   -4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -127;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -191) */
    r->walls[6].x1 =    -499;  r->walls[6].z1 =     749;
    r->walls[6].x2 =    -499;  r->walls[6].z2 =      31;
    r->walls[6].nx =    4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =    -383;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -233) */
    r->walls[7].x1 =     502;  r->walls[7].z1 =     999;
    r->walls[7].x2 =    -499;  r->walls[7].z2 =     999;
    r->walls[7].nx =       0;  r->walls[7].nz =   -4096;
    r->walls[7].y_min =    -466;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -209) */
    r->walls[8].x1 =    1500;  r->walls[8].z1 =     999;
    r->walls[8].x2 =     544;  r->walls[8].z2 =     999;
    r->walls[8].nx =       0;  r->walls[8].nz =   -4096;
    r->walls[8].y_min =    -466;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -63) */
    r->walls[9].x1 =    -499;  r->walls[9].z1 =      31;
    r->walls[9].x2 =    -300;  r->walls[9].z2 =      31;
    r->walls[9].nx =       0;  r->walls[9].nz =    4096;
    r->walls[9].y_min =    -126;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -63) */
    r->walls[10].x1 =     300;  r->walls[10].z1 =      31;
    r->walls[10].x2 =     502;  r->walls[10].z2 =      31;
    r->walls[10].nx =       0;  r->walls[10].nz =    4096;
    r->walls[10].y_min =    -126;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -63) */
    r->walls[11].x1 =    -300;  r->walls[11].z1 =       0;
    r->walls[11].x2 =    -499;  r->walls[11].z2 =       0;
    r->walls[11].nx =       0;  r->walls[11].nz =   -4096;
    r->walls[11].y_min =    -126;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -78) */
    r->walls[12].x1 =     502;  r->walls[12].z1 =     749;
    r->walls[12].x2 =     502;  r->walls[12].z2 =     999;
    r->walls[12].nx =   -4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =    -186;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -63) */
    r->walls[13].x1 =     502;  r->walls[13].z1 =       0;
    r->walls[13].x2 =     300;  r->walls[13].z2 =       0;
    r->walls[13].nx =       0;  r->walls[13].nz =   -4096;
    r->walls[13].y_min =    -126;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -211) */
    r->walls[14].x1 =     544;  r->walls[14].z1 =     999;
    r->walls[14].x2 =     544;  r->walls[14].z2 =     749;
    r->walls[14].nx =    4096;  r->walls[14].nz =       0;
    r->walls[14].y_min =    -466;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -78) */
    r->walls[15].x1 =    -499;  r->walls[15].z1 =     999;
    r->walls[15].x2 =    -499;  r->walls[15].z2 =     749;
    r->walls[15].nx =    4095;  r->walls[15].nz =       0;
    r->walls[15].y_min =    -186;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -63) */
    r->walls[16].x1 =     544;  r->walls[16].z1 =     249;
    r->walls[16].x2 =     544;  r->walls[16].z2 =      31;
    r->walls[16].nx =    4096;  r->walls[16].nz =       0;
    r->walls[16].y_min =    -126;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -190) */
    r->walls[17].x1 =     544;  r->walls[17].z1 =     749;
    r->walls[17].x2 =     544;  r->walls[17].z2 =     249;
    r->walls[17].nx =    4095;  r->walls[17].nz =       0;
    r->walls[17].y_min =    -380;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -191) */
    r->walls[18].x1 =    -499;  r->walls[18].z1 =       0;
    r->walls[18].x2 =    -543;  r->walls[18].z2 =      31;
    r->walls[18].nx =   -2407;  r->walls[18].nz =   -3313;
    r->walls[18].y_min =    -383;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -190) */
    r->walls[19].x1 =     544;  r->walls[19].z1 =      31;
    r->walls[19].x2 =     502;  r->walls[19].z2 =       0;
    r->walls[19].nx =    2472;  r->walls[19].nz =   -3265;
    r->walls[19].y_min =    -380;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -190) */
    r->walls[20].x1 =     502;  r->walls[20].z1 =      31;
    r->walls[20].x2 =     502;  r->walls[20].z2 =     749;
    r->walls[20].nx =   -4096;  r->walls[20].nz =       0;
    r->walls[20].y_min =    -380;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -212) */
    r->walls[21].x1 =    -543;  r->walls[21].z1 =     749;
    r->walls[21].x2 =    -543;  r->walls[21].z2 =     999;
    r->walls[21].nx =   -4095;  r->walls[21].nz =       0;
    r->walls[21].y_min =    -466;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -540) */
    r->walls[22].x1 =    -534;  r->walls[22].z1 =     -43;
    r->walls[22].x2 =    -534;  r->walls[22].z2 =     -23;
    r->walls[22].nx =   -4096;  r->walls[22].nz =       0;
    r->walls[22].y_min =    -550;  r->walls[22].y_max =    -530;

    /* Wall 23 (avg Y: -540) */
    r->walls[23].x1 =     515;  r->walls[23].z1 =     -43;
    r->walls[23].x2 =     515;  r->walls[23].z2 =     -23;
    r->walls[23].nx =   -4096;  r->walls[23].nz =       0;
    r->walls[23].y_min =    -550;  r->walls[23].y_max =    -530;

    /* Wall 24 (avg Y: -540) */
    r->walls[24].x1 =    -534;  r->walls[24].z1 =    -993;
    r->walls[24].x2 =    -534;  r->walls[24].z2 =    -973;
    r->walls[24].nx =   -4096;  r->walls[24].nz =       0;
    r->walls[24].y_min =    -550;  r->walls[24].y_max =    -530;

    /* Wall 25 (avg Y: -540) */
    r->walls[25].x1 =     515;  r->walls[25].z1 =    -993;
    r->walls[25].x2 =     515;  r->walls[25].z2 =    -973;
    r->walls[25].nx =   -4096;  r->walls[25].nz =       0;
    r->walls[25].y_min =    -550;  r->walls[25].y_max =    -530;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-1500 to 1500)  z(-999 to 999)
     * CEILING 1: y=  -530  x(-534 to -515)  z(-43 to -23)
     * FLOOR   2: y=  -550  x(-534 to -515)  z(-43 to -23)
     * CEILING 3: y=  -530  x(515 to 535)  z(-43 to -23)
     * FLOOR   4: y=  -550  x(515 to 535)  z(-43 to -23)
     * CEILING 5: y=  -530  x(-534 to -515)  z(-993 to -973)
     * FLOOR   6: y=  -550  x(-534 to -515)  z(-993 to -973)
     * CEILING 7: y=  -530  x(515 to 535)  z(-993 to -973)
     * FLOOR   8: y=  -550  x(515 to 535)  z(-993 to -973)
     */
}
