/*
 * Auto-generated collision data from: Attic Exit mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 *
 * NOTE: this src/ copy is not byte-identical to the assets/ original — the .c
 * carries the hand-added multi_level / shoot_over_mask lines the generator does
 * not emit (see tools/ADDING_A_ROOM.txt STEP 4c).
 */

#ifndef ATTIC_EXIT_MESH_COLLISION_H
#define ATTIC_EXIT_MESH_COLLISION_H

#include "collision.h"

#define ATTIC_EXIT_WALL_COUNT  26
#define ATTIC_EXIT_FLOOR_COUNT 9

void attic_exit_collision_init(CollisionRoom *r);

#endif /* ATTIC_EXIT_MESH_COLLISION_H */
