/*
 * Auto-generated collision data from: Catacombs Entry mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead. Note that src/ is NOT
 * byte-identical to assets/catacombs/: the .c there carries hand-added
 * multi_level / shoot_over_mask lines the generator does not emit.
 */

#ifndef CATACOMBS_ENTRY_MESH_COLLISION_H
#define CATACOMBS_ENTRY_MESH_COLLISION_H

#include "collision.h"

#define CATACOMBS_ENTRY_WALL_COUNT  30
#define CATACOMBS_ENTRY_FLOOR_COUNT 7

void catacombs_entry_collision_init(CollisionRoom *r);

#endif /* CATACOMBS_ENTRY_MESH_COLLISION_H */
