/*
 * Auto-generated collision data from: Cleaver Corridor mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * NOTE: src/ is not byte-identical to assets/ — the #include is lowercased and
 *       r->multi_level / r->shoot_over_mask are added by hand (STEP 4c of
 *       tools/ADDING_A_ROOM.txt). Regenerate into assets/ and re-apply those.
 */

#ifndef CLEAVER_CORRIDOR_MESH_COLLISION_H
#define CLEAVER_CORRIDOR_MESH_COLLISION_H

#include "collision.h"

#define CLEAVER_CORRIDOR_WALL_COUNT  4
#define CLEAVER_CORRIDOR_FLOOR_COUNT 1

void cleaver_corridor_collision_init(CollisionRoom *r);

#endif /* CLEAVER_CORRIDOR_MESH_COLLISION_H */
