/*
 * Auto-generated collision data from: Cleaver L mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * NOTE: src/ is not byte-identical to assets/ - the #include is lowercased and
 *       r->multi_level / r->shoot_over_mask are added by hand (STEP 4c of
 *       tools/ADDING_A_ROOM.txt). Regenerate into assets/ and re-apply those.
 */

#ifndef CLEAVER_L_MESH_COLLISION_H
#define CLEAVER_L_MESH_COLLISION_H

#include "collision.h"

#define CLEAVER_L_WALL_COUNT  6
#define CLEAVER_L_FLOOR_COUNT 2

void cleaver_l_collision_init(CollisionRoom *r);

#endif /* CLEAVER_L_MESH_COLLISION_H */
