/*
 * Auto-generated collision data from: Cleaver L mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  6
 * Floors: 2
 * Bounds: X(-2399 to 600)  Z(-2400 to 600)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "cleaver_l_mesh_collision.h"

void cleaver_l_collision_init(CollisionRoom *r) {
    r->wall_count = CLEAVER_L_WALL_COUNT;
    /* FLAT, SINGLE-STOREY, so 0 - the Room of Legs' case. The proxy found
       two floor faces, the two shafts of the L, and both are at y=0. */
    r->multi_level     = 0;
    /* Six full-height outer walls and nothing low to shoot over. */
    r->shoot_over_mask = 0;
    r->min_x = -2399;
    r->max_x = 600;
    r->min_z = -2400;
    r->max_z = 600;

    /* Wall 0 (avg Y: -400) */
    r->walls[0].x1 =     600;  r->walls[0].z1 =     600;
    r->walls[0].x2 =       0;  r->walls[0].z2 =     600;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =    -800;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -400) */
    r->walls[1].x1 =   -2399;  r->walls[1].z1 =   -2400;
    r->walls[1].x2 =     600;  r->walls[1].z2 =   -2400;
    r->walls[1].nx =       0;  r->walls[1].nz =    4096;
    r->walls[1].y_min =    -800;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -400) */
    r->walls[2].x1 =     600;  r->walls[2].z1 =   -2400;
    r->walls[2].x2 =     600;  r->walls[2].z2 =     600;
    r->walls[2].nx =   -4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -800;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -400) */
    r->walls[3].x1 =   -2399;  r->walls[3].z1 =   -1800;
    r->walls[3].x2 =   -2399;  r->walls[3].z2 =   -2400;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -800;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -400) */
    r->walls[4].x1 =       0;  r->walls[4].z1 =   -1800;
    r->walls[4].x2 =   -2399;  r->walls[4].z2 =   -1800;
    r->walls[4].nx =       0;  r->walls[4].nz =   -4096;
    r->walls[4].y_min =    -800;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -400) */
    r->walls[5].x1 =       0;  r->walls[5].z1 =     600;
    r->walls[5].x2 =       0;  r->walls[5].z2 =   -1800;
    r->walls[5].nx =    4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -800;  r->walls[5].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(0 to 600)  z(-2400 to 600)
     * FLOOR   1: y=     0  x(-2399 to 600)  z(-2400 to -1800)
     */
}
