/*
 * Auto-generated collision data from: Conservatory_mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef CONSERVATORY_MESH_COLLISION_H
#define CONSERVATORY_MESH_COLLISION_H

#include "collision.h"

#define CONSERVATORY_WALL_COUNT  29
#define CONSERVATORY_FLOOR_COUNT 26

void conservatory_collision_init(CollisionRoom *r);

#endif /* CONSERVATORY_MESH_COLLISION_H */
