/*
 * Auto-generated collision data from: Conservatory_mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  29
 * Floors: 26
 * Bounds: X(-2601 to 0)  Z(-311 to 1702)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "Conservatory_mesh_collision.h"

void conservatory_collision_init(CollisionRoom *r) {
    r->wall_count = CONSERVATORY_WALL_COUNT;
    r->multi_level = 0;       /* one flat walkable floor (added by hand);
                                 the visible upstairs is scenery only */
    r->shoot_over_mask = 0;   /* no shoot-over walls here */
    r->min_x = -2601;
    r->max_x = 0;
    r->min_z = -311;
    r->max_z = 1702;

    /* Wall 0 (avg Y: -257) */
    r->walls[0].x1 =    -750;  r->walls[0].z1 =     331;
    r->walls[0].x2 =   -1400;  r->walls[0].z2 =     331;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =    -514;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -257) */
    r->walls[1].x1 =   -2000;  r->walls[1].z1 =     331;
    r->walls[1].x2 =   -2601;  r->walls[1].z2 =     331;
    r->walls[1].nx =       0;  r->walls[1].nz =   -4096;
    r->walls[1].y_min =    -514;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -222) */
    r->walls[2].x1 =       0;  r->walls[2].z1 =     331;
    r->walls[2].x2 =    -450;  r->walls[2].z2 =     331;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4096;
    r->walls[2].y_min =    -514;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -85) */
    r->walls[3].x1 =    -450;  r->walls[3].z1 =     331;
    r->walls[3].x2 =    -450;  r->walls[3].z2 =     385;
    r->walls[3].nx =   -4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -171;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -85) */
    r->walls[4].x1 =    -750;  r->walls[4].z1 =     385;
    r->walls[4].x2 =    -750;  r->walls[4].z2 =     331;
    r->walls[4].nx =    4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -171;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -85) */
    r->walls[5].x1 =    -838;  r->walls[5].z1 =     385;
    r->walls[5].x2 =    -750;  r->walls[5].z2 =     385;
    r->walls[5].nx =       0;  r->walls[5].nz =    4096;
    r->walls[5].y_min =    -171;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -85) */
    r->walls[6].x1 =    -450;  r->walls[6].z1 =     385;
    r->walls[6].x2 =    -333;  r->walls[6].z2 =     385;
    r->walls[6].nx =       0;  r->walls[6].nz =    4096;
    r->walls[6].y_min =    -171;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -85) */
    r->walls[7].x1 =   -2000;  r->walls[7].z1 =     380;
    r->walls[7].x2 =   -2000;  r->walls[7].z2 =     331;
    r->walls[7].nx =    4096;  r->walls[7].nz =       0;
    r->walls[7].y_min =    -171;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -85) */
    r->walls[8].x1 =   -1400;  r->walls[8].z1 =     331;
    r->walls[8].x2 =   -1400;  r->walls[8].z2 =     380;
    r->walls[8].nx =   -4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =    -171;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -85) */
    r->walls[9].x1 =   -1150;  r->walls[9].z1 =     380;
    r->walls[9].x2 =    -901;  r->walls[9].z2 =     380;
    r->walls[9].nx =       0;  r->walls[9].nz =    4096;
    r->walls[9].y_min =    -171;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -85) */
    r->walls[10].x1 =   -2599;  r->walls[10].z1 =     380;
    r->walls[10].x2 =   -2401;  r->walls[10].z2 =     380;
    r->walls[10].nx =       0;  r->walls[10].nz =    4096;
    r->walls[10].y_min =    -171;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -85) */
    r->walls[11].x1 =   -2599;  r->walls[11].z1 =    1303;
    r->walls[11].x2 =   -2599;  r->walls[11].z2 =    1164;
    r->walls[11].nx =    4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -171;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -85) */
    r->walls[12].x1 =   -2202;  r->walls[12].z1 =     380;
    r->walls[12].x2 =   -2000;  r->walls[12].z2 =     380;
    r->walls[12].nx =       0;  r->walls[12].nz =    4096;
    r->walls[12].y_min =    -171;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -85) */
    r->walls[13].x1 =   -2000;  r->walls[13].z1 =    1702;
    r->walls[13].x2 =   -2202;  r->walls[13].z2 =    1702;
    r->walls[13].nx =       0;  r->walls[13].nz =   -4096;
    r->walls[13].y_min =    -171;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -257) */
    r->walls[14].x1 =   -2601;  r->walls[14].z1 =    -311;
    r->walls[14].x2 =       0;  r->walls[14].z2 =    -311;
    r->walls[14].nx =       0;  r->walls[14].nz =    4096;
    r->walls[14].y_min =    -514;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -257) */
    r->walls[15].x1 =       0;  r->walls[15].z1 =    -311;
    r->walls[15].x2 =       0;  r->walls[15].z2 =     331;
    r->walls[15].nx =   -4096;  r->walls[15].nz =       0;
    r->walls[15].y_min =    -514;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -257) */
    r->walls[16].x1 =   -2601;  r->walls[16].z1 =     331;
    r->walls[16].x2 =   -2601;  r->walls[16].z2 =    -311;
    r->walls[16].nx =    4096;  r->walls[16].nz =       0;
    r->walls[16].y_min =    -514;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -187) */
    r->walls[17].x1 =    -838;  r->walls[17].z1 =     997;
    r->walls[17].x2 =    -838;  r->walls[17].z2 =     385;
    r->walls[17].nx =    4096;  r->walls[17].nz =       0;
    r->walls[17].y_min =    -375;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -187) */
    r->walls[18].x1 =    -333;  r->walls[18].z1 =     385;
    r->walls[18].x2 =    -333;  r->walls[18].z2 =     997;
    r->walls[18].nx =   -4096;  r->walls[18].nz =       0;
    r->walls[18].y_min =    -375;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -187) */
    r->walls[19].x1 =    -333;  r->walls[19].z1 =     997;
    r->walls[19].x2 =    -838;  r->walls[19].z2 =     997;
    r->walls[19].nx =       0;  r->walls[19].nz =   -4096;
    r->walls[19].y_min =    -375;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -280) */
    r->walls[20].x1 =    -901;  r->walls[20].z1 =     380;
    r->walls[20].x2 =    -901;  r->walls[20].z2 =    1702;
    r->walls[20].nx =   -4096;  r->walls[20].nz =       0;
    r->walls[20].y_min =    -561;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -280) */
    r->walls[21].x1 =    -901;  r->walls[21].z1 =    1702;
    r->walls[21].x2 =   -2000;  r->walls[21].z2 =    1702;
    r->walls[21].nx =       0;  r->walls[21].nz =   -4096;
    r->walls[21].y_min =    -561;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -85) */
    r->walls[22].x1 =   -1400;  r->walls[22].z1 =     380;
    r->walls[22].x2 =   -1150;  r->walls[22].z2 =     380;
    r->walls[22].nx =       0;  r->walls[22].nz =    4096;
    r->walls[22].y_min =    -171;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -280) */
    r->walls[23].x1 =   -2202;  r->walls[23].z1 =    1702;
    r->walls[23].x2 =   -2326;  r->walls[23].z2 =    1627;
    r->walls[23].nx =    2123;  r->walls[23].nz =   -3502;
    r->walls[23].y_min =    -561;  r->walls[23].y_max =       0;

    /* Wall 24 (avg Y: -280) */
    r->walls[24].x1 =   -2326;  r->walls[24].z1 =    1627;
    r->walls[24].x2 =   -2449;  r->walls[24].z2 =    1552;
    r->walls[24].nx =    2123;  r->walls[24].nz =   -3502;
    r->walls[24].y_min =    -561;  r->walls[24].y_max =       0;

    /* Wall 25 (avg Y: -280) */
    r->walls[25].x1 =   -2449;  r->walls[25].z1 =    1552;
    r->walls[25].x2 =   -2524;  r->walls[25].z2 =    1427;
    r->walls[25].nx =    3507;  r->walls[25].nz =   -2115;
    r->walls[25].y_min =    -561;  r->walls[25].y_max =       0;

    /* Wall 26 (avg Y: -280) */
    r->walls[26].x1 =   -2524;  r->walls[26].z1 =    1427;
    r->walls[26].x2 =   -2599;  r->walls[26].z2 =    1303;
    r->walls[26].nx =    3507;  r->walls[26].nz =   -2115;
    r->walls[26].y_min =    -561;  r->walls[26].y_max =       0;

    /* Wall 27 (avg Y: -280) */
    r->walls[27].x1 =   -2599;  r->walls[27].z1 =    1164;
    r->walls[27].x2 =   -2599;  r->walls[27].z2 =     380;
    r->walls[27].nx =    4096;  r->walls[27].nz =       0;
    r->walls[27].y_min =    -561;  r->walls[27].y_max =       0;

    /* Wall 28 (avg Y: -85) */
    r->walls[28].x1 =   -2401;  r->walls[28].z1 =     380;
    r->walls[28].x2 =   -2202;  r->walls[28].z2 =     380;
    r->walls[28].nx =       0;  r->walls[28].nz =    4096;
    r->walls[28].y_min =    -171;  r->walls[28].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-600 to -450)  z(331 to 385)
     * FLOOR   1: y=     0  x(-1700 to -1400)  z(331 to 380)
     * FLOOR   2: y=     0  x(-1700 to -1400)  z(1502 to 1702)
     * FLOOR   3: y=     0  x(-2000 to -1700)  z(331 to 380)
     * FLOOR   4: y=     0  x(-2524 to -2326)  z(1427 to 1627)
     * FLOOR   5: y=     0  x(-2000 to -1700)  z(1502 to 1702)
     * FLOOR   6: y=     0  x(-1150 to -901)  z(1303 to 1502)
     * FLOOR   7: y=     0  x(-2599 to -2401)  z(1164 to 1303)
     * FLOOR   8: y=     0  x(-2202 to -2000)  z(1502 to 1702)
     * FLOOR   9: y=     0  x(-2599 to -2401)  z(968 to 1164)
     * FLOOR   10: y=     0  x(-838 to -333)  z(385 to 997)
     * FLOOR   11: y=     0  x(-2601 to 0)  z(-311 to 331)
     * FLOOR   12: y=     0  x(-750 to -600)  z(331 to 385)
     * FLOOR   13: y=     0  x(-2599 to -2401)  z(380 to 576)
     * FLOOR   14: y=     0  x(-2599 to -2401)  z(576 to 772)
     * FLOOR   15: y=     0  x(-2599 to -2401)  z(772 to 968)
     * FLOOR   16: y=     0  x(-2202 to -2000)  z(1303 to 1502)
     * FLOOR   17: y=     0  x(-1150 to -901)  z(1502 to 1702)
     * FLOOR   18: y=     0  x(-2000 to -1700)  z(1303 to 1502)
     * FLOOR   19: y=     0  x(-2599 to -2363)  z(1303 to 1465)
     * FLOOR   20: y=     0  x(-1700 to -1400)  z(1303 to 1502)
     * FLOOR   21: y=     0  x(-1400 to -1150)  z(1502 to 1702)
     * FLOOR   22: y=     0  x(-1400 to -1150)  z(1303 to 1502)
     * FLOOR   23: y=     0  x(-2401 to -2202)  z(1303 to 1502)
     * FLOOR   24: y=     0  x(-2401 to -901)  z(380 to 1303)
     * FLOOR   25: y=     0  x(-2363 to -2202)  z(1465 to 1702)
     */
}
