/*
 * Auto-generated collision data from: Crucifix Corridor mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * NOTE: src/ is not byte-identical to assets/ — the #include is lowercased and
 *       r->multi_level / r->shoot_over_mask are added by hand (STEP 4c of
 *       tools/ADDING_A_ROOM.txt). Regenerate into assets/ and re-apply those.
 */

#ifndef CRUCIFIX_CORRIDOR_MESH_COLLISION_H
#define CRUCIFIX_CORRIDOR_MESH_COLLISION_H

#include "collision.h"

#define CRUCIFIX_CORRIDOR_WALL_COUNT  12
#define CRUCIFIX_CORRIDOR_FLOOR_COUNT 3

void crucifix_corridor_collision_init(CollisionRoom *r);

#endif /* CRUCIFIX_CORRIDOR_MESH_COLLISION_H */
