/*
 * Auto-generated collision data from: delivery_area_mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef DELIVERY_AREA_MESH_COLLISION_H
#define DELIVERY_AREA_MESH_COLLISION_H

#include "collision.h"

#define DELIVERY_AREA_WALL_COUNT  16
#define DELIVERY_AREA_FLOOR_COUNT 5

void delivery_area_collision_init(CollisionRoom *r);

#endif /* DELIVERY_AREA_MESH_COLLISION_H */
