#ifndef DRESSER_TEX_MAP_H
#define DRESSER_TEX_MAP_H

/* Per-primitive texture slot for the dresser prop, in SMD primitive order
   (matches Dresser.smx poly order). Resolved by texture NAME so a change to
   the SMX <textures> ordering can't silently mis-map (see MESH_CONVERSION_NOTES).
     slot 0 = wd_flr  (reused from the room's resident wood-floor texture)
     slot 1 = dresser (the prop's own streamed texture)
   Generated by gen_dresser_tex_map.py. */
#define DRESSER_PRIM_COUNT 34

static const unsigned char dresser_tex_map[DRESSER_PRIM_COUNT] = {
    0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
    1, 0,
};

#endif
