/*
 * Auto-generated collision data from: East Stairwell mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 *
 * NOTE: this src/ copy is NOT byte-identical to the assets/ original — the
 * #include was lowercased and multi_level/shoot_over_mask added by hand (the
 * generator does not emit them). See tools/ADDING_A_ROOM.txt step 4c.
 *
 * Walls 2 (x=-44) and 7 (x=+44) are the chain-link fences that close off the
 * stairwell shaft: they split the room into two landings that do not connect.
 */

#ifndef EAST_STAIRWELL_MESH_COLLISION_H
#define EAST_STAIRWELL_MESH_COLLISION_H

#include "collision.h"

#define EAST_STAIRWELL_WALL_COUNT  8
#define EAST_STAIRWELL_FLOOR_COUNT 2

void east_stairwell_collision_init(CollisionRoom *r);

#endif /* EAST_STAIRWELL_MESH_COLLISION_H */
