/*
 * Auto-generated collision data from: Fountain Square mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 *
 * NOTE: src/ is not byte-identical to the generated pair in assets/garden/.
 * The .c carries two hand-added lines the generator does not emit
 * (r->multi_level and r->shoot_over_mask); see the comment there.
 */

#ifndef FOUNTAIN_SQUARE_MESH_COLLISION_H
#define FOUNTAIN_SQUARE_MESH_COLLISION_H

#include "collision.h"

#define FOUNTAIN_SQUARE_WALL_COUNT  84
#define FOUNTAIN_SQUARE_FLOOR_COUNT 20

void fountain_square_collision_init(CollisionRoom *r);

#endif /* FOUNTAIN_SQUARE_MESH_COLLISION_H */
