/*
 * Auto-generated collision data from: Gaol Entry mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  4
 * Floors: 1
 * Bounds: X(-300 to 899)  Z(-500 to 1700)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "gaol_entry_mesh_collision.h"

void gaol_entry_collision_init(CollisionRoom *r) {
    r->wall_count = GAOL_ENTRY_WALL_COUNT;
    /* FLAT, SINGLE-STOREY, so 0. One box, one floor face at y=0. */
    r->multi_level     = 0;
    /* Four outer walls, all full height: nothing to shoot over. */
    r->shoot_over_mask = 0;
    r->min_x = -300;
    r->max_x = 899;
    r->min_z = -500;
    r->max_z = 1700;

    /* Wall 0 (avg Y: -400) */
    r->walls[0].x1 =     899;  r->walls[0].z1 =    1700;
    r->walls[0].x2 =    -300;  r->walls[0].z2 =    1700;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;
    r->walls[0].y_min =    -800;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -400) */
    r->walls[1].x1 =    -300;  r->walls[1].z1 =    -500;
    r->walls[1].x2 =     899;  r->walls[1].z2 =    -500;
    r->walls[1].nx =       0;  r->walls[1].nz =    4096;
    r->walls[1].y_min =    -800;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -400) */
    r->walls[2].x1 =    -300;  r->walls[2].z1 =    1700;
    r->walls[2].x2 =    -300;  r->walls[2].z2 =    -500;
    r->walls[2].nx =    4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -800;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -400) */
    r->walls[3].x1 =     899;  r->walls[3].z1 =    -500;
    r->walls[3].x2 =     899;  r->walls[3].z2 =    1700;
    r->walls[3].nx =   -4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -800;  r->walls[3].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-300 to 899)  z(-500 to 1700)
     */
}
