/*
 * Auto-generated collision data from: Gaol Entry mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * NOTE: src/ is not byte-identical to assets/ - the #include is lowercased and
 *       r->multi_level / r->shoot_over_mask are added by hand (STEP 4c of
 *       tools/ADDING_A_ROOM.txt). Regenerate into assets/ and re-apply those.
 */

#ifndef GAOL_ENTRY_MESH_COLLISION_H
#define GAOL_ENTRY_MESH_COLLISION_H

#include "collision.h"

#define GAOL_ENTRY_WALL_COUNT  4
#define GAOL_ENTRY_FLOOR_COUNT 1

void gaol_entry_collision_init(CollisionRoom *r);

#endif /* GAOL_ENTRY_MESH_COLLISION_H */
