/*
 * Auto-generated collision data from: Garden Courtyard mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead.
 *
 * NOTE: src/ is not byte-identical to assets/ — the copy here has its #include
 * lowercased and r->multi_level / r->shoot_over_mask added by hand (see
 * tools/ADDING_A_ROOM.txt STEP 4c).
 */

#ifndef GARDEN_COURTYARD_MESH_COLLISION_H
#define GARDEN_COURTYARD_MESH_COLLISION_H

#include "collision.h"

#define GARDEN_COURTYARD_WALL_COUNT  10
#define GARDEN_COURTYARD_FLOOR_COUNT 7

void garden_courtyard_collision_init(CollisionRoom *r);

#endif /* GARDEN_COURTYARD_MESH_COLLISION_H */
