/*
 * Auto-generated collision data from: Greenhouse mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead.
 *
 * NOTE: src/ is not byte-identical to assets/garden/ - see the .c's header.
 */

#ifndef GREENHOUSE_MESH_COLLISION_H
#define GREENHOUSE_MESH_COLLISION_H

#include "collision.h"

#define GREENHOUSE_WALL_COUNT  38
#define GREENHOUSE_FLOOR_COUNT 5

void greenhouse_collision_init(CollisionRoom *r);

#endif /* GREENHOUSE_MESH_COLLISION_H */
