#ifndef GRINDER_TEX_MAP_H
#define GRINDER_TEX_MAP_H

/* Per-primitive texture slot for the grinder prop, in SMD primitive order
   (matches Grinder.smx poly order). Resolved by texture NAME so a change to
   the SMX <textures> ordering can't silently mis-map (see MESH_CONVERSION_NOTES).
     slot 0 = plinth  (reused from the room's resident plinth texture)
     slot 1 = grinder (the prop's own startup-resident texture, and the
                       faces that need the half-page U remap in grinder.c)
   Generated by gen_grinder_tex_map.py. */
#define GRINDER_PRIM_COUNT 18

static const unsigned char grinder_tex_map[GRINDER_PRIM_COUNT] = {
    1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
    1, 1,
};

#endif
