/*
 * Auto-generated collision data from: Incinerator Room mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * NOTE: src/ is not byte-identical to assets/ — the #include is lowercased and
 *       r->multi_level / r->shoot_over_mask are added by hand (STEP 4c of
 *       tools/ADDING_A_ROOM.txt). Regenerate into assets/ and re-apply those.
 */

#ifndef INCINERATOR_ROOM_MESH_COLLISION_H
#define INCINERATOR_ROOM_MESH_COLLISION_H

#include "collision.h"

#define INCINERATOR_ROOM_WALL_COUNT  8
#define INCINERATOR_ROOM_FLOOR_COUNT 2

void incinerator_room_collision_init(CollisionRoom *r);

#endif /* INCINERATOR_ROOM_MESH_COLLISION_H */
