/*
 * Auto-generated collision data from: kitchen_dining_mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef KITCHEN_DINING_MESH_COLLISION_H
#define KITCHEN_DINING_MESH_COLLISION_H

#include "collision.h"

#define KITCHEN_DINING_WALL_COUNT  32
#define KITCHEN_DINING_FLOOR_COUNT 8

void kitchen_dining_collision_init(CollisionRoom *r);

#endif /* KITCHEN_DINING_MESH_COLLISION_H */
