/*
 * Auto-generated collision data from: kitchen_dining_mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  32
 * Floors: 8
 * Bounds: X(-3294 to 600)  Z(-1699 to 1000)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "kitchen_dining_mesh_collision.h"

void kitchen_dining_collision_init(CollisionRoom *r) {
    r->wall_count = KITCHEN_DINING_WALL_COUNT;
    r->min_x = -3294;
    r->max_x = 600;
    r->min_z = -1699;
    r->max_z = 1000;

    /* Wall 0 (avg Y: -104) */
    r->walls[0].x1 =     150;  r->walls[0].z1 =    -660;
    r->walls[0].x2 =    -150;  r->walls[0].z2 =    -660;
    r->walls[0].nx =       0;  r->walls[0].nz =   -4096;

    /* Wall 1 (avg Y: -104) */
    r->walls[1].x1 =    -150;  r->walls[1].z1 =    -660;
    r->walls[1].x2 =    -150;  r->walls[1].z2 =     479;
    r->walls[1].nx =   -4096;  r->walls[1].nz =       0;

    /* Wall 2 (avg Y: -104) */
    r->walls[2].x1 =    -150;  r->walls[2].z1 =     479;
    r->walls[2].x2 =     150;  r->walls[2].z2 =     479;
    r->walls[2].nx =       0;  r->walls[2].nz =    4096;

    /* Wall 3 (avg Y: -104) */
    r->walls[3].x1 =     150;  r->walls[3].z1 =     479;
    r->walls[3].x2 =     150;  r->walls[3].z2 =    -660;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;

    /* Wall 4 (avg Y: -187) */
    r->walls[4].x1 =     450;  r->walls[4].z1 =   -1000;
    r->walls[4].x2 =     600;  r->walls[4].z2 =   -1000;
    r->walls[4].nx =       0;  r->walls[4].nz =    4096;

    /* Wall 5 (avg Y: -187) */
    r->walls[5].x1 =    -600;  r->walls[5].z1 =    1000;
    r->walls[5].x2 =    -600;  r->walls[5].z2 =    -249;
    r->walls[5].nx =    4096;  r->walls[5].nz =       0;

    /* Wall 6 (avg Y: -187) */
    r->walls[6].x1 =    -600;  r->walls[6].z1 =   -1000;
    r->walls[6].x2 =    -450;  r->walls[6].z2 =   -1000;
    r->walls[6].nx =       0;  r->walls[6].nz =    4096;

    /* Wall 7 (avg Y: -187) */
    r->walls[7].x1 =     150;  r->walls[7].z1 =   -1000;
    r->walls[7].x2 =     150;  r->walls[7].z2 =   -1025;
    r->walls[7].nx =    4096;  r->walls[7].nz =       0;

    /* Wall 8 (avg Y: -187) */
    r->walls[8].x1 =     450;  r->walls[8].z1 =   -1025;
    r->walls[8].x2 =     450;  r->walls[8].z2 =   -1000;
    r->walls[8].nx =   -4096;  r->walls[8].nz =       0;

    /* Wall 9 (avg Y: -187) */
    r->walls[9].x1 =    -450;  r->walls[9].z1 =   -1000;
    r->walls[9].x2 =    -450;  r->walls[9].z2 =   -1025;
    r->walls[9].nx =    4096;  r->walls[9].nz =       0;

    /* Wall 10 (avg Y: -187) */
    r->walls[10].x1 =    -150;  r->walls[10].z1 =   -1025;
    r->walls[10].x2 =    -150;  r->walls[10].z2 =   -1000;
    r->walls[10].nx =   -4096;  r->walls[10].nz =       0;

    /* Wall 11 (avg Y: -187) */
    r->walls[11].x1 =    -450;  r->walls[11].z1 =   -1025;
    r->walls[11].x2 =    -581;  r->walls[11].z2 =   -1025;
    r->walls[11].nx =       0;  r->walls[11].nz =   -4096;

    /* Wall 12 (avg Y: -187) */
    r->walls[12].x1 =     591;  r->walls[12].z1 =   -1025;
    r->walls[12].x2 =     450;  r->walls[12].z2 =   -1025;
    r->walls[12].nx =       0;  r->walls[12].nz =   -4096;

    /* Wall 13 (avg Y: -187) */
    r->walls[13].x1 =      -8;  r->walls[13].z1 =   -1025;
    r->walls[13].x2 =    -150;  r->walls[13].z2 =   -1025;
    r->walls[13].nx =       0;  r->walls[13].nz =   -4096;

    /* Wall 14 (avg Y: -187) */
    r->walls[14].x1 =     150;  r->walls[14].z1 =   -1025;
    r->walls[14].x2 =      18;  r->walls[14].z2 =   -1025;
    r->walls[14].nx =       0;  r->walls[14].nz =   -4096;

    /* Wall 15 (avg Y: -187) */
    r->walls[15].x1 =    -600;  r->walls[15].z1 =    -500;
    r->walls[15].x2 =    -600;  r->walls[15].z2 =   -1000;
    r->walls[15].nx =    4096;  r->walls[15].nz =       0;

    /* Wall 16 (avg Y: -187) */
    r->walls[16].x1 =    -600;  r->walls[16].z1 =    -249;
    r->walls[16].x2 =    -629;  r->walls[16].z2 =    -249;
    r->walls[16].nx =       0;  r->walls[16].nz =   -4096;

    /* Wall 17 (avg Y: -187) */
    r->walls[17].x1 =    -629;  r->walls[17].z1 =    -500;
    r->walls[17].x2 =    -600;  r->walls[17].z2 =    -500;
    r->walls[17].nx =       0;  r->walls[17].nz =    4096;

    /* Wall 18 (avg Y: -187) */
    r->walls[18].x1 =    -629;  r->walls[18].z1 =   -1000;
    r->walls[18].x2 =    -629;  r->walls[18].z2 =    -500;
    r->walls[18].nx =   -4096;  r->walls[18].nz =       0;

    /* Wall 19 (avg Y: -250) */
    r->walls[19].x1 =     600;  r->walls[19].z1 =    1000;
    r->walls[19].x2 =    -600;  r->walls[19].z2 =    1000;
    r->walls[19].nx =       0;  r->walls[19].nz =   -4096;

    /* Wall 20 (avg Y: -187) */
    r->walls[20].x1 =    -629;  r->walls[20].z1 =    -249;
    r->walls[20].x2 =    -629;  r->walls[20].z2 =    1000;
    r->walls[20].nx =   -4096;  r->walls[20].nz =       0;

    /* Wall 21 (avg Y: -375) */
    r->walls[21].x1 =    -629;  r->walls[21].z1 =    1000;
    r->walls[21].x2 =   -3294;  r->walls[21].z2 =    1000;
    r->walls[21].nx =       0;  r->walls[21].nz =   -4096;

    /* Wall 22 (avg Y: -375) */
    r->walls[22].x1 =   -3294;  r->walls[22].z1 =    1000;
    r->walls[22].x2 =   -3294;  r->walls[22].z2 =   -1000;
    r->walls[22].nx =    4096;  r->walls[22].nz =       0;

    /* Wall 23 (avg Y: -375) */
    r->walls[23].x1 =   -3294;  r->walls[23].z1 =   -1000;
    r->walls[23].x2 =    -629;  r->walls[23].z2 =   -1000;
    r->walls[23].nx =       0;  r->walls[23].nz =    4096;

    /* Wall 24 (avg Y: -250) */
    r->walls[24].x1 =     600;  r->walls[24].z1 =   -1000;
    r->walls[24].x2 =     600;  r->walls[24].z2 =    1000;
    r->walls[24].nx =   -4096;  r->walls[24].nz =       0;

    /* Wall 25 (avg Y: -235) */
    r->walls[25].x1 =     591;  r->walls[25].z1 =   -1699;
    r->walls[25].x2 =     591;  r->walls[25].z2 =   -1025;
    r->walls[25].nx =   -4096;  r->walls[25].nz =       0;

    /* Wall 26 (avg Y: -235) */
    r->walls[26].x1 =      18;  r->walls[26].z1 =   -1699;
    r->walls[26].x2 =     591;  r->walls[26].z2 =   -1699;
    r->walls[26].nx =       0;  r->walls[26].nz =    4096;

    /* Wall 27 (avg Y: -235) */
    r->walls[27].x1 =      18;  r->walls[27].z1 =   -1025;
    r->walls[27].x2 =      18;  r->walls[27].z2 =   -1699;
    r->walls[27].nx =    4096;  r->walls[27].nz =       0;

    /* Wall 28 (avg Y: -235) */
    r->walls[28].x1 =      -8;  r->walls[28].z1 =   -1699;
    r->walls[28].x2 =      -8;  r->walls[28].z2 =   -1025;
    r->walls[28].nx =   -4096;  r->walls[28].nz =       0;

    /* Wall 29 (avg Y: -235) */
    r->walls[29].x1 =    -581;  r->walls[29].z1 =   -1025;
    r->walls[29].x2 =    -581;  r->walls[29].z2 =   -1699;
    r->walls[29].nx =    4096;  r->walls[29].nz =       0;

    /* Wall 30 (avg Y: -235) */
    r->walls[30].x1 =    -581;  r->walls[30].z1 =   -1699;
    r->walls[30].x2 =      -8;  r->walls[30].z2 =   -1699;
    r->walls[30].nx =       0;  r->walls[30].nz =    4096;

    /* Wall 31 (avg Y: -187) */
    r->walls[31].x1 =    -150;  r->walls[31].z1 =   -1000;
    r->walls[31].x2 =     150;  r->walls[31].z2 =   -1000;
    r->walls[31].nx =       0;  r->walls[31].nz =    4096;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=  -208  x(-150 to 150)  z(-660 to 479)
     * FLOOR   1: y=     0  x(150 to 450)  z(-1025 to -1000)
     * FLOOR   2: y=     0  x(-450 to -150)  z(-1025 to -1000)
     * FLOOR   3: y=     0  x(-629 to -600)  z(-500 to -249)
     * FLOOR   4: y=     0  x(-3294 to -629)  z(-1000 to 1000)
     * FLOOR   5: y=     0  x(-600 to 600)  z(-1000 to 1000)
     * FLOOR   6: y=     0  x(-581 to -8)  z(-1699 to -1025)
     * FLOOR   7: y=     0  x(18 to 591)  z(-1699 to -1025)
     */

#ifdef DEBUG_COLLISION
    {
        int i;
        for (i = 0; i < KITCHEN_DINING_WALL_COUNT; i++) {
            r->walls[i].y_max = -375;   /* bottom (debug viz only; kitchen is flat) */
            r->walls[i].y_min = -600;   /* top */
        }
    }
#endif
}
