/*
 * Auto-generated collision data from: Library mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 *
 * NOTE: src/ is NOT byte-identical to assets/. The copy here has its #include
 * lowercased and carries the r->multi_level / r->shoot_over_mask fields the
 * generator does not emit. Re-apply both after any regeneration.
 */

#ifndef LIBRARY_MESH_COLLISION_H
#define LIBRARY_MESH_COLLISION_H

#include "collision.h"

#define LIBRARY_WALL_COUNT  14
#define LIBRARY_FLOOR_COUNT 2

void library_collision_init(CollisionRoom *r);

#endif /* LIBRARY_MESH_COLLISION_H */
