/*
 * Auto-generated collision data from: Maze Two mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 *
 * NOTE: src/ is NOT byte-identical to assets/garden/. The generator's output is
 * copied here and then hand-edited in two places the generator does not emit —
 * the lowercase #include, and r->multi_level / r->shoot_over_mask in the .c.
 * Re-copy after a regeneration and re-apply both.
 */

#ifndef MAZE_TWO_MESH_COLLISION_H
#define MAZE_TWO_MESH_COLLISION_H

#include "collision.h"

#define MAZE_TWO_WALL_COUNT  48
#define MAZE_TWO_FLOOR_COUNT 17

void maze_two_collision_init(CollisionRoom *r);

#endif /* MAZE_TWO_MESH_COLLISION_H */
