/*
 * Auto-generated collision data from: North Chamber mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 *
 * src/ is NOT byte-identical to assets/: the .c here carries the lowercase
 * #include plus r->multi_level and r->shoot_over_mask, which the generator does
 * not emit. Re-apply all three after any re-export (tools/ADDING_A_ROOM.txt
 * STEP 4c).
 */

#ifndef NORTH_CHAMBER_MESH_COLLISION_H
#define NORTH_CHAMBER_MESH_COLLISION_H

#include "collision.h"

#define NORTH_CHAMBER_WALL_COUNT  23
#define NORTH_CHAMBER_FLOOR_COUNT 12

void north_chamber_collision_init(CollisionRoom *r);

#endif /* NORTH_CHAMBER_MESH_COLLISION_H */
