/*
 * Auto-generated collision data from: Nursery mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  8
 * Floors: 3
 * Bounds: X(-1293 to 1293)  Z(-1293 to 1293)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "nursery_mesh_collision.h"

void nursery_collision_init(CollisionRoom *r) {
    r->wall_count = NURSERY_WALL_COUNT;
    /* FLAT, SINGLE-STOREY, so 0 - the Room of Torsos' case. The proxy found
       three floor faces and all three are at y=0. */
    r->multi_level     = 0;
    /* Nothing low to shoot over: the eight walls are the octagon, all
       y[-1200,0]. The cribs and the Gula Tablet are prop boxes, not walls. */
    r->shoot_over_mask = 0;
    r->min_x = -1293;
    r->max_x = 1293;
    r->min_z = -1293;
    r->max_z = 1293;

    /* Wall 0 (avg Y: -600) */
    r->walls[0].x1 =     535;  r->walls[0].z1 =   -1293;
    r->walls[0].x2 =    1293;  r->walls[0].z2 =    -535;
    r->walls[0].nx =   -2896;  r->walls[0].nz =    2896;
    r->walls[0].y_min =   -1200;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -600) */
    r->walls[1].x1 =   -1293;  r->walls[1].z1 =    -535;
    r->walls[1].x2 =    -535;  r->walls[1].z2 =   -1293;
    r->walls[1].nx =    2896;  r->walls[1].nz =    2896;
    r->walls[1].y_min =   -1200;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -600) */
    r->walls[2].x1 =     535;  r->walls[2].z1 =    1293;
    r->walls[2].x2 =    -535;  r->walls[2].z2 =    1293;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4096;
    r->walls[2].y_min =   -1200;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -600) */
    r->walls[3].x1 =   -1293;  r->walls[3].z1 =     535;
    r->walls[3].x2 =   -1293;  r->walls[3].z2 =    -535;
    r->walls[3].nx =    4095;  r->walls[3].nz =       0;
    r->walls[3].y_min =   -1200;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -600) */
    r->walls[4].x1 =    -535;  r->walls[4].z1 =   -1293;
    r->walls[4].x2 =     535;  r->walls[4].z2 =   -1293;
    r->walls[4].nx =       0;  r->walls[4].nz =    4096;
    r->walls[4].y_min =   -1200;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -600) */
    r->walls[5].x1 =    -535;  r->walls[5].z1 =    1293;
    r->walls[5].x2 =   -1293;  r->walls[5].z2 =     535;
    r->walls[5].nx =    2896;  r->walls[5].nz =   -2896;
    r->walls[5].y_min =   -1200;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -600) */
    r->walls[6].x1 =    1293;  r->walls[6].z1 =    -535;
    r->walls[6].x2 =    1293;  r->walls[6].z2 =     535;
    r->walls[6].nx =   -4095;  r->walls[6].nz =       0;
    r->walls[6].y_min =   -1200;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -600) */
    r->walls[7].x1 =    1293;  r->walls[7].z1 =     535;
    r->walls[7].x2 =     535;  r->walls[7].z2 =    1293;
    r->walls[7].nx =   -2896;  r->walls[7].nz =   -2896;
    r->walls[7].y_min =   -1200;  r->walls[7].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-1293 to -535)  z(-1293 to 1293)
     * FLOOR   1: y=     0  x(535 to 1293)  z(-1293 to 1293)
     * FLOOR   2: y=     0  x(-535 to 535)  z(-1293 to 1293)
     */
}
