/*
 * Auto-generated collision data from: Nursery mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * NOTE: src/ is not byte-identical to assets/ - the #include is lowercased and
 *       r->multi_level / r->shoot_over_mask are added by hand (STEP 4c of
 *       tools/ADDING_A_ROOM.txt). Regenerate into assets/ and re-apply those.
 */

#ifndef NURSERY_MESH_COLLISION_H
#define NURSERY_MESH_COLLISION_H

#include "collision.h"

#define NURSERY_WALL_COUNT  8
#define NURSERY_FLOOR_COUNT 3

void nursery_collision_init(CollisionRoom *r);

#endif /* NURSERY_MESH_COLLISION_H */
