/*
 * Auto-generated collision data from: Rear Gate mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  40
 * Floors: 13
 * Bounds: X(-2200 to 2200)  Z(-3200 to 4106)
 * Normal scale: 4096 = 1.0 (fixed point)
 *
 * NOT byte-identical to assets/garden/Rear Gate mesh_collision.c: the #include
 * below was lowercased and multi_level / shoot_over_mask added by hand, neither
 * of which the generator emits (tools/ADDING_A_ROOM.txt STEP 4c). Regenerate
 * from the SMX and re-apply those two, rather than editing the wall data here.
 *
 * READ THIS BEFORE TRUSTING THE FLOOR LIST AT THE BOTTOM. "FLOOR 9: y=-250" is
 * not a plane; it is the generator averaging a RAMP. The real surface climbs
 * linearly from y=0 at z=-2100 to y=-500 at z=-3200, and src/rear_gate.c models
 * it as a FLOOR_RAMP zone, not as a flat floor at -250. Every other floor in
 * the list is genuinely at y=0.
 *
 * WALL 39, and the full-height y_min on walls 27 and 33, EXIST ONLY BECAUSE THE
 * GENERATOR WAS FIXED. They are the south brick wall's upper band, standing on
 * the TOP of that ramp rather than on a level floor, and smx_to_collision.py
 * used to throw every one of them away as "above the ceiling" because a ramp
 * registered only its LOW end as a floor level. It did so silently — the wall
 * count came back unchanged from a mesh that had grown by three faces. If this
 * room is ever re-exported with an older copy of the tool the door end of the
 * ramp will quietly open up again; see the note in assets/smx_to_collision.py.
 */

#include "rear_gate_mesh_collision.h"

void rear_gate_collision_init(CollisionRoom *r) {
    r->wall_count = REAR_GATE_WALL_COUNT;
    /* 0, like every other garden room. The walls DO carry real Y data — the
       500-tall hedge runs, the 200-tall plinth, the 1237-tall brick wall — but
       multi_level is not a "has per-wall Y" flag: collide_wall_frontonly_y gates
       on Y regardless of it, so the player is already held correctly all the way
       up the ramp. What the flag actually switches is the hitscan Y-gate and, in
       apply_ddog_collision, a branch into delivery_collide_walls() — a
       hand-picked list of DELIVERY's wall indices, which applied here would let
       a dog walk out through most of this room. Leave it 0. */
    r->multi_level = 0;
    r->shoot_over_mask = 0;   /* no low walls the gun shoots over */
    r->min_x = -2200;
    r->max_x = 2200;
    r->min_z = -3200;
    r->max_z = 4106;

    /* Wall 0 (avg Y: -250) */
    r->walls[0].x1 =    -300;  r->walls[0].z1 =    1500;
    r->walls[0].x2 =    -300;  r->walls[0].z2 =   -1500;
    r->walls[0].nx =    4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -500;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -250) */
    r->walls[1].x1 =     300;  r->walls[1].z1 =   -1500;
    r->walls[1].x2 =     300;  r->walls[1].z2 =    1500;
    r->walls[1].nx =   -4096;  r->walls[1].nz =       0;
    r->walls[1].y_min =    -500;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -100) */
    r->walls[2].x1 =     300;  r->walls[2].z1 =    2500;
    r->walls[2].x2 =    -300;  r->walls[2].z2 =    2500;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4096;
    r->walls[2].y_min =    -200;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -250) */
    r->walls[3].x1 =    1299;  r->walls[3].z1 =    3600;
    r->walls[3].x2 =    1299;  r->walls[3].z2 =    4106;
    r->walls[3].nx =   -4095;  r->walls[3].nz =       2;
    r->walls[3].y_min =    -500;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -250) */
    r->walls[4].x1 =   -1300;  r->walls[4].z1 =    4100;
    r->walls[4].x2 =   -1300;  r->walls[4].z2 =    3600;
    r->walls[4].nx =    4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -500;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -250) */
    r->walls[5].x1 =    2000;  r->walls[5].z1 =    2500;
    r->walls[5].x2 =    1800;  r->walls[5].z2 =    2500;
    r->walls[5].nx =       0;  r->walls[5].nz =   -4096;
    r->walls[5].y_min =    -500;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -250) */
    r->walls[6].x1 =    1800;  r->walls[6].z1 =    2500;
    r->walls[6].x2 =    1800;  r->walls[6].z2 =    3600;
    r->walls[6].nx =   -4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =    -500;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -250) */
    r->walls[7].x1 =    1800;  r->walls[7].z1 =    3600;
    r->walls[7].x2 =    1299;  r->walls[7].z2 =    3600;
    r->walls[7].nx =       0;  r->walls[7].nz =   -4096;
    r->walls[7].y_min =    -500;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -250) */
    r->walls[8].x1 =   -1799;  r->walls[8].z1 =    3600;
    r->walls[8].x2 =   -1799;  r->walls[8].z2 =    2500;
    r->walls[8].nx =    4096;  r->walls[8].nz =       0;
    r->walls[8].y_min =    -500;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -250) */
    r->walls[9].x1 =   -1300;  r->walls[9].z1 =    3600;
    r->walls[9].x2 =   -1799;  r->walls[9].z2 =    3600;
    r->walls[9].nx =       0;  r->walls[9].nz =   -4096;
    r->walls[9].y_min =    -500;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -250) */
    r->walls[10].x1 =    2000;  r->walls[10].z1 =    2300;
    r->walls[10].x2 =    2000;  r->walls[10].z2 =    2500;
    r->walls[10].nx =   -4096;  r->walls[10].nz =       0;
    r->walls[10].y_min =    -500;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -250) */
    r->walls[11].x1 =   -2000;  r->walls[11].z1 =    2500;
    r->walls[11].x2 =   -2000;  r->walls[11].z2 =    2300;
    r->walls[11].nx =    4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -500;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -250) */
    r->walls[12].x1 =   -1799;  r->walls[12].z1 =    2500;
    r->walls[12].x2 =   -2000;  r->walls[12].z2 =    2500;
    r->walls[12].nx =       0;  r->walls[12].nz =   -4096;
    r->walls[12].y_min =    -500;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -250) */
    r->walls[13].x1 =    1300;  r->walls[13].z1 =    4093;
    r->walls[13].x2 =   -1300;  r->walls[13].z2 =    4100;
    r->walls[13].nx =     -10;  r->walls[13].nz =   -4095;
    r->walls[13].y_min =    -500;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -250) */
    r->walls[14].x1 =    -900;  r->walls[14].z1 =    1500;
    r->walls[14].x2 =    -300;  r->walls[14].z2 =    1500;
    r->walls[14].nx =       0;  r->walls[14].nz =    4096;
    r->walls[14].y_min =    -500;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -250) */
    r->walls[15].x1 =     300;  r->walls[15].z1 =    1500;
    r->walls[15].x2 =     900;  r->walls[15].z2 =    1500;
    r->walls[15].nx =       0;  r->walls[15].nz =    4096;
    r->walls[15].y_min =    -500;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -250) */
    r->walls[16].x1 =     900;  r->walls[16].z1 =    1299;
    r->walls[16].x2 =    2000;  r->walls[16].z2 =    1299;
    r->walls[16].nx =       0;  r->walls[16].nz =    4096;
    r->walls[16].y_min =    -500;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -250) */
    r->walls[17].x1 =    2200;  r->walls[17].z1 =    1500;
    r->walls[17].x2 =    2200;  r->walls[17].z2 =    2300;
    r->walls[17].nx =   -4096;  r->walls[17].nz =       0;
    r->walls[17].y_min =    -500;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -250) */
    r->walls[18].x1 =    -900;  r->walls[18].z1 =    1299;
    r->walls[18].x2 =    -900;  r->walls[18].z2 =    1500;
    r->walls[18].nx =   -4096;  r->walls[18].nz =       0;
    r->walls[18].y_min =    -500;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -250) */
    r->walls[19].x1 =     900;  r->walls[19].z1 =    1500;
    r->walls[19].x2 =     900;  r->walls[19].z2 =    1299;
    r->walls[19].nx =    4096;  r->walls[19].nz =       0;
    r->walls[19].y_min =    -500;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -250) */
    r->walls[20].x1 =    2000;  r->walls[20].z1 =    1299;
    r->walls[20].x2 =    2000;  r->walls[20].z2 =    1500;
    r->walls[20].nx =   -4096;  r->walls[20].nz =       0;
    r->walls[20].y_min =    -500;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -250) */
    r->walls[21].x1 =   -2000;  r->walls[21].z1 =    1500;
    r->walls[21].x2 =   -2000;  r->walls[21].z2 =    1299;
    r->walls[21].nx =    4096;  r->walls[21].nz =       0;
    r->walls[21].y_min =    -500;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -250) */
    r->walls[22].x1 =    2200;  r->walls[22].z1 =    2300;
    r->walls[22].x2 =    2000;  r->walls[22].z2 =    2300;
    r->walls[22].nx =       0;  r->walls[22].nz =   -4096;
    r->walls[22].y_min =    -500;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -250) */
    r->walls[23].x1 =   -2000;  r->walls[23].z1 =    2300;
    r->walls[23].x2 =   -2200;  r->walls[23].z2 =    2300;
    r->walls[23].nx =       0;  r->walls[23].nz =   -4096;
    r->walls[23].y_min =    -500;  r->walls[23].y_max =       0;

    /* Wall 24 (avg Y: -166) */
    r->walls[24].x1 =    -300;  r->walls[24].z1 =   -3200;
    r->walls[24].x2 =    -300;  r->walls[24].z2 =   -2100;
    r->walls[24].nx =   -4096;  r->walls[24].nz =       0;
    r->walls[24].y_min =    -500;  r->walls[24].y_max =       0;

    /* Wall 25 (avg Y: -250) */
    r->walls[25].x1 =     899;  r->walls[25].z1 =   -1500;
    r->walls[25].x2 =     300;  r->walls[25].z2 =   -1500;
    r->walls[25].nx =       0;  r->walls[25].nz =   -4096;
    r->walls[25].y_min =    -500;  r->walls[25].y_max =       0;

    /* Wall 26 (avg Y: -166) */
    r->walls[26].x1 =     300;  r->walls[26].z1 =   -2100;
    r->walls[26].x2 =     300;  r->walls[26].z2 =   -3200;
    r->walls[26].nx =    4096;  r->walls[26].nz =       0;
    r->walls[26].y_min =    -500;  r->walls[26].y_max =       0;

    /* Wall 27 (avg Y: -250) */
    r->walls[27].x1 =    -900;  r->walls[27].z1 =   -3200;
    r->walls[27].x2 =    -300;  r->walls[27].z2 =   -3200;
    r->walls[27].nx =       0;  r->walls[27].nz =    4096;
    r->walls[27].y_min =   -1237;  r->walls[27].y_max =       0;

    /* Wall 28 (avg Y: -250) */
    r->walls[28].x1 =    -300;  r->walls[28].z1 =   -1500;
    r->walls[28].x2 =    -900;  r->walls[28].z2 =   -1500;
    r->walls[28].nx =       0;  r->walls[28].nz =   -4096;
    r->walls[28].y_min =    -500;  r->walls[28].y_max =       0;

    /* Wall 29 (avg Y: -250) */
    r->walls[29].x1 =    2000;  r->walls[29].z1 =    1500;
    r->walls[29].x2 =    2200;  r->walls[29].z2 =    1500;
    r->walls[29].nx =       0;  r->walls[29].nz =    4096;
    r->walls[29].y_min =    -500;  r->walls[29].y_max =       0;

    /* Wall 30 (avg Y: -250) */
    r->walls[30].x1 =    -900;  r->walls[30].z1 =   -1500;
    r->walls[30].x2 =    -900;  r->walls[30].z2 =   -3200;
    r->walls[30].nx =    4096;  r->walls[30].nz =       0;
    r->walls[30].y_min =    -500;  r->walls[30].y_max =       0;

    /* Wall 31 (avg Y: -250) */
    r->walls[31].x1 =   -2200;  r->walls[31].z1 =    1500;
    r->walls[31].x2 =   -2000;  r->walls[31].z2 =    1500;
    r->walls[31].nx =       0;  r->walls[31].nz =    4096;
    r->walls[31].y_min =    -500;  r->walls[31].y_max =       0;

    /* Wall 32 (avg Y: -250) */
    r->walls[32].x1 =     899;  r->walls[32].z1 =   -3200;
    r->walls[32].x2 =     899;  r->walls[32].z2 =   -1500;
    r->walls[32].nx =   -4096;  r->walls[32].nz =       0;
    r->walls[32].y_min =    -500;  r->walls[32].y_max =       0;

    /* Wall 33 (avg Y: -250) */
    r->walls[33].x1 =     300;  r->walls[33].z1 =   -3200;
    r->walls[33].x2 =     899;  r->walls[33].z2 =   -3200;
    r->walls[33].nx =       0;  r->walls[33].nz =    4096;
    r->walls[33].y_min =   -1237;  r->walls[33].y_max =       0;

    /* Wall 34 (avg Y: -100) */
    r->walls[34].x1 =    -300;  r->walls[34].z1 =    2500;
    r->walls[34].x2 =    -300;  r->walls[34].z2 =    3100;
    r->walls[34].nx =   -4096;  r->walls[34].nz =       0;
    r->walls[34].y_min =    -200;  r->walls[34].y_max =       0;

    /* Wall 35 (avg Y: -100) */
    r->walls[35].x1 =    -300;  r->walls[35].z1 =    3100;
    r->walls[35].x2 =     300;  r->walls[35].z2 =    3100;
    r->walls[35].nx =       0;  r->walls[35].nz =    4096;
    r->walls[35].y_min =    -200;  r->walls[35].y_max =       0;

    /* Wall 36 (avg Y: -100) */
    r->walls[36].x1 =     300;  r->walls[36].z1 =    3100;
    r->walls[36].x2 =     300;  r->walls[36].z2 =    2500;
    r->walls[36].nx =    4096;  r->walls[36].nz =       0;
    r->walls[36].y_min =    -200;  r->walls[36].y_max =       0;

    /* Wall 37 (avg Y: -250) */
    r->walls[37].x1 =   -2200;  r->walls[37].z1 =    2300;
    r->walls[37].x2 =   -2200;  r->walls[37].z2 =    1500;
    r->walls[37].nx =    4096;  r->walls[37].nz =       0;
    r->walls[37].y_min =    -500;  r->walls[37].y_max =       0;

    /* Wall 38 (avg Y: -250) */
    r->walls[38].x1 =   -2000;  r->walls[38].z1 =    1299;
    r->walls[38].x2 =    -900;  r->walls[38].z2 =    1299;
    r->walls[38].nx =       0;  r->walls[38].nz =    4096;
    r->walls[38].y_min =    -500;  r->walls[38].y_max =       0;

    /* Wall 39 (avg Y: -868) */
    r->walls[39].x1 =    -300;  r->walls[39].z1 =   -3200;
    r->walls[39].x2 =     300;  r->walls[39].z2 =   -3200;
    r->walls[39].nx =       0;  r->walls[39].nz =    4096;
    r->walls[39].y_min =   -1237;  r->walls[39].y_max =    -500;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-1300 to 1300)  z(3600 to 4100)
     * FLOOR   1: y=     0  x(-1799 to 1800)  z(3100 to 3600)
     * FLOOR   2: y=     0  x(-1799 to -300)  z(2500 to 3100)
     * FLOOR   3: y=     0  x(300 to 1800)  z(2500 to 3100)
     * FLOOR   4: y=     0  x(-2000 to 2000)  z(1500 to 2500)
     * FLOOR   5: y=     0  x(900 to 2000)  z(1299 to 1500)
     * FLOOR   6: y=     0  x(2000 to 2200)  z(1500 to 2300)
     * FLOOR   7: y=     0  x(-2200 to -2000)  z(1500 to 2300)
     * FLOOR   8: y=     0  x(-2000 to -900)  z(1299 to 1500)
     * FLOOR   9: y=  -250  x(-300 to 300)  z(-3200 to -2100)
     * FLOOR   10: y=     0  x(-900 to -300)  z(-3200 to -1500)
     * FLOOR   11: y=     0  x(300 to 899)  z(-3200 to -1500)
     * FLOOR   12: y=     0  x(-300 to 300)  z(-2100 to 1500)
     */
}
