/* room_arena_size.h - GENERATED by tools/gen_room_arena.py. DO NOT EDIT.
 *
 * How big the single room-geometry buffer in src/room_arena.c has to be: the
 * largest .smd on the disc, rounded up to whole 2048-byte CD sectors.
 *
 * REGENERATE WHENEVER A ROOM MESH CHANGES SIZE:
 *     py tools/gen_room_arena.py
 *
 * A stale value here is caught at runtime - room_arena_load() refuses a mesh
 * that does not fit and the room draws empty - but fix it here, not there.
 *
 * The ten largest meshes on the disc at generation time:
 *
 *    118764 bytes   58 sectors  maze_one.smd
 *    112076 bytes   55 sectors  up_down_maze.smd
 *    109324 bytes   54 sectors  maze_two.smd
 *     82820 bytes   41 sectors  keystone_maze.smd
 *     79628 bytes   39 sectors  meat_plant.smd
 *     72492 bytes   36 sectors  north_chamber.smd
 *     68444 bytes   34 sectors  rear_gate.smd
 *     67860 bytes   34 sectors  Reception.smd
 *     66740 bytes   33 sectors  sliding_bars_room.smd
 *     65740 bytes   33 sectors  delivery_area.smd
 *
 */
#ifndef ROOM_ARENA_SIZE_H
#define ROOM_ARENA_SIZE_H

#define ROOM_ARENA_SECTORS 58
#define ROOM_ARENA_BYTES   (ROOM_ARENA_SECTORS * 2048)

#endif /* ROOM_ARENA_SIZE_H */
