/*
 * Auto-generated collision data from: Room of Guts mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef ROOM_OF_GUTS_MESH_COLLISION_H
#define ROOM_OF_GUTS_MESH_COLLISION_H

#include "collision.h"

#define ROOM_OF_GUTS_WALL_COUNT  8
#define ROOM_OF_GUTS_FLOOR_COUNT 3

void room_of_guts_collision_init(CollisionRoom *r);

#endif /* ROOM_OF_GUTS_MESH_COLLISION_H */
