/* room_arena_size.h - GENERATED by tools/gen_room_arena.py. DO NOT EDIT.
 *
 * How big the single room-geometry buffer in src/room_arena.c has to be: the
 * largest .smd on the disc, rounded up to whole 2048-byte CD sectors.
 *
 * REGENERATE WHENEVER A ROOM MESH CHANGES SIZE:
 *     py tools/gen_room_arena.py
 *
 * A stale value here is caught at runtime - room_arena_load() refuses a mesh
 * that does not fit and the room draws empty - but fix it here, not there.
 *
 * The ten largest meshes on the disc at generation time:
 *
 *    122340 bytes   60 sectors  maze_one.smd
 *    114824 bytes   57 sectors  up_down_maze.smd
 *    112268 bytes   55 sectors  maze_two.smd
 *     91848 bytes   45 sectors  gaol_cells.smd
 *     85572 bytes   42 sectors  keystone_maze.smd
 *     82512 bytes   41 sectors  meat_plant.smd
 *     74312 bytes   37 sectors  north_chamber.smd
 *     73812 bytes   37 sectors  zig_zag_tomb.smd
 *     70476 bytes   35 sectors  rear_gate.smd
 *     69812 bytes   35 sectors  Reception.smd
 *
 */
#ifndef ROOM_ARENA_SIZE_H
#define ROOM_ARENA_SIZE_H

#define ROOM_ARENA_SECTORS 60
#define ROOM_ARENA_BYTES   (ROOM_ARENA_SECTORS * 2048)

#endif /* ROOM_ARENA_SIZE_H */
