/* room_arena_size.h - GENERATED by tools/gen_room_arena.py. DO NOT EDIT.
 *
 * How big the single room-geometry buffer in src/room_arena.c has to be: the
 * largest .smd on the disc, rounded up to whole 2048-byte CD sectors.
 *
 * REGENERATE WHENEVER A ROOM MESH CHANGES SIZE:
 *     py tools/gen_room_arena.py
 *
 * A stale value here is caught at runtime - room_arena_load() refuses a mesh
 * that does not fit and the room draws empty - but fix it here, not there.
 *
 * The ten largest meshes on the disc at generation time:
 *
 *    117492 bytes   58 sectors  maze_one.smd
 *    109324 bytes   54 sectors  maze_two.smd
 *     67860 bytes   34 sectors  Reception.smd
 *     65836 bytes   33 sectors  outside_catacombs.smd
 *     65740 bytes   33 sectors  delivery_area.smd
 *     45676 bytes   23 sectors  fountain_square.smd
 *     42228 bytes   21 sectors  garden_stairs.smd
 *     40220 bytes   20 sectors  kitchen_dining.smd
 *     36320 bytes   18 sectors  master_bedroom.smd
 *     35924 bytes   18 sectors  attic_exit.smd
 *
 */
#ifndef ROOM_ARENA_SIZE_H
#define ROOM_ARENA_SIZE_H

#define ROOM_ARENA_SECTORS 58
#define ROOM_ARENA_BYTES   (ROOM_ARENA_SECTORS * 2048)

#endif /* ROOM_ARENA_SIZE_H */
