/*
 * Auto-generated collision data from: Room of Heads mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * NOTE: src/ is not byte-identical to assets/ — the #include is lowercased and
 *       r->multi_level / r->shoot_over_mask are added by hand (STEP 4c of
 *       tools/ADDING_A_ROOM.txt). Regenerate into assets/ and re-apply those.
 */

#ifndef ROOM_OF_HEADS_MESH_COLLISION_H
#define ROOM_OF_HEADS_MESH_COLLISION_H

#include "collision.h"

#define ROOM_OF_HEADS_WALL_COUNT  45
#define ROOM_OF_HEADS_FLOOR_COUNT 3

void room_of_heads_collision_init(CollisionRoom *r);

#endif /* ROOM_OF_HEADS_MESH_COLLISION_H */
