/*
 * Auto-generated collision data from: Sliding Bars Room mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * (src/ copy: the .c has the lowercase #include and multi_level /
 *  shoot_over_mask added, so it is not byte-identical to assets/.)
 */

#ifndef SLIDING_BARS_ROOM_MESH_COLLISION_H
#define SLIDING_BARS_ROOM_MESH_COLLISION_H

#include "collision.h"

#define SLIDING_BARS_ROOM_WALL_COUNT  58
#define SLIDING_BARS_ROOM_FLOOR_COUNT 1

void sliding_bars_room_collision_init(CollisionRoom *r);

#endif /* SLIDING_BARS_ROOM_MESH_COLLISION_H */
