/*
 * Auto-generated collision data from: Stables mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  16
 * Floors: 2
 * Bounds: X(-3400 to 100)  Z(-1600 to 1600)
 * Normal scale: 4096 = 1.0 (fixed point)
 *
 * NOT byte-identical to assets/garden/Stables mesh_collision.c: the #include
 * below was lowercased and multi_level / shoot_over_mask added by hand, neither
 * of which the generator emits (tools/ADDING_A_ROOM.txt STEP 4c). Regenerate
 * from the SMX and re-apply those two, rather than editing the wall data here.
 *
 * THE FLOOR LIST AT THE BOTTOM IS HONEST HERE. Both planes are genuinely at
 * y=0 - FLOOR 0 is the yard, FLOOR 1 the little alcove behind the east gate -
 * so unlike the Rear Gate this room needs no FLOOR_RAMP and one flat zone
 * spanning the bounds covers both (see stables_floor_zones_init).
 *
 * REGENERATED from a re-export that FIXED FOUR INVERTED FACES. The NORTHERN
 * stable block (walls 0, 1, 2 and 5, its z=1200 / z=400 / x=-700 / x=-2799
 * faces) came out of the first export with every normal pointing INWARD, so
 * collide_wall_frontonly_y would have let the player walk into the block and
 * then held them inside it. The southern block (walls 3, 4, 13, 14) was right
 * both times, which is exactly the kind of half-wrong that reads as "one
 * building is solid and the other is not" in game rather than as a bad export.
 * Wall counts and floor planes are unchanged; only those four normals and their
 * endpoint order moved.
 */

#include "stables_mesh_collision.h"

void stables_collision_init(CollisionRoom *r) {
    r->wall_count = STABLES_WALL_COUNT;
    /* 0, like every other garden room. The walls carry real Y data (the 500-tall
       perimeter and gate runs, the 600-tall stable blocks) and
       collide_wall_frontonly_y gates on Y regardless of this flag, so the player
       is already held correctly; what multi_level actually switches is the
       hitscan Y-gate and a branch into delivery_collide_walls(), a hand-picked
       list of DELIVERY's wall indices that means nothing here. */
    r->multi_level = 0;
    /* Nothing to shoot over: every wall in this room is at least 500 tall. */
    r->shoot_over_mask = 0;
    r->min_x = -3400;
    r->max_x = 100;
    r->min_z = -1600;
    r->max_z = 1600;

    /* Wall 0 (avg Y: -300) */
    r->walls[0].x1 =   -2799;  r->walls[0].z1 =    1200;
    r->walls[0].x2 =    -700;  r->walls[0].z2 =    1200;
    r->walls[0].nx =       0;  r->walls[0].nz =    4096;
    r->walls[0].y_min =    -600;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -300) */
    r->walls[1].x1 =    -700;  r->walls[1].z1 =     400;
    r->walls[1].x2 =   -2799;  r->walls[1].z2 =     400;
    r->walls[1].nx =       0;  r->walls[1].nz =   -4096;
    r->walls[1].y_min =    -600;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -300) */
    r->walls[2].x1 =    -700;  r->walls[2].z1 =    1200;
    r->walls[2].x2 =    -700;  r->walls[2].z2 =     400;
    r->walls[2].nx =    4096;  r->walls[2].nz =       0;
    r->walls[2].y_min =    -600;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -300) */
    r->walls[3].x1 =    -700;  r->walls[3].z1 =    -400;
    r->walls[3].x2 =    -700;  r->walls[3].z2 =   -1200;
    r->walls[3].nx =    4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -600;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -300) */
    r->walls[4].x1 =   -2799;  r->walls[4].z1 =   -1200;
    r->walls[4].x2 =   -2799;  r->walls[4].z2 =    -400;
    r->walls[4].nx =   -4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -600;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -300) */
    r->walls[5].x1 =   -2799;  r->walls[5].z1 =     400;
    r->walls[5].x2 =   -2799;  r->walls[5].z2 =    1200;
    r->walls[5].nx =   -4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =    -600;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -250) */
    r->walls[6].x1 =    -100;  r->walls[6].z1 =     400;
    r->walls[6].x2 =    -100;  r->walls[6].z2 =    1600;
    r->walls[6].nx =   -4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =    -500;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -250) */
    r->walls[7].x1 =   -3400;  r->walls[7].z1 =   -1600;
    r->walls[7].x2 =    -100;  r->walls[7].z2 =   -1600;
    r->walls[7].nx =       0;  r->walls[7].nz =    4096;
    r->walls[7].y_min =    -500;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -250) */
    r->walls[8].x1 =    -100;  r->walls[8].z1 =    1600;
    r->walls[8].x2 =   -3400;  r->walls[8].z2 =    1600;
    r->walls[8].nx =       0;  r->walls[8].nz =   -4096;
    r->walls[8].y_min =    -500;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -250) */
    r->walls[9].x1 =    -100;  r->walls[9].z1 =    -400;
    r->walls[9].x2 =     100;  r->walls[9].z2 =    -400;
    r->walls[9].nx =       0;  r->walls[9].nz =    4096;
    r->walls[9].y_min =    -500;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -250) */
    r->walls[10].x1 =     100;  r->walls[10].z1 =    -400;
    r->walls[10].x2 =     100;  r->walls[10].z2 =     400;
    r->walls[10].nx =   -4096;  r->walls[10].nz =       0;
    r->walls[10].y_min =    -500;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -250) */
    r->walls[11].x1 =    -100;  r->walls[11].z1 =   -1600;
    r->walls[11].x2 =    -100;  r->walls[11].z2 =    -400;
    r->walls[11].nx =   -4096;  r->walls[11].nz =       0;
    r->walls[11].y_min =    -500;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -250) */
    r->walls[12].x1 =     100;  r->walls[12].z1 =     400;
    r->walls[12].x2 =    -100;  r->walls[12].z2 =     400;
    r->walls[12].nx =       0;  r->walls[12].nz =   -4096;
    r->walls[12].y_min =    -500;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -300) */
    r->walls[13].x1 =    -700;  r->walls[13].z1 =   -1200;
    r->walls[13].x2 =   -2799;  r->walls[13].z2 =   -1200;
    r->walls[13].nx =       0;  r->walls[13].nz =   -4096;
    r->walls[13].y_min =    -600;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -300) */
    r->walls[14].x1 =   -2799;  r->walls[14].z1 =    -400;
    r->walls[14].x2 =    -700;  r->walls[14].z2 =    -400;
    r->walls[14].nx =       0;  r->walls[14].nz =    4096;
    r->walls[14].y_min =    -600;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -250) */
    r->walls[15].x1 =   -3400;  r->walls[15].z1 =    1600;
    r->walls[15].x2 =   -3400;  r->walls[15].z2 =   -1600;
    r->walls[15].nx =    4096;  r->walls[15].nz =       0;
    r->walls[15].y_min =    -500;  r->walls[15].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-3400 to -100)  z(-1600 to 1600)
     * FLOOR   1: y=     0  x(-100 to 100)  z(-400 to 400)
     */
}
