/*
 * Auto-generated collision data from: Stables mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 *
 * This copy in src/ is NOT byte-identical to the one the generator left in
 * assets/garden/: the .c's #include was lowercased and its multi_level /
 * shoot_over_mask lines added by hand. The include guard the generator derived
 * from the file name is already a valid C identifier here, so it stands.
 */

#ifndef STABLES_MESH_COLLISION_H
#define STABLES_MESH_COLLISION_H

#include "collision.h"

#define STABLES_WALL_COUNT  16
#define STABLES_FLOOR_COUNT 2

void stables_collision_init(CollisionRoom *r);

#endif /* STABLES_MESH_COLLISION_H */
