/*
 * Auto-generated collision data from: The Hatch mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead.
 *
 * NOTE: src/ is NOT byte-identical to the generated pair in assets/garden/.
 * The .c here has its #include lowercased and carries the two fields the
 * generator does not emit (multi_level, shoot_over_mask). Re-copy by hand
 * after any regeneration - see tools/ADDING_A_ROOM.txt STEP 4c.
 */

#ifndef THE_HATCH_MESH_COLLISION_H
#define THE_HATCH_MESH_COLLISION_H

#include "collision.h"

#define THE_HATCH_WALL_COUNT  32
#define THE_HATCH_FLOOR_COUNT 8

void the_hatch_collision_init(CollisionRoom *r);

#endif /* THE_HATCH_MESH_COLLISION_H */
