/*
 * Auto-generated collision data from: The Hatch mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  32
 * Floors: 8
 * Bounds: X(-200 to 4800)  Z(-1499 to 3900)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "the_hatch_mesh_collision.h"

void the_hatch_collision_init(CollisionRoom *r) {
    r->wall_count = THE_HATCH_WALL_COUNT;
    r->multi_level = 0;      /* one flat plane at y=0 throughout - all eight
                                generated floors agree (see the_hatch.h)  */
    r->shoot_over_mask = 0;  /* nothing here is low enough to shoot over  */
    r->min_x = -200;
    r->max_x = 4800;
    r->min_z = -1499;
    r->max_z = 3900;

    /* Wall 0 (avg Y: -250) */
    r->walls[0].x1 =    -200;  r->walls[0].z1 =     300;
    r->walls[0].x2 =    -200;  r->walls[0].z2 =    -300;
    r->walls[0].nx =    4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =    -500;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -250) */
    r->walls[1].x1 =    -200;  r->walls[1].z1 =    -300;
    r->walls[1].x2 =    1800;  r->walls[1].z2 =    -300;
    r->walls[1].nx =       0;  r->walls[1].nz =    4096;
    r->walls[1].y_min =    -500;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -250) */
    r->walls[2].x1 =    1800;  r->walls[2].z1 =     300;
    r->walls[2].x2 =    -200;  r->walls[2].z2 =     300;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4096;
    r->walls[2].y_min =    -500;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -249) */
    r->walls[3].x1 =    3000;  r->walls[3].z1 =    2700;
    r->walls[3].x2 =    3000;  r->walls[3].z2 =    3300;
    r->walls[3].nx =   -4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =    -499;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -250) */
    r->walls[4].x1 =    4400;  r->walls[4].z1 =   -1499;
    r->walls[4].x2 =    4400;  r->walls[4].z2 =   -1099;
    r->walls[4].nx =   -4096;  r->walls[4].nz =       0;
    r->walls[4].y_min =    -500;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -249) */
    r->walls[5].x1 =    3600;  r->walls[5].z1 =    2700;
    r->walls[5].x2 =    3000;  r->walls[5].z2 =    2700;
    r->walls[5].nx =       0;  r->walls[5].nz =   -4096;
    r->walls[5].y_min =    -499;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -249) */
    r->walls[6].x1 =    3000;  r->walls[6].z1 =    3300;
    r->walls[6].x2 =    3600;  r->walls[6].z2 =    3300;
    r->walls[6].nx =       0;  r->walls[6].nz =    4096;
    r->walls[6].y_min =    -499;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -250) */
    r->walls[7].x1 =    2200;  r->walls[7].z1 =    1100;
    r->walls[7].x2 =    1800;  r->walls[7].z2 =    1100;
    r->walls[7].nx =       0;  r->walls[7].nz =   -4096;
    r->walls[7].y_min =    -500;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -250) */
    r->walls[8].x1 =    1800;  r->walls[8].z1 =   -1100;
    r->walls[8].x2 =    2200;  r->walls[8].z2 =   -1099;
    r->walls[8].nx =       0;  r->walls[8].nz =    4095;
    r->walls[8].y_min =    -500;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -250) */
    r->walls[9].x1 =    4400;  r->walls[9].z1 =    1100;
    r->walls[9].x2 =    4400;  r->walls[9].z2 =    1500;
    r->walls[9].nx =   -4096;  r->walls[9].nz =       0;
    r->walls[9].y_min =    -500;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -250) */
    r->walls[10].x1 =    3000;  r->walls[10].z1 =    1500;
    r->walls[10].x2 =    2200;  r->walls[10].z2 =    1500;
    r->walls[10].nx =       0;  r->walls[10].nz =   -4096;
    r->walls[10].y_min =    -500;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -250) */
    r->walls[11].x1 =    4800;  r->walls[11].z1 =    1099;
    r->walls[11].x2 =    4400;  r->walls[11].z2 =    1100;
    r->walls[11].nx =       0;  r->walls[11].nz =   -4095;
    r->walls[11].y_min =    -500;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -250) */
    r->walls[12].x1 =    3000;  r->walls[12].z1 =    2100;
    r->walls[12].x2 =    3000;  r->walls[12].z2 =    1500;
    r->walls[12].nx =    4096;  r->walls[12].nz =       0;
    r->walls[12].y_min =    -500;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -250) */
    r->walls[13].x1 =    3600;  r->walls[13].z1 =    1500;
    r->walls[13].x2 =    3600;  r->walls[13].z2 =    2100;
    r->walls[13].nx =   -4096;  r->walls[13].nz =       0;
    r->walls[13].y_min =    -500;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -249) */
    r->walls[14].x1 =    3600;  r->walls[14].z1 =    3300;
    r->walls[14].x2 =    3600;  r->walls[14].z2 =    2700;
    r->walls[14].nx =    4096;  r->walls[14].nz =       0;
    r->walls[14].y_min =    -499;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -250) */
    r->walls[15].x1 =    4199;  r->walls[15].z1 =    3900;
    r->walls[15].x2 =    2400;  r->walls[15].z2 =    3900;
    r->walls[15].nx =       0;  r->walls[15].nz =   -4096;
    r->walls[15].y_min =    -500;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -250) */
    r->walls[16].x1 =    3600;  r->walls[16].z1 =    2100;
    r->walls[16].x2 =    4199;  r->walls[16].z2 =    2100;
    r->walls[16].nx =       0;  r->walls[16].nz =    4096;
    r->walls[16].y_min =    -500;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -250) */
    r->walls[17].x1 =    4199;  r->walls[17].z1 =    2100;
    r->walls[17].x2 =    4199;  r->walls[17].z2 =    3900;
    r->walls[17].nx =   -4096;  r->walls[17].nz =       0;
    r->walls[17].y_min =    -500;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -250) */
    r->walls[18].x1 =    2400;  r->walls[18].z1 =    3900;
    r->walls[18].x2 =    2400;  r->walls[18].z2 =    2100;
    r->walls[18].nx =    4096;  r->walls[18].nz =       0;
    r->walls[18].y_min =    -500;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -250) */
    r->walls[19].x1 =    2400;  r->walls[19].z1 =    2100;
    r->walls[19].x2 =    3000;  r->walls[19].z2 =    2100;
    r->walls[19].nx =       0;  r->walls[19].nz =    4096;
    r->walls[19].y_min =    -500;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -250) */
    r->walls[20].x1 =    4200;  r->walls[20].z1 =     300;
    r->walls[20].x2 =    4200;  r->walls[20].z2 =    -300;
    r->walls[20].nx =    4096;  r->walls[20].nz =       0;
    r->walls[20].y_min =    -500;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -250) */
    r->walls[21].x1 =    3000;  r->walls[21].z1 =    -300;
    r->walls[21].x2 =    3000;  r->walls[21].z2 =     300;
    r->walls[21].nx =   -4096;  r->walls[21].nz =       0;
    r->walls[21].y_min =    -500;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -250) */
    r->walls[22].x1 =    4200;  r->walls[22].z1 =    -300;
    r->walls[22].x2 =    3000;  r->walls[22].z2 =    -300;
    r->walls[22].nx =       0;  r->walls[22].nz =   -4096;
    r->walls[22].y_min =    -500;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -250) */
    r->walls[23].x1 =    3000;  r->walls[23].z1 =     300;
    r->walls[23].x2 =    4200;  r->walls[23].z2 =     300;
    r->walls[23].nx =       0;  r->walls[23].nz =    4096;
    r->walls[23].y_min =    -500;  r->walls[23].y_max =       0;

    /* Wall 24 (avg Y: -250) */
    r->walls[24].x1 =    2200;  r->walls[24].z1 =    1500;
    r->walls[24].x2 =    2200;  r->walls[24].z2 =    1100;
    r->walls[24].nx =    4096;  r->walls[24].nz =       0;
    r->walls[24].y_min =    -500;  r->walls[24].y_max =       0;

    /* Wall 25 (avg Y: -250) */
    r->walls[25].x1 =    1800;  r->walls[25].z1 =    1100;
    r->walls[25].x2 =    1800;  r->walls[25].z2 =     300;
    r->walls[25].nx =    4096;  r->walls[25].nz =       0;
    r->walls[25].y_min =    -500;  r->walls[25].y_max =       0;

    /* Wall 26 (avg Y: -250) */
    r->walls[26].x1 =    4400;  r->walls[26].z1 =    1500;
    r->walls[26].x2 =    3600;  r->walls[26].z2 =    1500;
    r->walls[26].nx =       0;  r->walls[26].nz =   -4096;
    r->walls[26].y_min =    -500;  r->walls[26].y_max =       0;

    /* Wall 27 (avg Y: -250) */
    r->walls[27].x1 =    4800;  r->walls[27].z1 =   -1099;
    r->walls[27].x2 =    4800;  r->walls[27].z2 =    1099;
    r->walls[27].nx =   -4096;  r->walls[27].nz =       0;
    r->walls[27].y_min =    -500;  r->walls[27].y_max =       0;

    /* Wall 28 (avg Y: -250) */
    r->walls[28].x1 =    2200;  r->walls[28].z1 =   -1499;
    r->walls[28].x2 =    4400;  r->walls[28].z2 =   -1499;
    r->walls[28].nx =       0;  r->walls[28].nz =    4096;
    r->walls[28].y_min =    -500;  r->walls[28].y_max =       0;

    /* Wall 29 (avg Y: -250) */
    r->walls[29].x1 =    2200;  r->walls[29].z1 =   -1099;
    r->walls[29].x2 =    2200;  r->walls[29].z2 =   -1499;
    r->walls[29].nx =    4096;  r->walls[29].nz =       0;
    r->walls[29].y_min =    -500;  r->walls[29].y_max =       0;

    /* Wall 30 (avg Y: -250) */
    r->walls[30].x1 =    4400;  r->walls[30].z1 =   -1099;
    r->walls[30].x2 =    4800;  r->walls[30].z2 =   -1099;
    r->walls[30].nx =       0;  r->walls[30].nz =    4095;
    r->walls[30].y_min =    -500;  r->walls[30].y_max =       0;

    /* Wall 31 (avg Y: -250) */
    r->walls[31].x1 =    1800;  r->walls[31].z1 =    -300;
    r->walls[31].x2 =    1800;  r->walls[31].z2 =   -1100;
    r->walls[31].nx =    4096;  r->walls[31].nz =       0;
    r->walls[31].y_min =    -500;  r->walls[31].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y=     0  x(-200 to 1800)  z(-300 to 300)
     * FLOOR   1: y=     0  x(3000 to 3600)  z(1500 to 2100)
     * FLOOR   2: y=     0  x(2400 to 4199)  z(2100 to 3900)
     * FLOOR   3: y=     0  x(1800 to 2200)  z(-1099 to 1099)
     * FLOOR   4: y=     0  x(4400 to 4800)  z(-1099 to 1099)
     * FLOOR   5: y=     0  x(2200 to 4400)  z(-1099 to 1099)
     * FLOOR   6: y=     0  x(2200 to 4400)  z(1099 to 1500)
     * FLOOR   7: y=     0  x(2200 to 4400)  z(-1499 to -1099)
     */
}
