/*
 * Auto-generated collision data from: The Shelf mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 */

#ifndef THE_SHELF_MESH_COLLISION_H
#define THE_SHELF_MESH_COLLISION_H

#include "collision.h"

#define THE_SHELF_WALL_COUNT  16
#define THE_SHELF_FLOOR_COUNT 3

void the_shelf_collision_init(CollisionRoom *r);

#endif /* THE_SHELF_MESH_COLLISION_H */
