/*
 * Auto-generated collision data from: The Pit mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 *
 * src/ is NOT byte-identical to assets/: the .c here carries the lowercase
 * #include plus r->multi_level and r->shoot_over_mask, which the generator does
 * not emit. Re-apply all three after any re-export (tools/ADDING_A_ROOM.txt
 * STEP 4c).
 */

#ifndef THE_PIT_MESH_COLLISION_H
#define THE_PIT_MESH_COLLISION_H

#include "collision.h"

#define THE_PIT_WALL_COUNT  24
#define THE_PIT_FLOOR_COUNT 9

void the_pit_collision_init(CollisionRoom *r);

#endif /* THE_PIT_MESH_COLLISION_H */
