/*
 * Auto-generated collision data from: The Head mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * NOTE: src/ is not byte-identical to assets/ - the #include is lowercased and
 *       r->multi_level / r->shoot_over_mask are added by hand (STEP 4c of
 *       tools/ADDING_A_ROOM.txt). Regenerate into assets/ and re-apply those.
 */

#ifndef THE_HEAD_MESH_COLLISION_H
#define THE_HEAD_MESH_COLLISION_H

#include "collision.h"

#define THE_HEAD_WALL_COUNT  4
#define THE_HEAD_FLOOR_COUNT 1

void the_head_collision_init(CollisionRoom *r);

#endif /* THE_HEAD_MESH_COLLISION_H */
