/*
 * Auto-generated collision data from: Tomb mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead
 * NOTE: src/ is not byte-identical to assets/ — the #include is lowercased and
 *       r->multi_level / r->shoot_over_mask are added by hand (STEP 4c of
 *       tools/ADDING_A_ROOM.txt). Regenerate into assets/ and re-apply those.
 */

#ifndef TOMB_MESH_COLLISION_H
#define TOMB_MESH_COLLISION_H

#include "collision.h"

#define TOMB_WALL_COUNT  40
#define TOMB_FLOOR_COUNT 1

void tomb_collision_init(CollisionRoom *r);

#endif /* TOMB_MESH_COLLISION_H */
