/*
 * Auto-generated collision data from: Up Down Maze mesh.smx
 * Generated by smx_to_collision.py
 * Walls:  29
 * Floors: 12
 * Bounds: X(-300 to 3900)  Z(-2100 to 3899)
 * Normal scale: 4096 = 1.0 (fixed point)
 */

#include "up_down_maze_mesh_collision.h"

void up_down_maze_collision_init(CollisionRoom *r) {
    r->wall_count = UP_DOWN_MAZE_WALL_COUNT;
    /* >>> 1, AND THIS IS THE FIRST CATACOMBS ROOM THAT EARNS IT. <<< The
       Catacombs Entry's own note says to re-check the flag "if a level is ever
       built back over another one here", and this room is that level: the ten
       walkways at y=-1000 are the TOPS of the blocks whose sides are the lower
       maze's corridor walls, so every one of walls 0-19 and 26-28 shares its XZ
       footprint with a stretch of floor a whole storey above it.

       What the flag switches is the HITSCAN Y-gate (collision.c's
       walls_crossed): without it a shot fired along an upper walkway is stopped
       by the block wall running underneath it, and the player cannot shoot
       anything across the maze from up top. The PLAYER's own push is Y-gated
       either way — collide_wall_frontonly_y never reads this field — which is
       what already lets them walk over the blocks rather than into them.

       THE ONE THING IT ALSO SWITCHES IS A HAZARD, and it is inert here:
       apply_ddog_collision() branches on multi_level into a hand-picked list of
       DELIVERY's wall indices, which applied to this room would let a demon dog
       walk out through most of it. No dog can exist down here — the catacomb
       mouth is one-way and area_bank_sync() has freed their art (src/area_bank.h)
       — so nothing places one. If Chapter 3 ever gets a four-legged enemy, that
       function is the first thing to read. */
    r->multi_level     = 1;
    r->shoot_over_mask = 0;  /* no low walls here - every one is full height */
    r->min_x = -300;
    r->max_x = 3900;
    r->min_z = -2100;
    r->max_z = 3899;

    /* Wall 0 (avg Y: -500) */
    r->walls[0].x1 =    2100;  r->walls[0].z1 =    2100;
    r->walls[0].x2 =    2100;  r->walls[0].z2 =    1500;
    r->walls[0].nx =    4096;  r->walls[0].nz =       0;
    r->walls[0].y_min =   -1000;  r->walls[0].y_max =       0;

    /* Wall 1 (avg Y: -500) */
    r->walls[1].x1 =     899;  r->walls[1].z1 =    -300;
    r->walls[1].x2 =     899;  r->walls[1].z2 =    1500;
    r->walls[1].nx =   -4096;  r->walls[1].nz =       0;
    r->walls[1].y_min =   -1000;  r->walls[1].y_max =       0;

    /* Wall 2 (avg Y: -500) */
    r->walls[2].x1 =    3300;  r->walls[2].z1 =     900;
    r->walls[2].x2 =    2700;  r->walls[2].z2 =     900;
    r->walls[2].nx =       0;  r->walls[2].nz =   -4096;
    r->walls[2].y_min =   -1000;  r->walls[2].y_max =       0;

    /* Wall 3 (avg Y: -500) */
    r->walls[3].x1 =    2699;  r->walls[3].z1 =    -299;
    r->walls[3].x2 =    2699;  r->walls[3].z2 =     300;
    r->walls[3].nx =   -4096;  r->walls[3].nz =       0;
    r->walls[3].y_min =   -1000;  r->walls[3].y_max =       0;

    /* Wall 4 (avg Y: -500) */
    r->walls[4].x1 =     899;  r->walls[4].z1 =    1500;
    r->walls[4].x2 =     299;  r->walls[4].z2 =    1500;
    r->walls[4].nx =       0;  r->walls[4].nz =   -4096;
    r->walls[4].y_min =   -1000;  r->walls[4].y_max =       0;

    /* Wall 5 (avg Y: -500) */
    r->walls[5].x1 =    2700;  r->walls[5].z1 =     900;
    r->walls[5].x2 =    2700;  r->walls[5].z2 =    2100;
    r->walls[5].nx =   -4096;  r->walls[5].nz =       0;
    r->walls[5].y_min =   -1000;  r->walls[5].y_max =       0;

    /* Wall 6 (avg Y: -500) */
    r->walls[6].x1 =    1499;  r->walls[6].z1 =    1500;
    r->walls[6].x2 =    1499;  r->walls[6].z2 =    -300;
    r->walls[6].nx =    4096;  r->walls[6].nz =       0;
    r->walls[6].y_min =   -1000;  r->walls[6].y_max =       0;

    /* Wall 7 (avg Y: -500) */
    r->walls[7].x1 =     300;  r->walls[7].z1 =    -899;
    r->walls[7].x2 =    -300;  r->walls[7].z2 =    -899;
    r->walls[7].nx =       0;  r->walls[7].nz =   -4096;
    r->walls[7].y_min =   -1000;  r->walls[7].y_max =       0;

    /* Wall 8 (avg Y: -500) */
    r->walls[8].x1 =    2700;  r->walls[8].z1 =    2100;
    r->walls[8].x2 =    2100;  r->walls[8].z2 =    2100;
    r->walls[8].nx =       0;  r->walls[8].nz =   -4096;
    r->walls[8].y_min =   -1000;  r->walls[8].y_max =       0;

    /* Wall 9 (avg Y: -500) */
    r->walls[9].x1 =    3899;  r->walls[9].z1 =    -300;
    r->walls[9].x2 =    2699;  r->walls[9].z2 =    -299;
    r->walls[9].nx =       0;  r->walls[9].nz =   -4095;
    r->walls[9].y_min =   -1000;  r->walls[9].y_max =       0;

    /* Wall 10 (avg Y: -500) */
    r->walls[10].x1 =    2100;  r->walls[10].z1 =    2700;
    r->walls[10].x2 =    3300;  r->walls[10].z2 =    2700;
    r->walls[10].nx =       0;  r->walls[10].nz =    4096;
    r->walls[10].y_min =   -1000;  r->walls[10].y_max =       0;

    /* Wall 11 (avg Y: -500) */
    r->walls[11].x1 =    2100;  r->walls[11].z1 =    1500;
    r->walls[11].x2 =    1499;  r->walls[11].z2 =    1500;
    r->walls[11].nx =       0;  r->walls[11].nz =   -4096;
    r->walls[11].y_min =   -1000;  r->walls[11].y_max =       0;

    /* Wall 12 (avg Y: -500) */
    r->walls[12].x1 =     299;  r->walls[12].z1 =    3300;
    r->walls[12].x2 =    2100;  r->walls[12].z2 =    3300;
    r->walls[12].nx =       0;  r->walls[12].nz =    4096;
    r->walls[12].y_min =   -1000;  r->walls[12].y_max =       0;

    /* Wall 13 (avg Y: -500) */
    r->walls[13].x1 =    2699;  r->walls[13].z1 =     300;
    r->walls[13].x2 =    3899;  r->walls[13].z2 =     300;
    r->walls[13].nx =       0;  r->walls[13].nz =    4095;
    r->walls[13].y_min =   -1000;  r->walls[13].y_max =       0;

    /* Wall 14 (avg Y: -500) */
    r->walls[14].x1 =     299;  r->walls[14].z1 =    1500;
    r->walls[14].x2 =     299;  r->walls[14].z2 =    3300;
    r->walls[14].nx =   -4096;  r->walls[14].nz =       0;
    r->walls[14].y_min =   -1000;  r->walls[14].y_max =       0;

    /* Wall 15 (avg Y: -500) */
    r->walls[15].x1 =     899;  r->walls[15].z1 =   -1499;
    r->walls[15].x2 =    2099;  r->walls[15].z2 =   -1500;
    r->walls[15].nx =       0;  r->walls[15].nz =    4095;
    r->walls[15].y_min =   -1000;  r->walls[15].y_max =       0;

    /* Wall 16 (avg Y: -500) */
    r->walls[16].x1 =    3300;  r->walls[16].z1 =    2700;
    r->walls[16].x2 =    3300;  r->walls[16].z2 =     900;
    r->walls[16].nx =    4096;  r->walls[16].nz =       0;
    r->walls[16].y_min =   -1000;  r->walls[16].y_max =       0;

    /* Wall 17 (avg Y: -500) */
    r->walls[17].x1 =     300;  r->walls[17].z1 =     900;
    r->walls[17].x2 =     300;  r->walls[17].z2 =    -899;
    r->walls[17].nx =    4096;  r->walls[17].nz =       0;
    r->walls[17].y_min =   -1000;  r->walls[17].y_max =       0;

    /* Wall 18 (avg Y: -500) */
    r->walls[18].x1 =    -300;  r->walls[18].z1 =     900;
    r->walls[18].x2 =     300;  r->walls[18].z2 =     900;
    r->walls[18].nx =       0;  r->walls[18].nz =    4096;
    r->walls[18].y_min =   -1000;  r->walls[18].y_max =       0;

    /* Wall 19 (avg Y: -500) */
    r->walls[19].x1 =    2100;  r->walls[19].z1 =    3300;
    r->walls[19].x2 =    2100;  r->walls[19].z2 =    2700;
    r->walls[19].nx =    4096;  r->walls[19].nz =       0;
    r->walls[19].y_min =   -1000;  r->walls[19].y_max =       0;

    /* Wall 20 (avg Y: -900) */
    r->walls[20].x1 =    -300;  r->walls[20].z1 =   -1500;
    r->walls[20].x2 =     300;  r->walls[20].z2 =   -2100;
    r->walls[20].nx =    2896;  r->walls[20].nz =    2896;
    r->walls[20].y_min =   -1800;  r->walls[20].y_max =       0;

    /* Wall 21 (avg Y: -900) */
    r->walls[21].x1 =    3300;  r->walls[21].z1 =   -2100;
    r->walls[21].x2 =    3900;  r->walls[21].z2 =   -1500;
    r->walls[21].nx =   -2896;  r->walls[21].nz =    2896;
    r->walls[21].y_min =   -1800;  r->walls[21].y_max =       0;

    /* Wall 22 (avg Y: -900) */
    r->walls[22].x1 =    3900;  r->walls[22].z1 =    3899;
    r->walls[22].x2 =    -300;  r->walls[22].z2 =    3899;
    r->walls[22].nx =       0;  r->walls[22].nz =   -4096;
    r->walls[22].y_min =   -1800;  r->walls[22].y_max =       0;

    /* Wall 23 (avg Y: -900) */
    r->walls[23].x1 =    -300;  r->walls[23].z1 =    3899;
    r->walls[23].x2 =    -300;  r->walls[23].z2 =   -1500;
    r->walls[23].nx =    4096;  r->walls[23].nz =       0;
    r->walls[23].y_min =   -1800;  r->walls[23].y_max =       0;

    /* Wall 24 (avg Y: -900) */
    r->walls[24].x1 =    3900;  r->walls[24].z1 =   -1500;
    r->walls[24].x2 =    3900;  r->walls[24].z2 =    3899;
    r->walls[24].nx =   -4096;  r->walls[24].nz =       0;
    r->walls[24].y_min =   -1800;  r->walls[24].y_max =       0;

    /* Wall 25 (avg Y: -900) */
    r->walls[25].x1 =     300;  r->walls[25].z1 =   -2100;
    r->walls[25].x2 =    3300;  r->walls[25].z2 =   -2100;
    r->walls[25].nx =       0;  r->walls[25].nz =    4096;
    r->walls[25].y_min =   -1800;  r->walls[25].y_max =       0;

    /* Wall 26 (avg Y: -500) */
    r->walls[26].x1 =    2099;  r->walls[26].z1 =   -1500;
    r->walls[26].x2 =    2099;  r->walls[26].z2 =   -2100;
    r->walls[26].nx =    4096;  r->walls[26].nz =       0;
    r->walls[26].y_min =   -1000;  r->walls[26].y_max =       0;

    /* Wall 27 (avg Y: -500) */
    r->walls[27].x1 =     899;  r->walls[27].z1 =   -2100;
    r->walls[27].x2 =     899;  r->walls[27].z2 =   -1499;
    r->walls[27].nx =   -4096;  r->walls[27].nz =       0;
    r->walls[27].y_min =   -1000;  r->walls[27].y_max =       0;

    /* Wall 28 (avg Y: -500) */
    r->walls[28].x1 =    1499;  r->walls[28].z1 =    -300;
    r->walls[28].x2 =     899;  r->walls[28].z2 =    -300;
    r->walls[28].nx =       0;  r->walls[28].nz =   -4096;
    r->walls[28].y_min =   -1000;  r->walls[28].y_max =       0;

    /*
     * Floor/ceiling planes detected:
     * Use these in apply_height() for vertical movement.
     *
     * FLOOR   0: y= -1000  x(2100 to 2700)  z(2100 to 2700)
     * FLOOR   1: y= -1000  x(299 to 2100)  z(1500 to 3300)
     * FLOOR   2: y= -1000  x(899 to 1499)  z(-300 to 1500)
     * FLOOR   3: y= -1000  x(3299 to 3899)  z(-300 to 300)
     * FLOOR   4: y= -1000  x(899 to 2099)  z(-2100 to -1499)
     * FLOOR   5: y= -1000  x(-300 to 300)  z(-899 to 900)
     * FLOOR   6: y=     0  x(-300 to 3900)  z(-2100 to -1500)
     * FLOOR   7: y=     0  x(-300 to 3900)  z(-1500 to 3899)
     * FLOOR   8: y= -1000  x(300 to 899)  z(-300 to 300)
     * FLOOR   9: y= -1000  x(2699 to 3300)  z(-299 to 2700)
     * FLOOR   10: y=  -999  x(-300 to 299)  z(2100 to 2700)
     * FLOOR   11: y=  -999  x(899 to 1499)  z(3300 to 3899)
     */
}
