/*
 * Auto-generated collision data from: Up Down Maze mesh.smx
 * Generated by smx_to_collision.py
 * DO NOT EDIT MANUALLY - regenerate from SMX instead. Note that src/ is NOT
 * byte-identical to assets/catacombs/: the .c there carries the lowercase
 * #include and the hand-added multi_level / shoot_over_mask lines the
 * generator does not emit (tools/ADDING_A_ROOM.txt STEP 4c).
 */

#ifndef UP_DOWN_MAZE_MESH_COLLISION_H
#define UP_DOWN_MAZE_MESH_COLLISION_H

#include "collision.h"

#define UP_DOWN_MAZE_WALL_COUNT  29
#define UP_DOWN_MAZE_FLOOR_COUNT 12

void up_down_maze_collision_init(CollisionRoom *r);

#endif /* UP_DOWN_MAZE_MESH_COLLISION_H */
